/* generated by purecrate-ts. do not edit. */

export type CalendarError =
  | Readonly<{ kind: "YearOutOfRange" }>
  | Readonly<{ kind: "MonthOutOfRange" }>
  | Readonly<{ kind: "DayOutOfRange" }>
  | Readonly<{ kind: "DaysOutOfRange" }>
  | Readonly<{ kind: "HourOutOfRange" }>
  | Readonly<{ kind: "MinuteOutOfRange" }>
  | Readonly<{ kind: "SecondOutOfRange" }>;

export const CalendarError = {
  YearOutOfRange: (): CalendarError => ({ kind: "YearOutOfRange" }),
  MonthOutOfRange: (): CalendarError => ({ kind: "MonthOutOfRange" }),
  DayOutOfRange: (): CalendarError => ({ kind: "DayOutOfRange" }),
  /** A day count outside `MIN_DAYS..=MAX_DAYS`. */
  DaysOutOfRange: (): CalendarError => ({ kind: "DaysOutOfRange" }),
  HourOutOfRange: (): CalendarError => ({ kind: "HourOutOfRange" }),
  MinuteOutOfRange: (): CalendarError => ({ kind: "MinuteOutOfRange" }),
  SecondOutOfRange: (): CalendarError => ({ kind: "SecondOutOfRange" }),
} as const;
