/* generated by purecrate-ts. do not edit. */

import { Result, type I64 } from "./purecrate-runtime.ts";
import type { CalendarError } from "./calendar-error.ts";
import type { CivilDate } from "./civil-date.ts";
import { MAX_DAYS, MIN_DAYS } from "./consts.ts";
import { daysToCivil } from "./days-to-civil.ts";

export const civilFromDays = (days: I64): Result<CivilDate, CalendarError> => {
  if (days < MIN_DAYS || days > MAX_DAYS) return Result.err({ kind: "DaysOutOfRange" });
  return Result.ok(daysToCivil(days));
};
