/* generated by purecrate-ts. do not edit. */

import type { I64 } from "./purecrate-runtime.ts";
import type { DayOfWeek } from "./day-of-week.ts";

/** The weekday for an ISO number; the number must be 1..=7. */
export const dayFromNumber = (n: I64): DayOfWeek => {
  if (n === 1n) return { kind: "Monday" };
  if (n === 2n) return { kind: "Tuesday" };
  if (n === 3n) return { kind: "Wednesday" };
  if (n === 4n) return { kind: "Thursday" };
  if (n === 5n) return { kind: "Friday" };
  if (n === 6n) return { kind: "Saturday" };
  return { kind: "Sunday" };
};
