/* generated by purecrate-ts. do not edit. */

import { Result, type I64 } from "./purecrate-runtime.ts";
import type { CalendarError } from "./calendar-error.ts";
import { checkedCivil } from "./checked-civil.ts";
import { civilToDays } from "./civil-to-days.ts";

/** Days since 1970-01-01 (negative before it). */
export const daysFromCivil = (year: I64, month: I64, day: I64): Result<I64, CalendarError> => {
  const dResult = checkedCivil(year, month, day);
  if (dResult.kind === "Err") return dResult;
  const d = dResult.value;
  return Result.ok(civilToDays(d.year, d.month, d.day));
};
