/* generated by purecrate-ts. do not edit. */

import type { I64, U32 } from "./purecrate-runtime.ts";

/**
 * A point in time: seconds since 1970-01-01T00:00:00Z (leap seconds not
 * counted, as POSIX) and milliseconds into that second.
 */
export type Instant = Readonly<{
  seconds: I64;
  millis: U32;
}>;

export const Instant = {
  of: (seconds: I64, millis: U32): Instant => ({ seconds, millis }),
} as const;
