/* generated by purecrate-ts. do not edit. */

import type { I64 } from "./purecrate-runtime.ts";
import type { DayOfWeek } from "./day-of-week.ts";

/**
 * An ISO 8601 week date. `year` is the ISO week-numbering year, which can
 * differ from the civil year near January 1.
 */
export type IsoWeekDate = Readonly<{
  year: I64;
  week: I64;
  day: DayOfWeek;
}>;

export const IsoWeekDate = {
  of: (year: I64, week: I64, day: DayOfWeek): IsoWeekDate => ({ year, week, day }),
} as const;
