/* generated by purecrate-ts. do not edit. */

import type { ErrorCode } from "./error-code.ts";

export type ErrorRedirect = Readonly<{
  redirect_uri: string;
  error: ErrorCode;
  state: string | null;
}>;

export const ErrorRedirect = {
  of: (redirect_uri: string, error: ErrorCode, state: string | null): ErrorRedirect => ({ redirect_uri, error, state }),
} as const;
