/* generated by purecrate-ts. do not edit. */

import type { PkceMethod } from "./pkce-method.ts";

export type Pkce = Readonly<{
  challenge: string;
  method: PkceMethod;
}>;

export const Pkce = {
  of: (challenge: string, method: PkceMethod): Pkce => ({ challenge, method }),
} as const;
