/* generated by purecrate-ts. do not edit. */

import { Str, type U8, type Usize } from "./purecrate-runtime.ts";

export const BASE32: ReadonlyArray<U8> = Str.bytes("0123456789bcdefghjkmnpqrstuvwxyz");
export const GEOHASH_MAX_LEN = 12 as Usize;
