/* generated by purecrate-ts. do not edit. */

import { Char, Int, type I64, type U32, type U8 } from "./purecrate-runtime.ts";

const chunkChar = (c: I64): Char => {
  let b = 0 as U8;
  let bit = 1n as I64;
  let add = 1 as U8;

  for (let i = 0 as U32; i < 6; i = (i + 1) as U32) {
    if (Int.i64.and(c, bit) !== 0n) {
      b = Int.u8.add(b, add);
    }

    bit = Int.i64.shl(bit, 1);
    add = Int.u8.mul(add, 2 as U8);
  }

  return Char.fromU8(Int.u8.add(63 as U8, b));
};

export const encodeValue = (v: I64): string => {
  let u: I64 = Int.i64.shl(v, 1);

  if (v < 0n) {
    u = Int.i64.not(u);
  }

  let s: string = "";

  while (u >= 0x20n) {
    s += chunkChar(Int.i64.or(Int.i64.and(u, 0x1fn as I64), 0x20n as I64));
    u = Int.i64.shr(u, 5);
  }

  s += chunkChar(u);
  return s;
};
