/* generated by purecrate-ts. do not edit. */

import { Int, type F64, type I64 } from "./purecrate-runtime.ts";
import { encodeValue } from "./encode-value.ts";
import { factor } from "./factor.ts";
import type { LatLng } from "./lat-lng.ts";
import type { Precision } from "./precision.ts";

export const encodePolyline = (points: ReadonlyArray<LatLng>, precision: Precision): string => {
  const f = factor(precision);
  let out: string = "";
  let prevLat = 0n as I64;
  let prevLng = 0n as I64;

  for (const p of points) {
    const lat = Int.i64.castFloat(Int.f64.round((p.lat * f) as F64));
    const lng = Int.i64.castFloat(Int.f64.round((p.lng * f) as F64));
    out += encodeValue(Int.i64.sub(lat, prevLat));
    out += encodeValue(Int.i64.sub(lng, prevLng));
    prevLat = lat;
    prevLng = lng;
  }

  return out;
};
