/* generated by purecrate-ts. do not edit. */

import type { F64 } from "./purecrate-runtime.ts";
import { unsafeMakeLatLng, type LatLng } from "./lat-lng.ts";

declare class GeohashCell$brand {
  private brand: unknown;
}
export type GeohashCell = Readonly<{
  min_lat: F64;
  max_lat: F64;
  min_lng: F64;
  max_lng: F64;
}> &
  GeohashCell$brand;

/**
 * Makes `GeohashCell` values without a check.
 *
 * Its fields are not `pub` in Rust, so outside the crate a value comes only
 * from the crate's functions; the generated files build them here, and
 * `index.ts` does not export it.
 * @internal
 */
export const unsafeMakeGeohashCell = (
  fields: Readonly<{ min_lat: F64; max_lat: F64; min_lng: F64; max_lng: F64 }>,
): GeohashCell => fields as GeohashCell;

export const GeohashCell = {
  minLat: (self: GeohashCell): F64 => self.min_lat,
  maxLat: (self: GeohashCell): F64 => self.max_lat,
  minLng: (self: GeohashCell): F64 => self.min_lng,
  maxLng: (self: GeohashCell): F64 => self.max_lng,
  centre: (self: GeohashCell): LatLng =>
    unsafeMakeLatLng({
      lat: (((self.min_lat + self.max_lat) as F64) / (2.0 as F64)) as F64,
      lng: (((self.min_lng + self.max_lng) as F64) / (2.0 as F64)) as F64,
    }),
} as const;
