/* generated by purecrate-ts. do not edit. */

import {
  Char,
  Int,
  Iter,
  Result,
  Str,
  type F64,
  type U32,
  type U8,
  type Usize,
} from "./purecrate-runtime.ts";
import { BASE32, GEOHASH_MAX_LEN } from "./consts.ts";
import type { GeoError } from "./geo-error.ts";
import { unsafeMakeGeohashCell, type GeohashCell } from "./geohash-cell.ts";

export const geohashDecode = (hash: string): Result<GeohashCell, GeoError> => {
  Str.wellFormed(hash);
  if (hash.length === 0) return Result.err({ kind: "EmptyGeohash" });
  let latLo = -90.0 as F64;
  let latHi = 90.0 as F64;
  let lngLo = -180.0 as F64;
  let lngHi = 180.0 as F64;
  let useLng = true;
  let count = 0 as Usize;
  let pos = 0 as Usize;

  for (const c of hash as Iterable<Char>) {
    if (count === GEOHASH_MAX_LEN) return Result.err({ kind: "GeohashTooLong" });
    const option = Iter.position(BASE32, (a: U8): boolean => Char.fromU8(a) === c);
    if (option === null) return Result.err({ kind: "BadGeohashChar", value: pos });
    const idx = Int.u32.cast(option);
    let mask = 16 as U32;
    while (mask > 0) {
      const upper = Int.u32.and(idx, mask) !== 0;

      if (useLng) {
        const mid = (((lngLo + lngHi) as F64) / (2.0 as F64)) as F64;

        if (upper) {
          lngLo = mid;
        } else {
          lngHi = mid;
        }
      } else {
        const mid = (((latLo + latHi) as F64) / (2.0 as F64)) as F64;

        if (upper) {
          latLo = mid;
        } else {
          latHi = mid;
        }
      }

      useLng = !useLng;
      mask = Int.u32.div(mask, 2 as U32);
    }

    count = Int.usize.add(count, 1 as Usize);
    pos = Int.usize.add(pos, Char.lenUtf8(c));
  }

  return Result.ok(
    unsafeMakeGeohashCell({ min_lat: latLo, max_lat: latHi, min_lng: lngLo, max_lng: lngHi }),
  );
};
