/* generated by purecrate-ts. do not edit. */

import { Result, type F64 } from "./purecrate-runtime.ts";
import { checkFinite } from "./check-finite.ts";
import type { GeoError } from "./geo-error.ts";

declare class LatLng$brand {
  private brand: unknown;
}
export type LatLng = Readonly<{
  lat: F64;
  lng: F64;
}> &
  LatLng$brand;

/**
 * Makes `LatLng` values without a check.
 *
 * Its fields are not `pub` in Rust, so outside the crate a value comes only
 * from the crate's functions; the generated files build them here, and
 * `index.ts` does not export it.
 * @internal
 */
export const unsafeMakeLatLng = (fields: Readonly<{ lat: F64; lng: F64 }>): LatLng =>
  fields as LatLng;

export const LatLng = {
  new: (lat: F64, lng: F64): Result<LatLng, GeoError> => {
    const checkFiniteResult = checkFinite(lat);
    if (checkFiniteResult.kind === "Err") return checkFiniteResult;
    const checkFiniteResult2 = checkFinite(lng);
    if (checkFiniteResult2.kind === "Err") return checkFiniteResult2;
    if (lat < (-90.0 as F64) || lat > (90.0 as F64))
      return Result.err({ kind: "LatitudeOutOfRange" });
    if (lng < (-180.0 as F64) || lng > (180.0 as F64))
      return Result.err({ kind: "LongitudeOutOfRange" });
    return Result.ok(unsafeMakeLatLng({ lat, lng }));
  },
  lat: (self: LatLng): F64 => self.lat,
  lng: (self: LatLng): F64 => self.lng,
} as const;
