/* generated by purecrate-ts. do not edit. */

import { Result, type I64 } from "./purecrate-runtime.ts";
import type { PaymentError } from "./payment-error.ts";

declare const Amount$brand: unique symbol;
export type Amount = I64 & { readonly [Amount$brand]: true };

/**
 * Makes `Amount` values without a check.
 *
 * Its fields are not `pub` in Rust, so outside the crate a value comes only
 * from the crate's functions; the generated files build them here, and
 * `index.ts` does not export it.
 * @internal
 */
export const unsafeMakeAmount = (value: I64): Amount => value as Amount;

export const Amount = {
  new: (value: I64): Result<Amount, PaymentError> => {
    if (value < 50n || value > 99999999n) return Result.err({ kind: "AmountOutOfRange" });
    return Result.ok(unsafeMakeAmount(value));
  },
  tryFrom: (value: I64): Result<Amount, PaymentError> => Amount.new(value),
} as const;
