/* generated by purecrate-ts. do not edit. */

import { type I32 } from "./purecrate-runtime.ts";

export type State = Readonly<{
  n: I32;
}>;

export const State = {
  of: (n: I32): State => ({ n }),
} as const;
