/* generated by purecrate-ts. do not edit. */

import { assertNever } from "./assert-never.ts";
import { Int, type U32, type U64, type U8, type Usize } from "./int.ts";
import { Result } from "./result.ts";
import { type Char, Str } from "./str.ts";
import { parse_build_ids } from "./parse-build-ids.ts";
import { parse_core_number } from "./parse-core-number.ts";
import { parse_pre_ids } from "./parse-pre-ids.ts";
import type { BuildIds } from "./build-ids.ts";
import type { PreIds } from "./pre-ids.ts";
import type { SemverError } from "./semver-error.ts";

declare const VersionBrand: unique symbol;
export type Version = Readonly<{
  major: U64;
  minor: U64;
  patch: U64;
  pre: PreIds;
  build: BuildIds;
}> & { readonly [VersionBrand]: true };

// A field is not `pub` in Rust: outside the crate, `Version` values come only from
// the crate's functions. The generated files build them here; `index.ts` does not export it.
export const Version$of = (fields: Readonly<{ major: U64; minor: U64; patch: U64; pre: PreIds; build: BuildIds }>): Version => fields as Version;

export const Version = {
  parse: (s: string): Result<Version, SemverError> => {
    if ((s.length === 0)) {
      return Result.err({ kind: "Empty" });
    }
    let plus: Usize | null;
    {
      const $src4: string = s;
      let $i3: Usize = (0 as Usize);
      let $acc2: Usize | null = null;
      $l3: for (const $x1 of Str.bytes($src4)) {
        const b: U8 = $x1;
        if (b === (43 as U8)) {
          $acc2 = $i3;
          break $l3;
        }
        $i3 = Int.usize.add($i3, (1 as Usize));
      }
      plus = $acc2;
    }
    let rest: string;
    if (plus !== null) {
      const i = plus;
      rest = Str.slice(s, (0 as Usize), i);
    } else {
      rest = s;
    }
    let dash: Usize | null;
    {
      const $src8: string = rest;
      let $i7: Usize = (0 as Usize);
      let $acc6: Usize | null = null;
      $l3: for (const $x5 of Str.bytes($src8)) {
        const b$1: U8 = $x5;
        if (b$1 === (45 as U8)) {
          $acc6 = $i7;
          break $l3;
        }
        $i7 = Int.usize.add($i7, (1 as Usize));
      }
      dash = $acc6;
    }
    let core: string;
    if (dash !== null) {
      const i$1 = dash;
      core = Str.slice(rest, (0 as Usize), i$1);
    } else {
      core = rest;
    }
    let major: U64 | null = null;
    let minor: U64 | null = null;
    let patch: U64 | null = null;
    let n: U32 = (0 as U32);
    for (const piece of core.split(("." as Char))) {
      if (n === (0 as U32)) {
        const $v_$q1 = parse_core_number(piece, { kind: "Major" });
        if ($v_$q1.kind === "Err") return $v_$q1;
        const $q1 = $v_$q1.value;
        major = $q1;
      } else if (n === (1 as U32)) {
        const $v_$q2 = parse_core_number(piece, { kind: "Minor" });
        if ($v_$q2.kind === "Err") return $v_$q2;
        const $q2 = $v_$q2.value;
        minor = $q2;
      } else if (n === (2 as U32)) {
        const $v_$q3 = parse_core_number(piece, { kind: "Patch" });
        if ($v_$q3.kind === "Err") return $v_$q3;
        const $q3 = $v_$q3.value;
        patch = $q3;
      } else {
        return Result.err({ kind: "ExtraCorePart" });
      }
      n = Int.u32.add(n, (1 as U32));
    }
    const $v_major$1 = (() => {
      const $opt9 = major as U64 | null;
      const $arg11 = { kind: "MissingPart", content: [{ kind: "Major" }] } as SemverError;
      let $res12: Result<U64, SemverError>;
      if ($opt9 !== null) {
        const $some10 = $opt9;
        $res12 = Result.ok($some10);
      } else {
        $res12 = Result.err($arg11);
      }
      return $res12;
    })();
    if ($v_major$1.kind === "Err") return $v_major$1;
    const major$1: U64 = $v_major$1.value;
    const $v_minor$1 = (() => {
      const $opt13 = minor as U64 | null;
      const $arg15 = { kind: "MissingPart", content: [{ kind: "Minor" }] } as SemverError;
      let $res16: Result<U64, SemverError>;
      if ($opt13 !== null) {
        const $some14 = $opt13;
        $res16 = Result.ok($some14);
      } else {
        $res16 = Result.err($arg15);
      }
      return $res16;
    })();
    if ($v_minor$1.kind === "Err") return $v_minor$1;
    const minor$1: U64 = $v_minor$1.value;
    const $v_patch$1 = (() => {
      const $opt17 = patch as U64 | null;
      const $arg19 = { kind: "MissingPart", content: [{ kind: "Patch" }] } as SemverError;
      let $res20: Result<U64, SemverError>;
      if ($opt17 !== null) {
        const $some18 = $opt17;
        $res20 = Result.ok($some18);
      } else {
        $res20 = Result.err($arg19);
      }
      return $res20;
    })();
    if ($v_patch$1.kind === "Err") return $v_patch$1;
    const patch$1: U64 = $v_patch$1.value;
    let pre: PreIds;
    if (dash !== null) {
      const i$2 = dash;
      const $v_$q4 = parse_pre_ids(Str.slice(rest, Int.usize.add(i$2, (1 as Usize))));
      if ($v_$q4.kind === "Err") return $v_$q4;
      const $q4 = $v_$q4.value;
      pre = $q4;
    } else {
      pre = { kind: "Nil" };
    }
    let build: BuildIds;
    if (plus !== null) {
      const i$3 = plus;
      const $v_$q5 = parse_build_ids(Str.slice(s, Int.usize.add(i$3, (1 as Usize))));
      if ($v_$q5.kind === "Err") return $v_$q5;
      const $q5 = $v_$q5.value;
      build = $q5;
    } else {
      build = { kind: "Nil" };
    }
    return Result.ok(Version$of({ major: major$1, minor: minor$1, patch: patch$1, pre: pre, build: build }));
  },
  major: (self: Version): U64 => self.major,
  minor: (self: Version): U64 => self.minor,
  patch: (self: Version): U64 => self.patch,
  pre_release: (self: Version): PreIds => self.pre,
  build_metadata: (self: Version): BuildIds => self.build,
  is_pre_release: (self: Version): boolean => !(() => {
    switch (self.pre.kind) {
      case "Nil":
        return true;
      case "Cons":
        return false;
      default:
        return assertNever(self.pre);
    }
  })(),
} as const;
