/* generated by purecrate-ts. do not edit. */

import type { Group } from "./group.ts";
import type { Yen } from "./yen.ts";

export type Summary = Readonly<{
  standard: Group;
  reduced: Group;
  standard_inclusive: Group;
  reduced_inclusive: Group;
  total: Yen;
}>;

export const Summary = {
  of: (standard: Group, reduced: Group, standard_inclusive: Group, reduced_inclusive: Group, total: Yen): Summary => ({ standard, reduced, standard_inclusive, reduced_inclusive, total }),
} as const;
