/* generated by purecrate-ts. do not edit. */

import { assertNever } from "./assert-never.ts";
import { Int, type I64 } from "./int.ts";
import { Result } from "./result.ts";
import { attempt } from "./attempt.ts";
import type { CancellationReason } from "./cancellation-reason.ts";
import type { DeclineCode } from "./decline-code.ts";
import type { Event } from "./event.ts";
import type { Outcome } from "./outcome.ts";
import type { PaymentError } from "./payment-error.ts";
import type { PaymentIntent } from "./payment-intent.ts";
import type { PaymentMethod } from "./payment-method.ts";
import type { Status } from "./status.ts";
import type { Terms } from "./terms.ts";

export const step = (intent: PaymentIntent, event: Event): Result<PaymentIntent, PaymentError> => {
  const terms = intent.terms as Terms;
  let status: Status;
  switch (intent.status.kind) {
    case "RequiresPaymentMethod":
      switch (event.kind) {
        case "AttachMethod": {
          const $f14 = event.content[0];
          const method = $f14 as PaymentMethod;
          status = { kind: "RequiresConfirmation", method: method };
          break;
        }
        case "Confirm": {
          const $f15 = event.method;
          const $f16 = event.outcome;
          const method$1 = $f15 as PaymentMethod | null;
          const outcome = $f16 as Outcome;
          const $v_method$2 = (() => {
            const $opt1 = method$1 as PaymentMethod | null;
            const $arg3 = { kind: "MissingPaymentMethod" } as PaymentError;
            let $res4: Result<PaymentMethod, PaymentError>;
            if ($opt1 !== null) {
              const $some2 = $opt1;
              $res4 = Result.ok($some2);
            } else {
              $res4 = Result.err($arg3);
            }
            return $res4;
          })();
          if ($v_method$2.kind === "Err") return $v_method$2;
          const method$2: PaymentMethod = $v_method$2.value;
          status = attempt(terms, method$2, outcome);
          break;
        }
        case "ActionHandled":
        case "ProcessingSucceeded":
        case "ProcessingFailed":
        case "Capture":
          return Result.err({ kind: "InvalidTransition" });
        case "Cancel": {
          const $f21 = event.content[0];
          const reason = $f21 as CancellationReason | null;
          status = { kind: "Canceled", reason: reason };
          break;
        }
        default:
          return assertNever(event);
      }
      break;
    case "RequiresConfirmation": {
      const $f22 = intent.status.method;
      switch (event.kind) {
        case "AttachMethod": {
          const $f23 = event.content[0];
          const method$3 = $f23 as PaymentMethod;
          status = { kind: "RequiresConfirmation", method: method$3 };
          break;
        }
        case "Confirm": {
          const $f24 = event.method;
          const $f25 = event.outcome;
          const current = $f22 as PaymentMethod;
          const method$4 = $f24 as PaymentMethod | null;
          const outcome$1 = $f25 as Outcome;
          status = attempt(terms, (() => {
            const $opt5 = method$4 as PaymentMethod | null;
            const $arg7 = current as PaymentMethod;
            if ($opt5 !== null) {
              const $some6 = $opt5;
              return $some6;
            } else {
              return $arg7;
            }
          })(), outcome$1);
          break;
        }
        case "ActionHandled":
        case "ProcessingSucceeded":
        case "ProcessingFailed":
        case "Capture":
          return Result.err({ kind: "InvalidTransition" });
        case "Cancel": {
          const $f30 = event.content[0];
          const reason$1 = $f30 as CancellationReason | null;
          status = { kind: "Canceled", reason: reason$1 };
          break;
        }
        default:
          return assertNever(event);
      }
      break;
    }
    case "RequiresAction": {
      const $f31 = intent.status.method;
      switch (event.kind) {
        case "AttachMethod":
        case "Confirm":
        case "ProcessingSucceeded":
        case "ProcessingFailed":
        case "Capture":
          return Result.err({ kind: "InvalidTransition" });
        case "ActionHandled": {
          const $f35 = event.content[0];
          if ((() => {
            switch (terms.confirmation.kind) {
              case "Manual":
                return true;
              case "Automatic":
                return false;
              default:
                return assertNever(terms.confirmation);
            }
          })() && !(() => {
            switch ($f35.kind) {
              case "Declined":
                return true;
              case "Authorized":
              case "ActionRequired":
              case "Pending":
                return false;
              default:
                return assertNever($f35);
            }
          })()) {
            const method$5 = $f31 as PaymentMethod;
            status = { kind: "RequiresConfirmation", method: method$5 };
          } else {
            const method$6 = $f31 as PaymentMethod;
            const outcome$3 = $f35 as Outcome;
            status = attempt(terms, method$6, outcome$3);
          }
          break;
        }
        case "Cancel": {
          const $f39 = event.content[0];
          const reason$2 = $f39 as CancellationReason | null;
          status = { kind: "Canceled", reason: reason$2 };
          break;
        }
        default:
          return assertNever(event);
      }
      break;
    }
    case "Processing": {
      const $f40 = intent.status.method;
      switch (event.kind) {
        case "AttachMethod":
        case "Confirm":
        case "ActionHandled":
        case "Capture":
          return Result.err({ kind: "InvalidTransition" });
        case "ProcessingSucceeded": {
          const method$7 = $f40 as PaymentMethod;
          status = attempt(terms, method$7, { kind: "Authorized" });
          break;
        }
        case "ProcessingFailed": {
          const $f45 = event.content[0];
          const code = $f45 as DeclineCode;
          status = { kind: "RequiresPaymentMethod", last_error: code };
          break;
        }
        case "Cancel": {
          const $f48 = event.content[0];
          if ((() => {
            switch ($f40.kind.kind) {
              case "BankDebit":
                return true;
              case "Card":
                return false;
              default:
                return assertNever($f40.kind);
            }
          })()) {
            const reason$3 = $f48 as CancellationReason | null;
            status = { kind: "Canceled", reason: reason$3 };
          } else {
            return Result.err({ kind: "NotCancelable" });
          }
          break;
        }
        default:
          return assertNever(event);
      }
      break;
    }
    case "RequiresCapture": {
      const $f50 = intent.status.capturable;
      switch (event.kind) {
        case "AttachMethod":
        case "Confirm":
        case "ActionHandled":
        case "ProcessingSucceeded":
        case "ProcessingFailed":
          return Result.err({ kind: "InvalidTransition" });
        case "Capture": {
          const $f56 = event.amount_to_capture;
          const $f57 = event.application_fee;
          const capturable: I64 = $f50;
          const amount_to_capture = $f56 as I64 | null;
          const application_fee = $f57 as I64 | null;
          if ((() => {
            if (amount_to_capture !== null) {
              const amount = amount_to_capture;
              return (amount < (1n as I64)) || (amount > capturable);
            } else {
              return false;
            }
          })()) {
            return Result.err({ kind: "InvalidCaptureAmount", capturable: capturable });
          }
          if ((() => {
            if (application_fee !== null) {
              const fee = application_fee;
              return fee < (0n as I64);
            } else {
              return false;
            }
          })()) {
            return Result.err({ kind: "NegativeApplicationFee" });
          }
          let received: I64;
          {
            const $opt8 = amount_to_capture as I64 | null;
            const $arg10: I64 = capturable;
            if ($opt8 !== null) {
              const $some9 = $opt8;
              received = $some9;
            } else {
              received = $arg10;
            }
          }
          status = { kind: "Succeeded", received: received, application_fee: (() => {
  const $opt11 = application_fee as I64 | null;
  if ($opt11 !== null) {
    const fee$1 = $opt11;
    return Int.i64.min(fee$1, received);
  } else {
    return null;
  }
})() };
          break;
        }
        case "Cancel": {
          const $f58 = event.content[0];
          const reason$4 = $f58 as CancellationReason | null;
          status = { kind: "Canceled", reason: reason$4 };
          break;
        }
        default:
          return assertNever(event);
      }
      break;
    }
    case "Succeeded":
      switch (event.kind) {
        case "AttachMethod":
        case "Confirm":
        case "ActionHandled":
        case "ProcessingSucceeded":
        case "ProcessingFailed":
        case "Capture":
          return Result.err({ kind: "InvalidTransition" });
        case "Cancel":
          return Result.err({ kind: "NotCancelable" });
        default:
          return assertNever(event);
      }
    case "Canceled":
      switch (event.kind) {
        case "AttachMethod":
        case "Confirm":
        case "ActionHandled":
        case "ProcessingSucceeded":
        case "ProcessingFailed":
        case "Capture":
          return Result.err({ kind: "InvalidTransition" });
        case "Cancel":
          return Result.err({ kind: "NotCancelable" });
        default:
          return assertNever(event);
      }
    default:
      return assertNever(intent.status);
  }
  return Result.ok({ terms: terms, status: status });
};
