/* generated by purecrate-ts. do not edit. */

import { assertNever, Int } from "./purecrate-runtime.ts";
import type { Line } from "./line.ts";
import type { Lines } from "./lines.ts";

export const addLine = (lines: Lines, line: Line): Lines => {
  switch (lines.kind) {
    case "Nil":
      return { kind: "Cons", content: [line, { kind: "Nil" }] };
    case "Cons": {
      const head = lines.content[0];
      const rest = lines.content[1];

      if (head.sku === line.sku) {
        const merged: Line = { ...head, qty: Int.u32.add(head.qty, line.qty) };
        return { kind: "Cons", content: [merged, rest] };
      }

      return { kind: "Cons", content: [head, addLine(rest, line)] };
    }
    default:
      return assertNever(lines);
  }
};
