/* generated by purecrate-ts. do not edit. */

import type { CancelReason } from "./cancel-reason.ts";
import type { Line } from "./line.ts";
import type { Sku } from "./sku.ts";
import type { Yen } from "./yen.ts";

export type Command =
  | Readonly<{ kind: "AddLine"; value: Line }>
  | Readonly<{ kind: "RemoveSku"; value: Sku }>
  | Readonly<{ kind: "Place" }>
  | Readonly<{ kind: "Pay"; value: Yen }>
  | Readonly<{ kind: "Ship"; value: string }>
  | Readonly<{ kind: "Cancel"; value: CancelReason }>;

export const Command = {
  AddLine: (value: Line): Command => ({ kind: "AddLine", value }),
  RemoveSku: (value: Sku): Command => ({ kind: "RemoveSku", value }),
  Place: (): Command => ({ kind: "Place" }),
  Pay: (value: Yen): Command => ({ kind: "Pay", value }),
  Ship: (value: string): Command => ({ kind: "Ship", value }),
  Cancel: (value: CancelReason): Command => ({ kind: "Cancel", value }),
} as const;
