/* generated by purecrate-ts. do not edit. */

import type { Line } from "./line.ts";

export type Lines =
  | Readonly<{ kind: "Nil" }>
  | Readonly<{ kind: "Cons"; content: readonly [Line, /* Box */ Lines] }>;

export const Lines = {
  Nil: (): Lines => ({ kind: "Nil" }),
  Cons: (_0: Line, _1: /* Box */ Lines): Lines => ({ kind: "Cons", content: [_0, _1] }),
} as const;
