/* generated by purecrate-ts. do not edit. */

import type { CancelReason } from "./cancel-reason.ts";
import type { Lines } from "./lines.ts";
import type { Yen } from "./yen.ts";

export type Order =
  | Readonly<{ kind: "Draft"; lines: Lines }>
  | Readonly<{ kind: "Placed"; lines: Lines; total: Yen }>
  | Readonly<{ kind: "Paid"; lines: Lines; total: Yen }>
  | Readonly<{ kind: "Shipped"; lines: Lines; total: Yen; tracking: string }>
  | Readonly<{ kind: "Cancelled"; reason: CancelReason }>;

export const Order = {
  Draft: (lines: Lines): Order => ({ kind: "Draft", lines }),
  Placed: (lines: Lines, total: Yen): Order => ({ kind: "Placed", lines, total }),
  Paid: (lines: Lines, total: Yen): Order => ({ kind: "Paid", lines, total }),
  Shipped: (lines: Lines, total: Yen, tracking: string): Order => ({
    kind: "Shipped",
    lines,
    total,
    tracking,
  }),
  Cancelled: (reason: CancelReason): Order => ({ kind: "Cancelled", reason }),
} as const;
