/* generated by purecrate-ts. do not edit. */

import { Result } from "./purecrate-runtime.ts";
import type { Command } from "./command.ts";
import type { Lines } from "./lines.ts";
import type { OrderError } from "./order-error.ts";
import type { Order } from "./order.ts";
import type { Yen } from "./yen.ts";

export const paid = (lines: Lines, total: Yen, cmd: Command): Result<Order, OrderError> => {
  if (cmd.kind !== "Ship") return Result.err({ kind: "InvalidTransition" });
  const tracking = cmd.value;
  if (tracking.length === 0) return Result.err({ kind: "EmptyTracking" });
  return Result.ok({ kind: "Shipped", lines, total, tracking });
};
