/* generated by purecrate-ts. do not edit. */
// `purecrate` from purecrate-ts (packages/boundary), copied in at the generator's revision.
//
// Copyright (c) 2026 Wataru Manji
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/**
 * The runtime of packages generated by purecrate-ts. Every generated package
 * carries its own copy (src/purecrate-runtime.ts). The brands are keyed by
 * string, not by `unique symbol`, so an `I32` or a `Uuid` from one package's
 * copy is the same type as another's and values pass between packages.
 *
 * A package's copy keeps only what its code uses: the region and needs
 * comments below mark code kept when any use they list is found in the
 * package, and are left out of the copy (crates/pack/src/trim.rs).
 */
/** Rust's `Result`, as every generated package reads and builds it. */
export type Result<T, E> =
  | Readonly<{ kind: "Ok"; value: T }>
  | Readonly<{ kind: "Err"; error: E }>;

export const Result = {
  ok: <T, E = never>(value: T): Result<T, E> => ({ kind: "Ok", value }),
  err: <T = never, E = never>(error: E): Result<T, E> => ({ kind: "Err", error }),
  isOk: <T, E>(r: Result<T, E>): r is Readonly<{ kind: "Ok"; value: T }> => r.kind === "Ok",
  isErr: <T, E>(r: Result<T, E>): r is Readonly<{ kind: "Err"; error: E }> => r.kind === "Err",
} as const;

/**
 * A domain panic: overflow, division by zero, a shift out of range, or an
 * index/slice Rust would panic on. `message` is Rust's panic text. Named
 * `Panic` so `instanceof` works across copies of this file (`Symbol.for`).
 */
const PANIC = Symbol.for("purecrate.Panic");

export class Panic extends Error {
  readonly [PANIC] = true;
  constructor(message: string) {
    super(message);
    this.name = "Panic";
  }
  static [Symbol.hasInstance](value: unknown): boolean {
    return typeof value === "object" && value !== null && PANIC in (value as object);
  }
}

/** The `default` of a `switch` that names every variant: unreachable. */
export const assertNever = (_x: never): never => {
  throw new Error("unexpected variant");
};

export type I64 = bigint & { readonly "purecrate.I64": true };
export type U32 = number & { readonly "purecrate.U32": true };

const panic = (what: string): never => {
  throw new Panic(`attempt to ${what}`);
};

const small = <T extends number>(min: number, max: number) => {
  const fit = (n: number, what: string): T =>
    (n < min || n > max ? panic(`${what} with overflow`) : n + 0) as T;
  const of = (value: number): T => {
    if (!Number.isInteger(value)) panic("convert a non-integer");
    return fit(value, "convert");
  };
  return {
    of,
  } as const;
};

const big = <T extends bigint>(min: bigint, max: bigint) => {
  const fit = (n: bigint, what: string): T =>
    (n < min || n > max ? panic(`${what} with overflow`) : n) as T;
  return {
    of: (value: bigint): T => fit(value, "convert"),
  } as const;
};

/**
 * The integer methods, from the exact result: `x.checked_add(y)` is it or
 * `null` outside the range, `saturating_*` clamps it, `wrapping_*` keeps its
 * low `bits`, and the others panic outside the range as a debug build does.
 * `lo..=hi` is Rust's range; `to` makes the runtime value, and for `usize`
 * throws above 2^53−1, which a `number` cannot hold (design/01 §3).
 */
const methods = <T extends number | bigint>(r: { lo: bigint; hi: bigint; bits: number; signed: boolean; to: (n: bigint) => T }) => {
  const v = (x: T): bigint => BigInt(x);
  const inRange = (n: bigint): boolean => n >= r.lo && n <= r.hi;
  const checked = (n: bigint | null): T | null => (n !== null && inRange(n) ? r.to(n) : null);
  return {
    checkedAdd: (a: T, b: T): T | null => checked(v(a) + v(b)),
    checkedMul: (a: T, b: T): T | null => checked(v(a) * v(b)),
  } as const;
};

/**
 * `str` operations whose result depends on the encoding (design/01 §6).
 * Rust counts and indexes a string in UTF-8 bytes; JS in UTF-16 units. The
 * string must be well-formed: a lone surrogate is not a Rust `String`, and
 * its bytes here are not specified.
 */
export const Str = {
  /**
   * A `pub` function's string argument checked on entry: a lone surrogate
   * is in no Rust `str`, so the call panics here rather than reading its
   * bytes, which are not specified (a string, `null`, or each of an array).
   */
  wellFormed: (x: string | null | ReadonlyArray<string>): void => {
    const lone = /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/;
    for (const s of typeof x === "string" ? [x] : (x ?? [])) {
      if (lone.test(s)) panicWith("a string holds a lone surrogate, which no Rust `str` does");
    }
  },
} as const;

/**
 * The consuming iterator methods, as std's default methods run them: in
 * order, `all` stopping at the first `false`, `any` and `position` at the
 * first `true`. `sum` adds from `zero` with `add`, the type's checked
 * addition, so it panics where a debug build does.
 */
export const Iter = {
  any: <T>(xs: Iterable<T>, f: (x: T) => boolean): boolean => {
    for (const x of xs) if (f(x)) return true;
    return false;
  },
} as const;

const panicWith = (message: string): never => {
  throw new Panic(message);
};

/** Integer and float widths. Domain packages and schema adapters share these brands. */
export const Int = {
  u32: {
    ...small<U32>(0, 4294967295),
    ...methods({ lo: 0n, hi: 4294967295n, bits: 32, signed: false, to: (n) => Number(n) as U32 }),
  },
  i64: {
    ...big<I64>(-9223372036854775808n, 9223372036854775807n),
    ...methods({ lo: -9223372036854775808n, hi: 9223372036854775807n, bits: 64, signed: true, to: (n) => n as I64 }),
  },
} as const;

