/* generated by purecrate-ts. do not edit. */

import { Result, Str } from "./purecrate-runtime.ts";
import type { OrderError } from "./order-error.ts";

declare const Sku$brand: unique symbol;
export type Sku = string & { readonly [Sku$brand]: true };

/**
 * Makes `Sku` values without a check.
 *
 * Its fields are not `pub` in Rust, so outside the crate a value comes only
 * from the crate's functions; the generated files build them here, and
 * `index.ts` does not export it.
 * @internal
 */
export const unsafeMakeSku = (value: string): Sku => value as Sku;

export const Sku = {
  new: (code: string): Result<Sku, OrderError> => {
    Str.wellFormed(code);
    return code.length === 0 ? Result.err({ kind: "EmptySku" }) : Result.ok(unsafeMakeSku(code));
  },
  code: (self: Sku): string => self,
} as const;
