/* generated by purecrate-ts. do not edit. */

import { assertNever, Result } from "./purecrate-runtime.ts";
import { addLine } from "./add-line.ts";
import type { Command } from "./command.ts";
import type { Lines } from "./lines.ts";
import type { OrderError } from "./order-error.ts";
import type { Order } from "./order.ts";
import { removeSku } from "./remove-sku.ts";
import { total } from "./total.ts";
import type { Yen } from "./yen.ts";

export const step = (order: Order, cmd: Command): Result<Order, OrderError> => {
  switch (order.kind) {
    case "Draft": {
      const lines = order.lines;
      return draft(lines, cmd);
    }
    case "Placed": {
      const lines = order.lines;
      const total2 = order.total;
      return placed(lines, total2, cmd);
    }
    case "Paid": {
      const lines = order.lines;
      const total2 = order.total;
      return paid(lines, total2, cmd);
    }
    default:
      return Result.err({ kind: "InvalidTransition" });
  }
};

const draft = (lines: Lines, cmd: Command): Result<Order, OrderError> => {
  switch (cmd.kind) {
    case "AddLine": {
      const line = cmd.value;
      if (line.qty === 0) return Result.err({ kind: "QtyZero" });
      return Result.ok({ kind: "Draft", lines: addLine(lines, line) });
    }
    case "RemoveSku": {
      const sku = cmd.value;
      const removeSkuResult = removeSku(lines, sku);
      if (removeSkuResult.kind === "Err") return removeSkuResult;
      return Result.ok({ kind: "Draft", lines: removeSkuResult.value });
    }
    case "Place":
      switch (lines.kind) {
        case "Nil":
          return Result.err({ kind: "Empty" });
        case "Cons": {
          const lines2 = lines as Lines;
          const total2 = total(lines2);
          return Result.ok({ kind: "Placed", lines: lines2, total: total2 });
        }
        default:
          return assertNever(lines);
      }
    case "Cancel": {
      const reason = cmd.value;
      return Result.ok({ kind: "Cancelled", reason });
    }
    default:
      return Result.err({ kind: "InvalidTransition" });
  }
};

const placed = (lines: Lines, total2: Yen, cmd: Command): Result<Order, OrderError> => {
  switch (cmd.kind) {
    case "Pay": {
      const amount = cmd.value;
      if (amount !== total2)
        return Result.err({ kind: "AmountMismatch", expected: total2, got: amount });
      return Result.ok({ kind: "Paid", lines, total: total2 });
    }
    case "Cancel": {
      const reason = cmd.value;
      return Result.ok({ kind: "Cancelled", reason });
    }
    default:
      return Result.err({ kind: "InvalidTransition" });
  }
};

const paid = (lines: Lines, total2: Yen, cmd: Command): Result<Order, OrderError> => {
  if (cmd.kind !== "Ship") return Result.err({ kind: "InvalidTransition" });
  const tracking = cmd.value;
  if (tracking.length === 0) return Result.err({ kind: "EmptyTracking" });
  return Result.ok({ kind: "Shipped", lines, total: total2, tracking });
};
