/* generated by purecrate-ts. do not edit. */

import { Result } from "./purecrate-runtime.ts";
import type { Command } from "./command.ts";
import { draft } from "./draft.ts";
import type { OrderError } from "./order-error.ts";
import type { Order } from "./order.ts";
import { paid } from "./paid.ts";
import { placed } from "./placed.ts";

export const step = (order: Order, cmd: Command): Result<Order, OrderError> => {
  switch (order.kind) {
    case "Draft": {
      const lines = order.lines;
      return draft(lines, cmd);
    }
    case "Placed": {
      const lines = order.lines;
      const total = order.total;
      return placed(lines, total, cmd);
    }
    case "Paid": {
      const lines = order.lines;
      const total = order.total;
      return paid(lines, total, cmd);
    }
    default:
      return Result.err({ kind: "InvalidTransition" });
  }
};
