/* generated by purecrate-ts. do not edit. */

import { assertNever, Int, type I64 } from "./purecrate-runtime.ts";
import { unsafeMakeYen } from "./yen.ts";
import type { Lines } from "./lines.ts";
import type { Yen } from "./yen.ts";

export const total = (lines: Lines): Yen => {
  switch (lines.kind) {
    case "Nil":
      return unsafeMakeYen(0n as I64);
    case "Cons": {
      const line = lines.content[0];
      const rest = lines.content[1];
      return unsafeMakeYen(Int.i64.add(
        Int.i64.mul(line.unit_price, (globalThis.BigInt(line.qty) as I64)),
        total(rest),
      ));
    }
    default:
      return assertNever(lines);
  }
};
