/* generated by purecrate-ts. do not edit. */

import { Result, type I64 } from "./purecrate-runtime.ts";
import type { OrderError } from "./order-error.ts";

export type Yen = I64 & { readonly "order.Yen": true };

// A field is not `pub` in Rust: outside the crate, `Yen` values come
// only from the crate's functions. The generated files build them here;
// `index.ts` does not export it.
export const Yen$of = (value: I64): Yen => value as Yen;

export const Yen = {
  new: (amount: I64): Result<Yen, OrderError> => amount < (0n as I64) ? Result.err({ kind: "NegativeAmount" }) : Result.ok(Yen$of(amount)),
} as const;
