/* generated by purecrate-ts. do not edit. */

import { assertNever } from "./assert-never.ts";
import type { Outcome } from "./outcome.ts";
import type { PaymentMethod } from "./payment-method.ts";
import type { Status } from "./status.ts";
import type { Terms } from "./terms.ts";

export const attempt = (terms: Terms, method: PaymentMethod, outcome: Outcome): Status => {
  switch (outcome.kind) {
    case "Authorized":
      return ((() => {
        switch (terms.capture.kind) {
          case "Manual":
            return true;
          case "Automatic":
            return false;
          default:
            return assertNever(terms.capture);
        }
      })() ? { kind: "RequiresCapture", method: method, capturable: terms.amount } : { kind: "Succeeded", received: terms.amount, application_fee: null });
    case "ActionRequired":
      return { kind: "RequiresAction", method: method };
    case "Pending":
      return { kind: "Processing", method: method };
    case "Declined": {
      const code = outcome.content[0];
      return { kind: "RequiresPaymentMethod", last_error: code };
    }
    default:
      return assertNever(outcome);
  }
};
