/* generated by purecrate-ts. do not edit. */

import { Result } from "./purecrate-runtime.ts";
import type { PaymentError } from "./payment-error.ts";
import type { Status } from "./status.ts";
import type { Terms } from "./terms.ts";
import type { UncheckedIntent } from "./unchecked-intent.ts";

/**
 * An intent whose amounts agree with its terms: `PaymentIntent::new`
 * checks them, and `step` keeps them (see `consistent`).
 */
declare const PaymentIntent$brand: unique symbol;
export type PaymentIntent = Readonly<{
  terms: Terms;
  status: Status;
}> & { readonly [PaymentIntent$brand]: true };

/**
 * Makes `PaymentIntent` values without a check.
 *
 * Its fields are not `pub` in Rust, so outside the crate a value comes only
 * from the crate's functions; the generated files build them here, and
 * `index.ts` does not export it.
 * @internal
 */
export const unsafeMakePaymentIntent = (
  fields: Readonly<{ terms: Terms; status: Status }>,
): PaymentIntent => fields as PaymentIntent;

export const PaymentIntent = {
  new: (raw: UncheckedIntent): Result<PaymentIntent, PaymentError> => {
    if (!consistent(raw.terms, raw.status)) return Result.err({ kind: "InconsistentStatus" });
    return Result.ok(unsafeMakePaymentIntent({ terms: raw.terms, status: raw.status }));
  },
  terms: (self: PaymentIntent): Terms => self.terms,
  status: (self: PaymentIntent): Status => self.status,
  tryFrom: (raw: UncheckedIntent): Result<PaymentIntent, PaymentError> => PaymentIntent.new(raw),
} as const;

/**
 * Stripe's amounts against the intent's: `amount_capturable` and
 * `amount_received` are at most `amount` (and at least 1, as a capture of 0
 * is refused here); `requires_capture` happens with manual capture only;
 * an automatic capture receives the whole amount and carries no fee; the
 * application fee is not negative and is capped at the amount captured.
 */
const consistent = (terms: Terms, status: Status): boolean => {
  const amount = terms.amount;
  const manual = terms.capture.kind === "Manual";

  switch (status.kind) {
    case "RequiresCapture": {
      const capturable = status.capturable;
      return manual && capturable >= 1n && capturable <= amount;
    }
    case "Succeeded": {
      const received = status.received;
      const applicationFee = status.application_fee;
      const feeOk =
        applicationFee === null || (manual && applicationFee >= 0n && applicationFee <= received);
      return feeOk && received >= 1n && received <= amount && (manual || received === amount);
    }
    default:
      return true;
  }
};
