/* generated by purecrate-ts. do not edit. */

import { assertNever, Int, Result, type I64 } from "./purecrate-runtime.ts";
import { attempt } from "./attempt.ts";
import type { Event } from "./event.ts";
import type { PaymentError } from "./payment-error.ts";
import type { PaymentIntent } from "./payment-intent.ts";
import type { Status } from "./status.ts";

export const step = (intent: PaymentIntent, event: Event): Result<PaymentIntent, PaymentError> => {
  const terms = intent.terms;
  let status: Status;
  switch (intent.status.kind) {
    case "RequiresPaymentMethod":
      switch (event.kind) {
        case "AttachMethod": {
          const method = event.value;
          status = { kind: "RequiresConfirmation", method };
          break;
        }
        case "Confirm": {
          const method = event.method;
          const outcome = event.outcome;
          if (method === null) return Result.err({ kind: "MissingPaymentMethod" });
          status = attempt(terms, method, outcome);
          break;
        }
        case "Cancel": {
          const reason = event.value;
          status = { kind: "Canceled", reason };
          break;
        }
        default:
          return Result.err({ kind: "InvalidTransition" });
      }
      break;
    case "RequiresConfirmation": {
      const current = intent.status.method;
      switch (event.kind) {
        case "AttachMethod": {
          const method = event.value;
          status = { kind: "RequiresConfirmation", method };
          break;
        }
        case "Confirm": {
          const method = event.method;
          const outcome = event.outcome;
          status = attempt(terms, method ?? current, outcome);
          break;
        }
        case "Cancel": {
          const reason = event.value;
          status = { kind: "Canceled", reason };
          break;
        }
        default:
          return Result.err({ kind: "InvalidTransition" });
      }
      break;
    }
    case "RequiresAction": {
      const method = intent.status.method;
      switch (event.kind) {
        case "ActionHandled": {
          const outcome = event.value;
          if (terms.confirmation.kind === "Manual" && outcome.kind !== "Declined") {
            status = { kind: "RequiresConfirmation", method };
          } else {
            status = attempt(terms, method, outcome);
          }
          break;
        }
        case "Cancel": {
          const reason = event.value;
          status = { kind: "Canceled", reason };
          break;
        }
        default:
          return Result.err({ kind: "InvalidTransition" });
      }
      break;
    }
    case "Processing": {
      const method = intent.status.method;
      switch (event.kind) {
        case "ProcessingSucceeded":
          status = attempt(terms, method, { kind: "Authorized" });
          break;
        case "ProcessingFailed": {
          const code = event.value;
          status = { kind: "RequiresPaymentMethod", last_error: code };
          break;
        }
        case "Cancel": {
          const reason = event.value;
          if (method.kind.kind !== "BankDebit") return Result.err({ kind: "NotCancelable" });
          status = { kind: "Canceled", reason };
          break;
        }
        default:
          return Result.err({ kind: "InvalidTransition" });
      }
      break;
    }
    case "RequiresCapture": {
      const capturable = intent.status.capturable;
      switch (event.kind) {
        case "Capture": {
          const amountToCapture = event.amount_to_capture;
          const applicationFee = event.application_fee;
          if (amountToCapture !== null && (amountToCapture < 1n || amountToCapture > capturable))
            return Result.err({ kind: "InvalidCaptureAmount", capturable });
          if (applicationFee !== null && applicationFee < 0n)
            return Result.err({ kind: "NegativeApplicationFee" });
          const received: I64 = amountToCapture ?? capturable;
          status = {
            kind: "Succeeded",
            received,
            application_fee: applicationFee !== null ? Int.i64.min(applicationFee, received) : null,
          };
          break;
        }
        case "Cancel": {
          const reason = event.value;
          status = { kind: "Canceled", reason };
          break;
        }
        default:
          return Result.err({ kind: "InvalidTransition" });
      }
      break;
    }
    case "Succeeded":
    case "Canceled":
      switch (event.kind) {
        case "Cancel":
          return Result.err({ kind: "NotCancelable" });
        default:
          return Result.err({ kind: "InvalidTransition" });
      }
    default:
      return assertNever(intent.status);
  }
  return Result.ok({ terms, status });
};
