/* generated by purecrate-ts. do not edit. */

import { assertNever, Json, parseJson } from "./purecrate-runtime.ts";
import { type } from "arktype";
import { fail, i64, keyed, memo, record, unitEnum, type Wire } from "./purecrate-arktype.ts";
import type { Group as DomainGroup } from "./group.ts";
import { InvoiceError as DomainInvoiceError } from "./invoice-error.ts";
import type { Invoice as DomainInvoice } from "./invoice.ts";
import type { Line as DomainLine } from "./line.ts";
import type { Method as DomainMethod } from "./method.ts";
import type { Pricing as DomainPricing } from "./pricing.ts";
import type { Rate as DomainRate } from "./rate.ts";
import type { Rounding as DomainRounding } from "./rounding.ts";
import type { Summary as DomainSummary } from "./summary.ts";
import { Yen as DomainYen } from "./yen.ts";

const yenWire = memo(() => i64);
export const Yen: Wire<DomainYen> = type("unknown").pipe((v, ctx): DomainYen => {
  const parsed = yenWire()(v);
  if (parsed instanceof type.errors) return fail(ctx, parsed);
  const r = DomainYen.tryFrom(parsed);
  if (r.kind === "Err") return ctx.error(`Yen: ${DomainInvoiceError.toString(r.error)}`) as never;
  return r.value;
});

export const Rate: Wire<DomainRate> = unitEnum("Rate", ["Standard", "Reduced"]);

export const Pricing: Wire<DomainPricing> = unitEnum("Pricing", ["Exclusive", "Inclusive"]);

export const Rounding: Wire<DomainRounding> = unitEnum("Rounding", ["Down", "Up", "HalfUp"]);

const methodSeparateArm = memo(() => type({ "+": "reject", Separate: "null" }));
const methodToExclusiveArm = memo(() =>
  type({ "+": "reject", ToExclusive: type({ conversion: Rounding }).narrow(record) }),
);
/** 問59: what to do with tax-inclusive lines among tax-exclusive ones. */
export const Method: Wire<DomainMethod> = type("unknown").pipe((v, ctx): DomainMethod => {
  if (v === "Separate") return { kind: "Separate" };
  {
    const parsed = methodSeparateArm()(v);
    if (!(parsed instanceof type.errors)) return { kind: "Separate" };
    if (keyed(v, "Separate")) return fail(ctx, parsed);
  }
  {
    const parsed = methodToExclusiveArm()(v);
    if (!(parsed instanceof type.errors))
      return { kind: "ToExclusive", conversion: parsed.ToExclusive.conversion };
    if (keyed(v, "ToExclusive")) return fail(ctx, parsed);
  }
  return ctx.error("Method") as never;
});

const lineWire = memo(() => type({ amount: Yen, rate: Rate, pricing: Pricing }).narrow(record));
export const Line: Wire<DomainLine> = type("unknown").pipe((v, ctx): DomainLine => {
  const parsed = lineWire()(v);
  if (parsed instanceof type.errors) return fail(ctx, parsed);
  return { amount: parsed.amount, rate: parsed.rate, pricing: parsed.pricing };
});

const invoiceWire = memo(() =>
  type({ lines: Line.array(), rounding: Rounding, method: Method }).narrow(record),
);
export const Invoice: Wire<DomainInvoice> = type("unknown").pipe((v, ctx): DomainInvoice => {
  const parsed = invoiceWire()(v);
  if (parsed instanceof type.errors) return fail(ctx, parsed);
  return { lines: parsed.lines, rounding: parsed.rounding, method: parsed.method };
});

const groupWire = memo(() => type({ base: Yen, tax: Yen }).narrow(record));
/** One rate and pricing: the total of its amounts and the tax on it. */
export const Group: Wire<DomainGroup> = type("unknown").pipe((v, ctx): DomainGroup => {
  const parsed = groupWire()(v);
  if (parsed instanceof type.errors) return fail(ctx, parsed);
  return { base: parsed.base, tax: parsed.tax };
});

const summaryWire = memo(() =>
  type({
    standard: Group,
    reduced: Group,
    standard_inclusive: Group,
    reduced_inclusive: Group,
    total: Yen,
  }).narrow(record),
);
export const Summary: Wire<DomainSummary> = type("unknown").pipe((v, ctx): DomainSummary => {
  const parsed = summaryWire()(v);
  if (parsed instanceof type.errors) return fail(ctx, parsed);
  return {
    standard: parsed.standard,
    reduced: parsed.reduced,
    standard_inclusive: parsed.standard_inclusive,
    reduced_inclusive: parsed.reduced_inclusive,
    total: parsed.total,
  };
});

export const InvoiceError: Wire<DomainInvoiceError> = unitEnum("InvoiceError", [
  "NegativeAmount",
  "NoLines",
]);

/**
 * Each type read from the JSON text serde_json writes, through `parseJson`;
 * throws on malformed text or a value the schema refuses.
 */
export const fromJson = {
  Yen: (text: string): DomainYen => Yen.assert(parseJson(text)),
  Rate: (text: string): DomainRate => Rate.assert(parseJson(text)),
  Pricing: (text: string): DomainPricing => Pricing.assert(parseJson(text)),
  Rounding: (text: string): DomainRounding => Rounding.assert(parseJson(text)),
  Method: (text: string): DomainMethod => Method.assert(parseJson(text)),
  Line: (text: string): DomainLine => Line.assert(parseJson(text)),
  Invoice: (text: string): DomainInvoice => Invoice.assert(parseJson(text)),
  Group: (text: string): DomainGroup => Group.assert(parseJson(text)),
  Summary: (text: string): DomainSummary => Summary.assert(parseJson(text)),
  InvoiceError: (text: string): DomainInvoiceError => InvoiceError.assert(parseJson(text)),
} as const;

/** Each type written as serde_json writes the Rust value. */
export const toJson = {
  Yen: (x: DomainYen): string => Json.int(x),
  Rate: (x: DomainRate): string => `"${x.kind}"`,
  Pricing: (x: DomainPricing): string => `"${x.kind}"`,
  Rounding: (x: DomainRounding): string => `"${x.kind}"`,
  Method: (x: DomainMethod): string => {
    switch (x.kind) {
      case "Separate":
        return '"Separate"';
      case "ToExclusive":
        return Json.object([
          ["ToExclusive", Json.object([["conversion", toJson.Rounding(x.conversion)]])],
        ]);
      default:
        return assertNever(x);
    }
  },
  Line: (x: DomainLine): string =>
    Json.object([
      ["amount", toJson.Yen(x.amount)],
      ["rate", toJson.Rate(x.rate)],
      ["pricing", toJson.Pricing(x.pricing)],
    ]),
  Invoice: (x: DomainInvoice): string =>
    Json.object([
      ["lines", Json.array(x.lines, (v0) => toJson.Line(v0))],
      ["rounding", toJson.Rounding(x.rounding)],
      ["method", toJson.Method(x.method)],
    ]),
  Group: (x: DomainGroup): string =>
    Json.object([
      ["base", toJson.Yen(x.base)],
      ["tax", toJson.Yen(x.tax)],
    ]),
  Summary: (x: DomainSummary): string =>
    Json.object([
      ["standard", toJson.Group(x.standard)],
      ["reduced", toJson.Group(x.reduced)],
      ["standard_inclusive", toJson.Group(x.standard_inclusive)],
      ["reduced_inclusive", toJson.Group(x.reduced_inclusive)],
      ["total", toJson.Yen(x.total)],
    ]),
  InvoiceError: (x: DomainInvoiceError): string => `"${x.kind}"`,
} as const;
