/* generated by purecrate-ts. do not edit. */

import { Str, Iter, type U8 } from "./purecrate-runtime.ts";

export const all_digits = (s: string): boolean => Iter.all(
  Str.bytes(s),
  ((b: U8): boolean => b >= (48 as U8) && b <= (57 as U8)),
);
