/* generated by purecrate-ts. do not edit. */

import { assertNever } from "./assert-never.ts";
import { compare_pre_id } from "./compare-pre-id.ts";
import type { Ordering } from "./ordering.ts";
import type { PreIds } from "./pre-ids.ts";

/** Identifiers left to right; a longer list with an equal prefix is greater. */
export const compare_pre_ids = (a: PreIds, b: PreIds): Ordering => {
  switch (a.kind) {
    case "Nil":
      switch (b.kind) {
        case "Nil":
          return { kind: "Equal" };
        case "Cons":
          return { kind: "Less" };
        default:
          return assertNever(b);
      }
    case "Cons": {
      const x = a.content[0];
      const xs = a.content[1];
      switch (b.kind) {
        case "Nil":
          return { kind: "Greater" };
        case "Cons": {
          const y = b.content[0];
          const ys = b.content[1];
          const $ord1: Ordering = compare_pre_id(x, y);
          switch ($ord1.kind) {
            case "Less":
              return { kind: "Less" };
            case "Equal":
              return compare_pre_ids(xs, ys);
            case "Greater":
              return { kind: "Greater" };
            default:
              return assertNever($ord1);
          }
        }
        default:
          return assertNever(b);
      }
    }
    default:
      return assertNever(a);
  }
};
