/* generated by purecrate-ts. do not edit. */

import { assertNever } from "./assert-never.ts";
import { type U64 } from "./int.ts";
import { compare_pre_ids } from "./compare-pre-ids.ts";
import type { Ordering } from "./ordering.ts";
import type { PreIds } from "./pre-ids.ts";
import type { Version } from "./version.ts";

/** Precedence per SemVer 2.0.0 §11. Build metadata is ignored. */
export const compare = (a: Version, b: Version): Ordering => {
  let $ord11: Ordering;
  {
    let $ord7: Ordering;
    {
      let $ord3: Ordering;
      {
        const $lhs1: U64 = a.major;
        const $rhs2: U64 = b.major;
        $ord3 = ($lhs1 < $rhs2 ? { kind: "Less" } : ($lhs1 === $rhs2 ? { kind: "Equal" } : { kind: "Greater" }));
      }
      let $arg6: Ordering;
      {
        const $lhs4: U64 = a.minor;
        const $rhs5: U64 = b.minor;
        $arg6 = ($lhs4 < $rhs5 ? { kind: "Less" } : ($lhs4 === $rhs5 ? { kind: "Equal" } : { kind: "Greater" }));
      }
      switch ($ord3.kind) {
        case "Less":
          $ord7 = { kind: "Less" };
          break;
        case "Equal":
          $ord7 = $arg6;
          break;
        case "Greater":
          $ord7 = { kind: "Greater" };
          break;
        default:
          return assertNever($ord3);
      }
    }
    let $arg10: Ordering;
    {
      const $lhs8: U64 = a.patch;
      const $rhs9: U64 = b.patch;
      $arg10 = ($lhs8 < $rhs9 ? { kind: "Less" } : ($lhs8 === $rhs9 ? { kind: "Equal" } : { kind: "Greater" }));
    }
    switch ($ord7.kind) {
      case "Less":
        $ord11 = { kind: "Less" };
        break;
      case "Equal":
        $ord11 = $arg10;
        break;
      case "Greater":
        $ord11 = { kind: "Greater" };
        break;
      default:
        return assertNever($ord7);
    }
  }
  switch ($ord11.kind) {
    case "Less":
      return { kind: "Less" };
    case "Equal":
      switch (a.pre.kind) {
        case "Nil":
          switch (b.pre.kind) {
            case "Nil":
              return { kind: "Equal" };
            case "Cons":
              return { kind: "Greater" };
            default:
              return assertNever(b.pre);
          }
        case "Cons":
          switch (b.pre.kind) {
            case "Nil":
              return { kind: "Less" };
            case "Cons": {
              const x = a.pre as PreIds;
              const y = b.pre as PreIds;
              return compare_pre_ids(x, y);
            }
            default:
              return assertNever(b.pre);
          }
        default:
          return assertNever(a.pre);
      }
    case "Greater":
      return { kind: "Greater" };
    default:
      return assertNever($ord11);
  }
};
