/* generated by purecrate-ts. do not edit. */

import { assertNever, Ord } from "./purecrate-runtime.ts";
import type { Ordering } from "./ordering.ts";
import type { PreId } from "./pre-id.ts";

export const comparePreId = (a: PreId, b: PreId): Ordering => {
  switch (a.kind) {
    case "Numeric": {
      const x = a.content[0];
      switch (b.kind) {
        case "Numeric": {
          const y = b.content[0];
          return Ord.cmp(x, y);
        }
        case "Alpha":
          return { kind: "Less" };
        default:
          return assertNever(b);
      }
    }
    case "Alpha": {
      const x$1 = a.content[0];
      switch (b.kind) {
        case "Numeric":
          return { kind: "Greater" };
        case "Alpha": {
          const y$1 = b.content[0];
          return Ord.cmpStr(x$1, y$1);
        }
        default:
          return assertNever(b);
      }
    }
    default:
      return assertNever(a);
  }
};
