/* generated by purecrate-ts. do not edit. */

import { assertNever } from "./assert-never.ts";
import { Ord } from "./str.ts";
import { compare_pre_ids } from "./compare-pre-ids.ts";
import type { Ordering } from "./ordering.ts";
import type { PreIds } from "./pre-ids.ts";
import type { Version } from "./version.ts";

/** Precedence per SemVer 2.0.0 §11. Build metadata is ignored. */
export const compare = (a: Version, b: Version): Ordering => {
  const $ord3: Ordering = Ord.then(
    Ord.then(Ord.cmp(a.major, b.major), Ord.cmp(a.minor, b.minor)),
    Ord.cmp(a.patch, b.patch),
  );
  switch ($ord3.kind) {
    case "Less":
      return { kind: "Less" };
    case "Equal":
      switch (a.pre.kind) {
        case "Nil":
          switch (b.pre.kind) {
            case "Nil":
              return { kind: "Equal" };
            case "Cons":
              return { kind: "Greater" };
            default:
              return assertNever(b.pre);
          }
        case "Cons":
          switch (b.pre.kind) {
            case "Nil":
              return { kind: "Less" };
            case "Cons": {
              const x = a.pre as PreIds;
              const y = b.pre as PreIds;
              return compare_pre_ids(x, y);
            }
            default:
              return assertNever(b.pre);
          }
        default:
          return assertNever(a.pre);
      }
    case "Greater":
      return { kind: "Greater" };
    default:
      return assertNever($ord3);
  }
};
