/* generated by purecrate-ts. do not edit. */

import { Int, Str, type U64, type U8 } from "./purecrate-runtime.ts";

/** Digits only, already checked non-empty. `None` on overflow. */
export const digits_to_u64 = (s: string): U64 | null => {
  let acc: U64 = 0n as U64;
  for (const b of Str.bytes(s)) {
    const $q1 = Int.u64.checkedMul(acc, (10n as U64));
    if ($q1 === null) return null;
    const $q2 = Int.u64.checkedAdd($q1, (globalThis.BigInt(Int.u8.sub(b, (48 as U8))) as U64));
    if ($q2 === null) return null;
    acc = $q2;
  }
  return acc;
};
