/* generated by purecrate-ts. do not edit. */

import { Str, type Usize } from "./purecrate-runtime.ts";

export const hasLeadingZero = (s: string): boolean => (Str.len(s) > (1 as Usize)) && s.startsWith("0");
