/* generated by purecrate-ts. do not edit. */

import { Result, Str, Iter, type U8 } from "./purecrate-runtime.ts";
import { isIdentChar } from "./is-ident-char.ts";
import type { SemverError } from "./semver-error.ts";

export const parseBuildId = (s: string): Result<string, SemverError> => {
  if (s === "") {
    return Result.err({ kind: "EmptyBuild" });
  } else {
    return !Iter.all(
      Str.bytes(s),
      ((x: U8): boolean => isIdentChar(x)),
    ) ? Result.err({ kind: "InvalidBuildChar" }) : Result.ok(s);
  }
};
