/* generated by purecrate-ts. do not edit. */

import { Int, Result, Str, Iter, type ParseIntError, type U64 } from "./purecrate-runtime.ts";
import { allDigits } from "./all-digits.ts";
import { hasLeadingZero } from "./has-leading-zero.ts";
import { isIdentChar } from "./is-ident-char.ts";
import type { PreId } from "./pre-id.ts";
import type { SemverError } from "./semver-error.ts";

export const parsePreId = (s: string): Result<PreId, SemverError> => {
  if (s === "") return Result.err({ kind: "EmptyPreRelease" });
  if (!Iter.all(Str.bytes(s), isIdentChar)) return Result.err({ kind: "InvalidPreReleaseChar" });
  if (!allDigits(s)) return Result.ok({ kind: "Alpha", value: s });
  if (hasLeadingZero(s)) return Result.err({ kind: "PreReleaseLeadingZero" });
  let result: Result<PreId, ParseIntError>;
  {
    const result2: Result<U64, ParseIntError> = Int.u64.parse(s);
    result = result2.kind === "Ok" ? Result.ok({
      kind: "Numeric",
      value: result2.value,
    }) : Result.err(result2.error);
  }
  return result.kind === "Ok"
    ? Result.ok(result.value)
    : Result.err({ kind: "PreReleaseTooLarge" });
};
