/* generated by purecrate-ts. do not edit. */

import { Int, Result, type ParseIntError, type U64 } from "./purecrate-runtime.ts";
import { allDigits } from "./all-digits.ts";
import { hasLeadingZero } from "./has-leading-zero.ts";
import type { CorePart } from "./core-part.ts";
import type { SemverError } from "./semver-error.ts";

export const parseCoreNumber = (s: string, part: CorePart): Result<U64, SemverError> => {
  if (s === "") {
    return Result.err({ kind: "EmptyNumber", value: part });
  } else {
    if (!allDigits(s)) {
      return Result.err({ kind: "NotANumber", value: part });
    } else {
      if (hasLeadingZero(s)) {
        return Result.err({ kind: "LeadingZero", value: part });
      } else {
        const result: Result<U64, ParseIntError> = Int.u64.parse(s);
        return result.kind === "Ok" ? Result.ok(result.value) : Result.err({
          kind: "NumberTooLarge",
          value: part,
        });
      }
    }
  }
};
