/* generated by purecrate-ts. do not edit. */

import { Result, Str, type U64, type Usize } from "./purecrate-runtime.ts";
import { allDigits } from "./all-digits.ts";
import { digitsToU64 } from "./digits-to-u64.ts";
import type { CorePart } from "./core-part.ts";
import type { SemverError } from "./semver-error.ts";

export const parseCoreNumber = (s: string, part: CorePart): Result<U64, SemverError> => {
  if (s.length === 0) return Result.err({ kind: "EmptyNumber", content: [part] });
  if (!allDigits(s)) return Result.err({ kind: "NotANumber", content: [part] });
  if ((Str.len(s) > (1 as Usize)) && s.startsWith("0")) return Result.err({
    kind: "LeadingZero",
    content: [part],
  });
  const $opt1: U64 | null = digitsToU64(s);
  const $arg3 = { kind: "NumberTooLarge", content: [part] } as SemverError;
  let $res4: Result<U64, SemverError>;
  if ($opt1 !== null) {
    const $some2 = $opt1;
    $res4 = Result.ok($some2);
  } else {
    $res4 = Result.err($arg3);
  }
  return $res4;
};
