/* generated by purecrate-ts. do not edit. */

import { Result, Str, Iter, type U8, type Usize } from "./purecrate-runtime.ts";
import { all_digits } from "./all-digits.ts";
import { digits_to_u64 } from "./digits-to-u64.ts";
import { is_ident_char } from "./is-ident-char.ts";
import type { PreId } from "./pre-id.ts";
import type { SemverError } from "./semver-error.ts";

export const parse_pre_id = (s: string): Result<PreId, SemverError> => {
  if (s.length === 0) return Result.err({ kind: "EmptyPreRelease" });
  if (!Iter.all(
    Str.bytes(s),
    (($x1: U8): boolean => is_ident_char($x1)),
  )) return Result.err({ kind: "InvalidPreReleaseChar" });
  if (all_digits(s)) {
    if ((Str.len(s) > (1 as Usize)) && s.startsWith("0")) return Result.err({ kind: "PreReleaseLeadingZero" });
    return (() => {
      const $m_3 = digits_to_u64(s);
      if ($m_3 !== null) {
        const n = $m_3;
        return Result.ok({ kind: "Numeric", content: [n] });
      } else {
        return Result.err({ kind: "PreReleaseTooLarge" });
      }
    })();
  }
  return Result.ok({ kind: "Alpha", content: [s] });
};
