/* generated by purecrate-ts. do not edit. */

/**
 * One pre-release identifier. A numeric one is its digits, without a
 * leading zero.
 */
export type PreId =
  | Readonly<{ kind: "Numeric"; value: string }>
  | Readonly<{ kind: "Alpha"; value: string }>;

export const PreId = {
  Numeric: (value: string): PreId => ({ kind: "Numeric", value }),
  Alpha: (value: string): PreId => ({ kind: "Alpha", value }),
} as const;
