/* generated by purecrate-ts. do not edit. */

import {
  Int,
  Result,
  Str,
  Iter,
  type Char,
  type U32,
  type U64,
  type U8,
  type Usize,
} from "./purecrate-runtime.ts";
import { parseBuildIds } from "./parse-build-ids.ts";
import { parseCoreNumber } from "./parse-core-number.ts";
import { parsePreIds } from "./parse-pre-ids.ts";
import type { BuildIds } from "./build-ids.ts";
import type { PreIds } from "./pre-ids.ts";
import type { SemverError } from "./semver-error.ts";

/** A valid semantic version. Only [`Version::parse`] makes one. */
export type Version = Readonly<{
  major: U64;
  minor: U64;
  patch: U64;
  pre: PreIds;
  build: BuildIds;
}> & { readonly "semver.Version": true };

// A field is not `pub` in Rust: outside the crate, `Version` values come
// only from the crate's functions. The generated files build them here;
// `index.ts` does not export it.
export const Version$of = (fields: Readonly<{ major: U64; minor: U64; patch: U64; pre: PreIds; build: BuildIds }>): Version => fields as Version;

export const Version = {
  parse: (s: string): Result<Version, SemverError> => {
    if (s.length === 0) return Result.err({ kind: "Empty" });
    const plus: Usize | null = Iter.position(Str.bytes(s), ((b: U8): boolean => b === (43 as U8)));
    let rest: string;
    if (plus !== null) {
      const i = plus;
      rest = Str.slice(s, (0 as Usize), i);
    } else {
      rest = s;
    }
    const dash: Usize | null = Iter.position(
      Str.bytes(rest),
      ((b$1: U8): boolean => b$1 === (45 as U8)),
    );
    let core: string;
    if (dash !== null) {
      const i$1 = dash;
      core = Str.slice(rest, (0 as Usize), i$1);
    } else {
      core = rest;
    }
    let major: U64 | null = null;
    let minor: U64 | null = null;
    let patch: U64 | null = null;
    let n: U32 = 0 as U32;
    for (const piece of core.split(("." as Char))) {
      if (n === (0 as U32)) {
        const $parseCoreNumber = parseCoreNumber(piece, { kind: "Major" });
        if ($parseCoreNumber.kind === "Err") return $parseCoreNumber;
        major = $parseCoreNumber.value;
      } else if (n === (1 as U32)) {
        const $parseCoreNumber2 = parseCoreNumber(piece, { kind: "Minor" });
        if ($parseCoreNumber2.kind === "Err") return $parseCoreNumber2;
        minor = $parseCoreNumber2.value;
      } else if (n === (2 as U32)) {
        const $parseCoreNumber3 = parseCoreNumber(piece, { kind: "Patch" });
        if ($parseCoreNumber3.kind === "Err") return $parseCoreNumber3;
        patch = $parseCoreNumber3.value;
      } else {
        return Result.err({ kind: "ExtraCorePart" });
      }
      n = Int.u32.add(n, (1 as U32));
    }
    const $major = major as U64 | null;
    const $majorOr = { kind: "MissingPart", content: [{ kind: "Major" }] } as SemverError;
    if ($major === null) return Result.err($majorOr);
    const major$1: U64 = $major;
    const $minor = minor as U64 | null;
    const $minorOr = { kind: "MissingPart", content: [{ kind: "Minor" }] } as SemverError;
    if ($minor === null) return Result.err($minorOr);
    const minor$1: U64 = $minor;
    const $patch = patch as U64 | null;
    const $patchOr = { kind: "MissingPart", content: [{ kind: "Patch" }] } as SemverError;
    if ($patch === null) return Result.err($patchOr);
    const patch$1: U64 = $patch;
    let pre: PreIds;
    if (dash !== null) {
      const i$2 = dash;
      const $parsePreIds = parsePreIds(Str.slice(rest, Int.usize.add(i$2, (1 as Usize))));
      if ($parsePreIds.kind === "Err") return $parsePreIds;
      pre = $parsePreIds.value;
    } else {
      pre = { kind: "Nil" };
    }
    let build: BuildIds;
    if (plus !== null) {
      const i$3 = plus;
      const $parseBuildIds = parseBuildIds(Str.slice(s, Int.usize.add(i$3, (1 as Usize))));
      if ($parseBuildIds.kind === "Err") return $parseBuildIds;
      build = $parseBuildIds.value;
    } else {
      build = { kind: "Nil" };
    }
    return Result.ok(Version$of({ major: major$1, minor: minor$1, patch: patch$1, pre, build }));
  },
  major: (self: Version): U64 => self.major,
  minor: (self: Version): U64 => self.minor,
  patch: (self: Version): U64 => self.patch,
  preRelease: (self: Version): PreIds => self.pre,
  buildMetadata: (self: Version): BuildIds => self.build,
  isPreRelease: (self: Version): boolean => self.pre.kind !== "Nil",
} as const;
