/* generated by purecrate-ts. do not edit. */

import { Result, Str, Slice, Iter, type U64, type Usize } from "./purecrate-runtime.ts";
import { parseBuildId } from "./parse-build-id.ts";
import { parseCoreNumber } from "./parse-core-number.ts";
import { parsePreId } from "./parse-pre-id.ts";
import type { PreId } from "./pre-id.ts";
import type { SemverError } from "./semver-error.ts";

/** A valid semantic version. Only [`Version::parse`] makes one. */
export type Version = Readonly<{
  major: U64;
  minor: U64;
  patch: U64;
  pre: ReadonlyArray<PreId>;
  build: ReadonlyArray<string>;
}> & { readonly "semver.Version": true };

// A field is not `pub` in Rust: outside the crate, `Version` values come
// only from the crate's functions. The generated files build them here;
// `index.ts` does not export it.
export const Version$of = (fields: Readonly<{
  major: U64;
  minor: U64;
  patch: U64;
  pre: ReadonlyArray<PreId>;
  build: ReadonlyArray<string>;
}>): Version => fields as Version;

export const Version = {
  parse: (s: string): Result<Version, SemverError> => {
    if (s.length === 0) return Result.err({ kind: "Empty" });
    const option = Str.splitOnce(s, "+");
    const [rest, build] = option !== null ? [option[0], option[1]] : [s, null];
    const option2 = Str.splitOnce(rest, "-");
    const [core, pre] = option2 !== null ? [option2[0], option2[1]] : [rest, null];
    const parts: ReadonlyArray<string> = core.split(".");
    const majorResult = parseCoreNumber(Slice.at(parts, 0 as Usize), { kind: "Major" });
    if (majorResult.kind === "Err") return majorResult;
    const major: U64 = majorResult.value;
    if (parts.length < 2) return Result.err({ kind: "MissingPart", value: { kind: "Minor" } });
    const minorResult = parseCoreNumber(Slice.at(parts, 1 as Usize), { kind: "Minor" });
    if (minorResult.kind === "Err") return minorResult;
    const minor: U64 = minorResult.value;
    if (parts.length < 3) return Result.err({ kind: "MissingPart", value: { kind: "Patch" } });
    const patchResult = parseCoreNumber(Slice.at(parts, 2 as Usize), { kind: "Patch" });
    if (patchResult.kind === "Err") return patchResult;
    const patch: U64 = patchResult.value;
    if (parts.length > 3) return Result.err({ kind: "ExtraCorePart" });
    let pre2: ReadonlyArray<PreId>;
    if (pre !== null) {
      const p = pre;
      const result = Iter.tryCollect(p.split("."), parsePreId);
      if (result.kind === "Err") return result;
      pre2 = result.value;
    } else {
      pre2 = [];
    }
    let build2: ReadonlyArray<string>;
    if (build !== null) {
      const b = build;
      const result2 = Iter.tryCollect(b.split("."), parseBuildId);
      if (result2.kind === "Err") return result2;
      build2 = result2.value;
    } else {
      build2 = [];
    }
    return Result.ok(Version$of({ major, minor, patch, pre: pre2, build: build2 }));
  },
  major: (self: Version): U64 => self.major,
  minor: (self: Version): U64 => self.minor,
  patch: (self: Version): U64 => self.patch,
  preRelease: (self: Version): ReadonlyArray<PreId> => self.pre,
  buildMetadata: (self: Version): ReadonlyArray<string> => self.build,
  isPreRelease: (self: Version): boolean => self.pre.length !== 0,
} as const;
