/* generated by purecrate-ts. do not edit. */

export type Client = Readonly<{
  client_id: string;
  redirect_uris: ReadonlyArray<string>;
  require_pkce: boolean;
  allow_plain_pkce: boolean;
}>;

export const Client = {
  of: (client_id: string, redirect_uris: ReadonlyArray<string>, require_pkce: boolean, allow_plain_pkce: boolean): Client => ({ client_id, redirect_uris, require_pkce, allow_plain_pkce }),
} as const;
