/* generated by purecrate-ts. do not edit. */

import type { Direction } from "./direction.ts";

/** The list negotiation found nothing in common for. */
export type Category =
  | Readonly<{ kind: "Kex" }>
  | Readonly<{ kind: "HostKey" }>
  | Readonly<{ kind: "Cipher"; value: Direction }>
  | Readonly<{ kind: "Mac"; value: Direction }>
  | Readonly<{ kind: "Compression"; value: Direction }>;

export const Category = {
  Kex: (): Category => ({ kind: "Kex" }),
  HostKey: (): Category => ({ kind: "HostKey" }),
  Cipher: (value: Direction): Category => ({ kind: "Cipher", value }),
  Mac: (value: Direction): Category => ({ kind: "Mac", value }),
  Compression: (value: Direction): Category => ({ kind: "Compression", value }),
} as const;
