/* generated by purecrate-ts. do not edit. */

import type { U32, Usize } from "./purecrate-runtime.ts";

/**
 * Key and IV lengths in bytes, block size, and whether the cipher
 * authenticates the packet itself (OpenSSH's cipher table).
 */
export type CipherSpec = Readonly<{
  key_len: Usize;
  iv_len: Usize;
  block: U32;
  aead: boolean;
}>;

export const CipherSpec = {
  of: (keyLen: Usize, ivLen: Usize, block: U32, aead: boolean): CipherSpec => ({
    key_len: keyLen,
    iv_len: ivLen,
    block,
    aead,
  }),
} as const;
