/* generated by purecrate-ts. do not edit. */

export type Direction = Readonly<{ kind: "ClientToServer" }> | Readonly<{ kind: "ServerToClient" }>;

export const Direction = {
  ClientToServer: (): Direction => ({ kind: "ClientToServer" }),
  ServerToClient: (): Direction => ({ kind: "ServerToClient" }),
} as const;
