/* generated by purecrate-ts. do not edit. */

/** StrictHostKeyChecking yes, accept-new, ask. */
export type HostKeyPolicy =
  | Readonly<{ kind: "Strict" }>
  | Readonly<{ kind: "AcceptNew" }>
  | Readonly<{ kind: "Ask" }>;

export const HostKeyPolicy = {
  Strict: (): HostKeyPolicy => ({ kind: "Strict" }),
  AcceptNew: (): HostKeyPolicy => ({ kind: "AcceptNew" }),
  Ask: (): HostKeyPolicy => ({ kind: "Ask" }),
} as const;
