/* generated by purecrate-ts. do not edit. */

/** `SSH-protoversion-softwareversion SP comments`, without the CR LF. */
export type Identification = Readonly<{
  proto_version: string;
  software_version: string;
  comments: string | null;
}>;

export const Identification = {
  of: (protoVersion: string, softwareVersion: string, comments: string | null): Identification => ({
    proto_version: protoVersion,
    software_version: softwareVersion,
    comments,
  }),
} as const;
