/* generated by purecrate-ts. do not edit. */

import type { KeyType } from "./key-type.ts";

/**
 * A user key: its type, and its public key blob as the caller encodes it
 * in a publickey request (PK_OK echoes it, RFC 4252 §7).
 */
export type Identity = Readonly<{
  key_type: KeyType;
  public_key: string;
}>;

export const Identity = {
  of: (keyType: KeyType, publicKey: string): Identity => ({
    key_type: keyType,
    public_key: publicKey,
  }),
} as const;
