/* generated by purecrate-ts. do not edit. */

import { assertNever, Iter, Str, type U16 } from "./purecrate-runtime.ts";
import type { HostKey } from "./host-key.ts";
import type { KnownHost } from "./known-host.ts";
import { namesHost } from "./names-host.ts";
import type { Trust } from "./trust.ts";

/** A revoked key is refused for every host (sshd(8), @revoked). */
export const judgeHostKey = (
  known: ReadonlyArray<KnownHost>,
  host: string,
  port: U16,
  key: HostKey,
): Trust => {
  Str.wellFormed(known);
  Str.wellFormed(host);
  Str.wellFormed(key);
  const revoked = Iter.any(
    known,
    (k: KnownHost): boolean =>
      k.revoked && k.key_type === key.key_type && k.fingerprint === key.fingerprint,
  );
  if (revoked) return { kind: "Revoked" };
  let trust = { kind: "Unknown" } as Trust;
  let unreadable = false;

  for (const k of known) {
    if (!k.revoked && k.key_type === key.key_type) {
      const lineMatch = namesHost(k.hosts, host, port);
      switch (lineMatch.kind) {
        case "Names":
          if (k.fingerprint === key.fingerprint) return { kind: "Known" };
          trust = { kind: "Changed" } as Trust;
          break;
        case "Unreadable":
          unreadable = true;
          break;
        case "Other":
          break;
        default:
          return assertNever(lineMatch);
      }
    }
  }

  if (unreadable && trust.kind === "Unknown") return { kind: "Undecidable" };
  return trust;
};
