/* generated by purecrate-ts. do not edit. */

export type KexMethod =
  | Readonly<{ kind: "Mlkem768X25519Sha256" }>
  | Readonly<{ kind: "Sntrup761X25519Sha512" }>
  | Readonly<{ kind: "Curve25519Sha256" }>
  | Readonly<{ kind: "EcdhSha2Nistp256" }>
  | Readonly<{ kind: "EcdhSha2Nistp384" }>
  | Readonly<{ kind: "EcdhSha2Nistp521" }>;

export const KexMethod = {
  Mlkem768X25519Sha256: (): KexMethod => ({ kind: "Mlkem768X25519Sha256" }),
  Sntrup761X25519Sha512: (): KexMethod => ({ kind: "Sntrup761X25519Sha512" }),
  Curve25519Sha256: (): KexMethod => ({ kind: "Curve25519Sha256" }),
  EcdhSha2Nistp256: (): KexMethod => ({ kind: "EcdhSha2Nistp256" }),
  EcdhSha2Nistp384: (): KexMethod => ({ kind: "EcdhSha2Nistp384" }),
  EcdhSha2Nistp521: (): KexMethod => ({ kind: "EcdhSha2Nistp521" }),
} as const;
