/* generated by purecrate-ts. do not edit. */

import type { KexStage } from "./kex-stage.ts";
import type { Resume } from "./resume.ts";

export type KexState = Readonly<{
  stage: KexStage;
  resume: Resume;
  initial: boolean;
}>;

export const KexState = {
  of: (stage: KexStage, resume: Resume, initial: boolean): KexState => ({ stage, resume, initial }),
} as const;
