/* generated by purecrate-ts. do not edit. */

import { assertNever } from "./purecrate-runtime.ts";
import type { Mac } from "./mac.ts";

export const macName = (m: Mac): string => {
  switch (m.kind) {
    case "HmacSha256Etm":
      return "hmac-sha2-256-etm@openssh.com";
    case "HmacSha512Etm":
      return "hmac-sha2-512-etm@openssh.com";
    case "HmacSha256":
      return "hmac-sha2-256";
    case "HmacSha512":
      return "hmac-sha2-512";
    default:
      return assertNever(m);
  }
};
