/* generated by purecrate-ts. do not edit. */

import { Int, Iter, Str, type U16 } from "./purecrate-runtime.ts";

export const namesHost = (hosts: string, host: string, port: U16): boolean =>
  Iter.any(hosts.split(","), (pattern: string): boolean => namesOne(pattern, host, port));

const namesOne = (pattern: string, host: string, port: U16): boolean => {
  const option = Str.stripPrefix(pattern, "[");
  if (option === null) return port === 22 && pattern === host;
  const rest = option;
  const option2 = Str.splitOnce(rest, "]:");
  if (option2 !== null) {
    const h = option2[0];
    const p = option2[1];
    const result = Int.u16.parse(p);
    if (result.kind === "Ok") {
      const n = result.value;
      return h === host && n === port;
    }

    return false;
  }

  return false;
};
