/* generated by purecrate-ts. do not edit. */

import {
  Int,
  Iter,
  Slice,
  Str,
  type U16,
  type U32,
  type U8,
  type Usize,
} from "./purecrate-runtime.ts";
import type { LineMatch } from "./line-match.ts";

/**
 * sshd(8): each pattern in turn; a negated one that matches means the
 * line does not apply, whatever else matched (OpenSSH `match_hostname`).
 * A hashed name is the whole field and takes no operators.
 */
export const namesHost = (hosts: string, host: string, port: U16): LineMatch => {
  const name = lookupName(host, port);
  if (hosts.startsWith("|")) return hashedNames(hosts, name);
  let positive = false;

  for (const pattern of hosts.split(",")) {
    const option = Str.stripPrefix(pattern, "!");
    if (option !== null) {
      const negated = option;
      if (glob(lowered(negated), name)) return { kind: "Other" };
    } else if (glob(lowered(pattern), name)) {
      positive = true;
    }
  }

  return positive ? { kind: "Names" } : { kind: "Other" };
};

const lower = (b: U32): U32 => (b >= 65 && b <= 90 ? Int.u32.add(b, 32 as U32) : b);

const lowered = (s: string): ReadonlyArray<U32> =>
  Array.from(Iter.map(Str.bytes(s), (b: U8): U32 => lower(b as number as U32)));

/**
 * The name as OpenSSH writes and looks it up (`misc.c` put_host_port):
 * the host for port 22, `[host]:port` in plain decimal for any other; its
 * bytes, ASCII lower-cased.
 */
const lookupName = (host: string, port: U16): ReadonlyArray<U32> => {
  const out: Array<U32> = [];

  if (port !== 22) {
    out.push(/* '[' */ 91 as U8 as number as U32);
  }

  for (const b of Str.bytes(host)) {
    out.push(lower(b as number as U32));
  }

  if (port !== 22) {
    out.push(/* ']' */ 93 as U8 as number as U32);
    out.push(/* ':' */ 58 as U8 as number as U32);
    const p = port as number as U32;
    let div = 1 as U32;
    while (Int.u32.mul(div, 10 as U32) <= p) {
      div = Int.u32.mul(div, 10 as U32);
    }

    while (div > 0) {
      out.push(
        Int.u32.add(
          /* '0' */ 48 as U8 as number as U32,
          Int.u32.rem(Int.u32.div(p, div), 10 as U32),
        ),
      );
      div = Int.u32.div(div, 10 as U32);
    }
  }

  return out;
};

/**
 * `*` any run of bytes, `?` one byte, anything else itself (OpenSSH
 * `match_pattern`), with the last `*` backtracked to.
 */
const glob = (pattern: ReadonlyArray<U32>, name: ReadonlyArray<U32>): boolean => {
  const star = /* '*' */ 42 as U8 as number as U32;
  let p = 0 as Usize;
  let n = 0 as Usize;
  let lastStar: Usize | null = null;
  let resume = 0 as Usize;

  while (n < name.length) {
    if (p < pattern.length && Slice.at(pattern, p) === star) {
      lastStar = p;
      resume = n;
      p = Int.usize.add(p, 1 as Usize);
    } else if (matchesOne(pattern, p, Slice.at(name, n))) {
      p = Int.usize.add(p, 1 as Usize);
      n = Int.usize.add(n, 1 as Usize);
    } else {
      if (lastStar === null) return false;
      p = Int.usize.add(lastStar, 1 as Usize);
      resume = Int.usize.add(resume, 1 as Usize);
      n = resume;
    }
  }

  while (p < pattern.length && Slice.at(pattern, p) === star) {
    p = Int.usize.add(p, 1 as Usize);
  }

  return p === pattern.length;
};

/** Whether `pattern[p]` exists and matches the byte `b` alone. */
const matchesOne = (pattern: ReadonlyArray<U32>, p: Usize, b: U32): boolean => {
  if (p >= pattern.length) return false;
  const any = /* '?' */ 63 as U8 as number as U32;
  return Slice.at(pattern, p) === any || Slice.at(pattern, p) === b;
};

/**
 * "|1|" base64(salt) "|" base64(HMAC-SHA1(salt, name)) (OpenSSH
 * hostfile.c `host_hash`, salt and hash 20 bytes each).
 */
const hashedNames = (field: string, name: ReadonlyArray<U32>): LineMatch => {
  const option = Str.stripPrefix(field, "|1|");
  const parts: readonly [string, string] | null =
    option !== null ? Str.splitOnce(option, "|") : null;

  let decoded: readonly [ReadonlyArray<U32> | null, ReadonlyArray<U32> | null];
  if (parts === null) return { kind: "Unreadable" };

  decoded = [base64Decode(parts[0]), base64Decode(parts[1])];

  if (decoded[0] !== null && decoded[1] !== null) {
    if (decoded[0].length !== 20 || decoded[1].length !== 20) return { kind: "Unreadable" };
    const mac = hmacSha1(decoded[0], name);

    for (let i = 0 as Usize; i < 20; i = (i + 1) as Usize) {
      if (Slice.at(mac, i) !== Slice.at(decoded[1], i)) return { kind: "Other" };
    }

    return { kind: "Names" };
  }

  return { kind: "Unreadable" };
};

/** The base64 alphabet (RFC 4648 §4). */
const base64Value = (b: U8): U32 | null => {
  if (b >= /* 'A' */ 65 && b <= /* 'Z' */ 90)
    return Int.u8.sub(b, /* 'A' */ 65 as U8) as number as U32;
  if (b >= /* 'a' */ 97 && b <= /* 'z' */ 122)
    return Int.u32.add(Int.u8.sub(b, /* 'a' */ 97 as U8) as number as U32, 26 as U32);
  if (b >= /* '0' */ 48 && b <= /* '9' */ 57)
    return Int.u32.add(Int.u8.sub(b, /* '0' */ 48 as U8) as number as U32, 52 as U32);
  if (b === /* '+' */ 43) return 62 as U32;
  if (b === /* '/' */ 47) return 63 as U32;
  return null;
};

/**
 * Base64 with padding (RFC 4648 §4) to bytes, one per u32; None when the
 * length is not a multiple of 4 or a character is out of place.
 */
const base64Decode = (s: string): ReadonlyArray<U32> | null => {
  if (Int.usize.rem(Str.len(s), 4 as Usize) !== 0) return null;
  const out: Array<U32> = [];
  let acc = 0 as U32;
  let held = 0 as U32;
  let padding = 0 as Usize;

  for (const b of Str.bytes(s)) {
    if (b === /* '=' */ 61) {
      padding = Int.usize.add(padding, 1 as Usize);
      continue;
    }

    if (padding > 0) return null;
    const vOption = base64Value(b);
    if (vOption === null) return null;
    const v = vOption;
    acc = Int.u32.or(Int.u32.shl(acc, 6), v);
    held = Int.u32.add(held, 6 as U32);

    if (held >= 8) {
      held = Int.u32.sub(held, 8 as U32);
      out.push(Int.u32.and(Int.u32.shr(acc, held), 0xff as U32));
      acc = Int.u32.and(acc, Int.u32.sub(Int.u32.shl(1 as U32, held), 1 as U32));
    }
  }

  if (padding > 2) return null;
  return out;
};

/** ROTL^n(x) (FIPS 180-4 §3.2), for 0 < n < 32. */
const rotl = (x: U32, n: U32): U32 =>
  Int.u32.or(Int.u32.shl(x, n), Int.u32.shr(x, Int.u32.sub(32 as U32, n)));

/**
 * SHA-1 (FIPS 180-4 §5.1.1, §6.1) of bytes held one per u32, as its 20
 * bytes. The bit length is a u32: the messages here are under 400 bytes.
 */
const sha1 = (message: ReadonlyArray<U32>): ReadonlyArray<U32> => {
  const bytes: Array<U32> = [];
  let bits = 0 as U32;

  for (const b of message) {
    bytes.push(b);
    bits = Int.u32.add(bits, 8 as U32);
  }

  bytes.push(0x80 as U32);

  while (Int.usize.rem(bytes.length as Usize, 64 as Usize) !== 56) {
    bytes.push(0 as U32);
  }

  bytes.push(0 as U32);
  bytes.push(0 as U32);
  bytes.push(0 as U32);
  bytes.push(0 as U32);
  bytes.push(Int.u32.shr(bits, 24));
  bytes.push(Int.u32.and(Int.u32.shr(bits, 16), 0xff as U32));
  bytes.push(Int.u32.and(Int.u32.shr(bits, 8), 0xff as U32));
  bytes.push(Int.u32.and(bits, 0xff as U32));
  let h0 = 0x67452301 as U32;
  let h1 = 0xefcdab89 as U32;
  let h2 = 0x98badcfe as U32;
  let h3 = 0x10325476 as U32;
  let h4 = 0xc3d2e1f0 as U32;
  let block = 0 as Usize;
  while (block < bytes.length) {
    const w: Array<U32> = [];

    for (let t = 0 as Usize; t < 80; t = (t + 1) as Usize) {
      if (t < 16) {
        const i = Int.usize.add(block, Int.usize.mul(4 as Usize, t));
        w.push(
          Int.u32.or(
            Int.u32.or(
              Int.u32.or(
                Int.u32.shl(Slice.at(bytes, i), 24),
                Int.u32.shl(Slice.at(bytes, Int.usize.add(i, 1 as Usize)), 16),
              ),
              Int.u32.shl(Slice.at(bytes, Int.usize.add(i, 2 as Usize)), 8),
            ),
            Slice.at(bytes, Int.usize.add(i, 3 as Usize)),
          ),
        );
      } else {
        w.push(
          rotl(
            Int.u32.xor(
              Int.u32.xor(
                Int.u32.xor(
                  Slice.at(w, Int.usize.sub(t, 3 as Usize)),
                  Slice.at(w, Int.usize.sub(t, 8 as Usize)),
                ),
                Slice.at(w, Int.usize.sub(t, 14 as Usize)),
              ),
              Slice.at(w, Int.usize.sub(t, 16 as Usize)),
            ),
            1 as U32,
          ),
        );
      }
    }

    let a: U32 = h0;
    let b: U32 = h1;
    let c: U32 = h2;
    let d: U32 = h3;
    let e: U32 = h4;

    for (let t = 0 as Usize; t < 80; t = (t + 1) as Usize) {
      const f: U32 =
        t < 20
          ? Int.u32.or(Int.u32.and(b, c), Int.u32.and(Int.u32.not(b), d))
          : t < 40 || t >= 60
            ? Int.u32.xor(Int.u32.xor(b, c), d)
            : Int.u32.or(Int.u32.or(Int.u32.and(b, c), Int.u32.and(b, d)), Int.u32.and(c, d));
      const k: U32 =
        t < 20
          ? (0x5a827999 as U32)
          : t < 40
            ? (0x6ed9eba1 as U32)
            : t < 60
              ? (0x8f1bbcdc as U32)
              : (0xca62c1d6 as U32);
      const temp = Int.u32.wrappingAdd(
        Int.u32.wrappingAdd(Int.u32.wrappingAdd(Int.u32.wrappingAdd(rotl(a, 5 as U32), f), e), k),
        Slice.at(w, t),
      );
      e = d;
      d = c;
      c = rotl(b, 30 as U32);
      b = a;
      a = temp;
    }

    h0 = Int.u32.wrappingAdd(h0, a);
    h1 = Int.u32.wrappingAdd(h1, b);
    h2 = Int.u32.wrappingAdd(h2, c);
    h3 = Int.u32.wrappingAdd(h3, d);
    h4 = Int.u32.wrappingAdd(h4, e);
    block = Int.usize.add(block, 64 as Usize);
  }

  const out: Array<U32> = [];

  for (const h of [h0, h1, h2, h3, h4]) {
    out.push(Int.u32.shr(h, 24));
    out.push(Int.u32.and(Int.u32.shr(h, 16), 0xff as U32));
    out.push(Int.u32.and(Int.u32.shr(h, 8), 0xff as U32));
    out.push(Int.u32.and(h, 0xff as U32));
  }

  return out;
};

/** HMAC-SHA1 (RFC 2104) with a key of at most 64 bytes. */
const hmacSha1 = (key: ReadonlyArray<U32>, message: ReadonlyArray<U32>): ReadonlyArray<U32> => {
  const inner: Array<U32> = [];
  const outer: Array<U32> = [];

  for (let i = 0 as Usize; i < 64; i = (i + 1) as Usize) {
    const k: U32 = i < key.length ? Slice.at(key, i) : (0 as U32);
    inner.push(Int.u32.xor(k, 0x36 as U32));
    outer.push(Int.u32.xor(k, 0x5c as U32));
  }

  for (const b of message) {
    inner.push(b);
  }

  for (const b of sha1(inner)) {
    outer.push(b);
  }

  return sha1(outer);
};
