/* generated by purecrate-ts. do not edit. */

import { Result } from "./purecrate-runtime.ts";
import type { Algorithms } from "./algorithms.ts";
import { cipherName } from "./cipher-name.ts";
import { cipherParams } from "./cipher-params.ts";
import type { Cipher } from "./cipher.ts";
import type { Config } from "./config.ts";
import type { Connection } from "./connection.ts";
import type { Direction } from "./direction.ts";
import type { Failure } from "./failure.ts";
import { hostKeyOrder } from "./host-key-order.ts";
import type { KexInit } from "./kex-init.ts";
import type { KexMethod } from "./kex-method.ts";
import { kexName } from "./kex-name.ts";
import { listed } from "./listed.ts";
import { macName } from "./mac-name.ts";
import type { Mac } from "./mac.ts";
import { nameList } from "./name-list.ts";
import type { SignatureAlgorithm } from "./signature-algorithm.ts";
import { signatureName } from "./signature-name.ts";
import type { Transform } from "./transform.ts";

const pickKex = (
  ours: ReadonlyArray<KexMethod>,
  theirs: ReadonlyArray<string>,
): KexMethod | null => {
  for (const k of ours) {
    if (listed(theirs, kexName(k))) return k;
  }

  return null;
};

const pickSignature = (
  ours: ReadonlyArray<SignatureAlgorithm>,
  theirs: ReadonlyArray<string>,
): SignatureAlgorithm | null => {
  for (const a of ours) {
    if (listed(theirs, signatureName(a))) return a;
  }

  return null;
};

const pickCipher = (ours: ReadonlyArray<Cipher>, theirs: ReadonlyArray<string>): Cipher | null => {
  for (const x of ours) {
    if (listed(theirs, cipherName(x))) return x;
  }

  return null;
};

const pickMac = (ours: ReadonlyArray<Mac>, theirs: ReadonlyArray<string>): Mac | null => {
  for (const m of ours) {
    if (listed(theirs, macName(m))) return m;
  }

  return null;
};

const pickTransform = (
  config: Config,
  ciphers: string,
  macs: string,
  compression: string,
  d: Direction,
): Result<Transform, Failure> => {
  const nameListResult = nameList(ciphers);
  if (nameListResult.kind === "Err") return nameListResult;
  const cipher = pickCipher(config.ciphers, nameListResult.value);
  if (cipher === null)
    return Result.err({ kind: "NoCommonAlgorithm", value: { kind: "Cipher", value: d } });
  const theirMacsResult = nameList(macs);
  if (theirMacsResult.kind === "Err") return theirMacsResult;
  const theirMacs = theirMacsResult.value;

  // An AEAD cipher authenticates the packet; the MAC list is not consulted.
  const elem = cipherParams(cipher).aead;
  const elem2 = pickMac(config.macs, theirMacs);

  let mac: Mac | null;
  if (elem) {
    mac = null;
  } else {
    if (elem2 === null)
      return Result.err({ kind: "NoCommonAlgorithm", value: { kind: "Mac", value: d } });
    mac = elem2;
  }

  const nameListResult2 = nameList(compression);
  if (nameListResult2.kind === "Err") return nameListResult2;
  if (!listed(nameListResult2.value, "none"))
    return Result.err({ kind: "NoCommonAlgorithm", value: { kind: "Compression", value: d } });
  return Result.ok({ cipher, mac });
};

/**
 * RFC 4253 §7.1: for each list, the first of the client's algorithms the
 * server also lists. Every method here needs a signature-capable host key,
 * and every host key algorithm here is one.
 */
export const negotiate = (
  c: Connection,
  initial: boolean,
  peer: KexInit,
): Result<Algorithms, Failure> => {
  const hostKeyOrderValue = hostKeyOrder(c, initial);
  const nameListResult = nameList(peer.host_keys);
  if (nameListResult.kind === "Err") return nameListResult;
  const hostKey = pickSignature(hostKeyOrderValue, nameListResult.value);
  if (hostKey === null)
    return Result.err({ kind: "NoCommonAlgorithm", value: { kind: "HostKey" } });
  const nameListResult2 = nameList(peer.kex);
  if (nameListResult2.kind === "Err") return nameListResult2;
  const kex = pickKex(c.config.kex, nameListResult2.value);
  if (kex === null) return Result.err({ kind: "NoCommonAlgorithm", value: { kind: "Kex" } });
  const clientToServerResult = pickTransform(
    c.config,
    peer.ciphers_client_to_server,
    peer.macs_client_to_server,
    peer.compression_client_to_server,
    { kind: "ClientToServer" },
  );
  if (clientToServerResult.kind === "Err") return clientToServerResult;
  const clientToServer = clientToServerResult.value;
  const serverToClientResult = pickTransform(
    c.config,
    peer.ciphers_server_to_client,
    peer.macs_server_to_client,
    peer.compression_server_to_client,
    { kind: "ServerToClient" },
  );
  if (serverToClientResult.kind === "Err") return serverToClientResult;
  const serverToClient = serverToClientResult.value;
  return Result.ok({
    kex,
    host_key: hostKey,
    client_to_server: clientToServer,
    server_to_client: serverToClient,
  });
};
