/* generated by purecrate-ts. do not edit. */

import { cipherName } from "./cipher-name.ts";
import type { Connection } from "./connection.ts";
import { EXT_INFO_CLIENT, STRICT_KEX_CLIENT } from "./consts.ts";
import { hostKeyOrder } from "./host-key-order.ts";
import { kexName } from "./kex-name.ts";
import { macName } from "./mac-name.ts";
import type { Offer } from "./offer.ts";
import { signatureName } from "./signature-name.ts";

/** `guess`: a guessed KEX_ECDH_INIT follows. */
export const ourOffer = (c: Connection, initial: boolean, guess: boolean): Offer => {
  const kex = c.config.kex.map(kexName);

  if (initial) {
    kex.push(EXT_INFO_CLIENT);
    kex.push(STRICT_KEX_CLIENT);
  }

  return {
    kex,
    host_keys: hostKeyOrder(c, initial).map(signatureName),
    ciphers: c.config.ciphers.map(cipherName),
    macs: c.config.macs.map(macName),
    compression: ["none"],
    first_kex_packet_follows: guess,
  };
};
