/* generated by purecrate-ts. do not edit. */

import type { U32 } from "./purecrate-runtime.ts";
import type { Auth } from "./auth.ts";
import type { KexState } from "./kex-state.ts";

export type Phase =
  | Readonly<{ kind: "Version"; preamble_lines: U32 }>
  | Readonly<{ kind: "KeyExchange"; value: KexState }>
  | Readonly<{ kind: "Service" }>
  | Readonly<{ kind: "Authenticating"; value: Auth }>
  | Readonly<{ kind: "Established" }>
  | Readonly<{ kind: "Closed"; code: U32; description: string }>;

export const Phase = {
  Version: (preambleLines: U32): Phase => ({ kind: "Version", preamble_lines: preambleLines }),
  KeyExchange: (value: KexState): Phase => ({ kind: "KeyExchange", value }),
  /** SERVICE_REQUEST "ssh-userauth" sent. */
  Service: (): Phase => ({ kind: "Service" }),
  Authenticating: (value: Auth): Phase => ({ kind: "Authenticating", value }),
  Established: (): Phase => ({ kind: "Established" }),
  Closed: (code: U32, description: string): Phase => ({ kind: "Closed", code, description }),
} as const;
