/* generated by purecrate-ts. do not edit. */

import { STRICT_KEX_CLIENT, STRICT_KEX_CLIENT_STANDARD } from "./consts.ts";

/**
 * The strict markers the initial KEXINIT offers: both, for the widest
 * reach (draft-ietf-sshm-strict-kex-02 §3.1).
 */
export const strictMarkers = (): ReadonlyArray<string> => [
  STRICT_KEX_CLIENT_STANDARD,
  STRICT_KEX_CLIENT,
];
