/* generated by purecrate-ts. do not edit. */

import type { Cipher } from "./cipher.ts";
import type { Mac } from "./mac.ts";

/** What protects one direction. `mac` is `None` under an AEAD cipher. */
export type Transform = Readonly<{
  cipher: Cipher;
  mac: Mac | null;
}>;

export const Transform = {
  of: (cipher: Cipher, mac: Mac | null): Transform => ({ cipher, mac }),
} as const;
