/* generated by purecrate-ts. do not edit. */

import type { Status } from "./status.ts";
import type { Terms } from "./terms.ts";

export type PaymentIntent = Readonly<{
  terms: Terms;
  status: Status;
}>;

export const PaymentIntent = {
  of: (terms: Terms, status: Status): PaymentIntent => ({ terms, status }),
} as const;
