/* generated by purecrate-ts. do not edit. */

export type ErrorCode =
  | Readonly<{ kind: "InvalidRequest" }>
  | Readonly<{ kind: "UnsupportedResponseType" }>
  | Readonly<{ kind: "InvalidScope" }>
  | Readonly<{ kind: "AccessDenied" }>
  | Readonly<{ kind: "LoginRequired" }>
  | Readonly<{ kind: "ConsentRequired" }>;

export const ErrorCode = {
  InvalidRequest: (): ErrorCode => ({ kind: "InvalidRequest" }),
  UnsupportedResponseType: (): ErrorCode => ({ kind: "UnsupportedResponseType" }),
  InvalidScope: (): ErrorCode => ({ kind: "InvalidScope" }),
  AccessDenied: (): ErrorCode => ({ kind: "AccessDenied" }),
  LoginRequired: (): ErrorCode => ({ kind: "LoginRequired" }),
  ConsentRequired: (): ErrorCode => ({ kind: "ConsentRequired" }),
} as const;
