/* generated by purecrate-ts. do not edit. */

import { type U32 } from "./int.ts";

export type Policy = Readonly<{
  max_password_failures: U32;
  max_otp_failures: U32;
}>;

export const Policy = {
  of: (max_password_failures: U32, max_otp_failures: U32): Policy => ({ max_password_failures, max_otp_failures }),
} as const;
