/* generated by purecrate-ts. do not edit. */

import { type I64, type U8 } from "./int.ts";

export type StepMac = Readonly<{
  step: I64;
  mac: ReadonlyArray<U8>;
}>;

export const StepMac = {
  of: (step: I64, mac: ReadonlyArray<U8>): StepMac => ({ step, mac }),
} as const;
