/* generated by purecrate-ts. do not edit. */

import { Result, type I64 } from "./purecrate-runtime.ts";
import type { InvoiceError } from "./invoice-error.ts";

export type Yen = I64 & { readonly "invoice.Yen": true };

// A field is not `pub` in Rust: outside the crate, `Yen` values come
// only from the crate's functions. The generated files build them here;
// `index.ts` does not export it.
export const Yen$of = (value: I64): Yen => value as Yen;

export const Yen = {
  new: (value: I64): Result<Yen, InvoiceError> => {
    if (value < (0n as I64)) return Result.err({ kind: "NegativeAmount" });
    return Result.ok(Yen$of(value));
  },
  value: (self: Yen): I64 => self,
  tryFrom: (value: I64): Result<Yen, InvoiceError> => Yen.new(value),
} as const;
