/* generated by purecrate-ts. do not edit. */

import { Ord } from "./purecrate-runtime.ts";
import type { Ordering } from "./ordering.ts";
import type { Ulid } from "./ulid.ts";

export const compare = (a: Ulid, b: Ulid): Ordering => Ord.cmp(a, b);
