/* generated by purecrate-ts. do not edit. */

import { assertNever } from "./assert-never.ts";
import { type I32, type U64 } from "./int.ts";
import { Str } from "./str.ts";
import type { Ordering } from "./ordering.ts";
import type { PreId } from "./pre-id.ts";

export const compare_pre_id = (a: PreId, b: PreId): Ordering => {
  switch (a.kind) {
    case "Numeric": {
      const $f1 = a.content[0];
      switch (b.kind) {
        case "Numeric": {
          const $f2 = b.content[0];
          const x: U64 = $f1;
          const y: U64 = $f2;
          return (x < y ? { kind: "Less" } : (x === y ? { kind: "Equal" } : { kind: "Greater" }));
        }
        case "Alpha":
          return { kind: "Less" };
        default:
          return assertNever(b);
      }
    }
    case "Alpha": {
      const $f4 = a.content[0];
      switch (b.kind) {
        case "Numeric":
          return { kind: "Greater" };
        case "Alpha": {
          const $f6 = b.content[0];
          const x$1: string = $f4;
          const y$1: string = $f6;
          return (Str.cmp(x$1, y$1) < (0 as I32) ? { kind: "Less" } : (x$1 === y$1 ? { kind: "Equal" } : { kind: "Greater" }));
        }
        default:
          return assertNever(b);
      }
    }
    default:
      return assertNever(a);
  }
};
