/* generated by purecrate-ts. do not edit. */

import type { DeclineCode } from "./decline-code.ts";

/** What Stripe reports for a confirmation attempt or a completed action. */
export type Outcome =
  | Readonly<{ kind: "Authorized" }>
  | Readonly<{ kind: "ActionRequired" }>
  | Readonly<{ kind: "Pending" }>
  | Readonly<{ kind: "Declined"; value: DeclineCode }>;

export const Outcome = {
  Authorized: (): Outcome => ({ kind: "Authorized" }),
  ActionRequired: (): Outcome => ({ kind: "ActionRequired" }),
  Pending: (): Outcome => ({ kind: "Pending" }),
  Declined: (value: DeclineCode): Outcome => ({ kind: "Declined", value }),
} as const;
