/* generated by purecrate-ts. do not edit. */

import type { MethodKind } from "./method-kind.ts";
import type { PaymentMethodId } from "./payment-method-id.ts";

export type PaymentMethod = Readonly<{
  id: PaymentMethodId;
  kind: MethodKind;
}>;

export const PaymentMethod = {
  of: (id: PaymentMethodId, kind: MethodKind): PaymentMethod => ({ id, kind }),
} as const;
