/* generated by purecrate-ts. do not edit. */

export type OtpDigits =
  | Readonly<{ kind: "Six" }>
  | Readonly<{ kind: "Seven" }>
  | Readonly<{ kind: "Eight" }>;

export const OtpDigits = {
  Six: (): OtpDigits => ({ kind: "Six" }),
  Seven: (): OtpDigits => ({ kind: "Seven" }),
  Eight: (): OtpDigits => ({ kind: "Eight" }),
} as const;
