/* generated by purecrate-ts. do not edit. */

export type CancelReason =
  | Readonly<{ kind: "ByCustomer" }>
  | Readonly<{ kind: "PaymentFailed" }>;

export const CancelReason = {
  ByCustomer: (): CancelReason => ({ kind: "ByCustomer" }),
  PaymentFailed: (): CancelReason => ({ kind: "PaymentFailed" }),
} as const;
