/* generated by purecrate-ts. do not edit. */

import type { Rounding } from "./rounding.ts";

export type Method =
  | Readonly<{ kind: "Separate" }>
  | Readonly<{ kind: "ToExclusive"; conversion: Rounding }>;

export const Method = {
  Separate: (): Method => ({ kind: "Separate" }),
  ToExclusive: (conversion: Rounding): Method => ({ kind: "ToExclusive", conversion }),
} as const;
