/* generated by purecrate-ts. do not edit. */

import type { Rounding } from "./rounding.ts";

/** 問59: the one basis the invoice's totals are on. */
export type Method =
  | Readonly<{ kind: "ToExclusive"; conversion: Rounding }>
  | Readonly<{ kind: "ToInclusive"; conversion: Rounding }>
  | Readonly<{ kind: "Separate" }>;

export const Method = {
  /**
   * Every total tax-exclusive; each rate's tax-inclusive lines are
   * totalled and converted once.
   */
  ToExclusive: (conversion: Rounding): Method => ({ kind: "ToExclusive", conversion }),
  /**
   * Every total tax-inclusive; each rate's tax-exclusive lines are
   * totalled and converted once.
   */
  ToInclusive: (conversion: Rounding): Method => ({ kind: "ToInclusive", conversion }),
  /**
   * Nothing converted: fixed retail prices are totalled and taxed apart
   * from tax-exclusive lines. Tax-inclusive lines are allowed only with no
   * tax-exclusive line.
   */
  Separate: (): Method => ({ kind: "Separate" }),
} as const;
