/* generated by purecrate-ts. do not edit. */

import { Json, parseJson } from "./purecrate-runtime.ts";
import { z } from "zod";
import { i64, unitEnum, unitVariant } from "./purecrate-zod.ts";
import { Yen as Yen$value, type Yen as Yen$ } from "./yen.ts";
import type { Rate as Rate$ } from "./rate.ts";
import type { Pricing as Pricing$ } from "./pricing.ts";
import type { Rounding as Rounding$ } from "./rounding.ts";
import type { Method as Method$ } from "./method.ts";
import type { Line as Line$ } from "./line.ts";
import type { Invoice as Invoice$ } from "./invoice.ts";
import type { Group as Group$ } from "./group.ts";
import type { Summary as Summary$ } from "./summary.ts";
import type { InvoiceError as InvoiceError$ } from "./invoice-error.ts";
import { InvoiceError as InvoiceError$text } from "./invoice-error.ts";

export const Yen: z.ZodType<Yen$, unknown> = i64.transform((v, ctx): Yen$ => {
  const r = Yen$value.tryFrom(v);
  if (r.kind === "Err") {
    ctx.addIssue({
      code: "custom",
      message: `Yen: ${InvoiceError$text.toString(r.error)}`,
      input: v,
      params: { error: r.error },
    });
    return z.NEVER;
  }
  return r.value;
});

export const Rate: z.ZodType<Rate$, unknown> = unitEnum(["Standard", "Reduced"]);

export const Pricing: z.ZodType<Pricing$, unknown> = unitEnum(["Exclusive", "Inclusive"]);

export const Rounding: z.ZodType<Rounding$, unknown> = unitEnum(["Down", "Up", "HalfUp"]);

/** 問59: what to do with tax-inclusive lines among tax-exclusive ones. */
export const Method: z.ZodType<Method$, unknown> = z.union([
  unitVariant("Separate").transform((): Method$ => ({ kind: "Separate" })),
  z.object({ ToExclusive: z.object({ conversion: Rounding }) })
    .strict()
    .transform((v): Method$ => ({ kind: "ToExclusive", conversion: v.ToExclusive.conversion })),
]);

export const Line: z.ZodType<Line$, unknown> = z.object({
  amount: Yen,
  rate: Rate,
  pricing: Pricing,
})
  .transform((v): Line$ => ({ amount: v.amount, rate: v.rate, pricing: v.pricing }));

export const Invoice: z.ZodType<Invoice$, unknown> = z.object({
  lines: z.array(Line),
  rounding: Rounding,
  method: Method,
})
  .transform((v): Invoice$ => ({ lines: v.lines, rounding: v.rounding, method: v.method }));

/** One rate and pricing: the total of its amounts and the tax on it. */
export const Group: z.ZodType<Group$, unknown> = z.object({ base: Yen, tax: Yen }).transform((v): Group$ => ({ base: v.base, tax: v.tax }));

export const Summary: z.ZodType<Summary$, unknown> = z.object({
  standard: Group,
  reduced: Group,
  standard_inclusive: Group,
  reduced_inclusive: Group,
  total: Yen,
})
  .transform((v): Summary$ => ({
    standard: v.standard,
    reduced: v.reduced,
    standard_inclusive: v.standard_inclusive,
    reduced_inclusive: v.reduced_inclusive,
    total: v.total,
  }));

export const InvoiceError: z.ZodType<InvoiceError$, unknown> = unitEnum([
  "NegativeAmount",
  "NoLines",
]);

/**
 * Each type read from the JSON text serde_json writes, through `parseJson`;
 * throws on malformed text or a value the schema refuses.
 */
export const fromJson = {
  Yen: (text: string): Yen$ => Yen.parse(parseJson(text)),
  Rate: (text: string): Rate$ => Rate.parse(parseJson(text)),
  Pricing: (text: string): Pricing$ => Pricing.parse(parseJson(text)),
  Rounding: (text: string): Rounding$ => Rounding.parse(parseJson(text)),
  Method: (text: string): Method$ => Method.parse(parseJson(text)),
  Line: (text: string): Line$ => Line.parse(parseJson(text)),
  Invoice: (text: string): Invoice$ => Invoice.parse(parseJson(text)),
  Group: (text: string): Group$ => Group.parse(parseJson(text)),
  Summary: (text: string): Summary$ => Summary.parse(parseJson(text)),
  InvoiceError: (text: string): InvoiceError$ => InvoiceError.parse(parseJson(text)),
} as const;

/** Each type written as serde_json writes the Rust value. */
export const toJson = {
  Yen: (x: Yen$): string => Json.int(x),
  Rate: (x: Rate$): string => `"${x.kind}"`,
  Pricing: (x: Pricing$): string => `"${x.kind}"`,
  Rounding: (x: Rounding$): string => `"${x.kind}"`,
  Method: (x: Method$): string => {
    switch (x.kind) {
      case "Separate":
        return "\"Separate\"";
      case "ToExclusive":
        return Json.object([[
          "ToExclusive",
          Json.object([["conversion", toJson.Rounding(x.conversion)]]),
        ]]);
    }
  },
  Line: (x: Line$): string => Json.object([
    ["amount", toJson.Yen(x.amount)],
    ["rate", toJson.Rate(x.rate)],
    ["pricing", toJson.Pricing(x.pricing)],
  ]),
  Invoice: (x: Invoice$): string => Json.object([
    ["lines", Json.array(x.lines, (v0) => toJson.Line(v0))],
    ["rounding", toJson.Rounding(x.rounding)],
    ["method", toJson.Method(x.method)],
  ]),
  Group: (x: Group$): string => Json.object([
    ["base", toJson.Yen(x.base)],
    ["tax", toJson.Yen(x.tax)],
  ]),
  Summary: (x: Summary$): string => Json.object([
    ["standard", toJson.Group(x.standard)],
    ["reduced", toJson.Group(x.reduced)],
    ["standard_inclusive", toJson.Group(x.standard_inclusive)],
    ["reduced_inclusive", toJson.Group(x.reduced_inclusive)],
    ["total", toJson.Yen(x.total)],
  ]),
  InvoiceError: (x: InvoiceError$): string => `"${x.kind}"`,
} as const;
