/* generated by purecrate-ts. do not edit. */

import { Result, type I64 } from "./purecrate-runtime.ts";
import type { PaymentError } from "./payment-error.ts";

export type Amount = I64 & { readonly "payment.Amount": true };

// A field is not `pub` in Rust: outside the crate, `Amount` values come
// only from the crate's functions. The generated files build them here;
// `index.ts` does not export it.
export const Amount$of = (value: I64): Amount => value as Amount;

export const Amount = {
  new: (value: I64): Result<Amount, PaymentError> => {
    if ((value < (50n as I64)) || (value > (99999999n as I64))) return Result.err({ kind: "AmountOutOfRange" });
    return Result.ok(Amount$of(value));
  },
  try_from: (value: I64): Result<Amount, PaymentError> => Amount.new(value),
} as const;
