/* generated by purecrate-ts. do not edit. */

export type CaptureMethod =
  | Readonly<{ kind: "Automatic" }>
  | Readonly<{ kind: "Manual" }>;

export const CaptureMethod = {
  Automatic: (): CaptureMethod => ({ kind: "Automatic" }),
  Manual: (): CaptureMethod => ({ kind: "Manual" }),
} as const;
