/* generated by purecrate-ts. do not edit. */

export type ConfirmationMethod = Readonly<{ kind: "Automatic" }> | Readonly<{ kind: "Manual" }>;

export const ConfirmationMethod = {
  Automatic: (): ConfirmationMethod => ({ kind: "Automatic" }),
  Manual: (): ConfirmationMethod => ({ kind: "Manual" }),
} as const;
