/* generated by purecrate-ts. do not edit. */

import { Json, parseJson } from "./purecrate-runtime.ts";
import { z } from "zod";
import { i64, nullable, optionalField, str, unitEnum, unitVariant } from "./purecrate-zod.ts";
import { Amount as DomainAmount } from "./amount.ts";
import { type CancellationReason as DomainCancellationReason } from "./cancellation-reason.ts";
import { type CaptureMethod as DomainCaptureMethod } from "./capture-method.ts";
import { type ConfirmationMethod as DomainConfirmationMethod } from "./confirmation-method.ts";
import { type DeclineCode as DomainDeclineCode } from "./decline-code.ts";
import { type Event as DomainEvent } from "./event.ts";
import { type MethodKind as DomainMethodKind } from "./method-kind.ts";
import { type Outcome as DomainOutcome } from "./outcome.ts";
import { PaymentError as DomainPaymentError } from "./payment-error.ts";
import { type PaymentIntent as DomainPaymentIntent } from "./payment-intent.ts";
import { type PaymentMethod as DomainPaymentMethod } from "./payment-method.ts";
import { PaymentMethodId as DomainPaymentMethodId } from "./payment-method-id.ts";
import { type Status as DomainStatus } from "./status.ts";
import { type Terms as DomainTerms } from "./terms.ts";

export const Amount: z.ZodType<DomainAmount, unknown> = i64.transform((x, ctx): DomainAmount => {
  const r = DomainAmount.tryFrom(x);
  if (r.kind === "Err") {
    ctx.addIssue({
      code: "custom",
      message: `Amount: ${DomainPaymentError.toString(r.error)}`,
      input: x,
      params: { error: r.error },
    });
    return z.NEVER;
  }
  return r.value;
});

/** A payment method ID: `pm_` followed by at least one character. */
export const PaymentMethodId: z.ZodType<
  DomainPaymentMethodId,
  unknown
> = str.transform((x, ctx): DomainPaymentMethodId => {
  const r = DomainPaymentMethodId.tryFrom(x);
  if (r.kind === "Err") {
    ctx.addIssue({
      code: "custom",
      message: `PaymentMethodId: ${DomainPaymentError.toString(r.error)}`,
      input: x,
      params: { error: r.error },
    });
    return z.NEVER;
  }
  return r.value;
});

export const MethodKind: z.ZodType<DomainMethodKind, unknown> = unitEnum(["Card", "BankDebit"]);

export const PaymentMethod: z.ZodType<DomainPaymentMethod, unknown> = z.object({
  id: PaymentMethodId,
  kind: MethodKind,
});

export const CaptureMethod: z.ZodType<
  DomainCaptureMethod,
  unknown
> = unitEnum(["Automatic", "Manual"]);

export const ConfirmationMethod: z.ZodType<
  DomainConfirmationMethod,
  unknown
> = unitEnum(["Automatic", "Manual"]);

export const Terms: z.ZodType<DomainTerms, unknown> = z.object({
  amount: Amount,
  capture: CaptureMethod,
  confirmation: ConfirmationMethod,
});

export const DeclineCode: z.ZodType<DomainDeclineCode, unknown> = unitEnum([
  "CardDeclined",
  "InsufficientFunds",
  "AuthenticationFailed",
  "DebitFailed",
]);

export const CancellationReason: z.ZodType<DomainCancellationReason, unknown> = unitEnum([
  "Duplicate",
  "Fraudulent",
  "RequestedByCustomer",
  "Abandoned",
]);

export const Status: z.ZodType<DomainStatus, unknown> = z.union([
  z.object({ RequiresPaymentMethod: z.object({ last_error: optionalField(DeclineCode) }) })
    .strict()
    .transform((x): DomainStatus => ({
      kind: "RequiresPaymentMethod",
      last_error: x.RequiresPaymentMethod.last_error,
    })),
  z.object({ RequiresConfirmation: z.object({ method: PaymentMethod }) })
    .strict()
    .transform((x): DomainStatus => ({
      kind: "RequiresConfirmation",
      method: x.RequiresConfirmation.method,
    })),
  z.object({ RequiresAction: z.object({ method: PaymentMethod }) })
    .strict()
    .transform((x): DomainStatus => ({ kind: "RequiresAction", method: x.RequiresAction.method })),
  z.object({ Processing: z.object({ method: PaymentMethod }) })
    .strict()
    .transform((x): DomainStatus => ({ kind: "Processing", method: x.Processing.method })),
  z.object({ RequiresCapture: z.object({ method: PaymentMethod, capturable: i64 }) })
    .strict()
    .transform((x): DomainStatus => ({
      kind: "RequiresCapture",
      method: x.RequiresCapture.method,
      capturable: x.RequiresCapture.capturable,
    })),
  z.object({ Succeeded: z.object({ received: i64, application_fee: optionalField(i64) }) })
    .strict()
    .transform((x): DomainStatus => ({
      kind: "Succeeded",
      received: x.Succeeded.received,
      application_fee: x.Succeeded.application_fee,
    })),
  z.object({ Canceled: z.object({ reason: optionalField(CancellationReason) }) })
    .strict()
    .transform((x): DomainStatus => ({ kind: "Canceled", reason: x.Canceled.reason })),
]);

export const PaymentIntent: z.ZodType<DomainPaymentIntent, unknown> = z.object({
  terms: Terms,
  status: Status,
});

/** What Stripe reports for a confirmation attempt or a completed action. */
export const Outcome: z.ZodType<DomainOutcome, unknown> = z.union([
  unitVariant("Authorized").transform((): DomainOutcome => ({ kind: "Authorized" })),
  unitVariant("ActionRequired").transform((): DomainOutcome => ({ kind: "ActionRequired" })),
  unitVariant("Pending").transform((): DomainOutcome => ({ kind: "Pending" })),
  z.object({ Declined: DeclineCode })
    .strict()
    .transform((x): DomainOutcome => ({ kind: "Declined", value: x.Declined })),
]);

export const Event: z.ZodType<DomainEvent, unknown> = z.union([
  z.object({ AttachMethod: PaymentMethod })
    .strict()
    .transform((x): DomainEvent => ({ kind: "AttachMethod", value: x.AttachMethod })),
  z.object({ Confirm: z.object({ method: optionalField(PaymentMethod), outcome: Outcome }) })
    .strict()
    .transform((x): DomainEvent => ({
      kind: "Confirm",
      method: x.Confirm.method,
      outcome: x.Confirm.outcome,
    })),
  z.object({ ActionHandled: Outcome })
    .strict()
    .transform((x): DomainEvent => ({ kind: "ActionHandled", value: x.ActionHandled })),
  unitVariant("ProcessingSucceeded")
    .transform((): DomainEvent => ({ kind: "ProcessingSucceeded" })),
  z.object({ ProcessingFailed: DeclineCode })
    .strict()
    .transform((x): DomainEvent => ({ kind: "ProcessingFailed", value: x.ProcessingFailed })),
  z.object({ Capture: z.object({
    amount_to_capture: optionalField(i64),
    application_fee: optionalField(i64),
  }) })
    .strict()
    .transform((x): DomainEvent => ({
      kind: "Capture",
      amount_to_capture: x.Capture.amount_to_capture,
      application_fee: x.Capture.application_fee,
    })),
  z.object({ Cancel: nullable(CancellationReason) })
    .strict()
    .transform((x): DomainEvent => ({ kind: "Cancel", value: x.Cancel })),
]);

export const PaymentError: z.ZodType<DomainPaymentError, unknown> = z.union([
  unitVariant("AmountOutOfRange")
    .transform((): DomainPaymentError => ({ kind: "AmountOutOfRange" })),
  unitVariant("InvalidPaymentMethodId")
    .transform((): DomainPaymentError => ({ kind: "InvalidPaymentMethodId" })),
  unitVariant("MissingPaymentMethod")
    .transform((): DomainPaymentError => ({ kind: "MissingPaymentMethod" })),
  z.object({ InvalidCaptureAmount: z.object({ capturable: i64 }) })
    .strict()
    .transform((x): DomainPaymentError => ({
      kind: "InvalidCaptureAmount",
      capturable: x.InvalidCaptureAmount.capturable,
    })),
  unitVariant("NegativeApplicationFee")
    .transform((): DomainPaymentError => ({ kind: "NegativeApplicationFee" })),
  unitVariant("NotCancelable").transform((): DomainPaymentError => ({ kind: "NotCancelable" })),
  unitVariant("InvalidTransition")
    .transform((): DomainPaymentError => ({ kind: "InvalidTransition" })),
]);

/**
 * Each type read from the JSON text serde_json writes, through `parseJson`;
 * throws on malformed text or a value the schema refuses.
 */
export const fromJson = {
  Amount: (text: string): DomainAmount => Amount.parse(parseJson(text)),
  PaymentMethodId: (text: string): DomainPaymentMethodId => PaymentMethodId.parse(parseJson(text)),
  MethodKind: (text: string): DomainMethodKind => MethodKind.parse(parseJson(text)),
  PaymentMethod: (text: string): DomainPaymentMethod => PaymentMethod.parse(parseJson(text)),
  CaptureMethod: (text: string): DomainCaptureMethod => CaptureMethod.parse(parseJson(text)),
  ConfirmationMethod: (text: string): DomainConfirmationMethod =>
    ConfirmationMethod.parse(parseJson(text)),
  Terms: (text: string): DomainTerms => Terms.parse(parseJson(text)),
  DeclineCode: (text: string): DomainDeclineCode => DeclineCode.parse(parseJson(text)),
  CancellationReason: (text: string): DomainCancellationReason =>
    CancellationReason.parse(parseJson(text)),
  Status: (text: string): DomainStatus => Status.parse(parseJson(text)),
  PaymentIntent: (text: string): DomainPaymentIntent => PaymentIntent.parse(parseJson(text)),
  Outcome: (text: string): DomainOutcome => Outcome.parse(parseJson(text)),
  Event: (text: string): DomainEvent => Event.parse(parseJson(text)),
  PaymentError: (text: string): DomainPaymentError => PaymentError.parse(parseJson(text)),
} as const;

/** Each type written as serde_json writes the Rust value. */
export const toJson = {
  Amount: (x: DomainAmount): string => Json.int(x),
  PaymentMethodId: (x: DomainPaymentMethodId): string => Json.str(x),
  MethodKind: (x: DomainMethodKind): string => `"${x.kind}"`,
  PaymentMethod: (x: DomainPaymentMethod): string => Json.object([
    ["id", toJson.PaymentMethodId(x.id)],
    ["kind", toJson.MethodKind(x.kind)],
  ]),
  CaptureMethod: (x: DomainCaptureMethod): string => `"${x.kind}"`,
  ConfirmationMethod: (x: DomainConfirmationMethod): string => `"${x.kind}"`,
  Terms: (x: DomainTerms): string => Json.object([
    ["amount", toJson.Amount(x.amount)],
    ["capture", toJson.CaptureMethod(x.capture)],
    ["confirmation", toJson.ConfirmationMethod(x.confirmation)],
  ]),
  DeclineCode: (x: DomainDeclineCode): string => `"${x.kind}"`,
  CancellationReason: (x: DomainCancellationReason): string => `"${x.kind}"`,
  Status: (x: DomainStatus): string => {
    switch (x.kind) {
      case "RequiresPaymentMethod":
        return Json.object([[
          "RequiresPaymentMethod",
          Json.object([[
            "last_error",
            (x.last_error === null ? "null" : toJson.DeclineCode(x.last_error)),
          ]]),
        ]]);
      case "RequiresConfirmation":
        return Json.object([[
          "RequiresConfirmation",
          Json.object([["method", toJson.PaymentMethod(x.method)]]),
        ]]);
      case "RequiresAction":
        return Json.object([[
          "RequiresAction",
          Json.object([["method", toJson.PaymentMethod(x.method)]]),
        ]]);
      case "Processing":
        return Json.object([[
          "Processing",
          Json.object([["method", toJson.PaymentMethod(x.method)]]),
        ]]);
      case "RequiresCapture":
        return Json.object([[
          "RequiresCapture",
          Json.object([
            ["method", toJson.PaymentMethod(x.method)],
            ["capturable", Json.int(x.capturable)],
          ]),
        ]]);
      case "Succeeded":
        return Json.object([[
          "Succeeded",
          Json.object([
            ["received", Json.int(x.received)],
            [
              "application_fee",
              (x.application_fee === null ? "null" : Json.int(x.application_fee)),
            ],
          ]),
        ]]);
      case "Canceled":
        return Json.object([[
          "Canceled",
          Json.object([[
            "reason",
            (x.reason === null ? "null" : toJson.CancellationReason(x.reason)),
          ]]),
        ]]);
    }
  },
  PaymentIntent: (x: DomainPaymentIntent): string => Json.object([
    ["terms", toJson.Terms(x.terms)],
    ["status", toJson.Status(x.status)],
  ]),
  Outcome: (x: DomainOutcome): string => {
    switch (x.kind) {
      case "Authorized":
        return "\"Authorized\"";
      case "ActionRequired":
        return "\"ActionRequired\"";
      case "Pending":
        return "\"Pending\"";
      case "Declined":
        return Json.object([["Declined", toJson.DeclineCode(x.value)]]);
    }
  },
  Event: (x: DomainEvent): string => {
    switch (x.kind) {
      case "AttachMethod":
        return Json.object([["AttachMethod", toJson.PaymentMethod(x.value)]]);
      case "Confirm":
        return Json.object([[
          "Confirm",
          Json.object([
            ["method", (x.method === null ? "null" : toJson.PaymentMethod(x.method))],
            ["outcome", toJson.Outcome(x.outcome)],
          ]),
        ]]);
      case "ActionHandled":
        return Json.object([["ActionHandled", toJson.Outcome(x.value)]]);
      case "ProcessingSucceeded":
        return "\"ProcessingSucceeded\"";
      case "ProcessingFailed":
        return Json.object([["ProcessingFailed", toJson.DeclineCode(x.value)]]);
      case "Capture":
        return Json.object([[
          "Capture",
          Json.object([
            [
              "amount_to_capture",
              (x.amount_to_capture === null ? "null" : Json.int(x.amount_to_capture)),
            ],
            [
              "application_fee",
              (x.application_fee === null ? "null" : Json.int(x.application_fee)),
            ],
          ]),
        ]]);
      case "Cancel":
        return Json.object([[
          "Cancel",
          (x.value === null ? "null" : toJson.CancellationReason(x.value)),
        ]]);
    }
  },
  PaymentError: (x: DomainPaymentError): string => {
    switch (x.kind) {
      case "AmountOutOfRange":
        return "\"AmountOutOfRange\"";
      case "InvalidPaymentMethodId":
        return "\"InvalidPaymentMethodId\"";
      case "MissingPaymentMethod":
        return "\"MissingPaymentMethod\"";
      case "InvalidCaptureAmount":
        return Json.object([[
          "InvalidCaptureAmount",
          Json.object([["capturable", Json.int(x.capturable)]]),
        ]]);
      case "NegativeApplicationFee":
        return "\"NegativeApplicationFee\"";
      case "NotCancelable":
        return "\"NotCancelable\"";
      case "InvalidTransition":
        return "\"InvalidTransition\"";
    }
  },
} as const;
