/* generated by purecrate-ts. do not edit. */

import { Json } from "./purecrate-runtime.ts";
import { z } from "zod";
import { i64, nullable, optionalField, str, unitVariant } from "./purecrate-zod.ts";
import { Amount as Amount$value, type Amount as Amount$ } from "./amount.ts";
import { PaymentMethodId as PaymentMethodId$value, type PaymentMethodId as PaymentMethodId$ } from "./payment-method-id.ts";
import type { MethodKind as MethodKind$ } from "./method-kind.ts";
import type { PaymentMethod as PaymentMethod$ } from "./payment-method.ts";
import type { CaptureMethod as CaptureMethod$ } from "./capture-method.ts";
import type { ConfirmationMethod as ConfirmationMethod$ } from "./confirmation-method.ts";
import type { Terms as Terms$ } from "./terms.ts";
import type { DeclineCode as DeclineCode$ } from "./decline-code.ts";
import type { CancellationReason as CancellationReason$ } from "./cancellation-reason.ts";
import type { Status as Status$ } from "./status.ts";
import type { PaymentIntent as PaymentIntent$ } from "./payment-intent.ts";
import type { Outcome as Outcome$ } from "./outcome.ts";
import type { Event as Event$ } from "./event.ts";
import type { PaymentError as PaymentError$ } from "./payment-error.ts";

export const Amount: z.ZodType<Amount$, unknown> = i64.transform((v, ctx): Amount$ => {
  const r = Amount$value.tryFrom(v);
  if (r.kind === "Err") {
    ctx.addIssue({ code: "custom", message: `Amount: ${r.error.kind}`, input: v, params: { error: r.error } });
    return z.NEVER;
  }
  return r.value;
});

export const PaymentMethodId: z.ZodType<PaymentMethodId$, unknown> = str.transform((v, ctx): PaymentMethodId$ => {
  const r = PaymentMethodId$value.tryFrom(v);
  if (r.kind === "Err") {
    ctx.addIssue({ code: "custom", message: `PaymentMethodId: ${r.error.kind}`, input: v, params: { error: r.error } });
    return z.NEVER;
  }
  return r.value;
});

export const MethodKind: z.ZodType<MethodKind$, unknown> = z.union([
  unitVariant("Card").transform((): MethodKind$ => ({ kind: "Card" })),
  unitVariant("BankDebit").transform((): MethodKind$ => ({ kind: "BankDebit" })),
]);

export const PaymentMethod: z.ZodType<PaymentMethod$, unknown> = z.object({
  id: PaymentMethodId,
  kind: MethodKind,
})
  .transform((v): PaymentMethod$ => ({ id: v.id, kind: v.kind }));

export const CaptureMethod: z.ZodType<CaptureMethod$, unknown> = z.union([
  unitVariant("Automatic").transform((): CaptureMethod$ => ({ kind: "Automatic" })),
  unitVariant("Manual").transform((): CaptureMethod$ => ({ kind: "Manual" })),
]);

export const ConfirmationMethod: z.ZodType<ConfirmationMethod$, unknown> = z.union([
  unitVariant("Automatic").transform((): ConfirmationMethod$ => ({ kind: "Automatic" })),
  unitVariant("Manual").transform((): ConfirmationMethod$ => ({ kind: "Manual" })),
]);

export const Terms: z.ZodType<Terms$, unknown> = z.object({
  amount: Amount,
  capture: CaptureMethod,
  confirmation: ConfirmationMethod,
})
  .transform((v): Terms$ => ({ amount: v.amount, capture: v.capture, confirmation: v.confirmation }));

export const DeclineCode: z.ZodType<DeclineCode$, unknown> = z.union([
  unitVariant("CardDeclined").transform((): DeclineCode$ => ({ kind: "CardDeclined" })),
  unitVariant("InsufficientFunds")
    .transform((): DeclineCode$ => ({ kind: "InsufficientFunds" })),
  unitVariant("AuthenticationFailed")
    .transform((): DeclineCode$ => ({ kind: "AuthenticationFailed" })),
  unitVariant("DebitFailed").transform((): DeclineCode$ => ({ kind: "DebitFailed" })),
]);

export const CancellationReason: z.ZodType<CancellationReason$, unknown> = z.union([
  unitVariant("Duplicate").transform((): CancellationReason$ => ({ kind: "Duplicate" })),
  unitVariant("Fraudulent").transform((): CancellationReason$ => ({ kind: "Fraudulent" })),
  unitVariant("RequestedByCustomer")
    .transform((): CancellationReason$ => ({ kind: "RequestedByCustomer" })),
  unitVariant("Abandoned").transform((): CancellationReason$ => ({ kind: "Abandoned" })),
]);

export const Status: z.ZodType<Status$, unknown> = z.union([
  z.object({ RequiresPaymentMethod: z.object({ last_error: optionalField(DeclineCode) }) })
    .strict()
    .transform((v): Status$ => ({ kind: "RequiresPaymentMethod", last_error: v.RequiresPaymentMethod.last_error })),
  z.object({ RequiresConfirmation: z.object({ method: PaymentMethod }) })
    .strict()
    .transform((v): Status$ => ({ kind: "RequiresConfirmation", method: v.RequiresConfirmation.method })),
  z.object({ RequiresAction: z.object({ method: PaymentMethod }) })
    .strict()
    .transform((v): Status$ => ({ kind: "RequiresAction", method: v.RequiresAction.method })),
  z.object({ Processing: z.object({ method: PaymentMethod }) })
    .strict()
    .transform((v): Status$ => ({ kind: "Processing", method: v.Processing.method })),
  z.object({ RequiresCapture: z.object({ method: PaymentMethod, capturable: i64 }) })
    .strict()
    .transform((v): Status$ => ({
      kind: "RequiresCapture",
      method: v.RequiresCapture.method,
      capturable: v.RequiresCapture.capturable,
    })),
  z.object({ Succeeded: z.object({ received: i64, application_fee: optionalField(i64) }) })
    .strict()
    .transform((v): Status$ => ({
      kind: "Succeeded",
      received: v.Succeeded.received,
      application_fee: v.Succeeded.application_fee,
    })),
  z.object({ Canceled: z.object({ reason: optionalField(CancellationReason) }) })
    .strict()
    .transform((v): Status$ => ({ kind: "Canceled", reason: v.Canceled.reason })),
]);

export const PaymentIntent: z.ZodType<PaymentIntent$, unknown> = z.object({
  terms: Terms,
  status: Status,
})
  .transform((v): PaymentIntent$ => ({ terms: v.terms, status: v.status }));

export const Outcome: z.ZodType<Outcome$, unknown> = z.union([
  unitVariant("Authorized").transform((): Outcome$ => ({ kind: "Authorized" })),
  unitVariant("ActionRequired").transform((): Outcome$ => ({ kind: "ActionRequired" })),
  unitVariant("Pending").transform((): Outcome$ => ({ kind: "Pending" })),
  z.object({ Declined: DeclineCode })
    .strict()
    .transform((v): Outcome$ => ({ kind: "Declined", content: [v.Declined] })),
]);

export const Event: z.ZodType<Event$, unknown> = z.union([
  z.object({ AttachMethod: PaymentMethod })
    .strict()
    .transform((v): Event$ => ({ kind: "AttachMethod", content: [v.AttachMethod] })),
  z.object({ Confirm: z.object({ method: optionalField(PaymentMethod), outcome: Outcome }) })
    .strict()
    .transform((v): Event$ => ({ kind: "Confirm", method: v.Confirm.method, outcome: v.Confirm.outcome })),
  z.object({ ActionHandled: Outcome })
    .strict()
    .transform((v): Event$ => ({ kind: "ActionHandled", content: [v.ActionHandled] })),
  unitVariant("ProcessingSucceeded")
    .transform((): Event$ => ({ kind: "ProcessingSucceeded" })),
  z.object({ ProcessingFailed: DeclineCode })
    .strict()
    .transform((v): Event$ => ({ kind: "ProcessingFailed", content: [v.ProcessingFailed] })),
  z.object({ Capture: z.object({ amount_to_capture: optionalField(i64), application_fee: optionalField(i64) }) })
    .strict()
    .transform((v): Event$ => ({
      kind: "Capture",
      amount_to_capture: v.Capture.amount_to_capture,
      application_fee: v.Capture.application_fee,
    })),
  z.object({ Cancel: nullable(CancellationReason) })
    .strict()
    .transform((v): Event$ => ({ kind: "Cancel", content: [v.Cancel] })),
]);

export const PaymentError: z.ZodType<PaymentError$, unknown> = z.union([
  unitVariant("AmountOutOfRange")
    .transform((): PaymentError$ => ({ kind: "AmountOutOfRange" })),
  unitVariant("InvalidPaymentMethodId")
    .transform((): PaymentError$ => ({ kind: "InvalidPaymentMethodId" })),
  unitVariant("MissingPaymentMethod")
    .transform((): PaymentError$ => ({ kind: "MissingPaymentMethod" })),
  z.object({ InvalidCaptureAmount: z.object({ capturable: i64 }) })
    .strict()
    .transform((v): PaymentError$ => ({ kind: "InvalidCaptureAmount", capturable: v.InvalidCaptureAmount.capturable })),
  unitVariant("NegativeApplicationFee")
    .transform((): PaymentError$ => ({ kind: "NegativeApplicationFee" })),
  unitVariant("NotCancelable").transform((): PaymentError$ => ({ kind: "NotCancelable" })),
  unitVariant("InvalidTransition")
    .transform((): PaymentError$ => ({ kind: "InvalidTransition" })),
]);

/** Each type written as serde_json writes the Rust value. */
export const toJson = {
  Amount: (x: Amount$): string => Json.int(x),
  PaymentMethodId: (x: PaymentMethodId$): string => Json.str(x),
  MethodKind: (x: MethodKind$): string => `"${x.kind}"`,
  PaymentMethod: (x: PaymentMethod$): string => `{"id":${toJson.PaymentMethodId(x.id)},"kind":${toJson.MethodKind(x.kind)}}`,
  CaptureMethod: (x: CaptureMethod$): string => `"${x.kind}"`,
  ConfirmationMethod: (x: ConfirmationMethod$): string => `"${x.kind}"`,
  Terms: (x: Terms$): string => `{"amount":${toJson.Amount(x.amount)},"capture":${toJson.CaptureMethod(x.capture)},"confirmation":${toJson.ConfirmationMethod(x.confirmation)}}`,
  DeclineCode: (x: DeclineCode$): string => `"${x.kind}"`,
  CancellationReason: (x: CancellationReason$): string => `"${x.kind}"`,
  Status: (x: Status$): string => {
    switch (x.kind) {
      case "RequiresPaymentMethod":
        return `{"RequiresPaymentMethod":{"last_error":${(x.last_error === null ? "null" : toJson.DeclineCode(x.last_error))}}}`;
      case "RequiresConfirmation":
        return `{"RequiresConfirmation":{"method":${toJson.PaymentMethod(x.method)}}}`;
      case "RequiresAction":
        return `{"RequiresAction":{"method":${toJson.PaymentMethod(x.method)}}}`;
      case "Processing":
        return `{"Processing":{"method":${toJson.PaymentMethod(x.method)}}}`;
      case "RequiresCapture":
        return `{"RequiresCapture":{"method":${toJson.PaymentMethod(x.method)},"capturable":${Json.int(x.capturable)}}}`;
      case "Succeeded":
        return `{"Succeeded":{"received":${Json.int(x.received)},"application_fee":${(x.application_fee === null ? "null" : Json.int(x.application_fee))}}}`;
      case "Canceled":
        return `{"Canceled":{"reason":${(x.reason === null ? "null" : toJson.CancellationReason(x.reason))}}}`;
    }
  },
  PaymentIntent: (x: PaymentIntent$): string => `{"terms":${toJson.Terms(x.terms)},"status":${toJson.Status(x.status)}}`,
  Outcome: (x: Outcome$): string => {
    switch (x.kind) {
      case "Authorized":
        return "\"Authorized\"";
      case "ActionRequired":
        return "\"ActionRequired\"";
      case "Pending":
        return "\"Pending\"";
      case "Declined":
        return `{"Declined":${toJson.DeclineCode(x.content[0])}}`;
    }
  },
  Event: (x: Event$): string => {
    switch (x.kind) {
      case "AttachMethod":
        return `{"AttachMethod":${toJson.PaymentMethod(x.content[0])}}`;
      case "Confirm":
        return `{"Confirm":{"method":${(x.method === null ? "null" : toJson.PaymentMethod(x.method))},"outcome":${toJson.Outcome(x.outcome)}}}`;
      case "ActionHandled":
        return `{"ActionHandled":${toJson.Outcome(x.content[0])}}`;
      case "ProcessingSucceeded":
        return "\"ProcessingSucceeded\"";
      case "ProcessingFailed":
        return `{"ProcessingFailed":${toJson.DeclineCode(x.content[0])}}`;
      case "Capture":
        return `{"Capture":{"amount_to_capture":${(x.amount_to_capture === null ? "null" : Json.int(x.amount_to_capture))},"application_fee":${(x.application_fee === null ? "null" : Json.int(x.application_fee))}}}`;
      case "Cancel":
        return `{"Cancel":${(x.content[0] === null ? "null" : toJson.CancellationReason(x.content[0]))}}`;
    }
  },
  PaymentError: (x: PaymentError$): string => {
    switch (x.kind) {
      case "AmountOutOfRange":
        return "\"AmountOutOfRange\"";
      case "InvalidPaymentMethodId":
        return "\"InvalidPaymentMethodId\"";
      case "MissingPaymentMethod":
        return "\"MissingPaymentMethod\"";
      case "InvalidCaptureAmount":
        return `{"InvalidCaptureAmount":{"capturable":${Json.int(x.capturable)}}}`;
      case "NegativeApplicationFee":
        return "\"NegativeApplicationFee\"";
      case "NotCancelable":
        return "\"NotCancelable\"";
      case "InvalidTransition":
        return "\"InvalidTransition\"";
    }
  },
} as const;
