/* generated by purecrate-ts. do not edit. */

import type { DisplayError } from "./display-error.ts";
import type { ErrorRedirect } from "./error-redirect.ts";

export type AuthorizationError =
  | Readonly<{ kind: "Display"; content: readonly [DisplayError] }>
  | Readonly<{ kind: "Redirect"; content: readonly [ErrorRedirect] }>;

export const AuthorizationError = {
  Display: (_0: DisplayError): AuthorizationError => ({ kind: "Display", content: [_0] }),
  Redirect: (_0: ErrorRedirect): AuthorizationError => ({ kind: "Redirect", content: [_0] }),
} as const;
