/* generated by purecrate-ts. do not edit. */

import { type I64 } from "./int.ts";
import type { OtpDigits } from "./otp-digits.ts";

export type TotpEnrollment = Readonly<{
  t0: I64;
  period: I64;
  digits: OtpDigits;
  last_used_step: I64 | null;
}>;

export const TotpEnrollment = {
  of: (t0: I64, period: I64, digits: OtpDigits, last_used_step: I64 | null): TotpEnrollment => ({ t0, period, digits, last_used_step }),
} as const;
