/* generated by purecrate-ts. do not edit. */

import type { EmailError } from "./email-error.ts";
import type { PasswordError } from "./password-error.ts";

export type SignupError =
  | Readonly<{ kind: "Email"; content: readonly [EmailError] }>
  | Readonly<{ kind: "Password"; content: readonly [PasswordError] }>;

export const SignupError = {
  Email: (_0: EmailError): SignupError => ({ kind: "Email", content: [_0] }),
  Password: (_0: PasswordError): SignupError => ({ kind: "Password", content: [_0] }),
} as const;
