/* generated by purecrate-ts. do not edit. */

const panic = (what: string): never => {
  throw new Error(`attempt to ${what}`);
};

const small = (min: number, max: number) => {
  const fit = (n: number, what: string): number =>
    n < min || n > max ? panic(`${what} with overflow`) : n + 0;
  return {
    add: (a: number, b: number): number => fit(a + b, "add"),
    sub: (a: number, b: number): number => fit(a - b, "subtract"),
    mul: (a: number, b: number): number => fit(a * b, "multiply"),
    div: (a: number, b: number): number =>
      b === 0 ? panic("divide by zero") : fit(Math.trunc(a / b), "divide"),
    rem: (a: number, b: number): number =>
      b === 0
        ? panic("calculate the remainder with a divisor of zero")
        : (fit(Math.trunc(a / b), "calculate the remainder"), (a % b) + 0),
    neg: (a: number): number => fit(-a, "negate"),
  } as const;
};

const big = (min: bigint, max: bigint) => {
  const fit = (n: bigint, what: string): bigint =>
    n < min || n > max ? panic(`${what} with overflow`) : n;
  return {
    add: (a: bigint, b: bigint): bigint => fit(a + b, "add"),
    sub: (a: bigint, b: bigint): bigint => fit(a - b, "subtract"),
    mul: (a: bigint, b: bigint): bigint => fit(a * b, "multiply"),
    div: (a: bigint, b: bigint): bigint =>
      b === 0n ? panic("divide by zero") : fit(a / b, "divide"),
    rem: (a: bigint, b: bigint): bigint =>
      b === 0n
        ? panic("calculate the remainder with a divisor of zero")
        : (fit(a / b, "calculate the remainder"), a % b),
    neg: (a: bigint): bigint => fit(-a, "negate"),
  } as const;
};

export const Int = {
  i8: small(-128, 127),
  i16: small(-32768, 32767),
  i32: small(-2147483648, 2147483647),
  u8: small(0, 255),
  u16: small(0, 65535),
  u32: small(0, 4294967295),
  usize: small(0, 9007199254740991),
  i64: big(-9223372036854775808n, 9223372036854775807n),
  u64: big(0n, 18446744073709551615n),
} as const;
