/* generated by purecrate-ts. do not edit. */
// `purecrate` from purecrate-ts (packages/boundary; MIT, https://github.com/manji-0/purecrate-ts),
// copied in at the generator's revision.

/**
 * The runtime of packages generated by purecrate-ts. Every generated package
 * carries its own copy (src/purecrate-runtime.ts). The brands are keyed by
 * string, not by `unique symbol`, so an `I32` or a `Uuid` from one package's
 * copy is the same type as another's and values pass between packages.
 */
export type I8 = number & { readonly "purecrate.I8": true };
export type I16 = number & { readonly "purecrate.I16": true };
export type I32 = number & { readonly "purecrate.I32": true };
export type I64 = bigint & { readonly "purecrate.I64": true };
export type U8 = number & { readonly "purecrate.U8": true };
export type U16 = number & { readonly "purecrate.U16": true };
export type U32 = number & { readonly "purecrate.U32": true };
export type U64 = bigint & { readonly "purecrate.U64": true };
export type Usize = number & { readonly "purecrate.Usize": true };
export type F32 = number & { readonly "purecrate.F32": true };
export type F64 = number & { readonly "purecrate.F64": true };
/** A Rust `char`: a string of exactly one Unicode scalar value (no lone surrogate). */
export type Char = string & { readonly "purecrate.Char": true };

const panic = (what: string): never => {
  throw new Error(`attempt to ${what}`);
};

const small = <T extends number>(min: number, max: number) => {
  const fit = (n: number, what: string): T =>
    (n < min || n > max ? panic(`${what} with overflow`) : n + 0) as T;
  const of = (value: number): T => {
    if (!Number.isInteger(value)) panic("convert a non-integer");
    return fit(value, "convert");
  };
  return {
    of,
    add: (a: T, b: T): T => fit(a + b, "add"),
    sub: (a: T, b: T): T => fit(a - b, "subtract"),
    mul: (a: T, b: T): T => fit(a * b, "multiply"),
    div: (a: T, b: T): T =>
      b === 0 ? panic("divide by zero") : fit(Math.trunc(a / b), "divide"),
    rem: (a: T, b: T): T =>
      b === 0
        ? panic("calculate the remainder with a divisor of zero")
        : ((fit(Math.trunc(a / b), "calculate the remainder"), (a % b) + 0) as T),
    neg: (a: T): T => fit(-a, "negate"),
  } as const;
};

const big = <T extends bigint>(min: bigint, max: bigint) => {
  const fit = (n: bigint, what: string): T =>
    (n < min || n > max ? panic(`${what} with overflow`) : n) as T;
  const n = (x: T): bigint => x as bigint;
  return {
    of: (value: bigint): T => fit(value, "convert"),
    add: (a: T, b: T): T => fit(n(a) + n(b), "add"),
    sub: (a: T, b: T): T => fit(n(a) - n(b), "subtract"),
    mul: (a: T, b: T): T => fit(n(a) * n(b), "multiply"),
    div: (a: T, b: T): T =>
      n(b) === 0n ? panic("divide by zero") : fit(n(a) / n(b), "divide"),
    rem: (a: T, b: T): T =>
      n(b) === 0n
        ? panic("calculate the remainder with a divisor of zero")
        : ((fit(n(a) / n(b), "calculate the remainder"), n(a) % n(b)) as unknown as T),
    neg: (a: T): T => fit(-n(a), "negate"),
  } as const;
};

/**
 * The integer methods, from the exact result: `x.checked_add(y)` is it or
 * `null` outside the range, `saturating_*` clamps it, `wrapping_*` keeps its
 * low `bits`, and the others panic outside the range as a debug build does.
 * `lo..=hi` is Rust's range; `to` makes the runtime value, and for `usize`
 * throws above 2^53−1, which a `number` cannot hold (design/01 §3).
 */
const methods = <T extends number | bigint>(lo: bigint, hi: bigint, bits: number, signed: boolean, to: (n: bigint) => T) => {
  const v = (x: T): bigint => BigInt(x);
  const inRange = (n: bigint): boolean => n >= lo && n <= hi;
  const fit = (n: bigint | null, what: string): T => (n !== null && inRange(n) ? to(n) : panic(`${what} with overflow`));
  const checked = (n: bigint | null): T | null => (n !== null && inRange(n) ? to(n) : null);
  const clamp = (n: bigint): T => to(n < lo ? lo : n > hi ? hi : n);
  const wrap = (n: bigint): T => to(signed ? BigInt.asIntN(bits, n) : BigInt.asUintN(bits, n));
  // `a ** e`, or `null` where it is certainly outside the range: a base of
  // magnitude 2 or more to an exponent of `bits` or more.
  const power = (a: bigint, e: number): bigint | null =>
    e === 0 ? 1n : a === 0n || a === 1n ? a : a === -1n ? (e % 2 === 0 ? 1n : -1n) : e >= bits ? null : a ** BigInt(e);
  const modPower = (a: bigint, e: number): bigint => {
    const m = 1n << BigInt(bits);
    let base = BigInt.asUintN(bits, a);
    let acc = 1n;
    for (let k = e; k > 0; k = Math.floor(k / 2)) {
      if (k % 2 === 1) acc = (acc * base) % m;
      base = (base * base) % m;
    }
    return acc;
  };
  const quotient = (a: bigint, b: bigint): bigint | null => (b === 0n ? null : a / b);
  const zero = (b: T, what: string): void => {
    if (v(b) === 0n) panic(what);
  };
  return {
    min: (a: T, b: T): T => (a <= b ? a : b),
    max: (a: T, b: T): T => (a >= b ? a : b),
    abs: (a: T): T => fit(v(a) < 0n ? -v(a) : v(a), "negate"),
    pow: (a: T, e: U32): T => fit(power(v(a), e), "exponentiate"),
    checkedAdd: (a: T, b: T): T | null => checked(v(a) + v(b)),
    checkedSub: (a: T, b: T): T | null => checked(v(a) - v(b)),
    checkedMul: (a: T, b: T): T | null => checked(v(a) * v(b)),
    checkedDiv: (a: T, b: T): T | null => checked(quotient(v(a), v(b))),
    // `MIN % -1` is `None`: the quotient it comes from overflows.
    checkedRem: (a: T, b: T): T | null =>
      checked(quotient(v(a), v(b))) === null ? null : to(v(a) % v(b)),
    checkedNeg: (a: T): T | null => checked(-v(a)),
    checkedPow: (a: T, e: U32): T | null => checked(power(v(a), e)),
    saturatingAdd: (a: T, b: T): T => clamp(v(a) + v(b)),
    saturatingSub: (a: T, b: T): T => clamp(v(a) - v(b)),
    saturatingMul: (a: T, b: T): T => clamp(v(a) * v(b)),
    saturatingPow: (a: T, e: U32): T => {
      const n = power(v(a), e);
      return n !== null ? clamp(n) : to(v(a) < 0n && e % 2 === 1 ? lo : hi);
    },
    wrappingAdd: (a: T, b: T): T => wrap(v(a) + v(b)),
    wrappingSub: (a: T, b: T): T => wrap(v(a) - v(b)),
    wrappingMul: (a: T, b: T): T => wrap(v(a) * v(b)),
    wrappingDiv: (a: T, b: T): T => (zero(b, "divide by zero"), wrap(v(a) / v(b))),
    wrappingRem: (a: T, b: T): T => (zero(b, "calculate the remainder with a divisor of zero"), wrap(v(a) % v(b))),
    wrappingNeg: (a: T): T => wrap(-v(a)),
    wrappingPow: (a: T, e: U32): T => wrap(modPower(v(a), e)),
  } as const;
};

const small64 = (n: bigint): Usize =>
  n > 9007199254740991n ? panicWith(`usize value ${n} does not fit in 53 bits`) : (Number(n) as Usize);

/**
 * The amount of a shift, of any integer type. A debug build panics unless it
 * is in `0..bits`, comparing the whole value (so `-1` and `2^32 + 1` panic);
 * bits shifted out of the result are dropped without a panic.
 */
const shiftAmount = (n: number | bigint, bits: number, what: string): number =>
  n < 0 || n >= bits ? panic(`shift ${what} with overflow`) : Number(n);

/**
 * `& | ^ ! << >>` on a width of at most 32 bits. The JS operators work on
 * int32; `wrap` sign- or zero-extends the low `bits` back into the width.
 */
const bits32 = <T extends number>(bits: number, signed: boolean) => {
  const s = 32 - bits;
  const wrap = (n: number): T => (signed ? (n << s) >> s : (n << s) >>> s) as T;
  return {
    and: (a: T, b: T): T => wrap(a & b),
    or: (a: T, b: T): T => wrap(a | b),
    xor: (a: T, b: T): T => wrap(a ^ b),
    not: (a: T): T => wrap(~a),
    shl: (a: T, n: number | bigint): T => wrap(a << shiftAmount(n, bits, "left")),
    shr: (a: T, n: number | bigint): T => {
      const k = shiftAmount(n, bits, "right");
      return wrap(signed ? a >> k : a >>> k);
    },
  } as const;
};

/** `& | ^ ! << >>` on 64 bits. `bigint` `>>` is arithmetic, as Rust's is on `i64`. */
const bits64 = <T extends bigint>(signed: boolean) => {
  const wrap = (n: bigint): T => (signed ? BigInt.asIntN(64, n) : BigInt.asUintN(64, n)) as T;
  const v = (x: T): bigint => x as bigint;
  return {
    and: (a: T, b: T): T => wrap(v(a) & v(b)),
    or: (a: T, b: T): T => wrap(v(a) | v(b)),
    xor: (a: T, b: T): T => wrap(v(a) ^ v(b)),
    not: (a: T): T => wrap(~v(a)),
    shl: (a: T, n: number | bigint): T => wrap(v(a) << BigInt(shiftAmount(n, 64, "left"))),
    shr: (a: T, n: number | bigint): T => wrap(v(a) >> BigInt(shiftAmount(n, 64, "right"))),
  } as const;
};

const INTEGER_LITERAL = /^-?(?:0|[1-9]\d*)$/;

/**
 * JSON text read as `JSON.parse` reads it, except that an integer literal
 * outside ±(2^53−1) becomes a `bigint` with its exact value. serde_json writes
 * `i64` and `u64` as JSON numbers; `JSON.parse` would round them.
 *
 * Needs a runtime that passes the literal's source text to the reviver
 * (Node 21+). Elsewhere the number stays rounded, and the `i64`/`u64`
 * schemas reject it instead of reading a wrong value.
 */
export const parseJson = (text: string): unknown =>
  JSON.parse(text, (_key: string, value: unknown, context?: { source?: string }) =>
    typeof value === "number" &&
    !Number.isSafeInteger(value) &&
    context?.source !== undefined &&
    INTEGER_LITERAL.test(context.source)
      ? BigInt(context.source)
      : value,
  );

/**
 * `str` operations whose result depends on the encoding (design/01 §6).
 * Rust counts and indexes a string in UTF-8 bytes; JS in UTF-16 units. The
 * string must be well-formed: a lone surrogate is not a Rust `String`, and
 * its bytes here are not specified.
 */
export const Str = {
  /** `str::as_bytes`: the UTF-8 bytes. */
  bytes: (s: string): ReadonlyArray<U8> => {
    const out: number[] = [];
    for (const c of s) {
      const p = c.codePointAt(0) as number;
      if (p < 0x80) out.push(p);
      else if (p < 0x800) out.push(0xc0 | (p >> 6), 0x80 | (p & 0x3f));
      else if (p < 0x10000) out.push(0xe0 | (p >> 12), 0x80 | ((p >> 6) & 0x3f), 0x80 | (p & 0x3f));
      else out.push(0xf0 | (p >> 18), 0x80 | ((p >> 12) & 0x3f), 0x80 | ((p >> 6) & 0x3f), 0x80 | (p & 0x3f));
    }
    return out as unknown as ReadonlyArray<U8>;
  },
  /** `str::len`: the number of UTF-8 bytes. */
  len: (s: string): Usize => utf8Len(s),
  /**
   * `&s[start..end]` at UTF-8 byte positions (`end` absent for `&s[start..]`).
   * Panics as Rust does, in its order: a position past the end, a reversed
   * range, then a position inside a character, shown as `Debug` shows it.
   */
  slice: (s: string, start: Usize, end?: Usize): string => {
    const len = utf8Len(s);
    const stop = end ?? len;
    if (start > len) panicWith(`start byte index ${start} is out of bounds for string of length ${len}`);
    if (stop > len) panicWith(`end byte index ${stop} is out of bounds for string of length ${len}`);
    if (start > stop) panicWith(`byte range starts at ${start} but ends at ${stop}`);
    let byte = 0;
    let unit = 0;
    let from = -1;
    let to = -1;
    let inside: string | null = null;
    for (const c of s) {
      const w = utf8Width(c);
      if (byte === start) from = unit;
      if (byte === stop) to = unit;
      for (const [which, at] of [["start", start], ["end", stop]] as const) {
        if (inside === null && at > byte && at < byte + w) {
          inside = `${which} byte index ${at} is not a char boundary; it is inside '${debugChar(c)}' (bytes ${byte}..${byte + w} of string)`;
        }
      }
      byte += w;
      unit += c.length;
    }
    if (byte === start) from = unit;
    if (byte === stop) to = unit;
    if (from < 0 || to < 0) panicWith(inside as string);
    return s.slice(from, to);
  },
  /** `str::strip_prefix` with a `&str`. */
  stripPrefix: (s: string, p: string): string | null => (s.startsWith(p) ? s.slice(p.length) : null),
  /** `str::strip_suffix` with a `&str`. */
  stripSuffix: (s: string, p: string): string | null => (s.endsWith(p) ? s.slice(0, s.length - p.length) : null),
} as const;

/**
 * A non-ASCII `char` as Rust's `Debug` writes it between quotes: `\u{..}`
 * for a grapheme extender or a code point that is not printable (the
 * categories core's `printable.py` escapes), itself otherwise. The tables are
 * the JS engine's; they agree with Rust's where both use one Unicode version
 * (design/01 §3).
 */
const debugChar = (c: string): string =>
  /[\p{Grapheme_Extend}\p{Zs}\p{Zl}\p{Zp}\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Cn}]/u.test(c) && c !== " "
    ? `\\u{${(c.codePointAt(0) as number).toString(16)}}`
    : c;

const utf8Len = (s: string): Usize => {
  let n = 0;
  for (const c of s) n += utf8Width(c);
  return n as Usize;
};

const utf8Width = (c: string): number => {
  const p = c.codePointAt(0) as number;
  return p < 0x80 ? 1 : p < 0x800 ? 2 : p < 0x10000 ? 3 : 4;
};

const code = (c: Char): number => c.codePointAt(0) as number;
const within = (c: Char, lo: number, hi: number): boolean => code(c) >= lo && code(c) <= hi;
const upper = (c: Char): boolean => within(c, 0x41, 0x5a);
const lower = (c: Char): boolean => within(c, 0x61, 0x7a);
const digit = (c: Char): boolean => within(c, 0x30, 0x39);
const radix = (r: U32): number =>
  r < 2 || r > 36 ? panicWith("to_digit: invalid radix -- radix must be in the range 2 to 36 inclusive") : r;
const panicWith = (message: string): never => {
  throw new Error(message);
};
const digitValue = (c: Char, r: U32): number | null => {
  const base = radix(r);
  const p = code(c);
  const d = p >= 0x30 && p <= 0x39 ? p - 0x30 : (p | 0x20) >= 0x61 && (p | 0x20) <= 0x7a ? (p | 0x20) - 0x61 + 10 : 99;
  return d < base ? d : null;
};

/**
 * `char` operations (design/01 §6). Ordering and ranges go through `code`:
 * JS orders strings by UTF-16 unit, which puts U+E000..=U+FFFF above the
 * supplementary planes. Only ASCII and code-point methods are here; the
 * Unicode-table ones (`is_alphabetic`, ...) are not.
 */
export const Char = {
  /** Checks `s` is one Unicode scalar value, as serde reads a `char`. */
  is: (s: string): s is Char => {
    const p = s.codePointAt(0);
    return p !== undefined && s.length === (p > 0xffff ? 2 : 1) && (p < 0xd800 || p > 0xdfff);
  },
  /** `u32::from(c)`: the code point. */
  code: (c: Char): U32 => code(c) as U32,
  /** `char::from(b)`: U+0000..=U+00FF. */
  fromU8: (b: U8): Char => String.fromCharCode(b) as Char,
  /** `char::from_u32(n)`: `None` for a surrogate or past U+10FFFF. */
  fromU32: (n: U32): Char | null =>
    (n >= 0xd800 && n <= 0xdfff) || n > 0x10ffff ? null : (String.fromCodePoint(n) as Char),
  isAscii: (c: Char): boolean => code(c) < 0x80,
  isAsciiAlphabetic: (c: Char): boolean => upper(c) || lower(c),
  isAsciiAlphanumeric: (c: Char): boolean => upper(c) || lower(c) || digit(c),
  isAsciiControl: (c: Char): boolean => code(c) < 0x20 || code(c) === 0x7f,
  isAsciiDigit: digit,
  isAsciiGraphic: (c: Char): boolean => within(c, 0x21, 0x7e),
  isAsciiHexdigit: (c: Char): boolean => digit(c) || within(c, 0x41, 0x46) || within(c, 0x61, 0x66),
  isAsciiLowercase: lower,
  isAsciiPunctuation: (c: Char): boolean =>
    within(c, 0x21, 0x2f) || within(c, 0x3a, 0x40) || within(c, 0x5b, 0x60) || within(c, 0x7b, 0x7e),
  isAsciiUppercase: upper,
  /** Space, tab, LF, FF, CR. Not VT (U+000B), unlike JS `\s`. */
  isAsciiWhitespace: (c: Char): boolean => [0x20, 0x09, 0x0a, 0x0c, 0x0d].includes(code(c)),
  toAsciiLowercase: (c: Char): Char => (upper(c) ? (String.fromCharCode(code(c) + 32) as Char) : c),
  toAsciiUppercase: (c: Char): Char => (lower(c) ? (String.fromCharCode(code(c) - 32) as Char) : c),
  eqIgnoreAsciiCase: (a: Char, b: Char): boolean => Char.toAsciiLowercase(a) === Char.toAsciiLowercase(b),
  /** `char::len_utf8`: 1 to 4. */
  lenUtf8: (c: Char): Usize => (code(c) < 0x80 ? 1 : code(c) < 0x800 ? 2 : code(c) < 0x10000 ? 3 : 4) as Usize,
  /** ASCII digits and letters only, as Rust; panics on a radix outside 2..=36. */
  isDigit: (c: Char, r: U32): boolean => digitValue(c, r) !== null,
  toDigit: (c: Char, r: U32): U32 | null => digitValue(c, r) as U32 | null,
} as const;

/**
 * A `uuid::Uuid`, always in the lowercase hyphenated form (8-4-4-4-12) that
 * serde writes. In that form `===` is Rust's `==`, and string order is the
 * order of the 16 bytes, as the hyphens sit at the same places in both.
 */
export type Uuid = string & { readonly "purecrate.Uuid": true };
/** A `uuid::Error`. Nothing translated reads one, so it carries nothing. */
export type UuidError = { readonly "purecrate.UuidError": true };

const UUID_ERROR = Object.freeze({}) as UuidError;
const HEX32 = /^[0-9a-fA-F]{32}$/;
const HYPHENATED = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/;

/**
 * The 32 hex digits of what `uuid`'s parser accepts, chosen by length as it
 * does: simple (32), hyphenated (36), braced (38), `urn:uuid:` (45; the
 * prefix in lowercase only). Rust measures in UTF-8 bytes and JS in UTF-16
 * units, but any non-ASCII character fails the hex check either way.
 */
const uuidDigits = (s: string): string | null => {
  if (s.length === 32) return HEX32.test(s) ? s : null;
  const body =
    s.length === 36
      ? s
      : s.length === 38 && s.startsWith("{") && s.endsWith("}")
        ? s.slice(1, 37)
        : s.length === 45 && s.startsWith("urn:uuid:")
          ? s.slice(9)
          : null;
  return body !== null && HYPHENATED.test(body) ? body.replaceAll("-", "") : null;
};

/** `uuid::Uuid` operations (design/01 §6). */
export const Uuid = {
  /**
   * `Uuid::parse_str` (and `try_parse`): the canonical form of any string
   * the `uuid` crate reads, in any case; `Err` otherwise. Shaped as the
   * generated `Result`.
   */
  parseStr: (s: string): Readonly<{ kind: "Ok"; value: Uuid }> | Readonly<{ kind: "Err"; error: UuidError }> => {
    const d = uuidDigits(s)?.toLowerCase();
    return d === undefined
      ? { kind: "Err", error: UUID_ERROR }
      : {
          kind: "Ok",
          value: `${d.slice(0, 8)}-${d.slice(8, 12)}-${d.slice(12, 16)}-${d.slice(16, 20)}-${d.slice(20)}` as Uuid,
        };
  },
  /** `Uuid::nil()`. */
  nil: (): Uuid => "00000000-0000-0000-0000-000000000000" as Uuid,
} as const;

/** Integer and float widths. Domain packages and schema adapters share these brands. */
export const Int = {
  i8: { ...small<I8>(-128, 127), ...bits32<I8>(8, true), ...methods(-128n, 127n, 8, true, (n) => Number(n) as I8) },
  i16: { ...small<I16>(-32768, 32767), ...bits32<I16>(16, true), ...methods(-32768n, 32767n, 16, true, (n) => Number(n) as I16) },
  i32: {
    ...small<I32>(-2147483648, 2147483647),
    ...bits32<I32>(32, true),
    ...methods(-2147483648n, 2147483647n, 32, true, (n) => Number(n) as I32),
  },
  u8: { ...small<U8>(0, 255), ...bits32<U8>(8, false), ...methods(0n, 255n, 8, false, (n) => Number(n) as U8) },
  u16: { ...small<U16>(0, 65535), ...bits32<U16>(16, false), ...methods(0n, 65535n, 16, false, (n) => Number(n) as U16) },
  u32: { ...small<U32>(0, 4294967295), ...bits32<U32>(32, false), ...methods(0n, 4294967295n, 32, false, (n) => Number(n) as U32) },
  // No bitwise operators: Rust's `usize` has 64 bits, this one 53. Its
  // methods work in Rust's 64 bits and throw on a result above 2^53−1.
  usize: { ...small<Usize>(0, 9007199254740991), ...methods(0n, 18446744073709551615n, 64, false, small64) },
  i64: {
    ...big<I64>(-9223372036854775808n, 9223372036854775807n),
    ...bits64<I64>(true),
    ...methods(-9223372036854775808n, 9223372036854775807n, 64, true, (n) => n as I64),
  },
  u64: {
    ...big<U64>(0n, 18446744073709551615n),
    ...bits64<U64>(false),
    ...methods(0n, 18446744073709551615n, 64, false, (n) => n as U64),
  },
  f32: {
    of: (value: number): F32 => Math.fround(value) as F32,
  },
  f64: {
    of: (value: number): F64 => value as F64,
  },
} as const;

/** Shortest digits and decimal exponent: `digits` × 10^(`point` − length). */
const decimal = (x: number): { digits: string; point: number } => {
  const [mantissa, exponent] = x.toExponential().split("e");
  return { digits: mantissa.replace("-", "").replace(".", ""), point: Number(exponent) + 1 };
};

/**
 * A finite float laid out as ryu writes it for serde_json: `1.0`, `0.001`,
 * `1e16`, `1.5e-7`. Plain notation holds for 10^(`low`) ≤ |x| < 10^`high`.
 */
const ryu = (x: number, digits: string, point: number, high: number, low: number): string => {
  const sign = x < 0 || Object.is(x, -0) ? "-" : "";
  if (x === 0) return `${sign}0.0`;
  const length = digits.length;
  if (point >= length && point <= high) return `${sign}${digits}${"0".repeat(point - length)}.0`;
  if (point > 0 && point <= high) return `${sign}${digits.slice(0, point)}.${digits.slice(point)}`;
  if (point > low && point <= 0) return `${sign}0.${"0".repeat(-point)}${digits}`;
  const rest = length === 1 ? "" : `.${digits.slice(1)}`;
  return `${sign}${digits[0]}${rest}e${point - 1}`;
};

/**
 * Writes domain values as serde_json writes the Rust value (design/04 §6):
 * integers exactly (`bigint` included), floats as ryu lays them out, and
 * non-finite floats as `null`, which serde_json then cannot read back.
 * Generated `toJson` encoders compose these.
 */
export const Json = {
  int: (n: number | bigint): string => String(n),
  bool: (b: boolean): string => (b ? "true" : "false"),
  /** JSON.stringify escapes as serde_json does for well-formed strings. */
  str: (s: string): string => JSON.stringify(s),
  f64: (x: number): string => {
    if (!Number.isFinite(x)) return "null";
    const { digits, point } = decimal(x);
    return ryu(x, digits, point, 16, -5);
  },
  /**
   * The shortest digits that read back as the same `f32`. When two are
   * equally near, ryu takes the even one; `toPrecision` rounds half up.
   */
  f32: (x: number): string => {
    if (!Number.isFinite(x)) return "null";
    // At most 9 digits are needed; 100 give the exact value of any `f32`
    // whose expansion could end in a tie.
    const [exact, exponent] = Math.abs(x).toExponential(99).split("e");
    const all = exact.replace(".", "");
    for (let p = 1; p <= 9; p++) {
      const shorter = Number(x.toPrecision(p));
      if (Math.fround(shorter) !== x) continue;
      let digits = decimal(shorter).digits;
      let point = decimal(shorter).point;
      const tie = all[p] === "5" && /^0*$/.test(all.slice(p + 1));
      if (tie && Number(all[p - 1]) % 2 === 0) {
        const down = Number(`${x < 0 ? "-" : ""}${all[0]}.${all.slice(1, p)}e${exponent}`);
        if (Math.fround(down) === x) ({ digits, point } = decimal(down));
      }
      return ryu(x, digits, point, 13, -6);
    }
    return "null";
  },
  array: <T>(xs: ReadonlyArray<T>, write: (x: T) => string): string => `[${xs.map((x) => write(x)).join(",")}]`,
} as const;
