/* generated by purecrate-ts. do not edit. */

import type { U32, Usize } from "./purecrate-runtime.ts";
import type { MediaParameter } from "./media-parameter.ts";

declare class Element$brand {
  private brand: unknown;
}
export type Element = Readonly<{
  head: string;
  tail: string;
  params: ReadonlyArray<MediaParameter>;
  q: U32;
  weighted: boolean;
  at: Usize;
}> &
  Element$brand;

/**
 * Makes `Element` values without a check.
 *
 * Its fields are not `pub` in Rust, so outside the crate a value comes only
 * from the crate's functions; the generated files build them here, and
 * `index.ts` does not export it.
 * @internal
 */
export const unsafeMakeElement = (
  fields: Readonly<{
    head: string;
    tail: string;
    params: ReadonlyArray<MediaParameter>;
    q: U32;
    weighted: boolean;
    at: Usize;
  }>,
): Element => fields as Element;

export const Element = {} as const;
