/* generated by purecrate-ts. do not edit. */

import { Char, Iter, Str } from "./purecrate-runtime.ts";

export const isLanguageRange = (s: string, wildcard: boolean): boolean => {
  if (s === "*") return wildcard;
  const option = Str.splitOnce(s, "-");
  const primary: string = option !== null ? option[0] : s;
  return (
    Iter.all(primary as Iterable<Char>, (c: Char): boolean => Char.isAsciiAlphabetic(c)) &&
    Iter.all(
      s.split("-"),
      (t: string): boolean =>
        t.length !== 0 &&
        Str.len(t) <= 8 &&
        Iter.all(t as Iterable<Char>, (c: Char): boolean => Char.isAsciiAlphanumeric(c)),
    )
  );
};
