/* generated by purecrate-ts. do not edit. */

import { Char } from "./purecrate-runtime.ts";

export const isTchar = (c: Char): boolean =>
  Char.isAsciiAlphanumeric(c) ||
  c === "!" ||
  c === "#" ||
  c === "$" ||
  c === "%" ||
  c === "&" ||
  c === "'" ||
  c === "*" ||
  c === "+" ||
  c === "-" ||
  c === "." ||
  c === "^" ||
  c === "_" ||
  c === "`" ||
  c === "|" ||
  c === "~";
