/* generated by purecrate-ts. do not edit. */

import type { Element } from "./element.ts";
import type { MediaRange } from "./media-range.ts";

export const mediaOf = (e: Element): MediaRange => ({
  ty: e.head,
  subtype: e.tail,
  params: [...e.params],
  q: e.q,
});
