/* generated by purecrate-ts. do not edit. */
// `purecrate` from purecrate-ts (packages/boundary), copied in at the generator's revision.
//
// Copyright (c) 2026 Wataru Manji
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/**
 * The runtime of packages generated by purecrate-ts. Every generated package
 * carries its own copy (src/purecrate-runtime.ts). The brands are keyed by
 * string, not by `unique symbol`, so an `I32` or a `Uuid` from one package's
 * copy is the same type as another's and values pass between packages.
 *
 * A package's copy keeps only what its code uses: the region and needs
 * comments below mark code kept when any use they list is found in the
 * package, and are left out of the copy (crates/pack/src/trim.rs).
 */
/** Rust's `Result`, as every generated package reads and builds it. */
export type Result<T, E> =
  | Readonly<{ kind: "Ok"; value: T }>
  | Readonly<{ kind: "Err"; error: E }>;

export const Result = {
  ok: <T, E = never>(value: T): Result<T, E> => ({ kind: "Ok", value }),
  err: <T = never, E = never>(error: E): Result<T, E> => ({ kind: "Err", error }),
  isOk: <T, E>(r: Result<T, E>): r is Readonly<{ kind: "Ok"; value: T }> => r.kind === "Ok",
  isErr: <T, E>(r: Result<T, E>): r is Readonly<{ kind: "Err"; error: E }> => r.kind === "Err",
} as const;

/**
 * A domain panic: overflow, division by zero, a shift out of range, or an
 * index/slice Rust would panic on. `message` is Rust's panic text. Named
 * `Panic` so `instanceof` works across copies of this file (`Symbol.for`).
 */
const PANIC = Symbol.for("purecrate.Panic");

export class Panic extends Error {
  readonly [PANIC] = true;
  constructor(message: string) {
    super(message);
    this.name = "Panic";
  }
  static [Symbol.hasInstance](value: unknown): boolean {
    return typeof value === "object" && value !== null && PANIC in (value as object);
  }
}

/** The `default` of a `switch` that names every variant: unreachable. */
export const assertNever = (_x: never): never => {
  throw new Error("unexpected variant");
};

export type U8 = number & { readonly "purecrate.U8": true };
export type U32 = number & { readonly "purecrate.U32": true };
export type Usize = number & { readonly "purecrate.Usize": true };
/** A Rust `char`: a string of exactly one Unicode scalar value (no lone surrogate). */
export type Char = string & { readonly "purecrate.Char": true };

const panic = (what: string): never => {
  throw new Panic(`attempt to ${what}`);
};

const small = <T extends number>(min: number, max: number) => {
  const fit = (n: number, what: string): T =>
    (n < min || n > max ? panic(`${what} with overflow`) : n + 0) as T;
  const of = (value: number): T => {
    if (!Number.isInteger(value)) panic("convert a non-integer");
    return fit(value, "convert");
  };
  return {
    of,
    add: (a: T, b: T): T => fit(a + b, "add"),
    sub: (a: T, b: T): T => fit(a - b, "subtract"),
    mul: (a: T, b: T): T => fit(a * b, "multiply"),
    div: (a: T, b: T): T =>
      b === 0 ? panic("divide by zero") : fit(Math.trunc(a / b), "divide"),
  } as const;
};

/** `x as T` to a type of 32 bits or fewer: the low `bits` bits, read signed or not, as Rust's `as` wraps. */
const cast32 =
  <T extends number>(bits: number, signed: boolean) =>
  (x: number | bigint): T => {
    if (typeof x === "bigint") return Number(signed ? BigInt.asIntN(bits, x) : BigInt.asUintN(bits, x)) as T;
    const s = 32 - bits;
    return (signed ? (x << s) >> s : (x << s) >>> s) as T;
  };

/**
 * `str` operations whose result depends on the encoding (design/01 §6).
 * Rust counts and indexes a string in UTF-8 bytes; JS in UTF-16 units. The
 * string must be well-formed: a lone surrogate is not a Rust `String`, and
 * its bytes here are not specified.
 */
/** The objects and arrays `Str.wellFormed` has found free of lone surrogates. */
const wellFormedSeen = new WeakSet<object>();
export const Str = {
  /** `str::as_bytes`: the UTF-8 bytes. */
  bytes: (s: string): ReadonlyArray<U8> => {
    const out: number[] = [];
    for (const c of s) {
      const p = c.codePointAt(0) as number;
      if (p < 0x80) out.push(p);
      else if (p < 0x800) out.push(0xc0 | (p >> 6), 0x80 | (p & 0x3f));
      else if (p < 0x10000) out.push(0xe0 | (p >> 12), 0x80 | ((p >> 6) & 0x3f), 0x80 | (p & 0x3f));
      else out.push(0xf0 | (p >> 18), 0x80 | ((p >> 12) & 0x3f), 0x80 | ((p >> 6) & 0x3f), 0x80 | (p & 0x3f));
    }
    return out as unknown as ReadonlyArray<U8>;
  },
  /** `str::len`: the number of UTF-8 bytes. */
  len: (s: string): Usize => utf8Len(s),
  /**
   * `&s[start..end]` at UTF-8 byte positions (`end` absent for `&s[start..]`).
   * Panics as Rust does, in its order: a position past the end, a reversed
   * range, then a position inside a character, shown as `Debug` shows it.
   */
  slice: (s: string, start: Usize, end?: Usize): string => {
    const len = utf8Len(s);
    const stop = end ?? len;
    if (start > len) panicWith(`start byte index ${start} is out of bounds for string of length ${len}`);
    if (stop > len) panicWith(`end byte index ${stop} is out of bounds for string of length ${len}`);
    if (start > stop) panicWith(`byte range starts at ${start} but ends at ${stop}`);
    let byte = 0;
    let unit = 0;
    let from = -1;
    let to = -1;
    let inside: string | null = null;
    for (const c of s) {
      const w = utf8Width(c);
      if (byte === start) from = unit;
      if (byte === stop) to = unit;
      for (const [which, at] of [["start", start], ["end", stop]] as const) {
        if (inside === null && at > byte && at < byte + w) {
          inside = `${which} byte index ${at} is not a char boundary; it is inside '${debugChar(c)}' (bytes ${byte}..${byte + w} of string)`;
        }
      }
      byte += w;
      unit += c.length;
    }
    if (byte === start) from = unit;
    if (byte === stop) to = unit;
    if (from < 0 || to < 0) panicWith(inside as string);
    return s.slice(from, to);
  },
  /**
   * A `pub` function's argument checked on entry: a lone surrogate is in no
   * Rust `str`, so the call panics here, wherever in the value the string
   * is (a field, a variant's payload, an element, an `Option`). An object or
   * array checked once is not walked again (`wellFormedSeen`): a state passed
   * back on every call costs only its new parts.
   */
  wellFormed: (x: unknown): void => {
    const lone = /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/;
    const visit = (v: unknown): void => {
      if (typeof v === "string") {
        if (lone.test(v)) panicWith("a string holds a lone surrogate, which no Rust `str` does");
      } else if (typeof v === "object" && v !== null && !wellFormedSeen.has(v)) {
        for (const e of Array.isArray(v) ? v : Object.values(v)) visit(e);
        wellFormedSeen.add(v);
      }
    };
    visit(x);
  },
  /** `str::split_once` with a `char` or a `&str`: the text around the first match. */
  splitOnce: (s: string, p: string): readonly [string, string] | null => {
    const i = s.indexOf(p);
    return i < 0 ? null : [s.slice(0, i), s.slice(i + p.length)];
  },
  /**
   * `str::eq_ignore_ascii_case`: equal once ASCII `A`..=`Z` are folded to
   * lower case; every other unit compares as it is (no Unicode folding).
   */
  eqIgnoreAsciiCase: (a: string, b: string): boolean => {
    if (a.length !== b.length) return false;
    const fold = (u: number): number => (u >= 65 && u <= 90 ? u + 32 : u);
    for (let i = 0; i < a.length; i++) {
      if (fold(a.charCodeAt(i)) !== fold(b.charCodeAt(i))) return false;
    }
    return true;
  },
  /** `str::to_ascii_lowercase`: ASCII `A`..=`Z` only (`toLowerCase` folds all of Unicode). */
  toAsciiLowercase: (s: string): string => s.replace(/[A-Z]+/g, (m) => m.toLowerCase()),
  /** `str::trim_start_matches` with a `char`, a `&str`, or a closure on a `char`. */
  trimStartMatches: (s: string, p: string | ((c: Char) => boolean)): string => trimStart(s, p),
} as const;

/** `s` without every leading match of `p`: a string as a whole, or a `char` the closure takes. */
const trimStart = (s: string, p: string | ((c: Char) => boolean)): string => {
  if (typeof p === "string") {
    if (p === "") return s;
    while (s.startsWith(p)) s = s.slice(p.length);
    return s;
  }
  let i = 0;
  for (const c of s) {
    if (!p(c as Char)) break;
    i += c.length;
  }
  return s.slice(i);
};

/** std's `Ordering`, as the crate's `Ordering` declares it. */
type Ordering = Readonly<{ kind: "Less" }> | Readonly<{ kind: "Equal" }> | Readonly<{ kind: "Greater" }>;

/** An `Ordering` as a comparator's number. */
const ORDER = { Less: -1, Equal: 0, Greater: 1 } as const;

const ORDERINGS: readonly [Ordering, Ordering, Ordering] = [{ kind: "Less" }, { kind: "Equal" }, { kind: "Greater" }];

/** `cmp` and `Ordering::then`, giving std's `Ordering`. */
export const Ord = {
  /** `a.cmp(&b)` on an integer or `bool`: JS `<` orders them as Rust does. */
  cmp: <T extends number | bigint | boolean>(a: T, b: T): Ordering => ORDERINGS[a < b ? 0 : a === b ? 1 : 2],
  /** `o.then(p)`: `p` when `o` is `Equal`, else `o`. */
  then: (o: Ordering, p: Ordering): Ordering => (o.kind === "Equal" ? p : o),
} as const;

/**
 * The consuming iterator methods, as std's default methods run them: in
 * order, `all` stopping at the first `false`, `any` and `position` at the
 * first `true`. `sum` adds from `zero` with `add`, the type's checked
 * addition, so it panics where a debug build does.
 */
export const Iter = {
  all: <T>(xs: Iterable<T>, f: (x: T) => boolean): boolean => {
    for (const x of xs) if (!f(x)) return false;
    return true;
  },
  any: <T>(xs: Iterable<T>, f: (x: T) => boolean): boolean => {
    for (const x of xs) if (f(x)) return true;
    return false;
  },
  position: <T>(xs: Iterable<T>, f: (x: T) => boolean): Usize | null => {
    let i = 0;
    for (const x of xs) {
      if (f(x)) return i as Usize;
      i++;
    }
    return null;
  },
  count: (xs: Iterable<unknown>): Usize => {
    let n = 0;
    for (const x of xs) {
      void x;
      n++;
    }
    return n as Usize;
  },
  /** `find(f)`: the first item `f` takes. The items are never `null` (no `Option<Option<_>>`). */
  find: <T>(xs: Iterable<T>, f: (x: T) => boolean): T | null => {
    for (const x of xs) if (f(x)) return x;
    return null;
  },
  /** `min()` / `min_by(f)`: the first of the least. */
  minBy: <T>(xs: Iterable<T>, f: (a: T, b: T) => Ordering): T | null => {
    let best: T | null = null;
    for (const x of xs) if (best === null || f(best, x).kind === "Greater") best = x;
    return best;
  },
  /** `collect::<Result<Vec<T>, E>>()` after `map(f)`: stops at the first `Err`. */
  tryCollect: <X, T, E>(xs: Iterable<X>, f: (x: X) => Result<T, E>): Result<ReadonlyArray<T>, E> => {
    const out: T[] = [];
    for (const x of xs) {
      const r = f(x);
      if (r.kind === "Err") return r;
      out.push(r.value);
    }
    return Result.ok(out);
  },
} as const;

/** Indexing and slicing a `Vec<T>` or `&[T]`, panicking where Rust panics. */
export const Slice = {
  /** `xs[i]`. */
  at: <T>(xs: ReadonlyArray<T>, i: number): T => {
    if (!Number.isInteger(i) || i < 0 || i >= xs.length) {
      throw new Panic(`index out of bounds: the len is ${xs.length} but the index is ${i}`);
    }
    return xs[i] as T;
  },
  /**
   * `v.sort()` / `v.sort_by(f)` on a local's own array: stable, as JS `sort`
   * is since ES2019, so equal elements keep their order as in Rust.
   */
  sortBy: <T>(xs: T[], f: (a: T, b: T) => Ordering): void => {
    xs.sort((a, b) => ORDER[f(a, b).kind]);
  },
} as const;

/**
 * A non-ASCII `char` as Rust's `Debug` writes it between quotes: `\u{..}`
 * for a grapheme extender or a code point that is not printable (the
 * categories core's `printable.py` escapes), itself otherwise. The tables are
 * the JS engine's; they agree with Rust's where both use one Unicode version
 * (design/01 §3).
 */
const debugChar = (c: string): string =>
  (escaped ??= new RegExp("[\\p{Grapheme_Extend}\\p{Zs}\\p{Zl}\\p{Zp}\\p{Cc}\\p{Cf}\\p{Cs}\\p{Co}\\p{Cn}]", "u")).test(c) && c !== " "
    ? `\\u{${(c.codePointAt(0) as number).toString(16)}}`
    : c;
// Built on first use: a literal with Unicode properties costs about half a
// millisecond when the module loads, for a message only a panic prints.
let escaped: RegExp | undefined;

const utf8Len = (s: string): Usize => {
  let n = 0;
  for (const c of s) n += utf8Width(c);
  return n as Usize;
};

const utf8Width = (c: string): number => {
  const p = c.codePointAt(0) as number;
  return p < 0x80 ? 1 : p < 0x800 ? 2 : p < 0x10000 ? 3 : 4;
};

const code = (c: Char): number => c.codePointAt(0) as number;
const within = (c: Char, lo: number, hi: number): boolean => code(c) >= lo && code(c) <= hi;
const upper = (c: Char): boolean => within(c, 0x41, 0x5a);
const lower = (c: Char): boolean => within(c, 0x61, 0x7a);
const digit = (c: Char): boolean => within(c, 0x30, 0x39);
const radix = (r: U32): number =>
  r < 2 || r > 36 ? panicWith("to_digit: invalid radix -- radix must be in the range 2 to 36 inclusive") : r;
const panicWith = (message: string): never => {
  throw new Panic(message);
};
const digitValue = (c: Char, r: U32): number | null => {
  const base = radix(r);
  const p = code(c);
  const d = p >= 0x30 && p <= 0x39 ? p - 0x30 : (p | 0x20) >= 0x61 && (p | 0x20) <= 0x7a ? (p | 0x20) - 0x61 + 10 : 99;
  return d < base ? d : null;
};

/**
 * `char` operations (design/01 §6). Ordering and ranges go through `code`:
 * JS orders strings by UTF-16 unit, which puts U+E000..=U+FFFF above the
 * supplementary planes. Only ASCII and code-point methods are here; the
 * Unicode-table ones (`is_alphabetic`, ...) are not.
 */
export const Char = {
  /** `u32::from(c)`: the code point. */
  code: (c: Char): U32 => code(c) as U32,
  /** `char::from(b)`: U+0000..=U+00FF. */
  fromU8: (b: U8): Char => String.fromCharCode(b) as Char,
  /** `char::from_u32(n)`: `None` for a surrogate or past U+10FFFF. */
  fromU32: (n: U32): Char | null =>
    (n >= 0xd800 && n <= 0xdfff) || n > 0x10ffff ? null : (String.fromCodePoint(n) as Char),
  isAscii: (c: Char): boolean => code(c) < 0x80,
  isAsciiAlphabetic: (c: Char): boolean => upper(c) || lower(c),
  isAsciiAlphanumeric: (c: Char): boolean => upper(c) || lower(c) || digit(c),
  isAsciiControl: (c: Char): boolean => code(c) < 0x20 || code(c) === 0x7f,
  isAsciiDigit: digit,
  isAsciiGraphic: (c: Char): boolean => within(c, 0x21, 0x7e),
  isAsciiHexdigit: (c: Char): boolean => digit(c) || within(c, 0x41, 0x46) || within(c, 0x61, 0x66),
  isAsciiLowercase: lower,
  isAsciiPunctuation: (c: Char): boolean =>
    within(c, 0x21, 0x2f) || within(c, 0x3a, 0x40) || within(c, 0x5b, 0x60) || within(c, 0x7b, 0x7e),
  isAsciiUppercase: upper,
  /** Space, tab, LF, FF, CR. Not VT (U+000B), unlike JS `\s`. */
  isAsciiWhitespace: (c: Char): boolean => [0x20, 0x09, 0x0a, 0x0c, 0x0d].includes(code(c)),
  toAsciiLowercase: (c: Char): Char => (upper(c) ? (String.fromCharCode(code(c) + 32) as Char) : c),
  toAsciiUppercase: (c: Char): Char => (lower(c) ? (String.fromCharCode(code(c) - 32) as Char) : c),
  eqIgnoreAsciiCase: (a: Char, b: Char): boolean => Char.toAsciiLowercase(a) === Char.toAsciiLowercase(b),
  /** `char::len_utf8`: 1 to 4. */
  lenUtf8: (c: Char): Usize => (code(c) < 0x80 ? 1 : code(c) < 0x800 ? 2 : code(c) < 0x10000 ? 3 : 4) as Usize,
  /** ASCII digits and letters only, as Rust; panics on a radix outside 2..=36. */
  isDigit: (c: Char, r: U32): boolean => digitValue(c, r) !== null,
  toDigit: (c: Char, r: U32): U32 | null => digitValue(c, r) as U32 | null,
} as const;

/** Integer and float widths. Domain packages and schema adapters share these brands. */
export const Int = {
  u32: {
    ...small<U32>(0, 4294967295),
    cast: cast32<U32>(32, false),
  },
  // No bitwise operators: Rust's `usize` has 64 bits, this one 53. Its
  // methods work in Rust's 64 bits and throw on a result above 2^53−1.
  usize: {
    ...small<Usize>(0, 9007199254740991),
  },
} as const;

