/* generated by purecrate-ts. do not edit. */

import { Int, Iter, Result, Slice, Str, type U32, type Usize } from "./purecrate-runtime.ts";
import { FULL } from "./consts.ts";
import type { Element } from "./element.ts";
import { insertRanked } from "./insert-ranked.ts";
import type { MediaParameter } from "./media-parameter.ts";
import type { MediaRange } from "./media-range.ts";
import type { NegotiationError } from "./negotiation-error.ts";
import { parseAccept } from "./parse-accept.ts";
import type { Ranked } from "./ranked.ts";
import { scanList } from "./scan-list.ts";

const sameValue = (name: string, a: string, b: string): boolean =>
  name === "charset" ? Str.eqIgnoreAsciiCase(a, b) : a === b;

const hasParameter = (params: ReadonlyArray<MediaParameter>, p: MediaParameter): boolean =>
  Iter.any(
    params,
    (x: MediaParameter): boolean => x.name === p.name && sameValue(p.name, x.value, p.value),
  );

const mediaSpecificity = (range: MediaRange, rep: MediaRange): U32 | null => {
  let level = 0 as U32;

  if (range.ty !== "*") {
    if (range.ty !== rep.ty) return null;
    level = 1000 as U32;

    if (range.subtype !== "*") {
      if (range.subtype !== rep.subtype) return null;
      level = 2000 as U32;
    }
  }

  let count = 0 as U32;

  for (const p of range.params) {
    if (!hasParameter(rep.params, p)) return null;
    count = Int.u32.add(count, 1 as U32);
  }

  return Int.u32.add(level, count);
};

const parseAvailableMedia = (
  available: ReadonlyArray<string>,
): Result<ReadonlyArray<MediaRange>, NegotiationError> => {
  const out: Array<MediaRange> = [];
  let i = 0 as Usize;

  for (const a of available) {
    const index = i;
    i = Int.usize.add(i, 1 as Usize);
    const result = scanList(a, true);
    if (result.kind === "Err") return Result.err({ kind: "InvalidAvailable", index });
    const elements = result.value;
    if (elements.length !== 1) return Result.err({ kind: "InvalidAvailable", index });
    const e: Element = Slice.at(elements, 0);
    if (e.weighted || e.head === "*" || e.tail === "*")
      return Result.err({ kind: "InvalidAvailable", index });
    out.push({ ty: e.head, subtype: e.tail, params: [...e.params], q: FULL });
  }

  return Result.ok(out);
};

export const rankMedia = (
  accept: string | null,
  available: ReadonlyArray<string>,
): Result<ReadonlyArray<Ranked>, NegotiationError> => {
  Str.wellFormed(accept);
  Str.wellFormed(available);
  const repsResult = parseAvailableMedia(available);
  if (repsResult.kind === "Err") return repsResult;
  const reps = repsResult.value;
  let out: ReadonlyArray<Ranked> = [];

  if (accept === null) {
    let i = 0 as Usize;

    for (const _ of reps) {
      const index = i;
      i = Int.usize.add(i, 1 as Usize);
      out = insertRanked(out, { index, q: FULL, specificity: 0 as U32 });
    }
  } else {
    const rangesResult = parseAccept(accept);
    if (rangesResult.kind === "Err") return rangesResult;
    const ranges = rangesResult.value;
    let i2 = 0 as Usize;

    for (const rep of reps) {
      const index = i2;
      i2 = Int.usize.add(i2, 1 as Usize);
      let found = false;
      let bestQ = 0 as U32;
      let bestS = 0 as U32;

      for (const range of ranges) {
        const option = mediaSpecificity(range, rep);
        if (option !== null) {
          const s = option;
          if (!found || s > bestS) {
            found = true;
            bestQ = range.q;
            bestS = s;
          }
        }
      }

      if (found && bestQ > 0) {
        out = insertRanked(out, { index, q: bestQ, specificity: bestS });
      }
    }
  }

  return Result.ok(out);
};
