/* generated by purecrate-ts. do not edit. */

import {
  Char,
  Int,
  Result,
  Slice,
  Str,
  type U32,
  type U8,
  type Usize,
} from "./purecrate-runtime.ts";
import { FULL } from "./consts.ts";
import { unsafeMakeElement, type Element } from "./element.ts";
import { isTchar } from "./is-tchar.ts";
import { malformed } from "./malformed.ts";
import type { MediaParameter } from "./media-parameter.ts";
import type { NegotiationError } from "./negotiation-error.ts";

const isCtl = (b: U8): boolean => (b < 0x20 && b !== /* '\t' */ 9) || b === 0x7f;

const skipOws = (s: string, start: Usize): Usize =>
  Int.usize.sub(
    Str.len(s),
    Str.len(
      Str.trimStartMatches(Str.slice(s, start), (c: Char): boolean => c === " " || c === "\t"),
    ),
  );

const tokenEnd = (s: string, start: Usize): Result<Usize, NegotiationError> => {
  const end = Int.usize.sub(
    Str.len(s),
    Str.len(Str.trimStartMatches(Str.slice(s, start), isTchar)),
  );
  if (end === start) return Result.err(malformed(start));
  return Result.ok(end);
};

const readValue = (s: string, start: Usize): Result<readonly [string, Usize], NegotiationError> => {
  if (!Str.slice(s, start).startsWith('"')) {
    const endResult = tokenEnd(s, start);
    if (endResult.kind === "Err") return endResult;
    const end = endResult.value;
    return Result.ok([Str.slice(s, start, end), end]);
  }

  const b = Str.bytes(s);
  let out: string = "";
  let chunk: Usize = Int.usize.add(start, 1 as Usize);
  let i: Usize = chunk;
  while (i < b.length && Slice.at(b, i) !== /* '\"' */ 34) {
    if (Slice.at(b, i) === /* '\\' */ 92) {
      if (Int.usize.add(i, 1 as Usize) === b.length) return Result.err(malformed(i));
      out += Str.slice(s, chunk, i);
      chunk = Int.usize.add(i, 1 as Usize);
      i = Int.usize.add(i, 1 as Usize);
    }

    if (isCtl(Slice.at(b, i))) return Result.err(malformed(i));
    i = Int.usize.add(i, 1 as Usize);
  }

  if (i === b.length) return Result.err(malformed(i));
  out += Str.slice(s, chunk, i);
  return Result.ok([out, Int.usize.add(i, 1 as Usize)]);
};

const readQvalue = (v: string): U32 | null => {
  const opt = Str.splitOnce(v, ".");
  const tuple: readonly [string, string] = opt ?? [v, ""];
  const whole = tuple[0];
  const frac = tuple[1];
  if (Str.len(frac) > 3) return null;
  let q = 0 as U32;
  let scale = 100 as U32;

  for (const c of frac as Iterable<Char>) {
    const opt2 = Char.toDigit(c, 10 as U32);
    if (opt2 === null) return null;
    q = Int.u32.add(q, Int.u32.mul(opt2, scale));
    scale = Int.u32.div(scale, 10 as U32);
  }

  if (whole === "0") return q;
  return whole === "1" && q === 0 ? FULL : null;
};

export const scanList = (
  s: string,
  slashed: boolean,
): Result<ReadonlyArray<Element>, NegotiationError> => {
  const out: Array<Element> = [];
  let i: Usize = skipOws(s, 0 as Usize);
  while (i < Str.len(s)) {
    if (Str.slice(s, i).startsWith(",")) {
      i = skipOws(s, Int.usize.add(i, 1 as Usize));
      continue;
    }

    const at = i;
    const tokenEndResult = tokenEnd(s, at);
    if (tokenEndResult.kind === "Err") return tokenEndResult;
    i = tokenEndResult.value;
    const head = Str.toAsciiLowercase(Str.slice(s, at, i));
    let tail: string = "";

    if (slashed) {
      if (!Str.slice(s, i).startsWith("/")) return Result.err(malformed(i));
      const start = Int.usize.add(i, 1 as Usize);
      const tokenEndResult2 = tokenEnd(s, start);
      if (tokenEndResult2.kind === "Err") return tokenEndResult2;
      i = tokenEndResult2.value;
      tail = Str.toAsciiLowercase(Str.slice(s, start, i));
    }

    const params: Array<MediaParameter> = [];
    let q: U32 | null = null;

    while (Str.slice(s, skipOws(s, i)).startsWith(";")) {
      i = skipOws(s, Int.usize.add(skipOws(s, i), 1 as Usize));
      if (i === Str.len(s) || Str.slice(s, i).startsWith(";") || Str.slice(s, i).startsWith(","))
        continue;
      const nameEndResult = tokenEnd(s, i);
      if (nameEndResult.kind === "Err") return nameEndResult;
      const nameEnd = nameEndResult.value;
      const name = Str.toAsciiLowercase(Str.slice(s, i, nameEnd));
      if (!Str.slice(s, nameEnd).startsWith("=")) return Result.err(malformed(nameEnd));
      const start = Int.usize.add(nameEnd, 1 as Usize);
      const result = readValue(s, start);
      if (result.kind === "Err") return result;
      const [value, after] = result.value;
      i = after;

      if (name !== "q") {
        params.push({ name, value });
        continue;
      }

      if (q !== null || Str.slice(s, start).startsWith('"')) return Result.err(malformed(start));
      const opt = readQvalue(value);
      const optOr = malformed(start);
      if (opt === null) return Result.err(optOr);
      q = opt;
    }

    i = skipOws(s, i);
    if (i < Str.len(s) && !Str.slice(s, i).startsWith(",")) return Result.err(malformed(i));
    out.push(unsafeMakeElement({ head, tail, params, q: q ?? FULL, weighted: q !== null, at }));
  }

  return Result.ok(out);
};
