/* generated by purecrate-ts. do not edit. */

import { Int, type U32, type U8 } from "./int.ts";
import { Str } from "./str.ts";
import { digit_count } from "./digit-count.ts";
import type { OtpDigits } from "./otp-digits.ts";

export const parse_otp = (code: string, digits: OtpDigits): U32 | null => {
  if ((Str.len(code) !== digit_count(digits)) || !(() => {
    const $src4: string = code;
    let $acc2: boolean = true;
    $l2: for (const $x1 of Str.bytes($src4)) {
      const b: U8 = $x1;
      if (!(() => {
        if (b >= (48 as U8) && b <= (57 as U8)) {
          return true;
        } else {
          return false;
        }
      })()) {
        $acc2 = false;
        break $l2;
      }
    }
    return $acc2;
  })()) {
    return null;
  }
  let value: U32 = (0 as U32);
  for (const b$1 of Str.bytes(code)) {
    value = Int.u32.add(Int.u32.mul(value, (10 as U32)), (Int.u8.sub(b$1, (48 as U8)) as number as U32));
  }
  return value;
};
