/* generated by purecrate-ts. do not edit. */

import { assertNever } from "./purecrate-runtime.ts";

export type InvoiceError =
  | Readonly<{ kind: "NegativeAmount" }>
  | Readonly<{ kind: "NoLines" }>;

export const InvoiceError = {
  NegativeAmount: (): InvoiceError => ({ kind: "NegativeAmount" }),
  NoLines: (): InvoiceError => ({ kind: "NoLines" }),
  toString: (self: InvoiceError): string => {
    switch (self.kind) {
      case "NegativeAmount":
        return "amount must not be negative";
      case "NoLines":
        return "an invoice needs a line";
      default:
        return assertNever(self);
    }
  },
} as const;
