/* generated by purecrate-ts. do not edit. */

export type Pricing =
  | Readonly<{ kind: "Exclusive" }>
  | Readonly<{ kind: "Inclusive" }>
  | Readonly<{ kind: "FixedRetail" }>;

export const Pricing = {
  Exclusive: (): Pricing => ({ kind: "Exclusive" }),
  Inclusive: (): Pricing => ({ kind: "Inclusive" }),
  /** Tax-inclusive at a price the law fixes (問59, ただし). */
  FixedRetail: (): Pricing => ({ kind: "FixedRetail" }),
} as const;
