/* generated by purecrate-ts. do not edit. */

export type ConfigError = Readonly<{ kind: "SelfInPeers" }> | Readonly<{ kind: "DuplicatePeer" }>;

export const ConfigError = {
  SelfInPeers: (): ConfigError => ({ kind: "SelfInPeers" }),
  DuplicatePeer: (): ConfigError => ({ kind: "DuplicatePeer" }),
} as const;
