/* generated by purecrate-ts. do not edit. */

import type { U64 } from "./purecrate-runtime.ts";

export type LogEntry = Readonly<{
  term: U64;
  command: U64;
}>;

export const LogEntry = {
  of: (term: U64, command: U64): LogEntry => ({ term, command }),
} as const;
