/* generated by purecrate-ts. do not edit. */

import type { Usize, Uuid } from "./purecrate-runtime.ts";

export type Progress = Readonly<{
  peer: Uuid;
  next_index: Usize;
  match_index: Usize;
}>;

export const Progress = {
  of: (peer: Uuid, nextIndex: Usize, matchIndex: Usize): Progress => ({
    peer,
    next_index: nextIndex,
    match_index: matchIndex,
  }),
} as const;
