/* generated by purecrate-ts. do not edit. */

import type { Uuid } from "./purecrate-runtime.ts";
import type { Progress } from "./progress.ts";

export type Role =
  | Readonly<{ kind: "Follower"; leader: Uuid | null }>
  | Readonly<{ kind: "Candidate"; votes: ReadonlyArray<Uuid> }>
  | Readonly<{ kind: "Leader"; progress: ReadonlyArray<Progress> }>;

export const Role = {
  Follower: (leader: Uuid | null): Role => ({ kind: "Follower", leader }),
  Candidate: (votes: ReadonlyArray<Uuid>): Role => ({ kind: "Candidate", votes }),
  Leader: (progress: ReadonlyArray<Progress>): Role => ({ kind: "Leader", progress }),
} as const;
