/* generated by purecrate-ts. do not edit. */

import {
  assertNever,
  Int,
  Iter,
  Result,
  Slice,
  type U64,
  type Usize,
  type Uuid,
} from "./purecrate-runtime.ts";
import type { AppendEntriesReply } from "./append-entries-reply.ts";
import type { AppendEntries } from "./append-entries.ts";
import type { Applied } from "./applied.ts";
import type { Envelope } from "./envelope.ts";
import type { Event } from "./event.ts";
import type { LogEntry } from "./log-entry.ts";
import { Message } from "./message.ts";
import { Node, unsafeMakeNode } from "./node.ts";
import type { Outcome } from "./outcome.ts";
import type { Progress } from "./progress.ts";
import type { RequestVoteReply } from "./request-vote-reply.ts";
import type { RequestVote } from "./request-vote.ts";
import type { StepError } from "./step-error.ts";

export const step = (node: Node, event: Event): Result<Outcome, StepError> => {
  switch (event.kind) {
    case "ElectionTimeout": {
      if (Node.isLeader(node)) return Result.ok(finish(node, [], false));
      const [next, sent] = startElection(node);
      return Result.ok(finish(next, sent, true));
    }
    case "HeartbeatTimeout": {
      const sent = heartbeat(node);
      return Result.ok(finish(node, sent, false));
    }
    case "Propose": {
      const command = event.command;
      return propose(node, command);
    }
    case "Receive": {
      const { from, message } = event;
      return receive(node, from, message);
    }
    default:
      return assertNever(event);
  }
};

const receive = (node: Node, from: Uuid, message: Message): Result<Outcome, StepError> => {
  if (!Iter.any(node.peers, (p: Uuid): boolean => p === from))
    return Result.err({ kind: "UnknownPeer" });
  const term = Message.term(message);
  const node2: Node =
    term > node.current_term
      ? unsafeMakeNode({
          id: node.id,
          peers: node.peers,
          current_term: term,
          voted_for: null,
          log: node.log,
          commit_index: node.commit_index,
          last_applied: node.last_applied,
          role: { kind: "Follower", leader: null },
        })
      : node;

  switch (message.kind) {
    case "RequestVote": {
      const m = message.value;
      return onRequestVote(node2, from, m);
    }
    case "RequestVoteReply": {
      const m = message.value;
      return Result.ok(onVoteReply(node2, from, m));
    }
    case "AppendEntries": {
      const m = message.value;
      return onAppendEntries(node2, from, m);
    }
    case "AppendEntriesReply": {
      const m = message.value;
      return Result.ok(onAppendReply(node2, from, m));
    }
    default:
      return assertNever(message);
  }
};

const termAt = (log: ReadonlyArray<LogEntry>, index: Usize): U64 =>
  index === 0 ? (0n as U64) : Slice.at(log, Int.usize.sub(index, 1 as Usize)).term;

const isMajority = (count: Usize, peers: Usize): boolean =>
  Int.usize.mul(count, 2 as Usize) > Int.usize.add(peers, 1 as Usize);

const finish = (node: Node, messages: ReadonlyArray<Envelope>, reset: boolean): Outcome => {
  const applied: Array<Applied> = [];

  for (
    let i = Int.usize.add(node.last_applied, 1 as Usize),
      end = Int.usize.add(node.commit_index, 1 as Usize);
    i < end;
    i = (i + 1) as Usize
  ) {
    applied.push({ index: i, entry: Slice.at(node.log, Int.usize.sub(i, 1 as Usize)) });
  }

  const commit = node.commit_index;
  return {
    node: unsafeMakeNode({
      id: node.id,
      peers: node.peers,
      current_term: node.current_term,
      voted_for: node.voted_for,
      log: node.log,
      commit_index: node.commit_index,
      last_applied: commit,
      role: node.role,
    }),
    messages,
    applied,
    reset_election_timer: reset,
  };
};

const startElection = (node: Node): readonly [Node, ReadonlyArray<Envelope>] => {
  const term = Int.u64.add(node.current_term, 1n as U64);
  const me = node.id;
  const candidate: Node = unsafeMakeNode({
    id: node.id,
    peers: node.peers,
    current_term: term,
    voted_for: me,
    log: node.log,
    commit_index: node.commit_index,
    last_applied: node.last_applied,
    role: { kind: "Candidate", votes: [me] },
  });
  if (isMajority(1 as Usize, candidate.peers.length as Usize)) return becomeLeader(candidate);
  const lastIndex = candidate.log.length as Usize;
  const lastTerm = termAt(candidate.log, lastIndex);
  const sent: Array<Envelope> = [];

  for (const p of candidate.peers) {
    sent.push({
      to: p,
      message: {
        kind: "RequestVote",
        value: { term, candidate_id: me, last_log_index: lastIndex, last_log_term: lastTerm },
      },
    });
  }

  return [candidate, sent];
};

const becomeLeader = (node: Node): readonly [Node, ReadonlyArray<Envelope>] => {
  const next = Int.usize.add(node.log.length as Usize, 1 as Usize);
  const progress: Array<Progress> = [];

  for (const p of node.peers) {
    progress.push({ peer: p, next_index: next, match_index: 0 as Usize });
  }

  const leader: Node = unsafeMakeNode({
    id: node.id,
    peers: node.peers,
    current_term: node.current_term,
    voted_for: node.voted_for,
    log: node.log,
    commit_index: node.commit_index,
    last_applied: node.last_applied,
    role: { kind: "Leader", progress },
  });
  const sent = heartbeat(leader);
  return [leader, sent];
};

const appendTo = (node: Node, peer: Uuid, nextIndex: Usize): Envelope => {
  const prev = Int.usize.sub(nextIndex, 1 as Usize);
  const entries: Array<LogEntry> = [];

  for (let i = prev, end = node.log.length as Usize; i < end; i = (i + 1) as Usize) {
    entries.push(Slice.at(node.log, i));
  }

  return {
    to: peer,
    message: {
      kind: "AppendEntries",
      value: {
        term: node.current_term,
        leader_id: node.id,
        prev_log_index: prev,
        prev_log_term: termAt(node.log, prev),
        entries,
        leader_commit: node.commit_index,
      },
    },
  };
};

const heartbeat = (node: Node): ReadonlyArray<Envelope> => {
  const sent: Array<Envelope> = [];

  switch (node.role.kind) {
    case "Leader": {
      const progress = node.role.progress;
      for (const p of progress) {
        sent.push(appendTo(node, p.peer, p.next_index));
      }
      break;
    }
    case "Follower":
    case "Candidate":
      break;
    default:
      return assertNever(node.role);
  }

  return sent;
};

const propose = (node: Node, command: U64): Result<Outcome, StepError> => {
  switch (node.role.kind) {
    case "Leader": {
      const progress = node.role.progress;
      const log = [...node.log];
      log.push({ term: node.current_term, command });
      const leader = advanceCommit(
        unsafeMakeNode({
          id: node.id,
          peers: node.peers,
          current_term: node.current_term,
          voted_for: node.voted_for,
          log,
          commit_index: node.commit_index,
          last_applied: node.last_applied,
          role: node.role,
        }),
        progress,
      );
      const sent = heartbeat(leader);
      return Result.ok(finish(leader, sent, false));
    }
    case "Follower": {
      const leader = node.role.leader;
      return Result.err({ kind: "NotLeader", leader });
    }
    case "Candidate":
      return Result.err({ kind: "NotLeader", leader: null });
    default:
      return assertNever(node.role);
  }
};

const advanceCommit = (node: Node, progress: ReadonlyArray<Progress>): Node => {
  let n = node.log.length as Usize;
  let commit: Usize = node.commit_index;

  while (n > node.commit_index) {
    if (Slice.at(node.log, Int.usize.sub(n, 1 as Usize)).term === node.current_term) {
      let count = 1 as Usize;

      for (const p of progress) {
        if (p.match_index >= n) {
          count = Int.usize.add(count, 1 as Usize);
        }
      }

      if (isMajority(count, node.peers.length as Usize)) {
        commit = n;
        break;
      }
    }

    n = Int.usize.sub(n, 1 as Usize);
  }

  return unsafeMakeNode({
    id: node.id,
    peers: node.peers,
    current_term: node.current_term,
    voted_for: node.voted_for,
    log: node.log,
    commit_index: commit,
    last_applied: node.last_applied,
    role: node.role,
  });
};

const replyVote = (node: Node, to: Uuid, granted: boolean): Outcome => {
  const reply: Envelope = {
    to,
    message: {
      kind: "RequestVoteReply",
      value: { term: node.current_term, vote_granted: granted },
    },
  };
  return finish(node, [reply], granted);
};

const onRequestVote = (node: Node, from: Uuid, m: RequestVote): Result<Outcome, StepError> => {
  if (m.candidate_id !== from) return Result.err({ kind: "SenderMismatch" });
  if (m.term < node.current_term) return Result.ok(replyVote(node, from, false));
  const free = node.voted_for === null || node.voted_for === from;
  const myLastIndex = node.log.length as Usize;
  const myLastTerm = termAt(node.log, myLastIndex);
  const upToDate =
    m.last_log_term > myLastTerm ||
    (m.last_log_term === myLastTerm && m.last_log_index >= myLastIndex);
  if (free && upToDate) {
    const voted: Node = unsafeMakeNode({
      id: node.id,
      peers: node.peers,
      current_term: node.current_term,
      voted_for: from,
      log: node.log,
      commit_index: node.commit_index,
      last_applied: node.last_applied,
      role: node.role,
    });
    return Result.ok(replyVote(voted, from, true));
  }

  return Result.ok(replyVote(node, from, false));
};

const onVoteReply = (node: Node, from: Uuid, m: RequestVoteReply): Outcome => {
  switch (node.role.kind) {
    case "Candidate": {
      const votes = node.role.votes;
      if (m.term !== node.current_term || !m.vote_granted) return finish(node, [], false);
      if (Iter.any(votes, (v: Uuid): boolean => v === from)) return finish(node, [], false);
      const more = [...votes];
      more.push(from);

      if (isMajority(more.length as Usize, node.peers.length as Usize)) {
        const [leader, sent] = becomeLeader(node);
        return finish(leader, sent, false);
      }

      return finish(
        unsafeMakeNode({
          id: node.id,
          peers: node.peers,
          current_term: node.current_term,
          voted_for: node.voted_for,
          log: node.log,
          commit_index: node.commit_index,
          last_applied: node.last_applied,
          role: { kind: "Candidate", votes: more },
        }),
        [],
        false,
      );
    }
    case "Follower":
    case "Leader":
      return finish(node, [], false);
    default:
      return assertNever(node.role);
  }
};

const replyAppend = (
  node: Node,
  to: Uuid,
  success: boolean,
  index: Usize,
  reset: boolean,
): Outcome => {
  const reply: Envelope = {
    to,
    message: { kind: "AppendEntriesReply", value: { term: node.current_term, success, index } },
  };
  return finish(node, [reply], reset);
};

const onAppendEntries = (node: Node, from: Uuid, m: AppendEntries): Result<Outcome, StepError> => {
  if (m.leader_id !== from) return Result.err({ kind: "SenderMismatch" });
  if (m.term < node.current_term)
    return Result.ok(replyAppend(node, from, false, m.prev_log_index, false));
  if (Node.isLeader(node)) return Result.err({ kind: "SecondLeader" });
  const node2: Node = unsafeMakeNode({
    id: node.id,
    peers: node.peers,
    current_term: node.current_term,
    voted_for: node.voted_for,
    log: node.log,
    commit_index: node.commit_index,
    last_applied: node.last_applied,
    role: { kind: "Follower", leader: from },
  });
  const prev = m.prev_log_index;
  if (prev > node2.log.length || termAt(node2.log, prev) !== m.prev_log_term)
    return Result.ok(replyAppend(node2, from, false, prev, true));
  const count = m.entries.length as Usize;
  let first: Usize = count;

  for (let k = 0 as Usize, end = count; k < end; k = (k + 1) as Usize) {
    if (first === count) {
      const pos = Int.usize.add(prev, k);
      if (
        pos >= node2.log.length ||
        Slice.at(node2.log, pos).term !== Slice.at(m.entries, k).term
      ) {
        first = k;
      }
    }
  }

  let log: ReadonlyArray<LogEntry>;
  if (first < count) {
    const rebuilt: Array<LogEntry> = [];

    for (let i = 0 as Usize, end = Int.usize.add(prev, first); i < end; i = (i + 1) as Usize) {
      rebuilt.push(Slice.at(node2.log, i));
    }

    for (let k = first, end = count; k < end; k = (k + 1) as Usize) {
      rebuilt.push(Slice.at(m.entries, k));
    }

    log = rebuilt;
  } else {
    log = [...node2.log];
  }

  const lastNew = Int.usize.add(prev, count);
  const commit: Usize =
    m.leader_commit > node2.commit_index
      ? Int.usize.max(node2.commit_index, Int.usize.min(m.leader_commit, lastNew))
      : node2.commit_index;
  const next: Node = unsafeMakeNode({
    id: node2.id,
    peers: node2.peers,
    current_term: node2.current_term,
    voted_for: node2.voted_for,
    log,
    commit_index: commit,
    last_applied: node2.last_applied,
    role: node2.role,
  });
  return Result.ok(replyAppend(next, from, true, lastNew, true));
};

const onAppendReply = (node: Node, from: Uuid, m: AppendEntriesReply): Outcome => {
  let progress: ReadonlyArray<Progress>;
  switch (node.role.kind) {
    case "Leader": {
      const progress2 = node.role.progress;
      progress = progress2;
      break;
    }
    case "Follower":
    case "Candidate":
      return finish(node, [], false);
    default:
      return assertNever(node.role);
  }

  if (m.term !== node.current_term) return finish(node, [], false);
  const last = node.log.length as Usize;
  const updated: Array<Progress> = [];
  let resend: Usize | null = null;

  for (const p of progress) {
    if (p.peer === from) {
      if (m.success) {
        const matched = Int.usize.max(p.match_index, m.index);
        const next = Int.usize.max(p.next_index, Int.usize.add(matched, 1 as Usize));
        updated.push({ peer: p.peer, next_index: next, match_index: matched });

        if (next <= last) {
          resend = next;
        }
      } else if (Int.usize.add(m.index, 1 as Usize) === p.next_index && p.next_index > 1) {
        const next = Int.usize.sub(p.next_index, 1 as Usize);
        updated.push({ peer: p.peer, next_index: next, match_index: p.match_index });
        resend = next;
      } else {
        updated.push(p);
      }
    } else {
      updated.push(p);
    }
  }

  const leader = advanceCommit(
    unsafeMakeNode({
      id: node.id,
      peers: node.peers,
      current_term: node.current_term,
      voted_for: node.voted_for,
      log: node.log,
      commit_index: node.commit_index,
      last_applied: node.last_applied,
      role: { kind: "Leader", progress: [...updated] },
    }),
    updated,
  );
  const sent: ReadonlyArray<Envelope> = resend !== null ? [appendTo(leader, from, resend)] : [];
  return finish(leader, sent, false);
};
