/* generated by purecrate-ts. do not edit. */

import { type I64 } from "./int.ts";
import type { AuthStrength } from "./auth-strength.ts";

/** A completed authentication. */
export type Authentication = Readonly<{
  subject: string;
  auth_time: I64;
  strength: AuthStrength;
  /**
   * The TOTP step accepted in this flow; the caller stores it as the new
   * `last_used_step`.
   */
  totp_step: I64 | null;
}>;

export const Authentication = {
  of: (
    subject: string,
    auth_time: I64,
    strength: AuthStrength,
    totp_step: I64 | null,
  ): Authentication => ({ subject, auth_time, strength, totp_step }),
} as const;
