/* generated by purecrate-ts. do not edit. */

import type { I64 } from "./purecrate-runtime.ts";
import type { Pkce } from "./pkce.ts";
import type { Prompt } from "./prompt.ts";

/**
 * A request that passed §3.1.2.2 validation. Only `validate_request`
 * builds one.
 */
declare const AuthorizationRequest$brand: unique symbol;
export type AuthorizationRequest = Readonly<{
  client_id: string;
  redirect_uri: string;
  scope: string;
  state: string;
  nonce: string | null;
  pkce: Pkce | null;
  prompt: Prompt;
  max_age: I64 | null;
  wants_mfa: boolean;
}> & { readonly [AuthorizationRequest$brand]: true };

/**
 * Makes `AuthorizationRequest` values without a check.
 *
 * Its fields are not `pub` in Rust, so outside the crate a value comes only
 * from the crate's functions; the generated files build them here, and
 * `index.ts` does not export it.
 * @internal
 */
export const unsafeMakeAuthorizationRequest = (
  fields: Readonly<{
    client_id: string;
    redirect_uri: string;
    scope: string;
    state: string;
    nonce: string | null;
    pkce: Pkce | null;
    prompt: Prompt;
    max_age: I64 | null;
    wants_mfa: boolean;
  }>,
): AuthorizationRequest => fields as AuthorizationRequest;

export const AuthorizationRequest = {
  clientId: (self: AuthorizationRequest): string => self.client_id,
  redirectUri: (self: AuthorizationRequest): string => self.redirect_uri,
  scope: (self: AuthorizationRequest): string => self.scope,
  state: (self: AuthorizationRequest): string => self.state,
  wantsMfa: (self: AuthorizationRequest): boolean => self.wants_mfa,
} as const;
