/* generated by purecrate-ts. do not edit. */

import { Int, type I64, type U32 } from "./purecrate-runtime.ts";
import { parseOtp } from "./parse-otp.ts";
import { totpStep } from "./totp-step.ts";
import { truncateMac } from "./truncate-mac.ts";
import type { OtpCheck } from "./otp-check.ts";
import type { StepMac } from "./step-mac.ts";
import type { TotpEnrollment } from "./totp-enrollment.ts";

/**
 * RFC 6238 §5.2: accept steps T-1, T, T+1, but never a step at or before
 * the last accepted one. Candidates outside that window are ignored, so
 * the caller cannot widen it by passing more MACs.
 */
export const checkTotp = (
  code: string,
  now: I64,
  enrollment: TotpEnrollment,
  candidates: ReadonlyArray<StepMac>,
): OtpCheck => {
  let current: I64;
  {
    const option = totpStep(now, enrollment.t0, enrollment.period);
    if (option !== null) {
      const t = option;
      current = t;
    } else {
      return { kind: "ClockBeforeEpoch" };
    }
  }
  let submitted: U32;
  {
    const option = parseOtp(code, enrollment.digits);
    if (option !== null) {
      const v = option;
      submitted = v;
    } else {
      return { kind: "Malformed" };
    }
  }
  let replayed: boolean = false;
  for (const c of candidates) {
    if (c.step >= Int.i64.sub(current, 1n as I64) && c.step <= Int.i64.add(current, 1n as I64)) {
      if ((() => {
        const option2 = truncateMac(c.mac, enrollment.digits);
        if (option2 !== null) {
          const value = option2;
          return value === submitted;
        }
        return false;
      })()) {
        let fresh: boolean;
        {
          const opt: boolean | null = enrollment.last_used_step !== null
            ? c.step > enrollment.last_used_step
            : null;
          fresh = !(opt !== null) || opt;
        }
        if (fresh) return { kind: "Accepted", value: c.step };
        replayed = true;
      }
    }
  }
  return replayed ? { kind: "Replayed" } : { kind: "Mismatch" };
};
