/* generated by purecrate-ts. do not edit. */

import { assertNever, Result } from "./purecrate-runtime.ts";
import { pkceStringIsValid } from "./pkce-string-is-valid.ts";
import type { CodeGrant } from "./code-grant.ts";
import type { TokenError } from "./token-error.ts";

/**
 * Checks a code redemption against its grant. `verifier_s256` is
 * BASE64URL(SHA256(ASCII(code_verifier))), computed by the caller.
 */
export const checkRedemption = (
  grant: CodeGrant,
  clientId: string,
  redirectUri: string,
  codeVerifier: string | null,
  verifierS256: string | null,
): Result<undefined, TokenError> => {
  if ((grant.client_id !== clientId) || (grant.redirect_uri !== redirectUri)) return Result.err({ kind: "InvalidGrant" });
  if (grant.pkce !== null) {
    const pkce = grant.pkce;
    if (codeVerifier !== null) {
      const verifier = codeVerifier;
      if (!pkceStringIsValid(verifier)) {
        return Result.err({ kind: "InvalidRequest" });
      } else {
        const verifier$1: string = verifier;
        let matches: boolean;
        switch (pkce.method.kind) {
          case "Plain":
            matches = verifier$1 === pkce.challenge;
            break;
          case "S256":
            if (verifierS256 !== null) {
              const h = verifierS256;
              matches = h === pkce.challenge;
            } else {
              matches = false;
            }
            break;
          default:
            return assertNever(pkce.method);
        }
        return matches ? Result.ok(undefined) : Result.err({ kind: "InvalidGrant" });
      }
    } else {
      return Result.err({ kind: "InvalidRequest" });
    }
  } else {
    if (codeVerifier !== null) {
      return Result.err({ kind: "InvalidRequest" });
    } else {
      return Result.ok(undefined);
    }
  }
};
