/* generated by purecrate-ts. do not edit. */

import { Result } from "./purecrate-runtime.ts";
import { pkceStringIsValid } from "./pkce-string-is-valid.ts";
import type { CodeGrant } from "./code-grant.ts";
import type { TokenError } from "./token-error.ts";

/**
 * Checks a code redemption against its grant. `verifier_s256` is
 * BASE64URL(SHA256(ASCII(code_verifier))), computed by the caller.
 */
export const checkRedemption = (
  grant: CodeGrant,
  clientId: string,
  redirectUri: string,
  codeVerifier: string | null,
  verifierS256: string | null,
): Result<undefined, TokenError> => {
  if (grant.client_id !== clientId || grant.redirect_uri !== redirectUri)
    return Result.err({ kind: "InvalidGrant" });
  if (grant.pkce !== null) {
    const pkce = grant.pkce;
    if (codeVerifier !== null) {
      const verifier = codeVerifier;
      if (!pkceStringIsValid(verifier)) {
        return Result.err({ kind: "InvalidRequest" });
      } else {
        const matches: boolean = pkce.method.kind === "Plain"
          ? verifier === pkce.challenge
          : verifierS256 !== null &&
        verifierS256 === pkce.challenge;
        return matches ? Result.ok(undefined) : Result.err({ kind: "InvalidGrant" });
      }
    } else {
      return Result.err({ kind: "InvalidRequest" });
    }
  } else {
    return codeVerifier !== null ? Result.err({ kind: "InvalidRequest" }) : Result.ok(undefined);
  }
};
