/* generated by purecrate-ts. do not edit. */

/** Client registration, looked up by the caller from `client_id`. */
export type Client = Readonly<{
  client_id: string;
  redirect_uris: ReadonlyArray<string>;
  /** Public clients must send a code_challenge. */
  require_pkce: boolean;
  /** RFC 7636 §4.2: `plain` only for clients that cannot do S256. */
  allow_plain_pkce: boolean;
}>;

export const Client = {
  of: (
    clientId: string,
    redirectUris: ReadonlyArray<string>,
    requirePkce: boolean,
    allowPlainPkce: boolean,
  ): Client => ({
    client_id: clientId,
    redirect_uris: redirectUris,
    require_pkce: requirePkce,
    allow_plain_pkce: allowPlainPkce,
  }),
} as const;
