/* generated by purecrate-ts. do not edit. */

import type { ErrorCode } from "./error-code.ts";

/**
 * An error response sent to the client's redirect_uri. `state` is echoed
 * exactly when the request carried one (RFC 6749 §4.1.2.1).
 */
export type ErrorRedirect = Readonly<{
  redirect_uri: string;
  error: ErrorCode;
  state: string | null;
}>;

export const ErrorRedirect = {
  of: (redirectUri: string, error: ErrorCode, state: string | null): ErrorRedirect => ({
    redirect_uri: redirectUri,
    error,
    state,
  }),
} as const;
