/* generated by purecrate-ts. do not edit. */

import type { I64 } from "./purecrate-runtime.ts";
import type { OtpRecord } from "./otp-record.ts";
import type { SecondFactor } from "./second-factor.ts";
import type { StepMac } from "./step-mac.ts";

export type Event =
  | Readonly<{
      kind: "PasswordChecked";
      subject: string;
      verified: boolean;
      second_factor: SecondFactor;
      now: I64;
    }>
  | Readonly<{
      kind: "OtpSubmitted";
      code: string;
      now: I64;
      candidates: ReadonlyArray<StepMac>;
      stored: OtpRecord;
    }>
  | Readonly<{ kind: "ConsentGranted" }>
  | Readonly<{ kind: "ConsentDenied" }>;

export const Event = {
  /** The caller verified the password hash for `subject`. */
  PasswordChecked: (
    subject: string,
    verified: boolean,
    secondFactor: SecondFactor,
    now: I64,
  ): Event => ({ kind: "PasswordChecked", subject, verified, second_factor: secondFactor, now }),
  /**
   * `stored`: the subject's record as the caller reads it now, which
   * other flows for the same subject may have advanced.
   */
  OtpSubmitted: (
    code: string,
    now: I64,
    candidates: ReadonlyArray<StepMac>,
    stored: OtpRecord,
  ): Event => ({ kind: "OtpSubmitted", code, now, candidates, stored }),
  ConsentGranted: (): Event => ({ kind: "ConsentGranted" }),
  ConsentDenied: (): Event => ({ kind: "ConsentDenied" }),
} as const;
