/* generated by purecrate-ts. do not edit. */

/** What the login UI should tell the End-User about the last attempt. */
export type Notice =
  | Readonly<{ kind: "Clear" }>
  | Readonly<{ kind: "WrongPassword" }>
  | Readonly<{ kind: "WrongOtp" }>
  | Readonly<{ kind: "OtpReplayed" }>
  | Readonly<{ kind: "MalformedOtp" }>;

export const Notice = {
  Clear: (): Notice => ({ kind: "Clear" }),
  WrongPassword: (): Notice => ({ kind: "WrongPassword" }),
  WrongOtp: (): Notice => ({ kind: "WrongOtp" }),
  OtpReplayed: (): Notice => ({ kind: "OtpReplayed" }),
  MalformedOtp: (): Notice => ({ kind: "MalformedOtp" }),
} as const;
