/* generated by purecrate-ts. do not edit. */

import { Int, type I64, type U8 } from "./int.ts";
import { Str, Iter } from "./str.ts";
import { MAX_SECONDS_DIGITS } from "./consts.ts";

/**
 * A non-negative decimal integer such as `max_age` (OIDC Core §3.1.2.1).
 * At most `MAX_SECONDS_DIGITS` digits so the value fits in i64.
 */
export const parse_seconds = (s: string): I64 | null => {
  if (((s.length === 0) || (Str.len(s) > MAX_SECONDS_DIGITS)) || !Iter.all(Str.bytes(s), ((b: U8): boolean => {
    return (b >= (48 as U8) && b <= (57 as U8));
  }))) {
    return null;
  }
  let value: I64 = (0n as I64);
  for (const b$1 of Str.bytes(s)) {
    value = Int.i64.add(Int.i64.mul(value, (10n as I64)), (globalThis.BigInt(Int.u8.sub(b$1, (48 as U8))) as I64));
  }
  return value;
};
