/* generated by purecrate-ts. do not edit. */

export type PkceMethod = Readonly<{ kind: "S256" }> | Readonly<{ kind: "Plain" }>;

export const PkceMethod = {
  S256: (): PkceMethod => ({ kind: "S256" }),
  Plain: (): PkceMethod => ({ kind: "Plain" }),
} as const;
