/* generated by purecrate-ts. do not edit. */

/** The `prompt` parameter (OIDC Core §3.1.2.1), a space-delimited set. */
export type Prompt = Readonly<{
  no_interaction: boolean;
  login: boolean;
  consent: boolean;
  select_account: boolean;
}>;

export const Prompt = {
  of: (
    noInteraction: boolean,
    login: boolean,
    consent: boolean,
    selectAccount: boolean,
  ): Prompt => ({ no_interaction: noInteraction, login, consent, select_account: selectAccount }),
} as const;
