/* generated by purecrate-ts. do not edit. */

import type { I64 } from "./purecrate-runtime.ts";
import type { AuthStrength } from "./auth-strength.ts";

/** An existing OP session for this browser. */
export type Session = Readonly<{
  subject: string;
  auth_time: I64;
  strength: AuthStrength;
}>;

export const Session = {
  of: (subject: string, authTime: I64, strength: AuthStrength): Session => ({
    subject,
    auth_time: authTime,
    strength,
  }),
} as const;
