/* generated by purecrate-ts. do not edit. */

export type TokenError = Readonly<{ kind: "InvalidRequest" }> | Readonly<{ kind: "InvalidGrant" }>;

export const TokenError = {
  InvalidRequest: (): TokenError => ({ kind: "InvalidRequest" }),
  InvalidGrant: (): TokenError => ({ kind: "InvalidGrant" }),
} as const;
