/* generated by purecrate-ts. do not edit. */

import type { I64, U32 } from "./purecrate-runtime.ts";
import type { OtpDigits } from "./otp-digits.ts";

/** A user's TOTP enrollment, loaded by the caller. */
export type TotpEnrollment = Readonly<{
  /** T0, Unix time to start counting steps (RFC 6238 §4.1). */
  t0: I64;
  /** X, the time step in seconds (RFC 6238 §4.1). */
  period: I64;
  digits: OtpDigits;
  /** The step of the last accepted OTP (RFC 6238 §5.2 replay rule). */
  last_used_step: I64 | null;
  /**
   * OTPs rejected since the last accepted one, across flows
   * (RFC 4226 §7.3).
   */
  failures: U32;
}>;

export const TotpEnrollment = {
  of: (
    t0: I64,
    period: I64,
    digits: OtpDigits,
    lastUsedStep: I64 | null,
    failures: U32,
  ): TotpEnrollment => ({ t0, period, digits, last_used_step: lastUsedStep, failures }),
} as const;
