/* generated by purecrate-ts. do not edit. */

import { Result, type I64 } from "./purecrate-runtime.ts";
import type { AuthorizationError } from "./authorization-error.ts";
import type { AuthorizationParams } from "./authorization-params.ts";
import {
  unsafeMakeAuthorizationRequest,
  type AuthorizationRequest,
} from "./authorization-request.ts";
import type { Client } from "./client.ts";
import { ACR_MFA } from "./consts.ts";
import type { ErrorCode } from "./error-code.ts";
import { hasToken } from "./has-token.ts";
import { parsePrompt } from "./parse-prompt.ts";
import { parseSeconds } from "./parse-seconds.ts";
import type { PkceMethod } from "./pkce-method.ts";
import { pkceStringIsValid } from "./pkce-string-is-valid.ts";
import type { Pkce } from "./pkce.ts";
import type { Prompt } from "./prompt.ts";
import { redirectError } from "./redirect-error.ts";
import { redirectUriRegistered } from "./redirect-uri-registered.ts";
import { stateIsValid } from "./state-is-valid.ts";

/**
 * Validates an authorization request against the client registration.
 *
 * Errors about the client or its redirect_uri are shown to the End-User;
 * everything after that is redirected with `error` and the echoed `state`.
 */
export const validateRequest = (
  params: AuthorizationParams,
  client: Client | null,
): Result<AuthorizationRequest, AuthorizationError> => {
  if (client === null) return Result.err({ kind: "Display", value: { kind: "UnknownClient" } });
  if (params.client_id === null || params.client_id !== client.client_id)
    return Result.err({ kind: "Display", value: { kind: "UnknownClient" } });
  if (params.redirect_uri === null)
    return Result.err({ kind: "Display", value: { kind: "MissingRedirectUri" } });
  const redirectUri: string = params.redirect_uri;
  if (!redirectUriRegistered(client, redirectUri))
    return Result.err({ kind: "Display", value: { kind: "UnregisteredRedirectUri" } });
  const echoed: string | null =
    params.state !== null && stateIsValid(params.state) ? params.state : null;
  const fail = (error: ErrorCode): AuthorizationError => redirectError(redirectUri, error, echoed);
  if (params.response_type === null) return Result.err(fail({ kind: "InvalidRequest" }));
  if (params.response_type !== "code") return Result.err(fail({ kind: "UnsupportedResponseType" }));
  if (params.scope === null || !hasToken(params.scope, "openid"))
    return Result.err(fail({ kind: "InvalidScope" }));
  const scope: string = params.scope;
  if (echoed === null) return Result.err(fail({ kind: "InvalidRequest" }));
  const state: string = echoed;
  let nonce: string | null;
  if (params.nonce !== null) {
    const n = params.nonce;
    if (!stateIsValid(n)) return Result.err(fail({ kind: "InvalidRequest" }));
    nonce = n;
  } else {
    nonce = null;
  }
  let pkce: Pkce | null;
  if (params.code_challenge !== null) {
    const challenge = params.code_challenge;
    if (!pkceStringIsValid(challenge)) return Result.err(fail({ kind: "InvalidRequest" }));
    const method: string | null = params.code_challenge_method;
    let method2: PkceMethod;
    if (method !== null) {
      if (method === "S256") {
        method2 = { kind: "S256" };
      } else if (method === "plain") {
        method2 = { kind: "Plain" };
      } else {
        return Result.err(fail({ kind: "InvalidRequest" }));
      }
    } else {
      method2 = { kind: "Plain" };
    }
    if (method2.kind === "Plain" && !client.allow_plain_pkce)
      return Result.err(fail({ kind: "InvalidRequest" }));
    pkce = { challenge, method: method2 };
  } else {
    if (params.code_challenge_method !== null) return Result.err(fail({ kind: "InvalidRequest" }));
    if (client.require_pkce) return Result.err(fail({ kind: "InvalidRequest" }));
    pkce = null;
  }
  let prompt: Prompt;
  if (params.prompt !== null) {
    const p = params.prompt;
    const opt: Prompt | null = parsePrompt(p);
    const optOr: AuthorizationError = fail({ kind: "InvalidRequest" });
    if (opt === null) return Result.err(optOr);
    prompt = opt;
  } else {
    prompt = { no_interaction: false, login: false, consent: false, select_account: false };
  }
  let maxAge: I64 | null;
  if (params.max_age !== null) {
    const m = params.max_age;
    const opt: I64 | null = parseSeconds(m);
    const optOr: AuthorizationError = fail({ kind: "InvalidRequest" });
    if (opt === null) return Result.err(optOr);
    maxAge = opt;
  } else {
    maxAge = null;
  }
  const wantsMfa: boolean = params.acr_values !== null && hasToken(params.acr_values, ACR_MFA);
  return Result.ok(
    unsafeMakeAuthorizationRequest({
      client_id: client.client_id,
      redirect_uri: redirectUri,
      scope,
      state,
      nonce,
      pkce,
      prompt,
      max_age: maxAge,
      wants_mfa: wantsMfa,
    }),
  );
};
