/* generated by purecrate-ts. do not edit. */

import {
  Int,
  Iter,
  Result,
  Slice,
  Str,
  type I64,
  type U8,
  type Usize,
} from "./purecrate-runtime.ts";
import type { AuthorizationError } from "./authorization-error.ts";
import type { AuthorizationParams } from "./authorization-params.ts";
import {
  unsafeMakeAuthorizationRequest,
  type AuthorizationRequest,
} from "./authorization-request.ts";
import type { Client } from "./client.ts";
import { ACR_MFA, MAX_STATE_LEN, S256_CHALLENGE_LEN } from "./consts.ts";
import type { ErrorCode } from "./error-code.ts";
import { hasToken } from "./has-token.ts";
import type { PkceMethod } from "./pkce-method.ts";
import { pkceStringIsValid } from "./pkce-string-is-valid.ts";
import type { Pkce } from "./pkce.ts";
import type { Prompt } from "./prompt.ts";
import { redirectError } from "./redirect-error.ts";

/**
 * RFC 6749 Appendix A.5: state = 1*VSCHAR, VSCHAR = %x20-7E, at most
 * `MAX_STATE_LEN` bytes.
 */
const stateIsValid = (state: string): boolean =>
  state.length !== 0 &&
  Str.len(state) <= MAX_STATE_LEN &&
  Iter.all(Str.bytes(state), (b: U8): boolean => b >= 0x20 && b <= 0x7e);

/**
 * Whether an S256 challenge can be the transform of some verifier: 43
 * base64url characters, the last of which carries 4 bits of the hash and 2
 * zero bits (RFC 7636 §4.2, RFC 4648 §3.5, §5). Any other challenge would
 * be stored and match no verifier at the token endpoint.
 */
const s256ChallengeIsValid = (s: string): boolean => {
  if (
    Str.len(s) !== S256_CHALLENGE_LEN ||
    !Iter.all(
      Str.bytes(s),
      (c: U8): boolean =>
        (c >= /* 'A' */ 65 && c <= /* 'Z' */ 90) ||
        (c >= /* 'a' */ 97 && c <= /* 'z' */ 122) ||
        (c >= /* '0' */ 48 && c <= /* '9' */ 57) ||
        c === /* '-' */ 45 ||
        c === /* '_' */ 95,
    )
  )
    return false;

  // The last character's value in the base64url alphabet (RFC 4648 §5).
  const last: U8 = Slice.at(Str.bytes(s), Int.usize.sub(S256_CHALLENGE_LEN, 1 as Usize));
  const value: U8 =
    last >= /* 'A' */ 65 && last <= /* 'Z' */ 90
      ? Int.u8.sub(last, /* 'A' */ 65 as U8)
      : last >= /* 'a' */ 97 && last <= /* 'z' */ 122
        ? Int.u8.add(Int.u8.sub(last, /* 'a' */ 97 as U8), 26 as U8)
        : last >= /* '0' */ 48 && last <= /* '9' */ 57
          ? Int.u8.add(Int.u8.sub(last, /* '0' */ 48 as U8), 52 as U8)
          : last === /* '-' */ 45
            ? (62 as U8)
            : (63 as U8);
  return Int.u8.rem(value, 4 as U8) === 0;
};

/**
 * A non-negative decimal integer such as `max_age` (OIDC Core §3.1.2.1):
 * ASCII digits only (no sign), leading zeros allowed, at most i64::MAX.
 */
const parseSeconds = (s: string): I64 | null => {
  if (
    s.length === 0 ||
    !Iter.all(Str.bytes(s), (b: U8): boolean => b >= /* '0' */ 48 && b <= /* '9' */ 57)
  )
    return null;
  const result = Int.i64.parse(s);
  return result.kind === "Ok" ? result.value : null;
};

/**
 * Parses `prompt` (OIDC Core §3.1.2.1). `none` with any other value is an
 * error, as the section requires; a value outside the four defined ones
 * is ignored, which the section allows ("MAY return an error or it MAY
 * ignore it"), except that it still counts as another value beside `none`.
 */
const parsePrompt = (s: string): Prompt | null => {
  const prompt: Prompt = {
    no_interaction: hasToken(s, "none"),
    login: hasToken(s, "login"),
    consent: hasToken(s, "consent"),
    select_account: hasToken(s, "select_account"),
  };
  if (
    prompt.no_interaction &&
    !Iter.all(s.split(" "), (t: string): boolean => t === "" || t === "none")
  )
    return null;
  return prompt;
};

const redirectUriRegistered = (client: Client, uri: string): boolean => {
  // OIDC Core §3.1.2.1: exact match using simple string comparison.
  return Iter.any(client.redirect_uris, (registered: string): boolean => registered === uri);
};

/**
 * Validates an authorization request against the client registration.
 *
 * Errors about the client or its redirect_uri are shown to the End-User;
 * everything after that is redirected with `error` and the echoed `state`.
 */
export const validateRequest = (
  params: AuthorizationParams,
  client: Client | null,
): Result<AuthorizationRequest, AuthorizationError> => {
  Str.wellFormed(params);
  Str.wellFormed(client);
  if (client === null || params.client_id === null || params.client_id !== client.client_id)
    return Result.err({ kind: "Display", value: { kind: "UnknownClient" } });
  const client2 = client;

  // redirect_uri is REQUIRED in OIDC (§3.1.2.1), unlike RFC 6749 §4.1.1.
  if (params.redirect_uri === null)
    return Result.err({ kind: "Display", value: { kind: "MissingRedirectUri" } });
  const redirectUri = params.redirect_uri;
  if (!redirectUriRegistered(client2, redirectUri))
    return Result.err({ kind: "Display", value: { kind: "UnregisteredRedirectUri" } });

  // From here on the redirect target is trusted. Every error echoes the
  // state exactly as received whenever the request carried one, well
  // formed or not (RFC 6749 §4.1.2.1, OIDC Core §3.1.2.6: "REQUIRED if
  // the Authorization Request included the state parameter").
  const echoed: string | null = params.state;
  const fail = (error: ErrorCode): AuthorizationError => redirectError(redirectUri, error, echoed);
  if (params.response_type === null) return Result.err(fail({ kind: "InvalidRequest" }));
  if (params.response_type !== "code") return Result.err(fail({ kind: "UnsupportedResponseType" }));

  // §3.1.2.1: scope MUST contain openid; without it this is not an OIDC
  // request, and this OP serves only OIDC.
  if (params.scope === null || !hasToken(params.scope, "openid"))
    return Result.err(fail({ kind: "InvalidScope" }));
  const scope = params.scope;

  // RFC 6749 §10.12: this OP requires state from every client, and
  // accepts only 1 to 512 VSCHAR (RFC 6749 Appendix A.5).
  if (params.state === null || !stateIsValid(params.state))
    return Result.err(fail({ kind: "InvalidRequest" }));
  const state = params.state;
  if (params.nonce !== null && !stateIsValid(params.nonce))
    return Result.err(fail({ kind: "InvalidRequest" }));
  const nonce: string | null = params.nonce;

  let pkce: Pkce | null;
  if (params.code_challenge !== null) {
    const challenge = params.code_challenge;
    if (!pkceStringIsValid(challenge)) return Result.err(fail({ kind: "InvalidRequest" }));
    const method: string | null = params.code_challenge_method;

    // RFC 7636 §4.3: absent method means plain.
    let method2: PkceMethod;
    if (method !== null) {
      if (method === "S256") {
        method2 = { kind: "S256" };
      } else if (method === "plain") {
        method2 = { kind: "Plain" };
      } else {
        return Result.err(fail({ kind: "InvalidRequest" }));
      }
    } else {
      method2 = { kind: "Plain" };
    }

    if (method2.kind === "Plain" && !client2.allow_plain_pkce)
      return Result.err(fail({ kind: "InvalidRequest" }));
    if (method2.kind === "S256" && !s256ChallengeIsValid(challenge))
      return Result.err(fail({ kind: "InvalidRequest" }));
    pkce = { challenge, method: method2 };
  } else {
    if (params.code_challenge_method !== null) {
      // RFC 7636 §4.4.1: a required challenge that is missing, or a method
      // without a challenge.
      return Result.err(fail({ kind: "InvalidRequest" }));
    }

    if (client2.require_pkce) return Result.err(fail({ kind: "InvalidRequest" }));
    pkce = null;
  }

  let prompt: Prompt;
  if (params.prompt !== null) {
    const p = params.prompt;
    const opt = parsePrompt(p);
    const optOr = fail({ kind: "InvalidRequest" });
    if (opt === null) return Result.err(optOr);
    prompt = opt;
  } else {
    prompt = { no_interaction: false, login: false, consent: false, select_account: false };
  }

  let maxAge: I64 | null;
  if (params.max_age !== null) {
    const m = params.max_age;
    const opt = parseSeconds(m);
    const optOr = fail({ kind: "InvalidRequest" });
    if (opt === null) return Result.err(optOr);
    maxAge = opt;
  } else {
    maxAge = null;
  }

  const wantsMfa = params.acr_values !== null && hasToken(params.acr_values, ACR_MFA);
  return Result.ok(
    unsafeMakeAuthorizationRequest({
      client_id: client2.client_id,
      redirect_uri: redirectUri,
      scope,
      state,
      nonce,
      pkce,
      prompt,
      max_age: maxAge,
      wants_mfa: wantsMfa,
    }),
  );
};
