/* generated by purecrate-ts. do not edit. */

import { Int, Result, Slice, Str, type U8, type Usize } from "./purecrate-runtime.ts";
import type { EmailError } from "./email-error.ts";

export type Email = string & { readonly "signup.Email": true };

/**
 * Makes `Email` values without a check.
 *
 * Its fields are not `pub` in Rust, so outside the crate a value comes only
 * from the crate's functions; the generated files build them here, and
 * `index.ts` does not export it.
 * @internal
 */
export const unsafeMakeEmail = (value: string): Email => value as Email;

export const Email = {
  parse: (raw: string): Result<Email, EmailError> => {
    const b = Str.bytes(raw);
    let at = b.length as Usize;

    for (let i = 0 as Usize, end = b.length as Usize; i < end; i = (i + 1) as Usize) {
      if (Slice.at(b, i) === /* '@' */ 64 && at === b.length) {
        at = i;
      }
    }

    if (at === b.length) return Result.err({ kind: "MissingAt" });
    if (at === 0) return Result.err({ kind: "BadLocal" });

    for (let i = 0 as Usize, end = at; i < end; i = (i + 1) as Usize) {
      if (!isLocal(Slice.at(b, i))) return Result.err({ kind: "BadLocal" });
    }

    // Labels of 1 to 63 letters, digits and hyphens, with a letter or
    // digit at both ends, separated by `.`. `i == b.len()` ends the last.
    let start: Usize = Int.usize.add(at, 1 as Usize);

    for (
      let i = Int.usize.add(at, 1 as Usize), end = Int.usize.add(b.length as Usize, 1 as Usize);
      i < end;
      i = (i + 1) as Usize
    ) {
      if (i === b.length || Slice.at(b, i) === /* '.' */ 46) {
        const n = Int.usize.sub(i, start);
        if (
          n === 0 ||
          n > 63 ||
          Slice.at(b, start) === /* '-' */ 45 ||
          Slice.at(b, Int.usize.sub(i, 1 as Usize)) === /* '-' */ 45
        )
          return Result.err({ kind: "BadDomain" });
        start = Int.usize.add(i, 1 as Usize);
      } else if (!isAlnum(Slice.at(b, i)) && Slice.at(b, i) !== /* '-' */ 45) {
        return Result.err({ kind: "BadDomain" });
      }
    }

    return Result.ok(unsafeMakeEmail(raw));
  },
} as const;

const isAlnum = (b: U8): boolean =>
  (b >= /* '0' */ 48 && b <= /* '9' */ 57) ||
  (b >= /* 'A' */ 65 && b <= /* 'Z' */ 90) ||
  (b >= /* 'a' */ 97 && b <= /* 'z' */ 122);

/** The local part's bytes besides letters and digits: .!#$%&'*+/=?^_`{|}~- */
const isLocal = (b: U8): boolean =>
  isAlnum(b) ||
  b === /* '.' */ 46 ||
  b === /* '!' */ 33 ||
  (b >= /* '#' */ 35 && b <= /* '\'' */ 39) ||
  b === /* '*' */ 42 ||
  b === /* '+' */ 43 ||
  b === /* '-' */ 45 ||
  b === /* '/' */ 47 ||
  b === /* '=' */ 61 ||
  b === /* '?' */ 63 ||
  (b >= /* '^' */ 94 && b <= /* '`' */ 96) ||
  (b >= /* '{' */ 123 && b <= /* '~' */ 126);
