/* generated by purecrate-ts. do not edit. */

import { type U8 } from "./int.ts";

export const is_alnum = (b: U8): boolean => {
  return ((b >= (48 as U8) && b <= (57 as U8)) || (b >= (65 as U8) && b <= (90 as U8)) || (b >= (97 as U8) && b <= (122 as U8)));
};
