/* generated by purecrate-ts. do not edit. */

import { Iter, Result, Str, type Char } from "./purecrate-runtime.ts";
import type { PasswordError } from "./password-error.ts";

declare const Password$brand: unique symbol;
export type Password = string & { readonly [Password$brand]: true };

/**
 * Makes `Password` values without a check.
 *
 * Its fields are not `pub` in Rust, so outside the crate a value comes only
 * from the crate's functions; the generated files build them here, and
 * `index.ts` does not export it.
 * @internal
 */
export const unsafeMakePassword = (value: string): Password => value as Password;

export const Password = {
  parse: (raw: string): Result<Password, PasswordError> => {
    Str.wellFormed(raw);
    const n = Iter.count(raw as Iterable<Char>);
    if (n < 15) return Result.err({ kind: "TooShort" });
    if (n > 64) return Result.err({ kind: "TooLong" });
    if (blocked(raw)) return Result.err({ kind: "Blocked" });
    return Result.ok(unsafeMakePassword(raw));
  },
} as const;

const blocked = (raw: string): boolean =>
  raw === "passwordpassword" || raw === "123456789012345" || raw === "qwertyuiopasdfgh";
