/* generated by purecrate-ts. do not edit. */

import { Int, Result, Slice, Str, type Usize } from "./purecrate-runtime.ts";
import type { PasswordError } from "./password-error.ts";

export type Password = string & { readonly "signup.Password": true };

/**
 * Makes `Password` values without a check.
 *
 * Its fields are not `pub` in Rust, so outside the crate a value comes only
 * from the crate's functions; the generated files build them here, and
 * `index.ts` does not export it.
 * @internal
 */
export const unsafeMakePassword = (value: string): Password => value as Password;

export const Password = {
  parse: (raw: string): Result<Password, PasswordError> => {
    // Code points: every byte but a UTF-8 continuation byte (0x80..=0xBF).
    const b = Str.bytes(raw);
    let n = 0 as Usize;

    for (let i = 0 as Usize, end = b.length as Usize; i < end; i = (i + 1) as Usize) {
      const value = Slice.at(b, i);
      if (!(value >= 128 && value <= 191)) {
        n = Int.usize.add(n, 1 as Usize);
      }
    }

    if (n < 15) return Result.err({ kind: "TooShort" });
    if (n > 64) return Result.err({ kind: "TooLong" });
    if (blocked(raw)) return Result.err({ kind: "Blocked" });
    return Result.ok(unsafeMakePassword(raw));
  },
} as const;

const blocked = (raw: string): boolean =>
  raw === "passwordpassword" || raw === "123456789012345" || raw === "qwertyuiopasdfgh";
