/* generated by purecrate-ts. do not edit. */

import { Result } from "./purecrate-runtime.ts";
import { Email } from "./email.ts";
import { Password } from "./password.ts";
import type { SignupError } from "./signup-error.ts";

export type Signup = Readonly<{
  email: Email;
  password: Password;
}> & { readonly "signup.Signup": true };

/**
 * A `Signup` built without a check. Its fields are not `pub` in Rust, so
 * outside the crate a value comes only from the crate's functions; the
 * generated files build them here, and `index.ts` does not export it.
 * @internal
 */
export const unsafeMakeSignup = (fields: Readonly<{
  email: Email;
  password: Password;
}>): Signup => fields as Signup;

export const Signup = {
  parse: (email: string, password: string): Result<Signup, SignupError> => {
    let email2: Email;
    {
      const result = Email.parse(email);
      if (result.kind === "Ok") {
        const e = result.value;
        email2 = e;
      } else {
        const e = result.error;
        return Result.err({ kind: "Email", value: e });
      }
    }
    let password2: Password;
    {
      const result = Password.parse(password);
      if (result.kind === "Ok") {
        const p = result.value;
        password2 = p;
      } else {
        const e = result.error;
        return Result.err({ kind: "Password", value: e });
      }
    }
    return Result.ok(unsafeMakeSignup({ email: email2, password: password2 }));
  },
} as const;
