/* generated by purecrate-ts. do not edit. */

import type { EmailError } from "./email-error.ts";
import type { PasswordError } from "./password-error.ts";

export type SignupError =
  | Readonly<{ kind: "Email"; value: EmailError }>
  | Readonly<{ kind: "Password"; value: PasswordError }>;

export const SignupError = {
  Email: (value: EmailError): SignupError => ({ kind: "Email", value }),
  Password: (value: PasswordError): SignupError => ({ kind: "Password", value }),
} as const;
