/* generated by purecrate-ts. do not edit. */

import type { Amount } from "./amount.ts";
import type { CaptureMethod } from "./capture-method.ts";
import type { ConfirmationMethod } from "./confirmation-method.ts";

export type Terms = Readonly<{
  amount: Amount;
  capture: CaptureMethod;
  confirmation: ConfirmationMethod;
}>;

export const Terms = {
  of: (amount: Amount, capture: CaptureMethod, confirmation: ConfirmationMethod): Terms => ({ amount, capture, confirmation }),
} as const;
