/* generated by purecrate-ts. do not edit. */

import { assertNever, Eq, Int, Result, Slice, Str, type Usize } from "./purecrate-runtime.ts";
import { childOf } from "./child-of.ts";
import type { Edit } from "./edit.ts";
import { existingIndex } from "./existing-index.ts";
import { findKey } from "./find-key.ts";
import { getValue } from "./get-value.ts";
import { indexOf } from "./index-of.ts";
import { jsonEq } from "./json-eq.ts";
import type { Json } from "./json.ts";
import type { Member } from "./member.ts";
import type { OpFailure } from "./op-failure.ts";
import type { Op } from "./op.ts";
import type { Pointer } from "./pointer.ts";

/**
 * No `&mut`: an edit rebuilds each container on the path, from the last
 * token back up to the root.
 */
const editAt = (
  doc: Json,
  tokens: ReadonlyArray<string>,
  k: Usize,
  edit: Edit,
): Result<Json, OpFailure> => {
  if (Int.usize.add(k, 1 as Usize) === tokens.length)
    return editLast(doc, Slice.at(tokens, k), edit);
  const childResult = childOf(doc, Slice.at(tokens, k));
  if (childResult.kind === "Err") return childResult;
  const child = childResult.value;
  const newChildResult = editAt(child, tokens, Int.usize.add(k, 1 as Usize), edit);
  if (newChildResult.kind === "Err") return newChildResult;
  const newChild = newChildResult.value;
  return editLast(doc, Slice.at(tokens, k), { kind: "Replace", value: newChild });
};

const editLast = (doc: Json, token: string, edit: Edit): Result<Json, OpFailure> => {
  switch (doc.kind) {
    case "Object": {
      const members = doc.value;
      return editMember(members, token, edit);
    }
    case "Array": {
      const items = doc.value;
      return editItem(items, token, edit);
    }
    default:
      return Result.err({ kind: "NotAContainer" });
  }
};

/**
 * `add` of an existing key replaces its value in place; of a new key,
 * appends it.
 */
const editMember = (
  members: ReadonlyArray<Member>,
  token: string,
  edit: Edit,
): Result<Json, OpFailure> => {
  const out = [...members];
  const elem = findKey(members, token);

  switch (edit.kind) {
    case "Add": {
      const v = edit.value;

      if (elem !== null) {
        Slice.set(out, elem, { key: token, value: v });
      } else {
        out.push({ key: token, value: v });
      }
      break;
    }
    case "Remove":
      if (elem === null) return Result.err({ kind: "NotFound" });
      Slice.remove(out, elem);
      break;
    case "Replace": {
      const v = edit.value;
      if (elem === null) return Result.err({ kind: "NotFound" });
      Slice.set(out, elem, { key: token, value: v });
      break;
    }
    default:
      return assertNever(edit);
  }

  return Result.ok({ kind: "Object", value: out });
};

const editItem = (
  items: ReadonlyArray<Json>,
  token: string,
  edit: Edit,
): Result<Json, OpFailure> => {
  const out = [...items];

  switch (edit.kind) {
    case "Add": {
      const v = edit.value;
      let at = items.length as Usize;

      if (token !== "-") {
        const indexOfResult = indexOf(token);
        if (indexOfResult.kind === "Err") return indexOfResult;
        at = indexOfResult.value;
        if (at > items.length) return Result.err({ kind: "IndexOutOfRange" });
      }

      Slice.insert(out, at, v);
      break;
    }
    case "Replace": {
      const v = edit.value;
      const atResult = existingIndex(items.length as Usize, token);
      if (atResult.kind === "Err") return atResult;
      const at = atResult.value;
      Slice.set(out, at, v);
      break;
    }
    case "Remove": {
      const atResult = existingIndex(items.length as Usize, token);
      if (atResult.kind === "Err") return atResult;
      const at = atResult.value;
      Slice.remove(out, at);
      break;
    }
    default:
      return assertNever(edit);
  }

  return Result.ok({ kind: "Array", value: out });
};

const addValue = (doc: Json, path: Pointer, value: Json): Result<Json, OpFailure> => {
  if (path.tokens.length === 0) return Result.ok(value);
  return editAt(doc, path.tokens, 0 as Usize, { kind: "Add", value });
};

const removeValue = (doc: Json, path: Pointer): Result<Json, OpFailure> => {
  if (path.tokens.length === 0) return Result.err({ kind: "RemoveRoot" });
  return editAt(doc, path.tokens, 0 as Usize, { kind: "Remove" });
};

const replaceValue = (doc: Json, path: Pointer, value: Json): Result<Json, OpFailure> => {
  if (path.tokens.length === 0) return Result.ok(value);
  return editAt(doc, path.tokens, 0 as Usize, { kind: "Replace", value });
};

/** `a` is a proper prefix of `b`: shorter, and equal on every token it has. */
const properPrefix = (a: ReadonlyArray<string>, b: ReadonlyArray<string>): boolean =>
  a.length < b.length && Eq.deep(Slice.range(a, null, null), Slice.range(b, null, a.length));

const moveValue = (doc: Json, from: Pointer, path: Pointer): Result<Json, OpFailure> => {
  if (properPrefix(from.tokens, path.tokens)) return Result.err({ kind: "MoveIntoOwnChild" });
  const valueResult = getValue(doc, from);
  if (valueResult.kind === "Err") return valueResult;
  const value = valueResult.value;
  if (Eq.deep(from.tokens, path.tokens)) return Result.ok(doc);
  const removedResult = removeValue(doc, from);
  if (removedResult.kind === "Err") return removedResult;
  const removed = removedResult.value;
  return addValue(removed, path, value);
};

const copyValue = (doc: Json, from: Pointer, path: Pointer): Result<Json, OpFailure> => {
  const valueResult = getValue(doc, from);
  if (valueResult.kind === "Err") return valueResult;
  const value = valueResult.value;
  return addValue(doc, path, value);
};

const testValue = (doc: Json, path: Pointer, value: Json): Result<Json, OpFailure> => {
  const actualResult = getValue(doc, path);
  if (actualResult.kind === "Err") return actualResult;
  const actual = actualResult.value;
  return jsonEq(actual, value) ? Result.ok(doc) : Result.err({ kind: "TestFailed" });
};

/** Applies one operation and returns the new document. */
export const applyOp = (doc: Json, op: Op): Result<Json, OpFailure> => {
  Str.wellFormed(doc);
  Str.wellFormed(op);

  switch (op.kind) {
    case "Add": {
      const { path, value } = op;
      return addValue(doc, path, value);
    }
    case "Remove": {
      const path = op.path;
      return removeValue(doc, path);
    }
    case "Replace": {
      const { path, value } = op;
      return replaceValue(doc, path, value);
    }
    case "Move": {
      const { from, path } = op;
      return moveValue(doc, from, path);
    }
    case "Copy": {
      const { from, path } = op;
      return copyValue(doc, from, path);
    }
    case "Test": {
      const { path, value } = op;
      return testValue(doc, path, value);
    }
    default:
      return assertNever(op);
  }
};
