/* generated by purecrate-ts. do not edit. */

import { Int, type Usize } from "./purecrate-runtime.ts";
import type { Member } from "./member.ts";

export const findKey = (members: ReadonlyArray<Member>, key: string): Usize | null => {
  let i2 = 0 as Usize;

  for (const m of members) {
    const i = i2;
    i2 = Int.usize.add(i2, 1 as Usize);
    if (m.key === key) return i;
  }

  return null;
};
