/* generated by purecrate-ts. do not edit. */

import { Int, Result, Slice, Str, type Usize } from "./purecrate-runtime.ts";
import { childOf } from "./child-of.ts";
import type { Json } from "./json.ts";
import type { OpFailure } from "./op-failure.ts";
import type { Pointer } from "./pointer.ts";

const lookup = (doc: Json, tokens: ReadonlyArray<string>, k: Usize): Result<Json, OpFailure> => {
  if (k === tokens.length) return Result.ok(doc);
  const childResult = childOf(doc, Slice.at(tokens, k));
  if (childResult.kind === "Err") return childResult;
  const child = childResult.value;
  return lookup(child, tokens, Int.usize.add(k, 1 as Usize));
};

/**
 * Evaluates a pointer against a document (RFC 6901 §4) and returns a copy
 * of the value it names.
 */
export const getValue = (doc: Json, pointer: Pointer): Result<Json, OpFailure> => {
  Str.wellFormed(doc);
  return lookup(doc, pointer.tokens, 0 as Usize);
};
