/* generated by purecrate-ts. do not edit. */

import { Int, Result, Slice, Str, type Usize } from "./purecrate-runtime.ts";
import type { OpFailure } from "./op-failure.ts";

/**
 * An array index token: `0`, or digits without a leading zero. `-` is
 * refused here; `add` handles it before asking.
 */
export const indexOf = (token: string): Result<Usize, OpFailure> => {
  if (token === "-") return Result.err({ kind: "DashNotAllowed" });
  const b = Str.bytes(token);
  if (b.length === 0) return Result.err({ kind: "InvalidIndex" });
  if (b.length > 1 && Slice.at(b, 0) === /* '0' */ 48) return Result.err({ kind: "InvalidIndex" });

  for (const c of Str.bytes(token)) {
    if (!(c >= /* '0' */ 48 && c <= /* '9' */ 57)) return Result.err({ kind: "InvalidIndex" });
  }

  const result = Int.usize.parse(token);
  return result.kind === "Ok" ? Result.ok(result.value) : Result.err({ kind: "IndexOutOfRange" });
};
