/* generated by purecrate-ts. do not edit. */

import type { Usize } from "./purecrate-runtime.ts";

/** Why a JSON text was refused. Positions are byte offsets into the text. */
export type JsonError =
  | Readonly<{ kind: "UnexpectedEnd" }>
  | Readonly<{ kind: "UnexpectedByte"; value: Usize }>
  | Readonly<{ kind: "NotAnInteger"; value: Usize }>
  | Readonly<{ kind: "OutOfRange"; value: Usize }>
  | Readonly<{ kind: "DuplicateKey"; value: Usize }>
  | Readonly<{ kind: "InvalidEscape"; value: Usize }>
  | Readonly<{ kind: "LoneSurrogate"; value: Usize }>
  | Readonly<{ kind: "ControlCharacter"; value: Usize }>
  | Readonly<{ kind: "TrailingInput"; value: Usize }>;

export const JsonError = {
  UnexpectedEnd: (): JsonError => ({ kind: "UnexpectedEnd" }),
  UnexpectedByte: (value: Usize): JsonError => ({ kind: "UnexpectedByte", value }),
  NotAnInteger: (value: Usize): JsonError => ({ kind: "NotAnInteger", value }),
  OutOfRange: (value: Usize): JsonError => ({ kind: "OutOfRange", value }),
  DuplicateKey: (value: Usize): JsonError => ({ kind: "DuplicateKey", value }),
  InvalidEscape: (value: Usize): JsonError => ({ kind: "InvalidEscape", value }),
  LoneSurrogate: (value: Usize): JsonError => ({ kind: "LoneSurrogate", value }),
  ControlCharacter: (value: Usize): JsonError => ({ kind: "ControlCharacter", value }),
  TrailingInput: (value: Usize): JsonError => ({ kind: "TrailingInput", value }),
} as const;
