/* generated by purecrate-ts. do not edit. */

/** Why one operation could not be applied. */
export type OpFailure =
  | Readonly<{ kind: "NotFound" }>
  | Readonly<{ kind: "NotAContainer" }>
  | Readonly<{ kind: "InvalidIndex" }>
  | Readonly<{ kind: "IndexOutOfRange" }>
  | Readonly<{ kind: "DashNotAllowed" }>
  | Readonly<{ kind: "MoveIntoOwnChild" }>
  | Readonly<{ kind: "RemoveRoot" }>
  | Readonly<{ kind: "TestFailed" }>;

export const OpFailure = {
  NotFound: (): OpFailure => ({ kind: "NotFound" }),
  NotAContainer: (): OpFailure => ({ kind: "NotAContainer" }),
  InvalidIndex: (): OpFailure => ({ kind: "InvalidIndex" }),
  IndexOutOfRange: (): OpFailure => ({ kind: "IndexOutOfRange" }),
  DashNotAllowed: (): OpFailure => ({ kind: "DashNotAllowed" }),
  MoveIntoOwnChild: (): OpFailure => ({ kind: "MoveIntoOwnChild" }),
  RemoveRoot: (): OpFailure => ({ kind: "RemoveRoot" }),
  TestFailed: (): OpFailure => ({ kind: "TestFailed" }),
} as const;
