/* generated by purecrate-ts. do not edit. */

import type { Json } from "./json.ts";
import type { Pointer } from "./pointer.ts";

/** One RFC 6902 operation. */
export type Op =
  | Readonly<{ kind: "Add"; path: Pointer; value: Json }>
  | Readonly<{ kind: "Remove"; path: Pointer }>
  | Readonly<{ kind: "Replace"; path: Pointer; value: Json }>
  | Readonly<{ kind: "Move"; from: Pointer; path: Pointer }>
  | Readonly<{ kind: "Copy"; from: Pointer; path: Pointer }>
  | Readonly<{ kind: "Test"; path: Pointer; value: Json }>;

export const Op = {
  Add: (path: Pointer, value: Json): Op => ({ kind: "Add", path, value }),
  Remove: (path: Pointer): Op => ({ kind: "Remove", path }),
  Replace: (path: Pointer, value: Json): Op => ({ kind: "Replace", path, value }),
  Move: (from: Pointer, path: Pointer): Op => ({ kind: "Move", from, path }),
  Copy: (from: Pointer, path: Pointer): Op => ({ kind: "Copy", from, path }),
  Test: (path: Pointer, value: Json): Op => ({ kind: "Test", path, value }),
} as const;
