/* generated by purecrate-ts. do not edit. */

/** Why a JSON Pointer was refused. */
export type PointerError =
  | Readonly<{ kind: "MissingSlash" }>
  | Readonly<{ kind: "InvalidEscape" }>
  | Readonly<{ kind: "NotAJsonString" }>;

export const PointerError = {
  MissingSlash: (): PointerError => ({ kind: "MissingSlash" }),
  InvalidEscape: (): PointerError => ({ kind: "InvalidEscape" }),
  NotAJsonString: (): PointerError => ({ kind: "NotAJsonString" }),
} as const;
