/* generated by purecrate-ts. do not edit. */

import {
  assertNever,
  Char,
  Int,
  Slice,
  Str,
  type I64,
  type U32,
  type Usize,
} from "./purecrate-runtime.ts";
import type { Json } from "./json.ts";
import type { Member } from "./member.ts";

/** Serializes a value compactly. */
export const writeJson = (value: Json): string => {
  Str.wellFormed(value);

  switch (value.kind) {
    case "Null":
      return "null";
    case "Bool": {
      const field = value.value;
      if (field) return "true";
      return "false";
    }
    case "Num": {
      const n = value.value;
      return intText(n);
    }
    case "Text": {
      const s = value.value;
      return quote(s);
    }
    case "Array": {
      const items = value.value;
      return writeArray(items);
    }
    case "Object": {
      const members = value.value;
      return writeObject(members);
    }
    default:
      return assertNever(value);
  }
};

const writeArray = (items: ReadonlyArray<Json>): string => {
  let out: string = "";
  out += "[";
  let i = 0 as Usize;

  for (const item of items) {
    const k = i;
    i = Int.usize.add(i, 1 as Usize);

    if (k > 0) {
      out += ",";
    }

    out += writeJson(item);
  }

  out += "]";
  return out;
};

const writeObject = (members: ReadonlyArray<Member>): string => {
  let out: string = "";
  out += "{";
  let i = 0 as Usize;

  for (const m of members) {
    const k = i;
    i = Int.usize.add(i, 1 as Usize);

    if (k > 0) {
      out += ",";
    }

    out += quote(m.key);
    out += ":";
    out += writeJson(m.value);
  }

  out += "}";
  return out;
};

const digitChar = (d: I64): Char => {
  if (d === 0n) return "0" as Char;
  if (d === 1n) return "1" as Char;
  if (d === 2n) return "2" as Char;
  if (d === 3n) return "3" as Char;
  if (d === 4n) return "4" as Char;
  if (d === 5n) return "5" as Char;
  if (d === 6n) return "6" as Char;
  if (d === 7n) return "7" as Char;
  if (d === 8n) return "8" as Char;
  return "9" as Char;
};

const hexChar = (d: U32): Char => {
  if (d === 0) return "0" as Char;
  if (d === 1) return "1" as Char;
  if (d === 2) return "2" as Char;
  if (d === 3) return "3" as Char;
  if (d === 4) return "4" as Char;
  if (d === 5) return "5" as Char;
  if (d === 6) return "6" as Char;
  if (d === 7) return "7" as Char;
  if (d === 8) return "8" as Char;
  if (d === 9) return "9" as Char;
  if (d === 10) return "a" as Char;
  if (d === 11) return "b" as Char;
  if (d === 12) return "c" as Char;
  if (d === 13) return "d" as Char;
  if (d === 14) return "e" as Char;
  return "f" as Char;
};

const intText = (n: I64): string => {
  const digits: Array<Char> = [];
  let rest: I64 = n;
  if (rest === 0n) {
    digits.push("0" as Char);
  }

  while (rest !== 0n) {
    digits.push(digitChar(Int.i64.abs(Int.i64.rem(rest, 10n as I64))));
    rest = Int.i64.div(rest, 10n as I64);
  }

  let out: string = "";

  if (n < 0n) {
    out += "-";
  }

  let k = digits.length as Usize;
  while (k > 0) {
    k = Int.usize.sub(k, 1 as Usize);
    out += Slice.at(digits, k);
  }

  return out;
};

const quote = (s: string): string => {
  let out: string = "";
  out += '"';

  for (const c of s as Iterable<Char>) {
    const n = Char.code(c);

    if (c === '"') {
      out += '\\"';
    } else if (c === "\\") {
      out += "\\\\";
    } else if (n === 8) {
      out += "\\b";
    } else if (n === 12) {
      out += "\\f";
    } else if (n === 10) {
      out += "\\n";
    } else if (n === 13) {
      out += "\\r";
    } else if (n === 9) {
      out += "\\t";
    } else if (n < 0x20) {
      out += "\\u00";
      out += hexChar(Int.u32.shr(n, 4));
      out += hexChar(Int.u32.and(n, 15 as U32));
    } else {
      out += c;
    }
  }

  out += '"';
  return out;
};
