//! Print a `Crate` into kamae-ts files. No I/O.

mod doc;
mod expr;
mod imports;
mod items;
mod join;
mod js;
mod plain;
mod tidy;
mod schema;
mod stmt;

use expr::*;
use imports::*;
use items::*;
use stmt::*;

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};

pub use schema::{emit_wire, has_wire, WireSchema};

use purecrate_ir::{
    BinOp, Callee, ClosureParam, Crate, Enum, Expr, Fields, FloatTy, Fn, IntTy, Item, Lit, Name, Pattern, Prim, TryOn,
    Struct, Ty, VariantBind, VariantFields, Vis, NEWTYPE_FIELD,
};

/// First line of every generated `.ts` file. `build` also reads it to tell
/// its own output from a directory it must not replace.
pub const HEADER: &str = "/* generated by purecrate-ts. do not edit. */\n";

/// The printer's temporaries start with `$`, which no Rust identifier has,
/// and end in `_<n>`, a count of them, so no two are one name before
/// `plain::plain_names` gives each a plain name that no other in an
/// overlapping block has. The final text does not depend on the count.
fn temp(base: &str, _indent: usize) -> String {
    let n = TEMPS.with(|t| {
        let n = t.get() + 1;
        t.set(n);
        n
    });
    format!("${base}_{n}")
}

thread_local! {
    /// Temporaries made so far (`temp`).
    static TEMPS: std::cell::Cell<usize> = const { std::cell::Cell::new(0) };
    /// Closed structs of the crate `emit` is printing (design/01 §4). The
    /// expression printer has no `Crate`; `emit` sets this for its duration.
    static CLOSED: RefCell<BTreeSet<String>> = const { RefCell::new(BTreeSet::new()) };
    /// Structs of the crate, likewise: a place of one needs no `as` to
    /// undo a narrowing (`stmt::emit_let`), since a struct is no union.
    static STRUCTS: RefCell<BTreeSet<String>> = const { RefCell::new(BTreeSet::new()) };
    /// The crate's internal names (`internal_names`), likewise.
    static INTERNAL: RefCell<BTreeMap<Internal, String>> = const { RefCell::new(BTreeMap::new()) };
    /// Methods that are not `pub`, as (type, method), likewise.
    static PRIVATE: RefCell<BTreeSet<(String, String)>> = const { RefCell::new(BTreeSet::new()) };
    /// Whether the statement `stmt::emit_stmts` prints next is the last of
    /// its JS block, so nothing after it could meet a name it declares.
    static TAIL: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
    /// The discriminant tables the file being printed reads (`expr::table`),
    /// each keyed by its enum and whether it holds `bigint`s, with its name
    /// and declaration; printed after the file's imports.
    static TABLES: RefCell<Vec<((String, bool), String, String)>> = const { RefCell::new(Vec::new()) };
    /// The loops being printed, innermost last, each with its label when a
    /// `break` or `continue` in it leaves it.
    static LOOPS: RefCell<Vec<Option<String>>> = const { RefCell::new(Vec::new()) };
}

fn is_closed(name: &str) -> bool {
    CLOSED.with(|c| c.borrow().contains(name))
}

fn is_struct(name: &str) -> bool {
    STRUCTS.with(|c| c.borrow().contains(name))
}

fn is_private_method(ty: &str, name: &str) -> bool {
    PRIVATE.with(|p| p.borrow().contains(&(ty.to_string(), name.to_string())))
}

/// A method that is not `pub` in Rust stays off the exported companion: TS
/// callers outside the package must not reach what Rust callers cannot (a
/// private `fn raw(v) -> Yen` would build a closed type unchecked). Like a
/// closed struct's constructor, it is exported from the type's file but not
/// from `index.ts`, as `yenRaw` (`internal_names`).
pub(crate) fn private_method(ty: &str, name: &str) -> String {
    internal_name(&Internal::Method(ty.to_string(), name.to_string()))
}

/// A name the generated files share that callers do not see.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) enum Internal {
    /// A closed struct's constructor.
    Ctor(String),
    /// A method that is not `pub`: the type and the method.
    Method(String, String),
}

fn internal_name(key: &Internal) -> String {
    INTERNAL
        .with(|m| m.borrow().get(key).cloned())
        .unwrap_or_else(|| internal_base(key))
}

fn internal_base(key: &Internal) -> String {
    let upper = |s: &str| {
        let mut c = s.chars();
        c.next().map(|f| f.to_uppercase().chain(c).collect::<String>()).unwrap_or_default()
    };
    match key {
        Internal::Ctor(ty) => format!("unsafeMake{ty}"),
        Internal::Method(ty, m) => {
            let mut c = ty.chars();
            let lower: String = c.next().map(|f| f.to_lowercase().chain(c).collect()).unwrap_or_default();
            format!("{lower}{}", upper(m))
        }
    }
}

/// The internal names of a crate, each told apart from the crate's own
/// top-level names and from the others by a number where they meet
/// (`unsafeMakeYen2` beside a `fn unsafe_make_yen`).
pub(crate) fn internal_names(krate: &Crate) -> BTreeMap<Internal, String> {
    let mut taken: BTreeSet<String> = krate
        .items
        .iter()
        .filter(|item| !matches!(item, Item::Fn(f) if f.owner.is_some()))
        .map(|item| item.name().as_str().to_string())
        .collect();
    let keys = closed_names(krate)
        .into_iter()
        .map(Internal::Ctor)
        .chain(private_methods(krate).into_iter().map(|(t, m)| Internal::Method(t, m)));
    let mut out = BTreeMap::new();
    for key in keys {
        let base = internal_base(&key);
        let name = (1..)
            .map(|n| if n == 1 { base.clone() } else { format!("{base}{n}") })
            .find(|n| !taken.contains(n))
            .expect("a free name");
        taken.insert(name.clone());
        out.insert(key, name);
    }
    out
}

/// Runs `f` with the crate's internal names in place for `closed_ctor` and
/// `private_method`.
pub(crate) fn with_internal_names<T>(krate: &Crate, f: impl FnOnce() -> T) -> T {
    let previous = INTERNAL.with(|m| m.replace(internal_names(krate)));
    let out = f();
    INTERNAL.with(|m| m.replace(previous));
    out
}

fn private_methods(krate: &Crate) -> BTreeSet<(String, String)> {
    krate
        .items
        .iter()
        .filter_map(|item| match item {
            Item::Fn(f) if f.vis == Vis::Internal => f
                .owner
                .as_ref()
                .map(|o| (o.as_str().to_string(), f.name.as_str().to_string())),
            _ => None,
        })
        .collect()
}

/// The package-internal constructor of a closed struct (`unsafeMakeYen`).
/// It is exported from the type's file for the other generated files, but
/// not from `index.ts`, and the package's `exports` reach no other file.
pub(crate) fn closed_ctor(name: &str) -> String {
    internal_name(&Internal::Ctor(name.to_string()))
}

pub(crate) fn closed_names(krate: &Crate) -> BTreeSet<String> {
    krate
        .items
        .iter()
        .filter_map(|item| match item {
            Item::Struct(st) if st.closed => Some(st.name.as_str().to_string()),
            _ => None,
        })
        .collect()
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct File {
    pub stem: String,
    pub source: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Package {
    pub files: Vec<File>,
}

pub fn emit(krate: &Crate) -> Package {
    let previous = CLOSED.with(|c| c.replace(closed_names(krate)));
    let previous_private = PRIVATE.with(|p| p.replace(private_methods(krate)));
    let structs = krate.items.iter().filter_map(|item| match item {
        Item::Struct(st) => Some(st.name.as_str().to_string()),
        _ => None,
    });
    let previous_structs = STRUCTS.with(|c| c.replace(structs.collect()));
    let package = with_internal_names(krate, || emit_package(krate));
    STRUCTS.with(|c| c.replace(previous_structs));
    CLOSED.with(|c| c.replace(previous));
    PRIVATE.with(|p| p.replace(previous_private));
    package
}

fn emit_package(krate: &Crate) -> Package {
    let mut buckets: BTreeMap<String, Vec<&Item>> = BTreeMap::new();
    for item in &krate.items {
        buckets.entry(item.file_stem()).or_default().push(item);
    }

    let mut files = Vec::new();

    for (stem, items) in &buckets {
        files.push(File {
            stem: stem.clone(),
            source: emit_file(krate, stem, items),
        });
    }

    files.push(File {
        stem: "index".to_string(),
        source: emit_index(krate),
    });

    Package { files }
}

/// Some public type, field, or signature satisfies `pred`.
fn surface_ty(krate: &Crate, pred: impl std::ops::Fn(&Ty) -> bool) -> bool {
    fn walk(ty: &Ty, pred: &impl std::ops::Fn(&Ty) -> bool) -> bool {
        if pred(ty) {
            return true;
        }
        match ty {
            Ty::Option(t) | Ty::Vec(t) | Ty::Ignored { inner: t, .. } => walk(t, pred),
            Ty::Result { ok, err } => walk(ok, pred) || walk(err, pred),
            Ty::Tuple(ts) => ts.iter().any(|t| walk(t, pred)),
            Ty::Fn { params, ret } => params.iter().any(|t| walk(t, pred)) || walk(ret, pred),
            Ty::Prim(_) | Ty::Named(_) | Ty::Never => false,
        }
    }
    krate.items.iter().filter(|i| i.vis() == Vis::Pub).any(|item| match item {
        Item::Struct(s) => s.fields.iter().any(|f| walk(&f.ty, &pred)),
        Item::Enum(e) => e.variants.iter().any(|v| match &v.fields {
            VariantFields::Unit => false,
            VariantFields::Tuple(ts) => ts.iter().any(|t| walk(t, &pred)),
            VariantFields::Struct(fs) => fs.iter().any(|f| walk(&f.ty, &pred)),
        }),
        Item::Alias(a) => walk(&a.ty, &pred),
        Item::Const(c) => walk(&c.ty, &pred),
        Item::Fn(f) => f.params.iter().any(|p| walk(&p.ty, &pred)) || walk(&f.ret, &pred),
    })
}

/// Some public type, field, or signature holds `prim`.
fn surface_holds(krate: &Crate, prim: Prim) -> bool {
    surface_ty(krate, |ty| matches!(ty, Ty::Prim(p) if *p == prim))
}

fn emit_index(krate: &Crate) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');
    // A single value export carries both the companion and its same-named
    // type. `pack` points `"purecrate"` at the package's copy of the runtime.
    // Runtime names go out when the public surface holds them, so two packages
    // re-exported from one barrel do not collide on unused `I8` / `Result`.
    // `pack` adds `parseJson` with a schema.
    let mut runtime = Vec::new();
    if surface_ty(krate, |ty| matches!(ty, Ty::Result { .. })) {
        runtime.push("Result");
    }
    runtime.extend(["Panic", "assertNever"]);
    // `Int` makes the values of the brands the surface holds; without one,
    // the runtime's copy has no `Int` to export.
    let numeric = IntTy::ALL.into_iter().any(|t| surface_holds(krate, Prim::from(t)))
        || [FloatTy::F32, FloatTy::F64].into_iter().any(|t| surface_holds(krate, Prim::from(t)));
    if numeric {
        runtime.push("Int");
    }
    if surface_holds(krate, Prim::Char) {
        runtime.push("Char");
    }
    if surface_holds(krate, Prim::Uuid) || surface_holds(krate, Prim::UuidError) {
        runtime.extend(["Uuid", "type UuidError"]);
    }
    if surface_holds(krate, Prim::ParseIntError) {
        runtime.push("type ParseIntError");
    }
    out.push_str(&format!("export {{ {} }} from \"purecrate\";\n", runtime.join(", ")));
    let mut types: Vec<&str> = IntTy::ALL
        .into_iter()
        .filter(|t| surface_holds(krate, Prim::from(*t)))
        .map(IntTy::ts_name)
        .collect();
    for t in [FloatTy::F32, FloatTy::F64] {
        if surface_holds(krate, Prim::from(t)) {
            types.push(t.ts_name());
        }
    }
    if !types.is_empty() {
        out.push_str(&format!("export type {{ {} }} from \"purecrate\";\n", types.join(", ")));
    }
    for item in krate.exported() {
        match item {
            Item::Fn(f) if f.owner.is_some() => {}
            Item::Alias(al) => {
                out.push_str(&format!(
                    "export type {{ {name} }} from \"./{stem}.ts\";\n",
                    name = al.name.as_str(),
                    stem = item.file_stem(),
                ));
            }
            other => {
                out.push_str(&format!(
                    "export {{ {name} }} from \"./{stem}.ts\";\n",
                    name = other.name().as_str(),
                    stem = other.file_stem(),
                ));
            }
        }
    }
    out
}

fn emit_file(krate: &Crate, stem: &str, items: &[&Item]) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');
    let imports = imports_for(krate, stem, items);
    out.push_str(&imports);
    if !imports.is_empty() {
        out.push('\n');
    }
    TABLES.with(|t| t.borrow_mut().clear());
    let mut body = String::new();
    let out_ = &mut body;
    for item in items {
        match item {
            Item::Enum(en) => out_.push_str(&emit_enum(krate, en)),
            Item::Struct(st) => out_.push_str(&emit_struct(krate, st)),
            Item::Alias(al) => {
                out_.push_str(&jsdoc(&al.doc, ""));
                out_.push_str(&format!(
                    "export type {name} = {ty};\n",
                    name = al.name.as_str(),
                    ty = emit_ty(&al.ty)
                ));
            }
            Item::Fn(f) if f.owner.is_none() => out_.push_str(&emit_free_fn(f)),
            Item::Fn(_) => {}
            Item::Const(c) => {
                out_.push_str(&jsdoc(&c.doc, ""));
                let value = emit_expr(&c.value, 0);
                let value = crate::tidy::strip_outer(&value);
                let ty = emit_ty(&c.ty);
                // A value cast to the type already states it.
                let annotation = if crate::tidy::cast_type(value) == Some(ty.as_str()) { String::new() } else { format!(": {ty}") };
                out_.push_str(&format!("export const {name}{annotation} = {value};\n", name = c.name.as_str()));
            }
        }
    }
    for (_, _, decl) in TABLES.with(|t| std::mem::take(&mut *t.borrow_mut())) {
        out.push_str(&decl);
        out.push('\n');
    }
    out.push_str(&body);
    // A companion with nothing in it is `{}`, as oxfmt prints it.
    let out = out.replace(" = {\n} as const;", " = {} as const;");
    tidy::wrap(&plain::plain_names(&imports::prune_unused(&out)), WIDTH)
}

/// The width past which `tidy::wrap` breaks a line.
pub const WIDTH: usize = 100;

/// Break generated source so no code line exceeds [`WIDTH`].
pub fn wrap_source(src: &str) -> String {
    tidy::wrap(src, WIDTH)
}

#[cfg(test)]
mod tests {
    use super::*;
    use purecrate_ir::counter_example;

    fn file<'a>(pkg: &'a Package, stem: &str) -> &'a str {
        &pkg.files
            .iter()
            .find(|f| f.stem == stem)
            .unwrap_or_else(|| panic!("missing {stem}"))
            .source
    }

    #[test]
    fn erased_wrappers_are_named_in_types_only() {
        use purecrate_ir::{Fn, Item, Param, Vis, Wrapper};
        let share = Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("share"),
            owner: None,
            params: vec![Param {
                name: Name::new("n"),
                ty: Ty::ignored(Wrapper::Mutex, Ty::i32()),
            }],
            ret: Ty::ignored(Wrapper::Box, Ty::i32()),
            body: Expr::Ignored {
                wrapper: Wrapper::Arc,
                expr: Box::new(Expr::var("n")),
            },
            doc: None,
        });
        let pkg = emit(&Crate::new("wraps", vec![share]));
        let src = file(&pkg, "share");
        assert!(src.contains("(n: /* Mutex */ I32): /* Box */ I32 => n;"), "{src}");
    }

    #[test]
    fn doc_comments_become_jsdoc() {
        let mut krate = counter_example();
        for item in &mut krate.items {
            match item {
                Item::Enum(e) => {
                    e.doc = Some("What happens.\n\nOne at a time; ends in */ here.".into());
                    e.variants[0].doc = Some("Up by one.".into());
                }
                Item::Struct(s) => s.fields[0].doc = Some("The count.".into()),
                Item::Fn(f) => f.doc = Some("The transition.".into()),
                _ => {}
            }
        }
        let pkg = emit(&krate);
        assert!(file(&pkg, "event").contains(
            "/**\n * What happens.\n *\n * One at a time; ends in *\\/ here.\n */\nexport type Event =\n"
        ), "{}", file(&pkg, "event"));
        assert!(file(&pkg, "event").contains("  /** Up by one. */\n  Inc: "), "{}", file(&pkg, "event"));
        assert!(file(&pkg, "state").contains("Readonly<{\n  /** The count. */\n  n: I32;\n}>"), "{}", file(&pkg, "state"));
        assert!(file(&pkg, "step").contains("/** The transition. */\nexport const step = "), "{}", file(&pkg, "step"));
    }

    #[test]
    fn counter_kamae_shape() {
        let pkg = emit(&counter_example());
        let stems: Vec<&str> = pkg.files.iter().map(|f| f.stem.as_str()).collect();
        assert!(stems.contains(&"event"));
        assert!(stems.contains(&"state"));
        assert!(stems.contains(&"step"));

        let event = file(&pkg, "event");
        assert!(event.contains("kind: \"Inc\""));
        assert!(event.contains("export const Event = {"));
        assert!(!event.contains("tag:"));

        let state = file(&pkg, "state");
        assert!(state.contains("export type State = Readonly<{"));
        assert!(state.contains("of: (n: I32): State =>"));

        let step = file(&pkg, "step");
        assert!(step.contains("export const step ="));
        assert!(step.contains("switch (event.kind)"));
        assert!(step.contains("assertNever(event)"));
        assert!(step.contains("import type { Event }"));
        assert!(step.contains("import type { State }"));
    }

    #[test]
    fn counter_step_is_a_switch_statement() {
        let pkg = emit(&counter_example());
        let expected = "\
export const step = (state: State, event: Event): State => {
  switch (event.kind) {
    case \"Inc\":
      return { n: state.n + 1 };
    case \"Dec\":
      return { n: state.n - 1 };
    case \"Reset\":
      return { n: 0 };
    default:
      return assertNever(event);
  }
};
";
        assert!(file(&pkg, "step").ends_with(expected), "{}", file(&pkg, "step"));
    }

    fn cmd_crate(body: Expr) -> Crate {
        use purecrate_ir::{Name, Param, Variant, Vis};
        let cmd = Item::Enum(Enum {
            vis: Vis::Pub,
            name: Name::new("Cmd"),
            variants: vec![
                Variant {
                    name: Name::new("Move"),
                    fields: VariantFields::Tuple(vec![Ty::i32(), Ty::i32()]),
                    discriminant: None,
                    doc: None,
                },
                Variant {
                    name: Name::new("Paint"),
                    fields: VariantFields::Struct(vec![purecrate_ir::Field {
                        name: Name::new("color"),
                        ty: Ty::i32(),
                        doc: None,
                    }]),
                    discriminant: None,
                    doc: None,
                },
            ],
            repr: None,
            std: false,
            serde: purecrate_ir::Serde::default(),
            doc: None,
        });
        let run = Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("run"),
            owner: None,
            params: vec![Param {
                name: Name::new("cmd"),
                ty: Ty::named("Cmd"),
            }],
            ret: Ty::i32(),
            body,
            doc: None,
        });
        Crate::new("cmds", vec![cmd, run])
    }

    fn cmd_match(scrutinee: Expr) -> Expr {
        use purecrate_ir::{Arm, Name};
        let var = |n: &str| Pattern::Var(Name::new(n));
        Expr::Match {
            scrutinee: Box::new(scrutinee),
            arms: vec![
                Arm {
                    guard: None,
                    pattern: Pattern::Variant {
                        ty: Name::new("Cmd"),
                        variant: Name::new("Move"),
                        bind: VariantBind::Tuple(vec![var("a"), var("b")]),
                    },
                    body: Expr::Binary {
                        op: BinOp::Add,
                        left: Box::new(Expr::var("a")),
                        right: Box::new(Expr::var("b")),
                    },
                },
                Arm {
                    guard: None,
                    pattern: Pattern::Variant {
                        ty: Name::new("Cmd"),
                        variant: Name::new("Paint"),
                        bind: VariantBind::Struct(vec![(Name::new("color"), var("c"))]),
                    },
                    body: Expr::var("c"),
                },
            ],
        }
    }

    #[test]
    fn bindings_read_from_the_scrutinee() {
        let pkg = emit(&cmd_crate(cmd_match(Expr::var("cmd"))));
        let run = file(&pkg, "run");
        assert!(run.contains("case \"Move\": {\n      const a = cmd.content[0];"), "{run}");
        assert!(run.contains("const b = cmd.content[1];"), "{run}");
        assert!(run.contains("const c = cmd.color;"), "{run}");
        assert!(!run.contains("event"), "{run}");
    }

    #[test]
    fn non_place_scrutinee_is_bound_once() {
        use purecrate_ir::{Callee, Name};
        let call = Expr::Call {
            callee: Callee::Fn(Name::new("next")),
            args: vec![Expr::var("cmd")],
        };
        let pkg = emit(&cmd_crate(cmd_match(call)));
        let run = file(&pkg, "run");
        // Named for its enum, numbered past the parameter of that name.
        assert!(run.contains("const cmd2 = next(cmd);\n  switch (cmd2.kind)"), "{run}");
        assert!(run.contains("const a = cmd2.content[0];"), "{run}");
    }

    #[test]
    fn object_literal_arrow_body_is_parenthesized() {
        use purecrate_ir::{Name, Param, Vis};
        let mut krate = counter_example();
        krate.items.push(Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("zero"),
            owner: Some(Name::new("State")),
            params: vec![Param {
                name: Name::new("self"),
                ty: Ty::named("State"),
            }],
            ret: Ty::named("State"),
            body: Expr::Construct {
                ty: Name::new("State"),
                variant: None,
                fields: Fields::Named(vec![(Name::new("n"), Expr::int(0))]),
                base: None,
            },
            doc: None,
        }));
        let pkg = emit(&krate);
        assert!(
            file(&pkg, "state").contains("zero: (self: State): State => ({ n: 0 }),"),
            "{}",
            file(&pkg, "state")
        );
    }

    #[test]
    fn imports_follow_body_and_nested_types() {
        use purecrate_ir::{Param, Vis};
        let mut krate = cmd_crate(cmd_match(Expr::Call {
            callee: Callee::Fn(Name::new("next")),
            args: vec![Expr::var("cmd")],
        }));
        krate.items.push(Item::Fn(Fn {
            vis: Vis::Internal,
            name: Name::new("next"),
            owner: None,
            params: vec![Param {
                name: Name::new("cmd"),
                ty: Ty::named("Cmd"),
            }],
            ret: Ty::named("Cmd"),
            body: Expr::var("cmd"),
            doc: None,
        }));
        krate.items.push(Item::Struct(Struct {
            vis: Vis::Pub,
            name: Name::new("Log"),
            fields: vec![purecrate_ir::Field {
                name: Name::new("last"),
                ty: Ty::option(Ty::Vec(Box::new(Ty::named("Cmd")))),
                doc: None,
            }],
            closed: false,
            wire_from: None,
            serde: purecrate_ir::Serde::default(),
            doc: None,
        }));
        let pkg = emit(&krate);

        let run = file(&pkg, "run");
        assert!(run.contains("import { next } from \"./next.ts\";\n"), "{run}");
        assert!(run.contains("import type { Cmd } from \"./cmd.ts\";\n"), "{run}");

        let log = file(&pkg, "log");
        assert!(log.contains("import type { Cmd } from \"./cmd.ts\";\n"), "{log}");
        let cmd = file(&pkg, "cmd");
        assert!(cmd.contains("import type { I32 } from \"purecrate\";\n"), "{cmd}");
        assert!(!cmd.contains("from \"./cmd.ts\""), "{cmd}");
    }

    #[test]
    fn enum_methods_join_the_companion() {
        use purecrate_ir::{Param, Vis};
        let mut krate = cmd_crate(Expr::int(0));
        krate.items.push(Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("weight"),
            owner: Some(Name::new("Cmd")),
            params: vec![Param {
                name: Name::new("self"),
                ty: Ty::named("Cmd"),
            }],
            ret: Ty::i32(),
            body: cmd_match(Expr::var("self")),
            doc: None,
        }));
        let pkg = emit(&krate);
        let cmd = file(&pkg, "cmd");
        assert!(cmd.contains("  weight: (self: Cmd): I32 => {\n    switch (self.kind) {"), "{cmd}");
        assert!(cmd.ends_with("  },\n} as const;\n"), "{cmd}");
        assert!(cmd.starts_with(&format!("{HEADER}\nimport {{ assertNever, type I32 }}")), "{cmd}");
    }

    #[test]
    fn index_exports_each_name_once() {
        let pkg = emit(&counter_example());
        let index = file(&pkg, "index");
        for name in ["Panic", "assertNever", "Int", "I32", "Event", "State", "step"] {
            // The names, not the paths they come from.
            let hits = index
                .lines()
                .filter_map(|l| l.split(" from ").next())
                .flat_map(|l| l.split(|c: char| !(c.is_alphanumeric() || c == '_' || c == '$')))
                .filter(|w| *w == name)
                .count();
            assert_eq!(hits, 1, "{name} in:\n{index}");
        }
        assert_eq!(
            index.lines().filter(|l| l.contains("export type {")).count(),
            1,
            "{index}"
        );
    }

    #[test]
    fn result_is_imported_once() {
        use purecrate_ir::{Callee, Name, Param, Vis};
        let parse = Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("parse"),
            owner: None,
            params: vec![Param {
                name: Name::new("n"),
                ty: Ty::i32(),
            }],
            ret: Ty::result(Ty::i32(), Ty::Prim(purecrate_ir::Prim::String)),
            body: Expr::Call {
                callee: Callee::ResultOk,
                args: vec![Expr::var("n")],
            },
            doc: None,
        });
        let pkg = emit(&Crate::new("p", vec![parse]));
        let src = file(&pkg, "parse");
        assert_eq!(src.matches("import ").count(), 1, "{src}");
        assert!(src.contains("import { Result, type I32 } from \"purecrate\";"), "{src}");
    }

    fn f64_fn(body: Expr) -> String {
        use purecrate_ir::{Name, Param, Prim, Vis};
        let f = Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("f"),
            owner: None,
            params: vec![Param {
                name: Name::new("x"),
                ty: Ty::Prim(Prim::F64),
            }],
            ret: Ty::Prim(Prim::F64),
            body,
            doc: None,
        });
        file(&emit(&Crate::new("p", vec![f])), "f").to_string()
    }

    #[test]
    fn nested_operators_keep_their_grouping() {
        use purecrate_ir::UnOp;
        let bin = |op, l, r| Expr::Binary {
            op,
            left: Box::new(l),
            right: Box::new(r),
        };
        let sum = bin(BinOp::Add, Expr::var("x"), Expr::var("x"));
        let src = f64_fn(bin(BinOp::Mul, sum.clone(), Expr::var("x")));
        assert!(src.contains("=> (x + x) * x;"), "{src}");
        let neg = |e| Expr::Unary {
            op: UnOp::Neg,
            expr: Box::new(e),
        };
        let src = f64_fn(neg(neg(Expr::var("x"))));
        assert!(src.contains("=> -(-x);"), "{src}");
        let src = f64_fn(neg(sum.clone()));
        assert!(src.contains("=> -(x + x);"), "{src}");
        let src = f64_fn(bin(BinOp::Add, sum, Expr::var("x")));
        assert!(src.contains("=> x + x + x;"), "{src}");
        let src = f64_fn(bin(
            BinOp::Sub,
            Expr::var("x"),
            bin(BinOp::Sub, Expr::var("x"), Expr::var("x")),
        ));
        assert!(src.contains("=> x - (x - x);"), "{src}");
    }

    fn bool_fn(body: Expr) -> String {
        use purecrate_ir::{Name, Param, Prim, Vis};
        let f = Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("f"),
            owner: None,
            params: vec![
                Param { name: Name::new("a"), ty: Ty::Prim(Prim::Bool) },
                Param { name: Name::new("b"), ty: Ty::Prim(Prim::Bool) },
                Param { name: Name::new("c"), ty: Ty::Prim(Prim::Bool) },
            ],
            ret: Ty::Prim(Prim::Bool),
            body,
            doc: None,
        });
        file(&emit(&Crate::new("p", vec![f])), "f").to_string()
    }

    #[test]
    fn boolean_operators_follow_precedence() {
        let bin = |op, l, r| Expr::Binary { op, left: Box::new(l), right: Box::new(r) };
        let and = bin(BinOp::And, Expr::var("a"), Expr::var("b"));
        let src = bool_fn(bin(BinOp::Or, and, Expr::var("c")));
        // Not needed for precedence, but read as oxfmt writes it.
        assert!(src.contains("=> (a && b) || c;"), "{src}");
        let or = bin(BinOp::Or, Expr::var("a"), Expr::var("b"));
        let src = bool_fn(bin(BinOp::And, or, Expr::var("c")));
        assert!(src.contains("=> (a || b) && c;"), "{src}");
    }

    #[test]
    fn typed_literals_print_their_js_form() {
        let big = Lit::Int {
            value: -5,
            ty: Some(IntTy::I64),
        };
        assert_eq!(emit_lit(&big), "(-5n as I64)");
        let single = Lit::Float {
            digits: "0.1".into(),
            ty: Some(FloatTy::F32),
        };
        assert_eq!(emit_lit(&single), "(0.10000000149011612 as F32)");
    }

    #[test]
    fn strings_escape_as_json_does() {
        let s = emit_lit(&Lit::Str("q\\\n\r\t\u{8}\u{c}\u{0}\u{1b}\u{2028}\u{2029}é".into()));
        assert_eq!(s, "\"q\\\\\\n\\r\\t\\b\\f\\u0000\\u001b\\u2028\\u2029é\"");
        // The quote that needs fewer escapes, as oxfmt picks it.
        assert_eq!(emit_lit(&Lit::Str("a\"b".into())), "'a\"b'");
        assert_eq!(emit_lit(&Lit::Str("a'b\"c".into())), "\"a'b\\\"c\"");
    }

    #[test]
    fn object_literals_inside_an_erased_wrapper_are_parenthesized() {
        use purecrate_ir::Wrapper;
        let lit = Expr::Construct {
            ty: Name::new("P"),
            variant: None,
            fields: Fields::Named(vec![(Name::new("a"), Expr::var("a"))]),
            base: None,
        };
        let boxed = Expr::Ignored {
            wrapper: Wrapper::Box,
            expr: Box::new(lit.clone()),
        };
        let body = arrow_expr(&boxed, 0);
        assert_eq!(body, "({ a })");
        let mut out = String::new();
        Sink::Effect.finish_expr(&boxed, 0, &mut out);
        assert_eq!(out, "({ a });\n");
        let some = Expr::Call {
            callee: Callee::OptionSome,
            args: vec![lit],
        };
        assert_eq!(arrow_expr(&some, 0), "({ a })");
    }

    #[test]
    fn integer_from_converts_only_into_bigint() {
        let from = |from, to| {
            emit_expr(
                &Expr::Call {
                    callee: purecrate_ir::Callee::IntFrom { from: Some(from), to },
                    args: vec![Expr::var("x")],
                },
                0,
            )
        };
        assert_eq!(from(IntTy::U32, IntTy::I64), "(globalThis.BigInt(x) as I64)");
        assert_eq!(from(IntTy::U8, IntTy::I32), "(x as number as I32)");
        assert_eq!(from(IntTy::I64, IntTy::I64), "x");
    }
}
