//! Print a `Crate` into kamae-ts files. No I/O.

mod imports;
mod schema;

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};

pub use schema::{emit_wire, WireSchema};

use purecrate_ir::{
    BinOp, Callee, ClosureParam, Crate, Enum, Expr, Fields, FloatTy, Fn, IntTy, Item, Lit, Name, Pattern, TryOn,
    Struct, Ty, VariantBind, VariantFields, Vis, NEWTYPE_FIELD,
};

/// First line of every generated `.ts` file. `build` also reads it to tell
/// its own output from a directory it must not replace.
pub const HEADER: &str = "/* generated by purecrate-ts. do not edit. */\n";

/// Prefixes of the printer's temporaries. Rust identifiers have no `$`;
/// `rename` puts one inside a name (`x$1`) and `lift` names its bindings
/// `$q1`, so each prefix here ends in a character no other generator puts
/// after a leading `$`.
const MATCH_TEMP: &str = "$m_";
const TRY_TEMP: &str = "$t_";
const TRY_LET_TEMP: &str = "$v_";
const FOR_END: &str = "$e_";

thread_local! {
    /// Closed structs of the crate `emit` is printing (design/01 §4). The
    /// expression printer has no `Crate`; `emit` sets this for its duration.
    static CLOSED: RefCell<BTreeSet<String>> = const { RefCell::new(BTreeSet::new()) };
    /// Methods that are not `pub`, as (type, method), likewise.
    static PRIVATE: RefCell<BTreeSet<(String, String)>> = const { RefCell::new(BTreeSet::new()) };
}

fn is_closed(name: &str) -> bool {
    CLOSED.with(|c| c.borrow().contains(name))
}

fn is_private_method(ty: &str, name: &str) -> bool {
    PRIVATE.with(|p| p.borrow().contains(&(ty.to_string(), name.to_string())))
}

/// A method that is not `pub` in Rust stays off the exported companion: TS
/// callers outside the package must not reach what Rust callers cannot (a
/// private `fn raw(v) -> Yen` would build a closed type unchecked). Like
/// `$of`, it is exported from the type's file but not from `index.ts`.
pub(crate) fn private_method(ty: &str, name: &str) -> String {
    format!("{ty}${name}")
}

fn private_methods(krate: &Crate) -> BTreeSet<(String, String)> {
    krate
        .items
        .iter()
        .filter_map(|item| match item {
            Item::Fn(f) if f.vis == Vis::Internal => f
                .owner
                .as_ref()
                .map(|o| (o.as_str().to_string(), f.name.as_str().to_string())),
            _ => None,
        })
        .collect()
}

/// The package-internal constructor of a closed struct. It is exported from
/// the type's file for the other generated files, but not from `index.ts`.
/// `rename` only appends `$` and digits, so `$of` does not collide.
pub(crate) fn closed_ctor(name: &str) -> String {
    format!("{name}$of")
}

pub(crate) fn closed_names(krate: &Crate) -> BTreeSet<String> {
    krate
        .items
        .iter()
        .filter_map(|item| match item {
            Item::Struct(st) if st.closed => Some(st.name.as_str().to_string()),
            _ => None,
        })
        .collect()
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct File {
    pub stem: String,
    pub source: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Package {
    pub files: Vec<File>,
}

pub fn emit(krate: &Crate) -> Package {
    let previous = CLOSED.with(|c| c.replace(closed_names(krate)));
    let previous_private = PRIVATE.with(|p| p.replace(private_methods(krate)));
    let package = emit_package(krate);
    CLOSED.with(|c| c.replace(previous));
    PRIVATE.with(|p| p.replace(previous_private));
    package
}

fn emit_package(krate: &Crate) -> Package {
    let mut buckets: BTreeMap<String, Vec<&Item>> = BTreeMap::new();
    for item in &krate.items {
        buckets.entry(item.file_stem()).or_default().push(item);
    }

    let mut files = vec![
        File {
            stem: "assert-never".to_string(),
            source: assert_never_src(),
        },
        File {
            stem: "int".to_string(),
            source: int_src(),
        },
        File {
            stem: "result".to_string(),
            source: result_src(),
        },
        File {
            stem: "str".to_string(),
            source: format!("{HEADER}\nexport {{ Char, Str, Uuid, type UuidError, parseJson }} from \"purecrate\";\n"),
        },
    ];

    for (stem, items) in &buckets {
        files.push(File {
            stem: stem.clone(),
            source: emit_file(krate, stem, items),
        });
    }

    files.push(File {
        stem: "index".to_string(),
        source: emit_index(krate),
    });

    Package { files }
}

fn assert_never_src() -> String {
    format!(
        "{HEADER}\nexport const assertNever = (_x: never): never => {{\n  throw new Error(\"unexpected variant\");\n}};\n"
    )
}

/// Integer arithmetic as a Rust debug build does it. `number` widths stay
/// exact because every in-range result is below 2^53, and rounding cannot move
/// an out-of-range product back inside the bounds. `+ 0` turns `-0` into `0`.
fn int_src() -> String {
    format!(
        "{HEADER}\nexport {{ Int, type I8, type I16, type I32, type I64, type U8, type U16, type U32, type U64, type Usize, type F32, type F64 }} from \"purecrate\";\n"
    )
}

fn result_src() -> String {
    format!(
        "{HEADER}
export type Result<T, E> =
  | Readonly<{{ kind: \"Ok\"; value: T }}>
  | Readonly<{{ kind: \"Err\"; error: E }}>;

export const Result = {{
  ok: <T, E>(value: T): Result<T, E> => ({{ kind: \"Ok\", value }}),
  err: <T, E>(error: E): Result<T, E> => ({{ kind: \"Err\", error }}),
  isOk: <T, E>(r: Result<T, E>): r is Readonly<{{ kind: \"Ok\"; value: T }}> =>
    r.kind === \"Ok\",
  isErr: <T, E>(r: Result<T, E>): r is Readonly<{{ kind: \"Err\"; error: E }}> =>
    r.kind === \"Err\",
}} as const;
"
    )
}

fn emit_index(krate: &Crate) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');
    // A single value export carries both the companion and its same-named type.
    out.push_str("export { Result } from \"./result.ts\";\n");
    out.push_str("export { assertNever } from \"./assert-never.ts\";\n");
    out.push_str(
        "export { Int } from \"./int.ts\";\n\
         export type { I8, I16, I32, I64, U8, U16, U32, U64, Usize, F32, F64 } from \"./int.ts\";\n\
         export { Char, Uuid, type UuidError, parseJson } from \"./str.ts\";\n",
    );
    for item in krate.exported() {
        match item {
            Item::Fn(f) if f.owner.is_some() => {}
            Item::Alias(al) => {
                out.push_str(&format!(
                    "export type {{ {name} }} from \"./{stem}.ts\";\n",
                    name = al.name.as_str(),
                    stem = item.file_stem(),
                ));
            }
            other => {
                out.push_str(&format!(
                    "export {{ {name} }} from \"./{stem}.ts\";\n",
                    name = other.name().as_str(),
                    stem = other.file_stem(),
                ));
            }
        }
    }
    out
}

fn emit_file(krate: &Crate, stem: &str, items: &[&Item]) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');
    let imports = imports_for(krate, stem, items);
    out.push_str(&imports);
    if !imports.is_empty() {
        out.push('\n');
    }
    for item in items {
        match item {
            Item::Enum(en) => out.push_str(&emit_enum(krate, en)),
            Item::Struct(st) => out.push_str(&emit_struct(krate, st)),
            Item::Alias(al) => {
                out.push_str(&format!(
                    "export type {name} = {ty};\n",
                    name = al.name.as_str(),
                    ty = emit_ty(&al.ty)
                ));
            }
            Item::Fn(f) if f.owner.is_none() => out.push_str(&emit_free_fn(f)),
            Item::Fn(_) => {}
            Item::Const(c) => out.push_str(&format!(
                "export const {name}: {ty} = {value};\n",
                name = c.name.as_str(),
                ty = emit_ty(&c.ty),
                value = emit_expr(&c.value, 0)
            )),
        }
    }
    imports::prune_unused(&out)
}

/// The `pub` methods, closing the companion object, then the others as
/// `Ty$name` (see `private_method`).
fn companion_methods(krate: &Crate, ty: &str) -> String {
    let mut out = String::new();
    let (public, private): (Vec<&Fn>, Vec<&Fn>) =
        methods_on(krate, ty).into_iter().partition(|m| m.vis == Vis::Pub);
    for m in public {
        out.push_str(&format!(
            "  {n}: {impl},\n",
            n = m.name.as_str(),
            impl = fn_arrow(m, 1)
        ));
    }
    out.push_str("} as const;\n");
    for m in private {
        out.push_str(&format!(
            "\nexport const {n} = {impl};\n",
            n = private_method(ty, m.name.as_str()),
            impl = fn_arrow(m, 0)
        ));
    }
    out
}

fn methods_on<'a>(krate: &'a Crate, ty: &str) -> Vec<&'a Fn> {
    krate
        .items
        .iter()
        .filter_map(|item| match item {
            Item::Fn(f) if f.owner.as_ref().map(|n| n.as_str()) == Some(ty) => Some(f),
            _ => None,
        })
        .collect()
}

fn emit_enum(krate: &Crate, en: &Enum) -> String {
    let name = en.name.as_str();
    let mut out = format!("export type {name} =\n");
    for (i, v) in en.variants.iter().enumerate() {
        let sep = if i + 1 == en.variants.len() {
            ";\n"
        } else {
            "\n"
        };
        out.push_str("  | ");
        out.push_str(&variant_type(v));
        out.push_str(sep);
    }
    out.push('\n');
    out.push_str(&format!("export const {name} = {{\n"));
    for v in &en.variants {
        out.push_str(&format!("  {}: ", v.name.as_str()));
        out.push_str(&variant_ctor(name, v));
        out.push_str(",\n");
    }
    out.push_str(&companion_methods(krate, name));
    out
}

fn variant_type(v: &purecrate_ir::Variant) -> String {
    let kind = v.name.as_str();
    match &v.fields {
        VariantFields::Unit => format!("Readonly<{{ kind: \"{kind}\" }}>"),
        VariantFields::Tuple(elems) => {
            let inner = elems
                .iter()
                .map(emit_ty)
                .collect::<Vec<_>>()
                .join(", ");
            format!("Readonly<{{ kind: \"{kind}\"; content: readonly [{inner}] }}>")
        }
        VariantFields::Struct(fields) => {
            let mut parts = vec![format!("kind: \"{kind}\"")];
            for f in fields {
                parts.push(format!("{}: {}", f.name.as_str(), emit_ty(&f.ty)));
            }
            format!("Readonly<{{ {} }}>", parts.join("; "))
        }
    }
}

fn variant_ctor(ty: &str, v: &purecrate_ir::Variant) -> String {
    let kind = v.name.as_str();
    match &v.fields {
        VariantFields::Unit => format!("(): {ty} => ({{ kind: \"{kind}\" }})"),
        VariantFields::Tuple(elems) => {
            let params: Vec<String> = elems
                .iter()
                .enumerate()
                .map(|(i, t)| format!("_{i}: {}", emit_ty(t)))
                .collect();
            let args: Vec<String> = (0..elems.len()).map(|i| format!("_{i}")).collect();
            format!(
                "({params}): {ty} => ({{ kind: \"{kind}\", content: [{args}] }})",
                params = params.join(", "),
                args = args.join(", ")
            )
        }
        VariantFields::Struct(fields) => {
            let params: Vec<String> = fields
                .iter()
                .map(|f| format!("{}: {}", f.name.as_str(), emit_ty(&f.ty)))
                .collect();
            let assigns: Vec<String> = fields
                .iter()
                .map(|f| f.name.as_str().to_string())
                .collect();
            format!(
                "({params}): {ty} => ({{ kind: \"{kind}\", {assigns} }})",
                params = params.join(", "),
                assigns = assigns.join(", ")
            )
        }
    }
}

fn emit_struct(krate: &Crate, st: &Struct) -> String {
    let name = st.name.as_str();
    if let Some(inner) = st.newtype_inner() {
        return emit_newtype(krate, name, inner, st.closed);
    }
    let fields = st
        .fields
        .iter()
        .map(|f| format!("  {}: {};", f.name.as_str(), emit_ty(&f.ty)))
        .collect::<Vec<_>>()
        .join("\n");
    if st.closed {
        return emit_closed_struct(krate, st, &fields);
    }
    let mut out = format!("export type {name} = Readonly<{{\n{fields}\n}}>;\n\n");
    let params = st
        .fields
        .iter()
        .map(|f| format!("{}: {}", f.name.as_str(), emit_ty(&f.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let assigns = st
        .fields
        .iter()
        .map(|f| f.name.as_str().to_string())
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!("export const {name} = {{\n"));
    out.push_str(&format!(
        "  of: ({params}): {name} => ({{ {assigns} }}),\n"
    ));
    out.push_str(&companion_methods(krate, name));
    out
}

/// A newtype is its inner value at runtime (as in serde's JSON), branded so
/// that `Id` and the bare inner type do not mix. A `unique symbol` key keeps
/// nested brands from colliding.
fn emit_newtype(krate: &Crate, name: &str, inner: &Ty, closed: bool) -> String {
    let inner = emit_ty(inner);
    let mut out = format!(
        "declare const {name}Brand: unique symbol;\n\
         export type {name} = {inner} & {{ readonly [{name}Brand]: true }};\n\n"
    );
    if closed {
        out.push_str(&closed_ctor_src(name, &format!("value: {inner}"), "value"));
    }
    out.push_str(&format!("export const {name} = {{\n"));
    if !closed {
        out.push_str(&format!("  of: (value: {inner}): {name} => value as {name},\n"));
    }
    out.push_str(&companion_methods(krate, name));
    out
}

/// A struct with a field that is not `pub`: branded, so an object literal is
/// not one, and with no `of` on the companion (design/01 §4).
fn emit_closed_struct(krate: &Crate, st: &Struct, fields: &str) -> String {
    let name = st.name.as_str();
    let shape = st
        .fields
        .iter()
        .map(|f| format!("{}: {}", f.name.as_str(), emit_ty(&f.ty)))
        .collect::<Vec<_>>()
        .join("; ");
    let mut out = format!(
        "declare const {name}Brand: unique symbol;\n\
         export type {name} = Readonly<{{\n{fields}\n}}> & {{ readonly [{name}Brand]: true }};\n\n"
    );
    out.push_str(&closed_ctor_src(name, &format!("fields: Readonly<{{ {shape} }}>"), "fields"));
    out.push_str(&format!("export const {name} = {{\n"));
    out.push_str(&companion_methods(krate, name));
    out
}

fn closed_ctor_src(name: &str, param: &str, arg: &str) -> String {
    format!(
        "// A field is not `pub` in Rust: outside the crate, `{name}` values come only from\n\
         // the crate's functions. The generated files build them here; `index.ts` does not export it.\n\
         export const {ctor} = ({param}): {name} => {arg} as {name};\n\n",
        ctor = closed_ctor(name)
    )
}

fn emit_free_fn(f: &Fn) -> String {
    format!(
        "export const {name} = {impl};\n",
        name = f.name.as_str(),
        impl = fn_arrow(f, 0)
    )
}

/// `indent` is the nesting level of the line the arrow starts on.
fn fn_arrow(f: &Fn, indent: usize) -> String {
    let params = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name.as_str(), emit_ty(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    arrow(&params, &emit_ty(&f.ret), &f.body, indent)
}

fn closure_arrow(params: &[ClosureParam], ret: Option<&Ty>, body: &Expr, indent: usize) -> String {
    let typed = |name: &Name, ty: Option<&Ty>| match ty {
        Some(t) => format!("{}: {}", name.as_str(), emit_ty(t)),
        None => name.as_str().to_string(),
    };
    let params = params.iter().map(|p| typed(&p.name, p.ty.as_ref())).collect::<Vec<_>>().join(", ");
    match ret {
        Some(r) => arrow(&params, &emit_ty(r), body, indent),
        None => format!("({params}) => {}", arrow_expr(body, indent)),
    }
}

fn arrow(params: &str, ret: &str, body: &Expr, indent: usize) -> String {
    if body.needs_statements() {
        let mut out = String::new();
        emit_stmts(body, indent + 1, Sink::Return, &mut out);
        format!("({params}): {ret} => {{\n{out}{pad}}}", pad = "  ".repeat(indent))
    } else {
        format!("({params}): {ret} => {}", arrow_expr(body, indent))
    }
}

/// An arrow body starting with `{` would parse as a block.
fn arrow_expr(expr: &Expr, indent: usize) -> String {
    let s = emit_expr(expr, indent);
    if leads_with_brace(expr) {
        format!("({s})")
    } else {
        s
    }
}

/// Whether `emit_expr` prints an object literal first, possibly after an
/// erased wrapper's comment. At the start of an arrow body or a statement it
/// would parse as a block, so the caller parenthesizes the whole expression.
fn leads_with_brace(expr: &Expr) -> bool {
    match expr {
        Expr::Ignored { expr, .. } => leads_with_brace(expr),
        Expr::Construct { ty, variant, fields, base: None } => {
            variant.is_some() || !(matches!(fields, Fields::Positional(_)) || is_closed(ty.as_str()))
        }
        Expr::Field { base, .. } => leads_with_brace(base),
        Expr::Binary { left, .. } => !matches!(**left, Expr::Binary { .. }) && leads_with_brace(left),
        Expr::Call { callee: Callee::OptionSome | Callee::StringFrom, args } => leads_with_brace(&args[0]),
        Expr::Call { callee: Callee::IntFrom { from, to }, args } if *from == Some(*to) => leads_with_brace(&args[0]),
        _ => false,
    }
}

/// Where the value of a statement-lowered expression goes.
#[derive(Clone, Copy)]
enum Sink<'a> {
    Return,
    /// A `let` declared without an initializer, or a `let mut` binding.
    Assign(&'a str),
    /// The value is dropped: the expression is a Rust statement.
    Effect,
}

impl Sink<'_> {
    fn finish(self, value: &str, pad: &str, out: &mut String) {
        match self {
            Sink::Return => out.push_str(&format!("{pad}return {value};\n")),
            Sink::Assign(target) => out.push_str(&format!("{pad}{target} = {value};\n")),
            // A variable or `()` has no effect; anything else may panic.
            Sink::Effect if value == "undefined" || is_ident(value) => {}
            Sink::Effect => out.push_str(&format!("{pad}{value};\n")),
        }
    }

    fn finish_expr(self, expr: &Expr, indent: usize, out: &mut String) {
        let pad = "  ".repeat(indent);
        let value = emit_expr(expr, indent);
        match self {
            Sink::Effect if leads_with_brace(expr) => out.push_str(&format!("{pad}({value});\n")),
            _ => self.finish(&value, &pad, out),
        }
    }

    /// Unique per nesting level, so an inner temporary never shadows one an
    /// arm prelude still reads.
    fn temp(self, indent: usize) -> String {
        match self {
            Sink::Return | Sink::Effect => format!("{MATCH_TEMP}{indent}"),
            Sink::Assign(target) => format!("{MATCH_TEMP}{indent}_{target}"),
        }
    }
}

/// `for (let i = start, $e = end; i < $e; i = i + 1)`: the bounds are
/// evaluated once, in order, as Rust evaluates the range. `i + 1` cannot
/// overflow below `end`. A brand does not survive `+`, so the step casts
/// back to the bounds' type, which `check::accept` records.
fn emit_for(var: &str, ty: IntTy, start: &Expr, end: &Expr, body: &Expr, indent: usize, out: &mut String) {
    let pad = "  ".repeat(indent);
    let one = if ty.is_big() { "1n" } else { "1" };
    let bound = format!("{FOR_END}{indent}");
    out.push_str(&format!(
        "{pad}for (let {var} = {}, {bound} = {}; {var} < {bound}; {var} = ({var} + {one}) as {}) {{\n",
        emit_expr(start, indent),
        emit_expr(end, indent),
        ty.ts_name()
    ));
    emit_stmts(body, indent + 1, Sink::Effect, out);
    out.push_str(&format!("{pad}}}\n"));
}

/// Lower an expression into statements that hand its value to `sink`.
fn emit_stmts(expr: &Expr, indent: usize, sink: Sink, out: &mut String) {
    let pad = "  ".repeat(indent);
    match expr {
        Expr::Let {
            name,
            mutable,
            ty,
            value,
            then,
        } => {
            emit_let(name.as_str(), *mutable, ty.as_ref(), value, indent, out);
            emit_stmts(then, indent, sink, out);
        }
        Expr::If { cond, then, else_ } if expr.needs_statements() => {
            out.push_str(&format!("{pad}if ({}) {{\n", emit_expr(cond, indent)));
            emit_stmts(then, indent + 1, sink, out);
            if !(matches!(sink, Sink::Effect) && **else_ == Expr::Lit(Lit::Unit)) {
                out.push_str(&format!("{pad}}} else {{\n"));
                emit_stmts(else_, indent + 1, sink, out);
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        Expr::Assign { name, value } => {
            if value.needs_statements() {
                emit_stmts(value, indent, Sink::Assign(name.as_str()), out);
            } else {
                out.push_str(&format!("{pad}{} = {};\n", name.as_str(), emit_expr(value, indent)));
            }
            sink.finish("undefined", &pad, out);
        }
        Expr::Seq { first, then } => {
            emit_stmts(first, indent, Sink::Effect, out);
            let dead = matches!(**first, Expr::Return(_)) && **then == Expr::Lit(Lit::Unit);
            if !dead {
                emit_stmts(then, indent, sink, out);
            }
        }
        Expr::Match { scrutinee, arms } => emit_switch(scrutinee, arms, indent, sink, out),
        Expr::For { var, ty, start, end, body } => {
            let ty = ty.expect("check::accept types the range");
            emit_for(var.as_str(), ty, start, end, body, indent, out);
            sink.finish("undefined", &pad, out);
        }
        Expr::ForEach { var, over, source: string, body } => {
            let source = emit_expr(string, indent);
            let iterable = match over {
                // A JS string iterates by code point, as `chars` does by
                // scalar value; the two agree on well-formed strings
                // (design/01 §6).
                purecrate_ir::Over::Chars => format!("({source} as Iterable<Char>)"),
                // The UTF-8 bytes, as `as_bytes` reads them.
                purecrate_ir::Over::Bytes => format!("Str.bytes({source})"),
                purecrate_ir::Over::Items => source,
            };
            out.push_str(&format!("{pad}for (const {} of {iterable}) {{\n", var.as_str()));
            emit_stmts(body, indent + 1, Sink::Effect, out);
            out.push_str(&format!("{pad}}}\n"));
            sink.finish("undefined", &pad, out);
        }
        Expr::Return(value) => out.push_str(&format!("{pad}return {};\n", emit_expr(value, indent))),
        // `x?;`: only the early return; there is no value to bind.
        Expr::Try { expr: inner, on } if matches!(sink, Sink::Effect) => {
            emit_try_exit(&format!("{TRY_LET_TEMP}{TRY_TEMP}{indent}"), inner, *on, indent, out);
        }
        Expr::Try { .. } => {
            let tmp = format!("{TRY_TEMP}{indent}");
            emit_let(&tmp, false, None, expr, indent, out);
            sink.finish(&tmp, &pad, out);
        }
        other => sink.finish_expr(other, indent, out),
    }
}

fn emit_let(name: &str, mutable: bool, ty: Option<&Ty>, value: &Expr, indent: usize, out: &mut String) {
    let pad = "  ".repeat(indent);
    let keyword = if mutable { "let" } else { "const" };
    let annotation = ty.map(|t| format!(": {}", emit_ty(t))).unwrap_or_default();
    match value {
        Expr::Try { expr, on } => {
            let tmp = format!("{TRY_LET_TEMP}{name}");
            emit_try_exit(&tmp, expr, *on, indent, out);
            let payload = match on {
                Some(TryOn::Option) => tmp,
                Some(TryOn::Result) | None => format!("{tmp}.value"),
            };
            out.push_str(&format!("{pad}{keyword} {name}{annotation} = {payload};\n"));
        }
        v if v.needs_statements() => {
            out.push_str(&format!("{pad}let {name}{annotation};\n"));
            if matches!(v, Expr::Let { .. } | Expr::Seq { .. }) {
                // A Rust block: its bindings end with it.
                out.push_str(&format!("{pad}{{\n"));
                emit_stmts(v, indent + 1, Sink::Assign(name), out);
                out.push_str(&format!("{pad}}}\n"));
            } else {
                emit_stmts(v, indent, Sink::Assign(name), out);
            }
        }
        // An annotation would narrow the union to this variant, or to what
        // an enclosing `switch` left of the place, and a later `switch` or
        // `=== null` on the binding could not name the rest.
        v if ty.is_some_and(is_union) && (matches!(v, Expr::Construct { variant: Some(_), .. }) || is_place(v)) => out.push_str(&format!(
            "{pad}{keyword} {name} = {} as {};\n",
            emit_expr(v, indent),
            emit_ty(ty.expect("checked"))
        )),
        v => out.push_str(&format!(
            "{pad}{keyword} {name}{annotation} = {};\n",
            emit_expr(v, indent)
        )),
    }
}

/// `const tmp = expr;` and the early return of `expr?` when it holds `None`
/// or an `Err`.
fn emit_try_exit(tmp: &str, expr: &Expr, on: Option<TryOn>, indent: usize, out: &mut String) {
    let pad = "  ".repeat(indent);
    out.push_str(&format!("{pad}const {tmp} = {};\n", emit_expr(expr, indent)));
    match on {
        Some(TryOn::Option) => out.push_str(&format!("{pad}if ({tmp} === null) return null;\n")),
        Some(TryOn::Result) | None => out.push_str(&format!("{pad}if ({tmp}.kind === \"Err\") return {tmp};\n")),
    }
}

/// A type TS narrows: an enum (or any named type, which may be one),
/// `Option`, or `Result`.
fn is_union(ty: &Ty) -> bool {
    matches!(ty, Ty::Named(_) | Ty::Option(_) | Ty::Result { .. })
}

/// `x`, `x.a.b`: references TS can narrow through `switch (x.kind)`.
fn is_place(expr: &Expr) -> bool {
    match expr {
        Expr::Var(_) => true,
        Expr::Field { base, .. } => is_place(base),
        _ => false,
    }
}

fn peel(expr: &Expr) -> &Expr {
    match expr {
        Expr::Ignored { expr, .. } => peel(expr),
        other => other,
    }
}

/// Without an annotation a variant literal widens to `{ kind: string }`.
fn scrutinee_ty(arms: &[purecrate_ir::Arm]) -> Option<&purecrate_ir::Name> {
    arms.iter().find_map(|arm| match &arm.pattern {
        Pattern::Variant { ty, .. } => Some(ty),
        Pattern::Or(alts) => alts.iter().find_map(|alt| match alt {
            Pattern::Variant { ty, .. } => Some(ty),
            _ => None,
        }),
        _ => None,
    })
}

fn declares_at_top(expr: &Expr) -> bool {
    match expr {
        Expr::Let { .. } | Expr::Try { .. } | Expr::Seq { .. } | Expr::Assign { .. } => true,
        Expr::Match { scrutinee, .. } => !is_place(scrutinee),
        _ => false,
    }
}

fn emit_switch(
    scrutinee: &Expr,
    arms: &[purecrate_ir::Arm],
    indent: usize,
    sink: Sink,
    out: &mut String,
) {
    // Statements after this one may hold another `match` at the same depth;
    // a block keeps the two temporaries apart.
    if !is_place(scrutinee) && !matches!(sink, Sink::Return) {
        let pad = "  ".repeat(indent);
        out.push_str(&format!("{pad}{{\n"));
        emit_switch_in(scrutinee, arms, indent + 1, sink, out);
        out.push_str(&format!("{pad}}}\n"));
    } else {
        emit_switch_in(scrutinee, arms, indent, sink, out);
    }
}

fn emit_switch_in(
    scrutinee: &Expr,
    arms: &[purecrate_ir::Arm],
    indent: usize,
    sink: Sink,
    out: &mut String,
) {
    let pad = "  ".repeat(indent);
    let pad1 = "  ".repeat(indent + 1);
    let subject = if is_place(scrutinee) {
        emit_expr(scrutinee, indent)
    } else {
        let tmp = sink.temp(indent);
        let value = emit_expr(scrutinee, indent);
        // An annotated literal initializer narrows the union and makes the
        // other cases unreachable; a cast keeps the full union.
        let decl = match (scrutinee_ty(arms), peel(scrutinee)) {
            (Some(ty), Expr::Construct { .. }) => format!("{tmp} = {value} as {}", ty.as_str()),
            (Some(ty), _) => format!("{tmp}: {} = {value}", ty.as_str()),
            (None, _) => format!("{tmp} = {value}"),
        };
        out.push_str(&format!("{pad}const {decl};\n"));
        tmp
    };
    if let [a, b] = arms {
        if let (Some(test), Some(_)) = (two_way_test(&a.pattern, &subject), two_way_test(&b.pattern, &subject)) {
            let pad2 = "  ".repeat(indent + 1);
            out.push_str(&format!("{pad}if ({test}) {{\n"));
            out.push_str(&two_way_prelude(&a.pattern, &subject, &pad2));
            emit_stmts(&a.body, indent + 1, sink, out);
            if !(matches!(sink, Sink::Effect) && b.body == Expr::Lit(Lit::Unit)) {
                out.push_str(&format!("{pad}}} else {{\n"));
                out.push_str(&two_way_prelude(&b.pattern, &subject, &pad2));
                emit_stmts(&b.body, indent + 1, sink, out);
            }
            out.push_str(&format!("{pad}}}\n"));
            return;
        }
    }
    if arms.iter().any(|a| a.pattern.is_lit_case()) {
        emit_lit_chain(&subject, arms, indent, sink, out);
        return;
    }
    out.push_str(&format!("{pad}switch ({subject}.kind) {{\n"));
    for arm in arms {
        // `A | B` binds nothing: its cases share one body.
        let (variants, bind) = match &arm.pattern {
            Pattern::Variant { variant, bind, .. } => (vec![variant], Some(bind)),
            Pattern::Or(alts) => (
                alts.iter()
                    .filter_map(|alt| match alt {
                        Pattern::Variant { variant, .. } => Some(variant),
                        _ => None,
                    })
                    .collect(),
                None,
            ),
            _ => continue,
        };
        if let Some((last, first)) = variants.split_last() {
            for v in first {
                out.push_str(&format!("{pad1}case \"{v}\":\n", v = v.as_str()));
            }
            out.push_str(&format!("{pad1}case \"{v}\":", v = last.as_str()));
            let prelude = bind
                .map(|bind| bind_prelude(bind, &subject, &"  ".repeat(indent + 2)))
                .unwrap_or_default();
            let braced = !prelude.is_empty() || declares_at_top(&arm.body);
            out.push_str(if braced { " {\n" } else { "\n" });
            out.push_str(&prelude);
            emit_stmts(&arm.body, indent + 2, sink, out);
            if !matches!(sink, Sink::Return) && !matches!(arm.body, Expr::Return(_)) {
                out.push_str(&format!("{pad1}  break;\n"));
            }
            if braced {
                out.push_str(&format!("{pad1}}}\n"));
            }
        }
    }
    out.push_str(&format!(
        "{pad1}default:\n{pad1}  return assertNever({subject});\n{pad}}}\n"
    ));
}

/// A `match` on an integer or a `&str`: arms tried in order, the last (`_`)
/// as `else`. Well-formed strings are equal in UTF-8 exactly when they are in
/// UTF-16, so `===` is `str` equality.
fn emit_lit_chain(subject: &str, arms: &[purecrate_ir::Arm], indent: usize, sink: Sink, out: &mut String) {
    let pad = "  ".repeat(indent);
    for (i, arm) in arms.iter().enumerate() {
        let head = match (i, lit_test(&arm.pattern, subject)) {
            (0, Some(test)) => format!("{pad}if ({test}) {{\n"),
            (_, Some(test)) => format!("{pad}}} else if ({test}) {{\n"),
            (_, None) => format!("{pad}}} else {{\n"),
        };
        out.push_str(&head);
        emit_stmts(&arm.body, indent + 1, sink, out);
    }
    out.push_str(&format!("{pad}}}\n"));
}

/// The test for an integer, `char`, or string arm; `None` for `_`.
fn lit_test(pattern: &Pattern, subject: &str) -> Option<String> {
    match pattern {
        Pattern::Lit(lit) => Some(format!("{subject} === {}", emit_lit(lit))),
        // By code point: JS orders strings by UTF-16 unit.
        Pattern::Range { lo: Lit::Char(lo), hi: Lit::Char(hi), inclusive } => Some(format!(
            "Char.code({subject}) >= {} && Char.code({subject}) {} {}",
            u32::from(*lo),
            if *inclusive { "<=" } else { "<" },
            u32::from(*hi)
        )),
        Pattern::Range { lo, hi, inclusive } => Some(format!(
            "{subject} >= {} && {subject} {} {}",
            emit_lit(lo),
            if *inclusive { "<=" } else { "<" },
            emit_lit(hi)
        )),
        Pattern::Or(alts) => Some(
            alts.iter()
                .filter_map(|a| match a {
                    Pattern::Range { .. } => lit_test(a, subject).map(|t| format!("({t})")),
                    _ => lit_test(a, subject),
                })
                .collect::<Vec<_>>()
                .join(" || "),
        ),
        _ => None,
    }
}

/// A `char` range, which prints through `Char.code`.
fn has_char_range(pattern: &Pattern) -> bool {
    match pattern {
        Pattern::Range { lo: Lit::Char(_), .. } => true,
        Pattern::Or(alts) => alts.iter().any(has_char_range),
        _ => false,
    }
}

/// The integer types of the literals in an integer arm.
fn int_case_lits(pattern: &Pattern, f: &mut impl FnMut(purecrate_ir::IntTy)) {
    match pattern {
        Pattern::Lit(Lit::Int { ty: Some(t), .. }) => f(*t),
        Pattern::Range { lo, hi, .. } => {
            for l in [lo, hi] {
                if let Lit::Int { ty: Some(t), .. } = l {
                    f(*t);
                }
            }
        }
        Pattern::Or(alts) => alts.iter().for_each(|a| int_case_lits(a, f)),
        _ => {}
    }
}

/// `Option` is `T | null` and `Result` is `kind`-tagged, so both narrow
/// with a single test.
fn two_way_test(pattern: &Pattern, subject: &str) -> Option<String> {
    match pattern {
        Pattern::OptionSome(_) => Some(format!("{subject} !== null")),
        Pattern::OptionNone => Some(format!("{subject} === null")),
        Pattern::ResultOk(_) => Some(format!("{subject}.kind === \"Ok\"")),
        Pattern::ResultErr(_) => Some(format!("{subject}.kind === \"Err\"")),
        _ => None,
    }
}

fn two_way_prelude(pattern: &Pattern, subject: &str, pad: &str) -> String {
    let (inner, read) = match pattern {
        Pattern::OptionSome(p) => (p, subject.to_string()),
        Pattern::ResultOk(p) => (p, format!("{subject}.value")),
        Pattern::ResultErr(p) => (p, format!("{subject}.error")),
        _ => return String::new(),
    };
    match &**inner {
        Pattern::Var(n) => format!("{pad}const {} = {read};\n", n.as_str()),
        _ => String::new(),
    }
}

fn emit_ty(ty: &Ty) -> String {
    match ty {
        Ty::Prim(p) => match p {
            purecrate_ir::Prim::Bool => "boolean".into(),
            purecrate_ir::Prim::String | purecrate_ir::Prim::Str => "string".into(),
            purecrate_ir::Prim::Char => "Char".into(),
            purecrate_ir::Prim::Uuid => "Uuid".into(),
            purecrate_ir::Prim::UuidError => "UuidError".into(),
            purecrate_ir::Prim::Unit => "undefined".into(),
            other => match other.int() {
                Some(t) => t.ts_name().into(),
                None => match other.float() {
                    Some(t) => t.ts_name().into(),
                    None => "number".into(),
                },
            },
        },
        Ty::Option(inner) => format!("{} | null", emit_ty(inner)),
        Ty::Result { ok, err } => format!("Result<{}, {}>", emit_ty(ok), emit_ty(err)),
        Ty::Vec(inner) => format!("ReadonlyArray<{}>", emit_ty(inner)),
        Ty::Tuple(elems) => {
            let inner = elems.iter().map(emit_ty).collect::<Vec<_>>().join(", ");
            format!("readonly [{inner}]")
        }
        Ty::Named(n) => n.as_str().to_string(),
        Ty::Ignored { wrapper, inner } => {
            format!("/* {} */ {}", wrapper.comment(), emit_ty(inner))
        }
        Ty::Fn { params, ret } => {
            let params = params
                .iter()
                .enumerate()
                .map(|(i, t)| format!("_{i}: {}", emit_ty(t)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("(({params}) => {})", emit_ty(ret))
        }
        Ty::Never => "never".into(),
    }
}

fn emit_expr(expr: &Expr, indent: usize) -> String {
    match expr {
        Expr::At { .. } => unreachable!("emit takes `check::accept` output, which has no positions"),
        Expr::Ignored { wrapper, expr } => {
            format!("/* {} */ {}", wrapper.comment(), emit_expr(expr, indent))
        }
        Expr::Lit(lit) => emit_lit(lit),
        Expr::Var(n) => n.as_str().to_string(),
        Expr::Field { base, name } if name.as_str() == NEWTYPE_FIELD => emit_expr(base, indent),
        Expr::Field { base, name } if name.as_str().starts_with('[') => format!("{}{}", emit_expr(base, indent), name.as_str()),
        Expr::Field { base, name } => format!("{}.{n}", emit_expr(base, indent), n = name.as_str()),
        Expr::Index { base, index } => format!(
            "((($xs, $i) => {{ if (!globalThis.Number.isInteger($i) || $i < 0 || $i >= $xs.length) throw new globalThis.Error(`index out of bounds: the len is ${{$xs.length}} but the index is ${{$i}}`); return $xs[$i]; }})({}, {}))",
            emit_expr(base, indent),
            emit_expr(index, indent)
        ),
        Expr::Binary { op, left, right } => format!(
            "{} {} {}",
            operand(left, indent),
            bin_op(*op),
            operand(right, indent)
        ),
        Expr::Unary { op, expr } => {
            let o = match op {
                purecrate_ir::UnOp::Not => "!",
                purecrate_ir::UnOp::Neg => "-",
            };
            let inner = operand(expr, indent);
            if inner.starts_with(o) {
                format!("{o}({inner})")
            } else {
                format!("{o}{inner}")
            }
        }
        Expr::Closure { params, ret, body } => format!("({})", closure_arrow(params, ret.as_ref(), body, indent)),
        Expr::MethodCall { name, .. } => {
            unreachable!("`.{}()` reaches emit unresolved; emit takes `check::accept` output", name.as_str())
        }
        Expr::Construct { ty, variant, fields, base } => match (variant, base) {
            (Some(v), None) => emit_variant_value(ty.as_str(), v.as_str(), fields),
            (None, None) if is_closed(ty.as_str()) => {
                format!("{}({})", closed_ctor(ty.as_str()), emit_struct_value(fields))
            }
            (None, None) => emit_struct_value(fields),
            (None, Some(base)) if is_closed(ty.as_str()) => {
                format!("{}{}", closed_ctor(ty.as_str()), emit_struct_update(fields, base))
            }
            (None, Some(base)) => emit_struct_update(fields, base),
            (Some(_), Some(_)) => unreachable!("enum variants have no struct update"),
        },
        Expr::Match { .. } | Expr::Let { .. } => emit_iife(expr, indent),
        Expr::If { .. } if expr.needs_statements() => emit_iife(expr, indent),
        Expr::Try { .. } | Expr::Seq { .. } | Expr::Assign { .. } | Expr::For { .. } | Expr::ForEach { .. } => {
            emit_iife(expr, indent)
        }
        Expr::If { cond, then, else_ } => format!(
            "({} ? {} : {})",
            emit_expr(cond, indent),
            emit_expr(then, indent),
            emit_expr(else_, indent)
        ),
        // Variant names are identifiers other than `__proto__` (checked), so
        // an object literal is a plain table.
        Expr::Call {
            callee: purecrate_ir::Callee::Discriminant { to, table },
            args,
        } => {
            let entries = table
                .iter()
                .map(|(v, d)| format!("{}: {}", v.as_str(), emit_lit(&Lit::Int { value: *d, ty: Some(*to) })))
                .collect::<Vec<_>>()
                .join(", ");
            // `kind` may be typed `string` (a variant literal widens), and a
            // consumer may set `noUncheckedIndexedAccess`: hence both casts.
            let t = to.ts_name();
            format!("(({{ {entries} }} as Record<string, {t}>)[{}.kind] as {t})", emit_expr(&args[0], indent))
        }
        Expr::Call { callee, args } => {
            let c = match callee {
                purecrate_ir::Callee::Fn(n) | purecrate_ir::Callee::Local(n) => n.as_str().to_string(),
                purecrate_ir::Callee::Method { ty, name } if is_private_method(ty.as_str(), name.as_str()) => {
                    private_method(ty.as_str(), name.as_str())
                }
                purecrate_ir::Callee::Method { ty, name } => {
                    format!("{}.{}", ty.as_str(), name.as_str())
                }
                purecrate_ir::Callee::Variant { ty, variant } => {
                    format!("{}.{}", ty.as_str(), variant.as_str())
                }
                purecrate_ir::Callee::StructNew(n) if is_closed(n.as_str()) => closed_ctor(n.as_str()),
                purecrate_ir::Callee::StructNew(n) => format!("{}.of", n.as_str()),
                purecrate_ir::Callee::ResultOk => "Result.ok".into(),
                purecrate_ir::Callee::ResultErr => "Result.err".into(),
                purecrate_ir::Callee::OptionSome => String::new(),
                purecrate_ir::Callee::OptionNone => "null".into(),
                purecrate_ir::Callee::Int { ty, op } => {
                    format!("Int.{}.{}", ty.as_str(), op.as_str())
                }
                purecrate_ir::Callee::Discriminant { .. } => unreachable!("printed above"),
                purecrate_ir::Callee::Fround => "globalThis.Math.fround".into(),
                purecrate_ir::Callee::AsFloat(_) => String::new(),
                purecrate_ir::Callee::VecLen
                | purecrate_ir::Callee::VecIsEmpty
                | purecrate_ir::Callee::OptionIsSome
                | purecrate_ir::Callee::OptionIsNone
                | purecrate_ir::Callee::StrBytes
                | purecrate_ir::Callee::StringFrom
                | purecrate_ir::Callee::Str(_)
                | purecrate_ir::Callee::IntFrom { .. }
                | purecrate_ir::Callee::CharCode(_) => String::new(),
                purecrate_ir::Callee::CharFromU8 => "Char.fromU8".into(),
                purecrate_ir::Callee::CharFromU32 => "Char.fromU32".into(),
                purecrate_ir::Callee::Char(m) => format!("Char.{}", m.ts_name()),
                purecrate_ir::Callee::UuidParse => "Uuid.parseStr".into(),
                purecrate_ir::Callee::UuidNil => "Uuid.nil".into(),
            };
            if let purecrate_ir::Callee::CharCode(to) = callee {
                let code = format!("Char.code({})", emit_expr(&args[0], indent));
                return if to.is_big() { format!("(globalThis.BigInt({code}) as {})", to.ts_name()) } else { code };
            }
            if let purecrate_ir::Callee::IntFrom { from, to } = callee {
                let x = emit_expr(&args[0], indent);
                let from = from.expect("check::accept sets the source width");
                return match (from.is_big(), to.is_big()) {
                    _ if from == *to => x,
                    (false, true) => format!("(globalThis.BigInt({x}) as {})", to.ts_name()),
                    _ => format!("({x} as number as {})", to.ts_name()),
                };
            }
            if matches!(callee, purecrate_ir::Callee::StrBytes) {
                return format!("Str.bytes({})", emit_expr(&args[0], indent));
            }
            if let purecrate_ir::Callee::Str(m) = callee {
                let s = emit_expr(&args[0], indent);
                let needle = || emit_expr(&args[1], indent);
                return match m {
                    purecrate_ir::StrMethod::Len => format!("Str.len({s})"),
                    purecrate_ir::StrMethod::IsEmpty => format!("({s}.length === 0)"),
                    purecrate_ir::StrMethod::StartsWith => format!("{s}.startsWith({})", needle()),
                    purecrate_ir::StrMethod::EndsWith => format!("{s}.endsWith({})", needle()),
                    purecrate_ir::StrMethod::Contains => format!("{s}.includes({})", needle()),
                    purecrate_ir::StrMethod::AsStr => s,
                };
            }
            if matches!(callee, purecrate_ir::Callee::VecLen) {
                return format!("(({}.length) as Usize)", emit_expr(&args[0], indent));
            }
            match callee {
                purecrate_ir::Callee::VecIsEmpty => return format!("({}.length === 0)", emit_expr(&args[0], indent)),
                purecrate_ir::Callee::OptionIsSome => return format!("({} !== null)", emit_expr(&args[0], indent)),
                purecrate_ir::Callee::OptionIsNone => return format!("({} === null)", emit_expr(&args[0], indent)),
                _ => {}
            }
            if matches!(callee, purecrate_ir::Callee::Fround) {
                return format!("(globalThis.Math.fround({}) as F32)", emit_expr(&args[0], indent));
            }
            if let purecrate_ir::Callee::AsFloat(ft) = callee {
                return format!("({} as {})", emit_expr(&args[0], indent), ft.ts_name());
            }
            if matches!(callee, purecrate_ir::Callee::OptionNone) {
                return "null".into();
            }
            if matches!(callee, purecrate_ir::Callee::OptionSome | purecrate_ir::Callee::StringFrom) {
                return emit_expr(&args[0], indent);
            }
            let a = args
                .iter()
                .map(|e| emit_expr(e, indent))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{c}({a})")
        }
        Expr::Tuple(elems) => {
            let inner = elems
                .iter()
                .map(|e| emit_expr(e, indent))
                .collect::<Vec<_>>()
                .join(", ");
            format!("[{inner}]")
        }
        Expr::Array(elems) => {
            let inner = elems
                .iter()
                .map(|e| emit_expr(e, indent))
                .collect::<Vec<_>>()
                .join(", ");
            format!("[{inner}]")
        }
        Expr::Return(e) => format!("(() => {{ return {}; }})()", emit_expr(e, indent)),
        Expr::Unreachable => "assertNever(undefined as never)".into(),
        Expr::Cast { .. } => unreachable!("`check::accept` rewrites `as`"),
    }
}

/// The IR has no parentheses, so a nested operator is always grouped.
fn operand(expr: &Expr, indent: usize) -> String {
    let s = emit_expr(expr, indent);
    match expr {
        Expr::Binary { .. } => format!("({s})"),
        _ => s,
    }
}

/// `{ ...base, a: e1 }`. `?` in the fields and the base is hoisted before this
/// expression, fields first, so the spread running first in JS does not move
/// a failing `?` ahead of an earlier one.
fn emit_struct_update(fields: &Fields, base: &Expr) -> String {
    let Fields::Named(pairs) = fields else {
        unreachable!("struct update has named fields");
    };
    let mut parts = vec![format!("...{}", emit_expr(base, 0))];
    for (name, expr) in pairs {
        parts.push(format!("{}: {}", name.as_str(), emit_expr(expr, 0)));
    }
    format!("({{ {} }})", parts.join(", "))
}

fn emit_struct_value(fields: &Fields) -> String {
    match fields {
        Fields::Unit => "{}".into(),
        Fields::Positional(elems) => {
            let inner = elems
                .iter()
                .map(|e| emit_expr(e, 0))
                .collect::<Vec<_>>()
                .join(", ");
            format!("[{inner}]")
        }
        Fields::Named(pairs) => {
            let inner = pairs
                .iter()
                .map(|(n, e)| format!("{k}: {v}", k = n.as_str(), v = emit_expr(e, 0)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {inner} }}")
        }
    }
}

fn emit_variant_value(_ty: &str, variant: &str, fields: &Fields) -> String {
    match fields {
        Fields::Unit => format!("{{ kind: \"{variant}\" }}"),
        Fields::Positional(elems) => {
            let inner = elems
                .iter()
                .map(|e| emit_expr(e, 0))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ kind: \"{variant}\", content: [{inner}] }}")
        }
        Fields::Named(pairs) => {
            let inner = pairs
                .iter()
                .map(|(n, e)| format!("{k}: {v}", k = n.as_str(), v = emit_expr(e, 0)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ kind: \"{variant}\", {inner} }}")
        }
    }
}

fn emit_iife(expr: &Expr, indent: usize) -> String {
    let mut body = String::new();
    emit_stmts(expr, indent + 1, Sink::Return, &mut body);
    format!("(() => {{\n{body}{pad}}})()", pad = "  ".repeat(indent))
}

fn bind_prelude(bind: &VariantBind, subject: &str, pad: &str) -> String {
    match bind {
        VariantBind::Unit => String::new(),
        VariantBind::Tuple(pats) => pats
            .iter()
            .enumerate()
            .filter_map(|(i, p)| match p {
                Pattern::Var(n) => Some(format!(
                    "{pad}const {name} = {subject}.content[{i}];\n",
                    name = n.as_str()
                )),
                _ => None,
            })
            .collect(),
        VariantBind::Struct(pairs) => pairs
            .iter()
            .filter_map(|(field, p)| match p {
                Pattern::Var(n) => Some(format!(
                    "{pad}const {name} = {subject}.{f};\n",
                    name = n.as_str(),
                    f = field.as_str()
                )),
                _ => None,
            })
            .collect(),
    }
}

fn emit_lit(lit: &Lit) -> String {
    match lit {
        Lit::Bool(b) => if *b { "true" } else { "false" }.into(),
        Lit::Int { value, ty } => match ty {
            Some(t) if t.is_big() => format!("({value}n as {})", t.ts_name()),
            Some(t) => format!("({value} as {})", t.ts_name()),
            None => value.to_string(),
        },
        Lit::Float { digits, ty } => match ty {
            Some(FloatTy::F32) => f32_literal(digits),
            Some(FloatTy::F64) => format!("({digits} as F64)"),
            None => digits.clone(),
        },
        Lit::Str(s) => js_string(s),
        Lit::Char(c) => format!("({} as Char)", js_string(&c.to_string())),
        Lit::Unit => "undefined".into(),
        Lit::Null => "null".into(),
    }
}

/// Rust rounds the decimal straight to `f32`. `Math.fround(1.0000000596…)`
/// would round it to `f64` first, which can land on a midpoint between two
/// `f32`s and then tie the wrong way. The `f32` value is printed as an exact
/// decimal instead: every `f32` is an `f64`, so JS reads it without rounding.
fn f32_literal(digits: &str) -> String {
    match digits.parse::<f32>() {
        Ok(v) if v.is_finite() => format!("({:?} as F32)", f64::from(v)),
        // rustc rejects an out-of-range literal, so the input never gets here.
        _ => format!("(globalThis.Math.fround({digits}) as F32)"),
    }
}

/// A double-quoted literal escaped as JSON escapes it, plus U+2028 and
/// U+2029, which end a line in older JS parsers.
fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{8}' => out.push_str("\\b"),
            '\u{c}' => out.push_str("\\f"),
            c if c < ' ' || c == '\u{2028}' || c == '\u{2029}' => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn bin_op(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Rem => "%",
        BinOp::Eq => "===",
        BinOp::Ne => "!==",
        BinOp::Lt => "<",
        BinOp::Le => "<=",
        BinOp::Gt => ">",
        BinOp::Ge => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::BitAnd | BinOp::BitOr | BinOp::BitXor | BinOp::Shl | BinOp::Shr => {
            unreachable!("`check::accept` rewrites bitwise operators into `Int` calls")
        }
    }
}

/// Names one file refers to. A value import also brings the same-named type.
#[derive(Default)]
struct Refs {
    never: bool,
    int: bool,
    result: bool,
    /// `Str` from `./str.ts`.
    str: bool,
    /// The `Char` runtime, and the `Char` type, from `./str.ts`.
    char_value: bool,
    char_type: bool,
    /// The `Uuid` runtime, and the `Uuid` / `UuidError` types, from `./str.ts`.
    uuid_value: bool,
    uuid_type: bool,
    uuid_error: bool,
    /// Brand type names (`I32`, `F64`) this file mentions.
    nums: BTreeSet<String>,
    types: BTreeSet<String>,
    values: BTreeSet<String>,
    /// Closed structs this file builds through their `$of`.
    ctors: BTreeSet<String>,
    /// Methods that are not `pub` this file calls, as `Ty$name`.
    privates: BTreeSet<(String, String)>,
}

impl Refs {
    fn ty(&mut self, ty: &Ty) {
        match ty {
            Ty::Named(n) => {
                self.types.insert(n.as_str().to_string());
            }
            Ty::Result { ok, err } => {
                self.result = true;
                self.ty(ok);
                self.ty(err);
            }
            Ty::Option(inner) | Ty::Vec(inner) | Ty::Ignored { inner, .. } => self.ty(inner),
            Ty::Tuple(elems) => elems.iter().for_each(|t| self.ty(t)),
            Ty::Fn { params, ret } => {
                params.iter().for_each(|t| self.ty(t));
                self.ty(ret);
            }
            Ty::Prim(purecrate_ir::Prim::Char) => self.char_type = true,
            Ty::Prim(purecrate_ir::Prim::Uuid) => self.uuid_type = true,
            Ty::Prim(purecrate_ir::Prim::UuidError) => self.uuid_error = true,
            Ty::Prim(p) => {
                if let Some(name) = p.int().map(|t| t.ts_name()).or_else(|| p.float().map(|t| t.ts_name())) {
                    self.nums.insert(name.to_string());
                }
            }
            Ty::Never => {}
        }
    }

    /// The integer brands and `Char` that literal and range patterns print.
    fn arm_literals<'p>(&mut self, patterns: impl Iterator<Item = &'p Pattern>) {
        for p in patterns {
            int_case_lits(p, &mut |t| {
                self.nums.insert(t.ts_name().to_string());
            });
            self.char_value |= has_char_range(p);
            self.char_type |= p.is_char_case();
        }
    }

    fn expr(&mut self, krate: &Crate, expr: &Expr) {
        match expr {
            Expr::At { expr, .. } => self.expr(krate, expr),
            Expr::Match { scrutinee, arms } => {
                self.never |= arms
                    .iter()
                    .any(|a| matches!(a.pattern, Pattern::Variant { .. }) || (matches!(a.pattern, Pattern::Or(_)) && !a.pattern.is_lit_case()));
                self.arm_literals(arms.iter().map(|a| &a.pattern));
                if !is_place(scrutinee) {
                    if let Some(ty) = scrutinee_ty(arms) {
                        self.types.insert(ty.as_str().to_string());
                    }
                }
                self.expr(krate, scrutinee);
                arms.iter().for_each(|a| self.expr(krate, &a.body));
            }
            Expr::Unreachable => self.never = true,
            Expr::Call { callee, args } => {
                match callee {
                    Callee::Fn(n) if is_free_fn(krate, n.as_str()) => {
                        self.values.insert(n.as_str().to_string());
                    }
                    Callee::StructNew(ty) if closed_in(krate, ty.as_str()) => {
                        self.ctors.insert(ty.as_str().to_string());
                    }
                    Callee::Method { ty, name } if private_in(krate, ty.as_str(), name.as_str()) => {
                        self.privates.insert((ty.as_str().to_string(), name.as_str().to_string()));
                    }
                    Callee::Method { ty, .. } | Callee::Variant { ty, .. } | Callee::StructNew(ty) => {
                        self.values.insert(ty.as_str().to_string());
                    }
                    Callee::ResultOk | Callee::ResultErr => self.result = true,
                    Callee::Int { ty, .. } => {
                        self.int = true;
                        self.nums.insert(ty.ts_name().to_string());
                    }
                    Callee::Fround => {
                        self.nums.insert("F32".into());
                        self.nums.insert("F64".into());
                    }
                    Callee::AsFloat(ft) => {
                        self.nums.insert(ft.ts_name().to_string());
                    }
                    Callee::VecLen => {
                        self.nums.insert("Usize".into());
                    }
                    Callee::StrBytes => self.str = true,
                    Callee::Str(purecrate_ir::StrMethod::Len) => {
                        self.str = true;
                        self.nums.insert("Usize".into());
                    }
                    Callee::IntFrom { to, .. } => {
                        self.nums.insert(to.ts_name().to_string());
                    }
                    Callee::CharCode(to) => {
                        self.char_value = true;
                        if to.is_big() {
                            self.nums.insert(to.ts_name().to_string());
                        }
                    }
                    Callee::CharFromU8 | Callee::CharFromU32 | Callee::Char(_) => self.char_value = true,
                    Callee::UuidParse | Callee::UuidNil => self.uuid_value = true,
                    Callee::Discriminant { to, .. } => {
                        self.nums.insert(to.ts_name().to_string());
                    }
                    _ => {}
                }
                args.iter().for_each(|a| self.expr(krate, a));
            }
            Expr::Let { ty, value, then, .. } => {
                if let Some(t) = ty {
                    self.ty(t);
                }
                self.expr(krate, value);
                self.expr(krate, then);
            }
            Expr::If { cond, then, else_ } => {
                self.expr(krate, cond);
                self.expr(krate, then);
                self.expr(krate, else_);
            }
            Expr::Construct { ty, variant, fields, base } => {
                if variant.is_none() && closed_in(krate, ty.as_str()) {
                    self.ctors.insert(ty.as_str().to_string());
                }
                match fields {
                    Fields::Positional(xs) => xs.iter().for_each(|e| self.expr(krate, e)),
                    Fields::Named(xs) => xs.iter().for_each(|(_, e)| self.expr(krate, e)),
                    Fields::Unit => {}
                }
                if let Some(b) = base {
                    self.expr(krate, b);
                }
            }
            Expr::Field { base, .. }
            | Expr::Unary { expr: base, .. }
            | Expr::Return(base)
            | Expr::Assign { value: base, .. }
            | Expr::Try { expr: base, .. }
            | Expr::Ignored { expr: base, .. } => {
                self.expr(krate, base)
            }
            Expr::Index { base, index } => {
                self.expr(krate, base);
                self.expr(krate, index);
            }
            Expr::Binary { left, right, .. } | Expr::Seq { first: left, then: right } => {
                self.expr(krate, left);
                self.expr(krate, right);
            }
            Expr::For { start, end, body, .. } => {
                self.expr(krate, start);
                self.expr(krate, end);
                self.expr(krate, body);
            }
            Expr::ForEach { over, source: string, body, .. } => {
                match over {
                    purecrate_ir::Over::Chars => self.char_type = true,
                    purecrate_ir::Over::Bytes => self.str = true,
                    purecrate_ir::Over::Items => {}
                }
                self.expr(krate, string);
                self.expr(krate, body);
            }
            Expr::Tuple(xs) | Expr::Array(xs) => xs.iter().for_each(|e| self.expr(krate, e)),
            Expr::MethodCall { .. } => expr.children().into_iter().for_each(|e| self.expr(krate, e)),
            Expr::Closure { params, ret, body } => {
                params.iter().filter_map(|p| p.ty.as_ref()).for_each(|t| self.ty(t));
                if let Some(t) = ret {
                    self.ty(t);
                }
                self.expr(krate, body);
            }
            Expr::Lit(lit) => match lit {
                purecrate_ir::Lit::Int { ty: Some(t), .. } => {
                    self.nums.insert(t.ts_name().to_string());
                }
                purecrate_ir::Lit::Float { ty: Some(t), .. } => {
                    self.nums.insert(t.ts_name().to_string());
                }
                purecrate_ir::Lit::Char(_) => self.char_type = true,
                _ => {}
            },
            Expr::Var(n) if is_const(krate, n.as_str()) => {
                self.values.insert(n.as_str().to_string());
            }
            Expr::Var(_) => {}
            Expr::Cast { .. } => unreachable!("`check::accept` rewrites `as`"),
        }
    }

    fn fn_sig_and_body(&mut self, krate: &Crate, f: &Fn) {
        f.params.iter().for_each(|p| self.ty(&p.ty));
        self.ty(&f.ret);
        self.expr(krate, &f.body);
    }
}

fn closed_in(krate: &Crate, name: &str) -> bool {
    krate
        .items
        .iter()
        .any(|item| matches!(item, Item::Struct(st) if st.closed && st.name.as_str() == name))
}

fn private_in(krate: &Crate, ty: &str, name: &str) -> bool {
    krate.items.iter().any(|item| {
        matches!(item, Item::Fn(f) if f.vis == Vis::Internal
            && f.name.as_str() == name
            && f.owner.as_ref().is_some_and(|o| o.as_str() == ty))
    })
}

fn is_const(krate: &Crate, name: &str) -> bool {
    krate.items.iter().any(|item| matches!(item, Item::Const(c) if c.name.as_str() == name))
}

fn is_free_fn(krate: &Crate, name: &str) -> bool {
    krate
        .items
        .iter()
        .any(|item| matches!(item, Item::Fn(f) if f.owner.is_none() && f.name.as_str() == name))
}

fn imports_for(krate: &Crate, stem: &str, items: &[&Item]) -> String {
    let mut refs = Refs::default();
    for item in items {
        match item {
            Item::Struct(st) => {
                st.fields.iter().for_each(|f| refs.ty(&f.ty));
                methods_on(krate, st.name.as_str())
                    .into_iter()
                    .for_each(|m| refs.fn_sig_and_body(krate, m));
            }
            Item::Enum(en) => {
                for v in &en.variants {
                    match &v.fields {
                        VariantFields::Unit => {}
                        VariantFields::Tuple(tys) => tys.iter().for_each(|t| refs.ty(t)),
                        VariantFields::Struct(fs) => fs.iter().for_each(|f| refs.ty(&f.ty)),
                    }
                }
                methods_on(krate, en.name.as_str())
                    .into_iter()
                    .for_each(|m| refs.fn_sig_and_body(krate, m));
            }
            Item::Alias(al) => refs.ty(&al.ty),
            Item::Const(c) => {
                refs.ty(&c.ty);
                refs.expr(krate, &c.value);
            }
            Item::Fn(f) if f.owner.is_none() => refs.fn_sig_and_body(krate, f),
            Item::Fn(_) => {}
        }
    }

    // A const lives in `consts.ts`, not in a file named after it.
    let file_of = |name: &String| {
        if is_const(krate, name) {
            purecrate_ir::CONSTS_STEM.to_string()
        } else {
            Name::new(name.clone()).file_stem()
        }
    };
    let elsewhere = |name: &String| file_of(name) != stem;
    let mut out = String::new();
    if refs.never {
        out.push_str("import { assertNever } from \"./assert-never.ts\";\n");
    }
    if refs.int || !refs.nums.is_empty() {
        let types = refs.nums.iter().map(|n| format!("type {n}")).collect::<Vec<_>>().join(", ");
        if refs.int && types.is_empty() {
            out.push_str("import { Int } from \"./int.ts\";\n");
        } else if refs.int {
            out.push_str(&format!("import {{ Int, {types} }} from \"./int.ts\";\n"));
        } else {
            out.push_str(&format!("import {{ {types} }} from \"./int.ts\";\n"));
        }
    }
    if refs.result {
        out.push_str("import { Result } from \"./result.ts\";\n");
    }
    let str_names = [
        refs.char_value.then_some("Char"),
        (refs.char_type && !refs.char_value).then_some("type Char"),
        refs.uuid_value.then_some("Uuid"),
        (refs.uuid_type && !refs.uuid_value).then_some("type Uuid"),
        refs.uuid_error.then_some("type UuidError"),
        refs.str.then_some("Str"),
    ]
    .into_iter()
    .flatten()
    .collect::<Vec<_>>();
    if !str_names.is_empty() {
        out.push_str(&format!("import {{ {} }} from \"./str.ts\";\n", str_names.join(", ")));
    }
    for v in refs.values.iter().filter(|v| elsewhere(v)) {
        out.push_str(&format!("import {{ {v} }} from \"./{s}.ts\";\n", s = file_of(v)));
    }
    for (ty, name) in refs.privates.iter().filter(|(ty, _)| elsewhere(ty)) {
        out.push_str(&format!(
            "import {{ {m} }} from \"./{s}.ts\";\n",
            m = private_method(ty, name),
            s = Name::new(ty.clone()).file_stem()
        ));
    }
    for c in refs.ctors.iter().filter(|c| elsewhere(c)) {
        out.push_str(&format!(
            "import {{ {ctor} }} from \"./{s}.ts\";\n",
            ctor = closed_ctor(c),
            s = Name::new(c.clone()).file_stem()
        ));
    }
    for t in refs
        .types
        .iter()
        .filter(|t| elsewhere(t) && !refs.values.contains(*t))
    {
        out.push_str(&format!(
            "import type {{ {t} }} from \"./{s}.ts\";\n",
            s = Name::new(t.clone()).file_stem()
        ));
    }
    out
}

fn is_ident(s: &str) -> bool {
    !s.is_empty() && s.chars().all(|c| c.is_alphanumeric() || c == '_' || c == '$')
}

#[cfg(test)]
mod tests {
    use super::*;
    use purecrate_ir::counter_example;

    fn file<'a>(pkg: &'a Package, stem: &str) -> &'a str {
        &pkg.files
            .iter()
            .find(|f| f.stem == stem)
            .unwrap_or_else(|| panic!("missing {stem}"))
            .source
    }

    #[test]
    fn erased_wrappers_keep_their_comment() {
        use purecrate_ir::{Fn, Item, Param, Vis, Wrapper};
        let share = Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("share"),
            owner: None,
            params: vec![Param {
                name: Name::new("n"),
                ty: Ty::ignored(Wrapper::Mutex, Ty::i32()),
            }],
            ret: Ty::ignored(Wrapper::Box, Ty::i32()),
            body: Expr::Ignored {
                wrapper: Wrapper::Arc,
                expr: Box::new(Expr::var("n")),
            },
        });
        let pkg = emit(&Crate::new("wraps", vec![share]));
        let src = file(&pkg, "share");
        assert!(src.contains(Wrapper::Box.comment()), "{src}");
        assert!(src.contains(Wrapper::Arc.comment()), "{src}");
        assert!(src.contains(Wrapper::Mutex.comment()), "{src}");
    }

    #[test]
    fn counter_kamae_shape() {
        let pkg = emit(&counter_example());
        let stems: Vec<&str> = pkg.files.iter().map(|f| f.stem.as_str()).collect();
        assert!(stems.contains(&"event"));
        assert!(stems.contains(&"state"));
        assert!(stems.contains(&"step"));

        let event = file(&pkg, "event");
        assert!(event.contains("kind: \"Inc\""));
        assert!(event.contains("export const Event = {"));
        assert!(!event.contains("tag:"));

        let state = file(&pkg, "state");
        assert!(state.contains("export type State = Readonly<{"));
        assert!(state.contains("of: (n: I32): State =>"));

        let step = file(&pkg, "step");
        assert!(step.contains("export const step ="));
        assert!(step.contains("switch (event.kind)"));
        assert!(step.contains("assertNever(event)"));
        assert!(step.contains("import type { Event }"));
        assert!(step.contains("import type { State }"));
    }

    #[test]
    fn counter_step_is_a_switch_statement() {
        let pkg = emit(&counter_example());
        let expected = "\
export const step = (state: State, event: Event): State => {
  switch (event.kind) {
    case \"Inc\":
      return { n: state.n + 1 };
    case \"Dec\":
      return { n: state.n - 1 };
    case \"Reset\":
      return { n: 0 };
    default:
      return assertNever(event);
  }
};
";
        assert!(file(&pkg, "step").ends_with(expected), "{}", file(&pkg, "step"));
    }

    fn cmd_crate(body: Expr) -> Crate {
        use purecrate_ir::{Name, Param, Variant, Vis};
        let cmd = Item::Enum(Enum {
            vis: Vis::Pub,
            name: Name::new("Cmd"),
            variants: vec![
                Variant {
                    name: Name::new("Move"),
                    fields: VariantFields::Tuple(vec![Ty::i32(), Ty::i32()]),
                    discriminant: None,
                },
                Variant {
                    name: Name::new("Paint"),
                    fields: VariantFields::Struct(vec![purecrate_ir::Field {
                        name: Name::new("color"),
                        ty: Ty::i32(),
                    }]),
                    discriminant: None,
                },
            ],
            repr: None,
        });
        let run = Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("run"),
            owner: None,
            params: vec![Param {
                name: Name::new("cmd"),
                ty: Ty::named("Cmd"),
            }],
            ret: Ty::i32(),
            body,
        });
        Crate::new("cmds", vec![cmd, run])
    }

    fn cmd_match(scrutinee: Expr) -> Expr {
        use purecrate_ir::{Arm, Name};
        let var = |n: &str| Pattern::Var(Name::new(n));
        Expr::Match {
            scrutinee: Box::new(scrutinee),
            arms: vec![
                Arm {
                    pattern: Pattern::Variant {
                        ty: Name::new("Cmd"),
                        variant: Name::new("Move"),
                        bind: VariantBind::Tuple(vec![var("a"), var("b")]),
                    },
                    body: Expr::Binary {
                        op: BinOp::Add,
                        left: Box::new(Expr::var("a")),
                        right: Box::new(Expr::var("b")),
                    },
                },
                Arm {
                    pattern: Pattern::Variant {
                        ty: Name::new("Cmd"),
                        variant: Name::new("Paint"),
                        bind: VariantBind::Struct(vec![(Name::new("color"), var("c"))]),
                    },
                    body: Expr::var("c"),
                },
            ],
        }
    }

    #[test]
    fn bindings_read_from_the_scrutinee() {
        let pkg = emit(&cmd_crate(cmd_match(Expr::var("cmd"))));
        let run = file(&pkg, "run");
        assert!(run.contains("case \"Move\": {\n      const a = cmd.content[0];"), "{run}");
        assert!(run.contains("const b = cmd.content[1];"), "{run}");
        assert!(run.contains("const c = cmd.color;"), "{run}");
        assert!(!run.contains("event"), "{run}");
    }

    #[test]
    fn non_place_scrutinee_is_bound_once() {
        use purecrate_ir::{Callee, Name};
        let call = Expr::Call {
            callee: Callee::Fn(Name::new("next")),
            args: vec![Expr::var("cmd")],
        };
        let pkg = emit(&cmd_crate(cmd_match(call)));
        let run = file(&pkg, "run");
        assert!(run.contains("const $m_1: Cmd = next(cmd);\n  switch ($m_1.kind)"), "{run}");
        assert!(run.contains("const a = $m_1.content[0];"), "{run}");
    }

    #[test]
    fn object_literal_arrow_body_is_parenthesized() {
        use purecrate_ir::{Name, Param, Vis};
        let mut krate = counter_example();
        krate.items.push(Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("zero"),
            owner: Some(Name::new("State")),
            params: vec![Param {
                name: Name::new("self"),
                ty: Ty::named("State"),
            }],
            ret: Ty::named("State"),
            body: Expr::Construct {
                ty: Name::new("State"),
                variant: None,
                fields: Fields::Named(vec![(Name::new("n"), Expr::int(0))]),
                base: None,
            },
        }));
        let pkg = emit(&krate);
        assert!(
            file(&pkg, "state").contains("zero: (self: State): State => ({ n: 0 }),"),
            "{}",
            file(&pkg, "state")
        );
    }

    #[test]
    fn imports_follow_body_and_nested_types() {
        use purecrate_ir::{Param, Vis};
        let mut krate = cmd_crate(cmd_match(Expr::Call {
            callee: Callee::Fn(Name::new("next")),
            args: vec![Expr::var("cmd")],
        }));
        krate.items.push(Item::Fn(Fn {
            vis: Vis::Internal,
            name: Name::new("next"),
            owner: None,
            params: vec![Param {
                name: Name::new("cmd"),
                ty: Ty::named("Cmd"),
            }],
            ret: Ty::named("Cmd"),
            body: Expr::var("cmd"),
        }));
        krate.items.push(Item::Struct(Struct {
            vis: Vis::Pub,
            name: Name::new("Log"),
            fields: vec![purecrate_ir::Field {
                name: Name::new("last"),
                ty: Ty::option(Ty::Vec(Box::new(Ty::named("Cmd")))),
            }],
            closed: false,
            wire_from: None,
        }));
        let pkg = emit(&krate);

        let run = file(&pkg, "run");
        assert!(run.contains("import { next } from \"./next.ts\";\n"), "{run}");
        assert!(run.contains("import type { Cmd } from \"./cmd.ts\";\n"), "{run}");

        let log = file(&pkg, "log");
        assert!(log.contains("import type { Cmd } from \"./cmd.ts\";\n"), "{log}");
        let cmd = file(&pkg, "cmd");
        assert!(cmd.contains("import { type I32 } from \"./int.ts\";\n"), "{cmd}");
        assert!(!cmd.contains("from \"./cmd.ts\""), "{cmd}");
    }

    #[test]
    fn enum_methods_join_the_companion() {
        use purecrate_ir::{Param, Vis};
        let mut krate = cmd_crate(Expr::int(0));
        krate.items.push(Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("weight"),
            owner: Some(Name::new("Cmd")),
            params: vec![Param {
                name: Name::new("self"),
                ty: Ty::named("Cmd"),
            }],
            ret: Ty::i32(),
            body: cmd_match(Expr::var("self")),
        }));
        let pkg = emit(&krate);
        let cmd = file(&pkg, "cmd");
        assert!(cmd.contains("  weight: (self: Cmd): I32 => {\n    switch (self.kind) {"), "{cmd}");
        assert!(cmd.ends_with("  },\n} as const;\n"), "{cmd}");
        assert!(cmd.starts_with(&format!("{HEADER}\nimport {{ assertNever }}")), "{cmd}");
    }

    #[test]
    fn index_exports_each_name_once() {
        let pkg = emit(&counter_example());
        let index = file(&pkg, "index");
        for name in ["Result", "assertNever", "Event", "State", "step"] {
            let hits = index
                .lines()
                .filter(|l| l.contains(&format!("{{ {name} }}")))
                .count();
            assert_eq!(hits, 1, "{name} in:\n{index}");
        }
        assert_eq!(
            index.lines().filter(|l| l.contains("export type {")).count(),
            1,
            "{index}"
        );
    }

    #[test]
    fn result_is_imported_once() {
        use purecrate_ir::{Callee, Name, Param, Vis};
        let parse = Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("parse"),
            owner: None,
            params: vec![Param {
                name: Name::new("n"),
                ty: Ty::i32(),
            }],
            ret: Ty::result(Ty::i32(), Ty::Prim(purecrate_ir::Prim::String)),
            body: Expr::Call {
                callee: Callee::ResultOk,
                args: vec![Expr::var("n")],
            },
        });
        let pkg = emit(&Crate::new("p", vec![parse]));
        let src = file(&pkg, "parse");
        assert_eq!(src.matches("from \"./result.ts\"").count(), 1, "{src}");
    }

    fn f64_fn(body: Expr) -> String {
        use purecrate_ir::{Name, Param, Prim, Vis};
        let f = Item::Fn(Fn {
            vis: Vis::Pub,
            name: Name::new("f"),
            owner: None,
            params: vec![Param {
                name: Name::new("x"),
                ty: Ty::Prim(Prim::F64),
            }],
            ret: Ty::Prim(Prim::F64),
            body,
        });
        file(&emit(&Crate::new("p", vec![f])), "f").to_string()
    }

    #[test]
    fn nested_operators_keep_their_grouping() {
        use purecrate_ir::UnOp;
        let bin = |op, l, r| Expr::Binary {
            op,
            left: Box::new(l),
            right: Box::new(r),
        };
        let sum = bin(BinOp::Add, Expr::var("x"), Expr::var("x"));
        let src = f64_fn(bin(BinOp::Mul, sum.clone(), Expr::var("x")));
        assert!(src.contains("=> (x + x) * x;"), "{src}");
        let neg = |e| Expr::Unary {
            op: UnOp::Neg,
            expr: Box::new(e),
        };
        let src = f64_fn(neg(neg(Expr::var("x"))));
        assert!(src.contains("=> -(-x);"), "{src}");
        let src = f64_fn(neg(sum));
        assert!(src.contains("=> -(x + x);"), "{src}");
    }

    #[test]
    fn typed_literals_print_their_js_form() {
        let big = Lit::Int {
            value: -5,
            ty: Some(IntTy::I64),
        };
        assert_eq!(emit_lit(&big), "(-5n as I64)");
        let single = Lit::Float {
            digits: "0.1".into(),
            ty: Some(FloatTy::F32),
        };
        assert_eq!(emit_lit(&single), "(0.10000000149011612 as F32)");
    }

    #[test]
    fn strings_escape_as_json_does() {
        let s = emit_lit(&Lit::Str("q\"\\\n\r\t\u{8}\u{c}\u{0}\u{1b}\u{2028}\u{2029}é".into()));
        assert_eq!(s, "\"q\\\"\\\\\\n\\r\\t\\b\\f\\u0000\\u001b\\u2028\\u2029é\"");
    }

    #[test]
    fn object_literals_behind_a_comment_are_parenthesized() {
        use purecrate_ir::Wrapper;
        let lit = Expr::Construct {
            ty: Name::new("P"),
            variant: None,
            fields: Fields::Named(vec![(Name::new("a"), Expr::var("a"))]),
            base: None,
        };
        let boxed = Expr::Ignored {
            wrapper: Wrapper::Box,
            expr: Box::new(lit.clone()),
        };
        let body = arrow_expr(&boxed, 0);
        assert!(body.starts_with("(/* ") && body.ends_with("{ a: a })"), "{body}");
        let mut out = String::new();
        Sink::Effect.finish_expr(&boxed, 0, &mut out);
        assert!(out.starts_with("(/* ") && out.ends_with("{ a: a });\n"), "{out}");
        let some = Expr::Call {
            callee: Callee::OptionSome,
            args: vec![lit],
        };
        assert_eq!(arrow_expr(&some, 0), "({ a: a })");
    }

    #[test]
    fn integer_from_converts_only_into_bigint() {
        let from = |from, to| {
            emit_expr(
                &Expr::Call {
                    callee: purecrate_ir::Callee::IntFrom { from: Some(from), to },
                    args: vec![Expr::var("x")],
                },
                0,
            )
        };
        assert_eq!(from(IntTy::U32, IntTy::I64), "(globalThis.BigInt(x) as I64)");
        assert_eq!(from(IntTy::U8, IntTy::I32), "(x as number as I32)");
        assert_eq!(from(IntTy::I64, IntTy::I64), "x");
    }
}
