/* generated by purecrate-ts. do not edit. */

import { Json } from "./purecrate-runtime.ts";
import * as v from "valibot";
import { str, u64, unitVariant } from "./purecrate-valibot.ts";
import type { CorePart as CorePart$ } from "./core-part.ts";
import type { SemverError as SemverError$ } from "./semver-error.ts";
import type { PreId as PreId$ } from "./pre-id.ts";
import type { PreIds as PreIds$ } from "./pre-ids.ts";
import type { BuildIds as BuildIds$ } from "./build-ids.ts";
import { Version$of, type Version as Version$ } from "./version.ts";

export const CorePart: v.GenericSchema<unknown, CorePart$> = v.union([
  v.pipe(unitVariant("Major"), v.transform((): CorePart$ => ({ kind: "Major" }))),
  v.pipe(unitVariant("Minor"), v.transform((): CorePart$ => ({ kind: "Minor" }))),
  v.pipe(unitVariant("Patch"), v.transform((): CorePart$ => ({ kind: "Patch" }))),
]);

export const SemverError: v.GenericSchema<unknown, SemverError$> = v.union([
  v.pipe(unitVariant("Empty"), v.transform((): SemverError$ => ({ kind: "Empty" }))),
  v.pipe(
    v.strictObject({ MissingPart: CorePart }),
    v.transform((v): SemverError$ => ({ kind: "MissingPart", content: [v.MissingPart] })),
  ),
  v.pipe(
    unitVariant("ExtraCorePart"),
    v.transform((): SemverError$ => ({ kind: "ExtraCorePart" })),
  ),
  v.pipe(
    v.strictObject({ EmptyNumber: CorePart }),
    v.transform((v): SemverError$ => ({ kind: "EmptyNumber", content: [v.EmptyNumber] })),
  ),
  v.pipe(
    v.strictObject({ NotANumber: CorePart }),
    v.transform((v): SemverError$ => ({ kind: "NotANumber", content: [v.NotANumber] })),
  ),
  v.pipe(
    v.strictObject({ LeadingZero: CorePart }),
    v.transform((v): SemverError$ => ({ kind: "LeadingZero", content: [v.LeadingZero] })),
  ),
  v.pipe(
    v.strictObject({ NumberTooLarge: CorePart }),
    v.transform((v): SemverError$ => ({ kind: "NumberTooLarge", content: [v.NumberTooLarge] })),
  ),
  v.pipe(
    unitVariant("EmptyPreRelease"),
    v.transform((): SemverError$ => ({ kind: "EmptyPreRelease" })),
  ),
  v.pipe(
    unitVariant("InvalidPreReleaseChar"),
    v.transform((): SemverError$ => ({ kind: "InvalidPreReleaseChar" })),
  ),
  v.pipe(
    unitVariant("PreReleaseLeadingZero"),
    v.transform((): SemverError$ => ({ kind: "PreReleaseLeadingZero" })),
  ),
  v.pipe(
    unitVariant("PreReleaseTooLarge"),
    v.transform((): SemverError$ => ({ kind: "PreReleaseTooLarge" })),
  ),
  v.pipe(
    unitVariant("EmptyBuild"),
    v.transform((): SemverError$ => ({ kind: "EmptyBuild" })),
  ),
  v.pipe(
    unitVariant("InvalidBuildChar"),
    v.transform((): SemverError$ => ({ kind: "InvalidBuildChar" })),
  ),
]);

export const PreId: v.GenericSchema<unknown, PreId$> = v.union([
  v.pipe(
    v.strictObject({ Numeric: u64 }),
    v.transform((v): PreId$ => ({ kind: "Numeric", content: [v.Numeric] })),
  ),
  v.pipe(
    v.strictObject({ Alpha: str }),
    v.transform((v): PreId$ => ({ kind: "Alpha", content: [v.Alpha] })),
  ),
]);

export const PreIds: v.GenericSchema<unknown, PreIds$> = v.lazy(() => v.union([
  v.pipe(unitVariant("Nil"), v.transform((): PreIds$ => ({ kind: "Nil" }))),
  v.pipe(
    v.strictObject({ Cons: v.tuple([PreId, PreIds]) }),
    v.transform((v): PreIds$ => ({ kind: "Cons", content: v.Cons })),
  ),
]));

export const BuildIds: v.GenericSchema<unknown, BuildIds$> = v.lazy(() => v.union([
  v.pipe(unitVariant("Nil"), v.transform((): BuildIds$ => ({ kind: "Nil" }))),
  v.pipe(
    v.strictObject({ Cons: v.tuple([str, BuildIds]) }),
    v.transform((v): BuildIds$ => ({ kind: "Cons", content: v.Cons })),
  ),
]));

export const Version: v.GenericSchema<unknown, Version$> = v.pipe(
  v.object({ major: u64, minor: u64, patch: u64, pre: PreIds, build: BuildIds }),
  v.transform((v): Version$ => Version$of({ major: v.major, minor: v.minor, patch: v.patch, pre: v.pre, build: v.build })),
);

/** Each type written as serde_json writes the Rust value. */
export const toJson = {
  CorePart: (x: CorePart$): string => `"${x.kind}"`,
  SemverError: (x: SemverError$): string => {
    switch (x.kind) {
      case "Empty":
        return "\"Empty\"";
      case "MissingPart":
        return `{"MissingPart":${toJson.CorePart(x.content[0])}}`;
      case "ExtraCorePart":
        return "\"ExtraCorePart\"";
      case "EmptyNumber":
        return `{"EmptyNumber":${toJson.CorePart(x.content[0])}}`;
      case "NotANumber":
        return `{"NotANumber":${toJson.CorePart(x.content[0])}}`;
      case "LeadingZero":
        return `{"LeadingZero":${toJson.CorePart(x.content[0])}}`;
      case "NumberTooLarge":
        return `{"NumberTooLarge":${toJson.CorePart(x.content[0])}}`;
      case "EmptyPreRelease":
        return "\"EmptyPreRelease\"";
      case "InvalidPreReleaseChar":
        return "\"InvalidPreReleaseChar\"";
      case "PreReleaseLeadingZero":
        return "\"PreReleaseLeadingZero\"";
      case "PreReleaseTooLarge":
        return "\"PreReleaseTooLarge\"";
      case "EmptyBuild":
        return "\"EmptyBuild\"";
      case "InvalidBuildChar":
        return "\"InvalidBuildChar\"";
    }
  },
  PreId: (x: PreId$): string => {
    switch (x.kind) {
      case "Numeric":
        return `{"Numeric":${Json.int(x.content[0])}}`;
      case "Alpha":
        return `{"Alpha":${Json.str(x.content[0])}}`;
    }
  },
  PreIds: (x: PreIds$): string => {
    switch (x.kind) {
      case "Nil":
        return "\"Nil\"";
      case "Cons":
        return `{"Cons":[${toJson.PreId(x.content[0])},${toJson.PreIds(x.content[1])}]}`;
    }
  },
  BuildIds: (x: BuildIds$): string => {
    switch (x.kind) {
      case "Nil":
        return "\"Nil\"";
      case "Cons":
        return `{"Cons":[${Json.str(x.content[0])},${toJson.BuildIds(x.content[1])}]}`;
    }
  },
  Version: (x: Version$): string => `{"major":${Json.int(x.major)},"minor":${Json.int(x.minor)},"patch":${Json.int(x.patch)},"pre":${toJson.PreIds(x.pre)},"build":${toJson.BuildIds(x.build)}}`,
} as const;
