/* generated by purecrate-ts. do not edit. */

import { Result } from "./purecrate-runtime.ts";
import { checkedULabel } from "./checked-u-label.ts";
import { ACE_PREFIX } from "./consts.ts";
import type { DomainError } from "./domain-error.ts";
import { encode } from "./encode.ts";
import { isAsciiLabel } from "./is-ascii-label.ts";

/** The A-label (ASCII form) of one label. */
export const aLabel = (label: string): Result<string, DomainError> => {
  // An "xn--" label is read as an A-label only, non-ASCII too: `xn--é`
  // fails as its payload is not ASCII (`Punycode(NonBasic)`).
  if (label.startsWith(ACE_PREFIX)) {
    const checkedULabelResult = checkedULabel(label);
    if (checkedULabelResult.kind === "Err") return checkedULabelResult;
    return Result.ok(label);
  }

  if (isAsciiLabel(label)) return Result.ok(label);
  const pResult = encode(label);
  if (pResult.kind === "Err") return Result.err({ kind: "Punycode", value: pResult.error });
  const p = pResult.value;
  let out: string = ACE_PREFIX;
  out += p;
  return Result.ok(out);
};
