/* generated by purecrate-ts. do not edit. */

import { Int, type U32 } from "./purecrate-runtime.ts";
import { BASE, DAMP, SKEW, TMAX, TMIN } from "./consts.ts";

/** §6.1. */
export const adapt = (delta: U32, numPoints: U32, firstTime: boolean): U32 => {
  let d: U32 = firstTime ? Int.u32.div(delta, DAMP) : Int.u32.div(delta, 2 as U32);
  d = Int.u32.add(d, Int.u32.div(d, numPoints));
  let k = 0 as U32;

  while (d > Int.u32.div(Int.u32.mul(Int.u32.sub(BASE, TMIN), TMAX), 2 as U32)) {
    d = Int.u32.div(d, Int.u32.sub(BASE, TMIN));
    k = Int.u32.add(k, BASE);
  }

  return Int.u32.add(
    k,
    Int.u32.div(
      Int.u32.mul(Int.u32.add(Int.u32.sub(BASE, TMIN), 1 as U32), d),
      Int.u32.add(d, SKEW),
    ),
  );
};
