/* generated by purecrate-ts. do not edit. */

import type { Char, U32, Usize } from "./purecrate-runtime.ts";

export const BASE = 36 as U32;
export const TMIN = 1 as U32;
export const TMAX = 26 as U32;
export const SKEW = 38 as U32;
export const DAMP = 700 as U32;
export const INITIAL_BIAS = 72 as U32;
export const INITIAL_N = 128 as U32;
export const DELIMITER = "-" as Char;
export const MAX_LABEL_LEN = 63 as Usize;
export const MAX_DOMAIN_LEN = 253 as Usize;
export const ACE_PREFIX: string = "xn--";
