/* generated by purecrate-ts. do not edit. */

import type { Char, Result } from "./purecrate-runtime.ts";
import { encodeChars } from "./encode-chars.ts";
import type { PunycodeError } from "./punycode-error.ts";

/**
 * Punycode of a string of Unicode scalar values (RFC 3492 §6.3), as its
 * characters (all ASCII).
 */
export const encode = (input: string): Result<ReadonlyArray<Char>, PunycodeError> => {
  const cs = Array.from(input as Iterable<Char>);
  return encodeChars(cs);
};
