/* generated by purecrate-ts. do not edit. */

import { Char, Iter } from "./purecrate-runtime.ts";

export const isAsciiLabel = (label: ReadonlyArray<Char>): boolean =>
  Iter.all(label, (c: Char): boolean => Char.isAscii(c));
