/* generated by purecrate-ts. do not edit. */

import { Int, type Usize } from "./purecrate-runtime.ts";

/** The labels joined with '.', with the root dot when `rooted`. */
export const joinLabels = (labels: ReadonlyArray<string>, rooted: boolean): string => {
  let out: string = "";
  let i = 0 as Usize;

  for (const label of labels) {
    const j = i;
    i = Int.usize.add(i, 1 as Usize);

    if (j > 0) {
      out += ".";
    }

    out += label;
  }

  if (rooted) {
    out += ".";
  }

  return out;
};
