/* generated by purecrate-ts. do not edit. */

export type PunycodeError =
  | Readonly<{ kind: "NonBasic" }>
  | Readonly<{ kind: "BadDigit" }>
  | Readonly<{ kind: "Overflow" }>
  | Readonly<{ kind: "InvalidCodePoint" }>;

export const PunycodeError = {
  /** The input to `decode` contains a non-ASCII character. */
  NonBasic: (): PunycodeError => ({ kind: "NonBasic" }),
  /**
   * A character after the last delimiter is not a base-36 digit, or the
   * input ends inside a variable-length integer.
   */
  BadDigit: (): PunycodeError => ({ kind: "BadDigit" }),
  /** A value exceeds 2^32-1 (§6.4). */
  Overflow: (): PunycodeError => ({ kind: "Overflow" }),
  /** A decoded code point is a surrogate or above U+10FFFF. */
  InvalidCodePoint: (): PunycodeError => ({ kind: "InvalidCodePoint" }),
} as const;
