/* generated by purecrate-ts. do not edit. */

import { Int, type U32 } from "./purecrate-runtime.ts";
import { TMAX, TMIN } from "./consts.ts";

/** The threshold t for position k (§6.2, §6.3). */
export const threshold = (k: U32, bias: U32): U32 =>
  k <= bias ? TMIN : k >= Int.u32.add(bias, TMAX) ? TMAX : Int.u32.sub(k, bias);
