/* generated by purecrate-ts. do not edit. */

import { Result, type Char } from "./purecrate-runtime.ts";
import { aLabel } from "./a-label.ts";
import { checkLengths } from "./check-lengths.ts";
import { checkedULabel } from "./checked-u-label.ts";
import type { DomainError } from "./domain-error.ts";
import { hasAcePrefix } from "./has-ace-prefix.ts";
import { joinLabels } from "./join-labels.ts";
import { splitLabels } from "./split-labels.ts";

/** The U-label (Unicode form) of one label. */
const uLabel = (label: ReadonlyArray<Char>): Result<ReadonlyArray<Char>, DomainError> => {
  if (hasAcePrefix(label)) return checkedULabel(label);
  return Result.ok([...label]);
};

/** The Unicode form of a domain name, as its characters. */
export const toUnicode = (domain: string): Result<ReadonlyArray<Char>, DomainError> => {
  const result = splitLabels(domain);
  if (result.kind === "Err") return result;
  const [labels, rooted] = result.value;
  const ascii: Array<ReadonlyArray<Char>> = [];
  const out: Array<ReadonlyArray<Char>> = [];

  for (const label of labels) {
    const aLabelResult = aLabel(label);
    if (aLabelResult.kind === "Err") return aLabelResult;
    ascii.push(aLabelResult.value);
    const uLabelResult = uLabel(label);
    if (uLabelResult.kind === "Err") return uLabelResult;
    out.push(uLabelResult.value);
  }

  const checkLengthsResult = checkLengths(ascii);
  if (checkLengthsResult.kind === "Err") return checkLengthsResult;
  return Result.ok(joinLabels(out, rooted));
};
